In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/data.yaml
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit193_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit488_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit224_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit396_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit492_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit293_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit344_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit2_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit180_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit388_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit181_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit472_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit165_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit29_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit35_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit272_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit217_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit356_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit399_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit174_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit276_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit361_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit236_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit67_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit475_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit301_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit301_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit241_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit98_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit207_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit159_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit479_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit460_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit181_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit458_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit456_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit423_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit358_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit4_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit133_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit381_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit39_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit354_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit96_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit201_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit379_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit146_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit76_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit3_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit77_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit436_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit94_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit198_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit449_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit357_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit60_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit210_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit405_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit212_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit258_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit286_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit302_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit217_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit203_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit499_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit325_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit82_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit41_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit298_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit497_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit295_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit16_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit379_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit213_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit133_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit344_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit495_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit209_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit257_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit32_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit388_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit438_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit369_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit473_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit467_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit293_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit104_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit461_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit404_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit264_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit398_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit258_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit345_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit436_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit145_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit195_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit481_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit218_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit118_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit223_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit451_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit264_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit487_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit488_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit431_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit50_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit459_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit146_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit102_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit187_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit71_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit406_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit113_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit213_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit143_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit499_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit412_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit138_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit399_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit33_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit430_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit121_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit309_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit91_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit228_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit101_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit233_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit176_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit300_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit235_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit455_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit384_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit134_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit315_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit321_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit188_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit298_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit70_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit147_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit25_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit482_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit81_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit113_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit425_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit177_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit89_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit41_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit83_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit323_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit389_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit434_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit92_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit101_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit235_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit375_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit112_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit42_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit290_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit104_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit400_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit34_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit106_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit322_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit495_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit421_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit278_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit378_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit394_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit292_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit108_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit281_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit446_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit31_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit63_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit232_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit39_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit481_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit276_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit496_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit182_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit85_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit102_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit377_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit204_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit376_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit466_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit368_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit262_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit212_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit136_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit448_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit99_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit48_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit8_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit413_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit303_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit442_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit314_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit319_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit449_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit184_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit271_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit80_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit494_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit12_aug_2.txt

In [1]:
pip install ultralytics

Collecting ultralytics
  Downloading ultralytics-8.3.193-py3-none-any.whl.metadata (37 kB)
Requirement already satisfied: numpy>=1.23.0 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (1.26.4)
Requirement already satisfied: matplotlib>=3.3.0 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (3.7.2)
Requirement already satisfied: opencv-python>=4.6.0 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (4.11.0.86)
Requirement already satisfied: pillow>=7.1.2 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (11.2.1)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (6.0.2)
Requirement already satisfied: requests>=2.23.0 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (2.32.4)
Requirement already satisfied: scipy>=1.4.1 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (1.15.3)
Requirement already satisfied: torch>=1.8.0 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (2.6.0+cu124)
Requirement already satisfied: torchvision>=0.9.0 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (0.21.0+cu124)
Requirement already satisfied: psutil in /usr/local/lib/python3.11/dist-packages (from ultralytics) (7.0.0)
Requirement already satisfied: py-cpuinfo in /usr/local/lib/python3.11/dist-packages (from ultralytics) (9.0.0)
Requirement already satisfied: polars in /usr/local/lib/python3.11/dist-packages (from ultralytics) (1.21.0)
Collecting ultralytics-thop>=2.0.0 (from ultralytics)
  Downloading ultralytics_thop-2.0.17-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.3.0->ultralytics) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.3.0->ultralytics) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.3.0->ultralytics) (4.58.4)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.3.0->ultralytics) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.3.0->ultralytics) (25.0)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.3.0->ultralytics) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.3.0->ultralytics) (2.9.0.post0)
Requirement already satisfied: mkl_fft in /usr/local/lib/python3.11/dist-packages (from numpy>=1.23.0->ultralytics) (1.3.8)
Requirement already satisfied: mkl_random in /usr/local/lib/python3.11/dist-packages (from numpy>=1.23.0->ultralytics) (1.2.4)
Requirement already satisfied: mkl_umath in /usr/local/lib/python3.11/dist-packages (from numpy>=1.23.0->ultralytics) (0.1.1)
Requirement already satisfied: mkl in /usr/local/lib/python3.11/dist-packages (from numpy>=1.23.0->ultralytics) (2025.2.0)
Requirement already satisfied: tbb4py in /usr/local/lib/python3.11/dist-packages (from numpy>=1.23.0->ultralytics) (2022.2.0)
Requirement already satisfied: mkl-service in /usr/local/lib/python3.11/dist-packages (from numpy>=1.23.0->ultralytics) (2.4.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.23.0->ultralytics) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.23.0->ultralytics) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.23.0->ultralytics) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.23.0->ultralytics) (2025.6.15)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (3.18.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (4.14.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (2025.5.1)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (12.4.127)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=1.8.0->ultralytics) (1.3.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib>=3.3.0->ultralytics) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch>=1.8.0->ultralytics) (3.0.2)
Requirement already satisfied: intel-openmp<2026,>=2024 in /usr/local/lib/python3.11/dist-packages (from mkl->numpy>=1.23.0->ultralytics) (2024.2.0)
Requirement already satisfied: tbb==2022.* in /usr/local/lib/python3.11/dist-packages (from mkl->numpy>=1.23.0->ultralytics) (2022.2.0)
Requirement already satisfied: tcmlib==1.* in /usr/local/lib/python3.11/dist-packages (from tbb==2022.*->mkl->numpy>=1.23.0->ultralytics) (1.4.0)
Requirement already satisfied: intel-cmplr-lib-rt in /usr/local/lib/python3.11/dist-packages (from mkl_umath->numpy>=1.23.0->ultralytics) (2024.2.0)
Requirement already satisfied: intel-cmplr-lib-ur==2024.2.0 in /usr/local/lib/python3.11/dist-packages (from intel-openmp<2026,>=2024->mkl->numpy>=1.23.0->ultralytics) (2024.2.0)
Downloading ultralytics-8.3.193-py3-none-any.whl (1.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 27.5 MB/s eta 0:00:0000:01
Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 4.6 MB/s eta 0:00:00:00:0100:01
Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 66.2 MB/s eta 0:00:0000:0100:01
Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 54.5 MB/s eta 0:00:0000:01m00:01
Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 38.0 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 952.0 kB/s eta 0:00:0000:0100:01
Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 7.4 MB/s eta 0:00:00:00:0100:01
Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 17.6 MB/s eta 0:00:0000:0100:01
Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 12.1 MB/s eta 0:00:0000:0100:01
Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 7.6 MB/s eta 0:00:00:00:0100:01
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 18.8 MB/s eta 0:00:0000:0100:01
Downloading ultralytics_thop-2.0.17-py3-none-any.whl (28 kB)
Installing collected packages: nvidia-nvjitlink-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12, ultralytics-thop, ultralytics
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.5.82
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.6.82
    Uninstalling nvidia-curand-cu12-10.3.6.82:
      Successfully uninstalled nvidia-curand-cu12-10.3.6.82
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.2.3.61
    Uninstalling nvidia-cufft-cu12-11.2.3.61:
      Successfully uninstalled nvidia-cufft-cu12-11.2.3.61
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.5.82
    Uninstalling nvidia-cuda-runtime-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.5.82
    Uninstalling nvidia-cuda-nvrtc-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.5.82
    Uninstalling nvidia-cuda-cupti-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.5.82
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.5.3.2
    Uninstalling nvidia-cublas-cu12-12.5.3.2:
      Successfully uninstalled nvidia-cublas-cu12-12.5.3.2
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.1.3
    Uninstalling nvidia-cusparse-cu12-12.5.1.3:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.1.3
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.3.0.75
    Uninstalling nvidia-cudnn-cu12-9.3.0.75:
      Successfully uninstalled nvidia-cudnn-cu12-9.3.0.75
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.6.3.83
    Uninstalling nvidia-cusolver-cu12-11.6.3.83:
      Successfully uninstalled nvidia-cusolver-cu12-11.6.3.83
Successfully installed nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-nvjitlink-cu12-12.4.127 ultralytics-8.3.193 ultralytics-thop-2.0.17
Note: you may need to restart the kernel to use updated packages.

In [2]:
import time
import json
import pandas as pd
from ultralytics import YOLO
from pathlib import Path

# =============================
# CONFIG
# =============================
DATA_PATH = "/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/data.yaml"
RESULTS_CSV = "yolov8_ablation_results.csv"

# Global Best Parameters (update as you go)
BEST_PARAMS = {
    "epochs": 32,          # default, update after finding best
    "batch": 32,
    "lr0": 0.01,
    "weight_decay": 0.0005,
    "optimizer": "SGD",
    "img_size": 640,
    "dropout": 0.0,
    "freeze": 0,
    "activation": "SiLU"
}

# Initialize results DataFrame
if Path(RESULTS_CSV).exists():
    results_df = pd.read_csv(RESULTS_CSV)
else:
    results_df = pd.DataFrame(columns=[
        "Case", "Exp No", "Experiment Name", "Epochs", "Batch", "lr0", "Weight Decay",
        "Optimizer", "Image Size", "Dropout", "Freeze Layers", "Activation",
        "Training Time (s)", "Precision", "Recall", "mAP@0.5", "mAP@0.5:0.95"
    ])

Creating new Ultralytics Settings v0.0.6 file ✅
View Ultralytics Settings with 'yolo settings' or at '/root/.config/Ultralytics/settings.json'
Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/quickstart/#ultralytics-settings.

In [6]:
def run_experiment(case, exp_no, exp_name, epochs=32, batch=32, lr0=0.01,
                   weight_decay=0.0005, optimizer="SGD", img_size=640,
                   dropout=0.0, freeze=0, activation="SiLU"):
    global results_df

    model = YOLO("yolov8n.pt")  # Using YOLOv8 nano

    # Track training time
    start_time = time.time()
    model.train(
        data=DATA_PATH,
        epochs=epochs,
        batch=batch,
        lr0=lr0,
        optimizer=optimizer,
        imgsz=img_size,
        dropout=dropout,
        freeze=freeze,
        verbose=False
    )
    train_time = time.time() - start_time

    # ✅ FIX: Load YOLO metrics from results.csv
    results_file = Path(model.trainer.save_dir) / "results.csv"
    results_df_yolo = pd.read_csv(results_file)
    last_row = results_df_yolo.iloc[-1]

    precision = last_row["metrics/precision(B)"]
    recall = last_row["metrics/recall(B)"]
    map50 = last_row["metrics/mAP50(B)"]
    map5095 = last_row["metrics/mAP50-95(B)"]

    new_row = {
        "Case": case,
        "Exp No": exp_no,
        "Experiment Name": exp_name,
        "Epochs": epochs,
        "Batch": batch,
        "lr0": lr0,
        "Weight Decay": weight_decay,
        "Optimizer": optimizer,
        "Image Size": img_size,
        "Dropout": dropout,
        "Freeze Layers": freeze,
        "Activation": activation,
        "Training Time (s)": round(train_time, 2),
        "Precision": precision,
        "Recall": recall,
        "mAP@0.5": map50,
        "mAP@0.5:0.95": map5095,
    }
    results_df = pd.concat([results_df, pd.DataFrame([new_row])], ignore_index=True)

    results_df.to_csv(RESULTS_CSV, index=False)
    display(results_df.tail(10))
# =============================
# Wrapper to use BEST_PARAMS
# =============================
def run_with_best(case, exp_no, exp_name, **kwargs):
    params = BEST_PARAMS.copy()
    params.update(kwargs)
    run_experiment(case, exp_no, exp_name, **params)

In [7]:
# Case 1: Epoch Variation
def case1_epoch_variation():
    run_with_best("Case 1: Epoch Variation", 1, "epochs_16", epochs=16)
    run_with_best("Case 1: Epoch Variation", 2, "epochs_32", epochs=32)
    run_with_best("Case 1: Epoch Variation", 3, "epochs_64", epochs=64)

# Case 2: Weight Decay
def case2_weight_decay():
    run_with_best("Case 2: Weight Decay", 1, "wd_0", weight_decay=0)
    run_with_best("Case 2: Weight Decay", 2, "wd_0.0001", weight_decay=0.0001)
    run_with_best("Case 2: Weight Decay", 3, "wd_0.0005", weight_decay=0.0005)
    run_with_best("Case 2: Weight Decay", 4, "wd_0.001", weight_decay=0.001)
    run_with_best("Case 2: Weight Decay", 5, "wd_0.005", weight_decay=0.005)

# Case 3: Batch Size
def case3_batch_size():
    run_with_best("Case 3: Batch Size", 1, "batch_16", batch=16)
    run_with_best("Case 3: Batch Size", 2, "batch_32", batch=32)
    run_with_best("Case 3: Batch Size", 3, "batch_64", batch=64)  # may OOM

# Case 4: Dropout
def case4_dropout():
    for i, d in enumerate([0, 0.1, 0.2, 0.3, 0.5], start=1):
        run_with_best("Case 4: Dropout", i, f"dropout_{d}", dropout=d)

# Case 6: Optimizer
def case6_optimizer():
    opts = ["SGD", "Adam", "AdamW", "RMSProp", "Adamax"]
    for i, opt in enumerate(opts, start=1):
        run_with_best("Case 6: Optimizer", i, f"optimizer_{opt}", optimizer=opt)
# Case 7: Learning Rate
def case7_learning_rate():
    for i, lr in enumerate([0.001, 0.005, 0.01, 0.05], start=1):
        run_with_best("Case 7: Learning Rate", i, f"lr_{lr}", lr0=lr)

# Case 8: Freeze Layers
def case8_freeze_layers():
    for i, freeze in enumerate([0, 10, 15, 22], start=1):
        run_with_best("Case 8: Freeze Layers", i, f"freeze_{freeze}", freeze=freeze)
# Case 5: Image Size
# Case 5: Image Size
def case5_image_size():
    for i, img_size in enumerate([320, 512, 640], start=1):
        run_with_best("Case 5: Image Size", i, f"imgsz_{img_size}", img_size=img_size)

In [20]:
# =============================
# Case 9: Activation Functions
# =============================

# !pip install ultralytics

import time, yaml, copy
import pandas as pd
from pathlib import Path
from ultralytics import YOLO
from ultralytics.nn.tasks import yaml_model_load
from tabulate import tabulate

# -------------------------------
# CONFIG
# -------------------------------
DATA_PATH = "/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/data.yaml"
RESULTS_CSV = "case9_results.csv"
BASE_MODEL = "yolov8n.yaml"   # change to yolov8m.yaml if you want bigger model

# -------------------------------
# Initialize results file
# -------------------------------
if Path(RESULTS_CSV).exists():
    results_df = pd.read_csv(RESULTS_CSV)
else:
    results_df = pd.DataFrame(columns=[
        "Activation", "Epochs", "Batch", "Optimizer", "lr0", "Weight Decay",
        "Image Size", "Freeze", "Training Time (s)",
        "Precision", "Recall", "mAP@0.5", "mAP@0.5:0.95"
    ])

# -------------------------------
# Baseline training params
# -------------------------------
BASE_PARAMS = {
    "epochs": 32,      # small for demo, increase later
    "batch": 32,
    "lr0": 0.05,
    "weight_decay": 0.0005,
    "optimizer": "SGD",
    "imgsz": 640,
    "freeze": 0
}

# -------------------------------
# Helper: Create new YAML with activation
# -------------------------------
def create_activation_yaml(base_yaml, act_expr, suffix):
    cfg = yaml_model_load(base_yaml)   # loads YOLO config from ultralytics
    cfg["activation"] = act_expr

    out_path = f"/kaggle/working/{Path(base_yaml).stem}_{suffix}.yaml"
    with open(out_path, "w") as f:
        yaml.dump(cfg, f)

    return out_path

# -------------------------------
# Case 9: Activation Functions
# -------------------------------
activations = {
    "ReLU": ("nn.ReLU()", "relu"),
    "LeakyReLU": ("nn.LeakyReLU(0.1)", "leakyrelu"),
    "Mish": ("nn.Mish()", "mish"),
    "SiLU": ("nn.SiLU()", "silu")
}

all_results = []

for act_name, (act_expr, suffix) in activations.items():
    print(f"\n🚀 Training with {act_name} activation...")

    # Create activation YAML
    yaml_path = create_activation_yaml(BASE_MODEL, act_expr, suffix)

    # Init model from YAML
    model = YOLO(yaml_path)

    # Train
    start = time.time()
    model.train(
        data=DATA_PATH,
        epochs=BASE_PARAMS["epochs"],
        batch=BASE_PARAMS["batch"],
        lr0=BASE_PARAMS["lr0"],
        optimizer=BASE_PARAMS["optimizer"],
        imgsz=BASE_PARAMS["imgsz"],
        weight_decay=BASE_PARAMS["weight_decay"],
        freeze=BASE_PARAMS["freeze"],
        verbose=False
    )
    train_time = time.time() - start

    # Load YOLO's results.csv (last row)
    results_file = Path(model.trainer.save_dir) / "results.csv"
    df_metrics = pd.read_csv(results_file)
    last = df_metrics.iloc[-1]

    result = {
        "Activation": act_name,
        "Epochs": BASE_PARAMS["epochs"],
        "Batch": BASE_PARAMS["batch"],
        "Optimizer": BASE_PARAMS["optimizer"],
        "lr0": BASE_PARAMS["lr0"],
        "Weight Decay": BASE_PARAMS["weight_decay"],
        "Image Size": BASE_PARAMS["imgsz"],
        "Freeze": BASE_PARAMS["freeze"],
        "Training Time (s)": round(train_time, 2),
        "Precision": last["metrics/precision(B)"],
        "Recall": last["metrics/recall(B)"],
        "mAP@0.5": last["metrics/mAP50(B)"],
        "mAP@0.5:0.95": last["metrics/mAP50-95(B)"]
    }

    results_df = pd.concat([results_df, pd.DataFrame([result])], ignore_index=True)
    results_df.to_csv(RESULTS_CSV, index=False)

    all_results.append(result)

# -------------------------------
# Show final results
# -------------------------------
print("\n📊 Case 9 Results:\n")
print(tabulate(pd.DataFrame(all_results), headers="keys", tablefmt="grid"))

🚀 Training with ReLU activation...
Ultralytics 8.3.193 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.05, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=/kaggle/working/yolov8n_relu.yaml, momentum=0.937, mosaic=1.0, multi_scale=False, name=train4, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=/kaggle/working/runs/detect/train4, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=1
activation: nn.ReLU()

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    751507  ultralytics.nn.modules.head.Detect           [1, [64, 128, 256]]
YOLOv8n_relu summary: 129 layers, 3,011,043 parameters, 3,011,027 gradients, 8.2 GFLOPs

Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 101.0±26.8 MB/s, size: 52.0 KB)
train: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train/labels... 1200 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1200/1200 912.3it/s 1.3s0.1s
WARNING ⚠️ train: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 47.1±36.8 MB/s, size: 61.5 KB)
val: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels... 300 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 300/300 448.2it/s 0.7s0.1s
WARNING ⚠️ val: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val is not writeable, cache not saved.
Plotting labels to /kaggle/working/runs/detect/train4/labels.jpg...
optimizer: SGD(lr=0.05, momentum=0.937) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to /kaggle/working/runs/detect/train4
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/32      3.51G      3.771      3.166      3.658        145        640: 100% ━━━━━━━━━━━━ 38/38 2.9it/s 13.1s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5s0.4s
                   all        300       1798          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/32      3.85G       2.31      1.924      2.233        166        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.6it/s 1.4s0.4s
                   all        300       1798     0.0111      0.112    0.00977    0.00301

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/32      3.85G      2.047      1.868      1.947        166        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.8it/s 1.8s0.5s
                   all        300       1798      0.196      0.581      0.259     0.0754

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/32      3.85G      1.859      1.691      1.796        136        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.5it/s 2.0s0.5s
                   all        300       1798   5.57e-05    0.00278   2.91e-05   7.51e-06

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/32      3.85G      1.622      1.545      1.566        165        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.5it/s 2.0s0.5s
                   all        300       1798   5.56e-05    0.00278   2.79e-05   1.01e-05

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/32      3.85G      1.533       1.24      1.498        171        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.6it/s 1.9s0.5s
                   all        300       1798    0.00246    0.00167   9.38e-05   1.87e-05

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/32      3.85G      1.507     0.9628      1.473        167        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7s0.4s
                   all        300       1798     0.0914      0.089     0.0232    0.00397

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/32      3.85G      1.474     0.8701      1.432        141        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.5it/s 1.4s0.4s
                   all        300       1798      0.434      0.334      0.263     0.0534

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/32      3.85G      1.452     0.8109      1.436        129        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6s0.4s
                   all        300       1798      0.801      0.687      0.721      0.295

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/32      3.85G      1.431      0.773       1.41        153        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.5it/s 1.4s0.4s
                   all        300       1798      0.654      0.484      0.459      0.125

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/32      3.85G      1.397     0.7083      1.373        192        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.6it/s 1.4s0.4s
                   all        300       1798      0.394      0.271      0.223     0.0598

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/32      3.85G      1.358     0.7042       1.35        186        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6s0.4s
                   all        300       1798      0.861      0.871      0.881      0.393

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/32      3.85G      1.352     0.6807      1.364        168        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5s0.4s
                   all        300       1798      0.982      0.973      0.984      0.617

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/32      3.85G      1.321     0.6576       1.33        169        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5s0.4s
                   all        300       1798      0.976      0.964      0.986       0.62

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/32      3.85G      1.321      0.636      1.342        156        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5s0.4s
                   all        300       1798      0.892      0.918      0.925        0.4

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/32      3.85G      1.323     0.6342      1.341        176        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5s0.4s
                   all        300       1798      0.839      0.708      0.801      0.353

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/32      3.85G      1.312     0.6206      1.315        188        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5s0.4s
                   all        300       1798      0.977      0.977      0.983       0.62

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/32      3.85G      1.295      0.614      1.314        169        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5s0.4s
                   all        300       1798      0.966      0.962      0.967      0.541

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/32      3.85G      1.278     0.6002      1.292        155        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.5s0.4s
                   all        300       1798       0.99      0.984      0.994      0.631

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/32      3.85G      1.272     0.5819      1.296        180        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5s0.4s
                   all        300       1798      0.982      0.974      0.987      0.624

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/32      3.85G       1.26     0.5781      1.296        174        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5s0.4s
                   all        300       1798      0.975      0.973      0.976        0.6

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/32      3.85G      1.235     0.5636      1.278        149        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5s0.4s
                   all        300       1798      0.987      0.982      0.991      0.665
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/32      3.85G      1.203     0.5226      1.364         96        640: 100% ━━━━━━━━━━━━ 38/38 2.8it/s 13.5s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.6it/s 1.4s0.4s
                   all        300       1798      0.607      0.187      0.244     0.0977

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/32      3.85G      1.194     0.5172      1.362        100        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.7s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5s0.4s
                   all        300       1798      0.933      0.915      0.955      0.528

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/32      3.85G      1.173     0.5034      1.349         99        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.7s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.5s0.4s
                   all        300       1798      0.885      0.845      0.893      0.468

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/32      3.86G      1.175     0.4848      1.343        100        640: 100% ━━━━━━━━━━━━ 38/38 3.3it/s 11.7s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.5it/s 1.4s0.4s
                   all        300       1798      0.985       0.98      0.987      0.492

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/32      3.87G      1.165     0.4804      1.328         82        640: 100% ━━━━━━━━━━━━ 38/38 3.3it/s 11.6s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5s0.4s
                   all        300       1798      0.988      0.991      0.994       0.64

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/32      3.88G      1.148     0.4715      1.328         92        640: 100% ━━━━━━━━━━━━ 38/38 3.3it/s 11.7s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.5it/s 1.4s0.4s
                   all        300       1798      0.987      0.985      0.992      0.653

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/32       3.9G      1.136     0.4634      1.316         96        640: 100% ━━━━━━━━━━━━ 38/38 3.3it/s 11.6s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.5it/s 1.4s0.4s
                   all        300       1798      0.989      0.991      0.993      0.691

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/32      3.91G      1.127     0.4596      1.303         89        640: 100% ━━━━━━━━━━━━ 38/38 3.3it/s 11.7s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5s0.4s
                   all        300       1798      0.987      0.989      0.993      0.681

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/32      3.92G       1.12     0.4553        1.3         93        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.7s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5s0.4s
                   all        300       1798       0.99      0.992      0.993      0.686

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/32      3.93G      1.118     0.4491      1.296         99        640: 100% ━━━━━━━━━━━━ 38/38 3.3it/s 11.6s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5s0.4s
                   all        300       1798       0.99      0.991      0.993      0.698

32 epochs completed in 0.122 hours.
Optimizer stripped from /kaggle/working/runs/detect/train4/weights/last.pt, 6.2MB
Optimizer stripped from /kaggle/working/runs/detect/train4/weights/best.pt, 6.2MB

Validating /kaggle/working/runs/detect/train4/weights/best.pt...
Ultralytics 8.3.193 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
YOLOv8n_relu summary (fused): 72 layers, 3,005,843 parameters, 0 gradients, 8.1 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.7s

/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        300       1798       0.99      0.991      0.993      0.698
Speed: 0.1ms preprocess, 1.4ms inference, 0.0ms loss, 3.1ms postprocess per image
Results saved to /kaggle/working/runs/detect/train4

🚀 Training with LeakyReLU activation...
Ultralytics 8.3.193 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.05, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=/kaggle/working/yolov8n_leakyrelu.yaml, momentum=0.937, mosaic=1.0, multi_scale=False, name=train5, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=/kaggle/working/runs/detect/train5, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=1
activation: nn.LeakyReLU(0.1)

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    751507  ultralytics.nn.modules.head.Detect           [1, [64, 128, 256]]
YOLOv8n_leakyrelu summary: 129 layers, 3,011,043 parameters, 3,011,027 gradients, 8.2 GFLOPs

Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 87.8±38.0 MB/s, size: 52.0 KB)
train: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train/labels... 1200 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1200/1200 1.0Kit/s 1.2s0.1s
WARNING ⚠️ train: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 76.9±40.9 MB/s, size: 61.5 KB)
val: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels... 300 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 300/300 545.8it/s 0.5s0.0s
WARNING ⚠️ val: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val is not writeable, cache not saved.
Plotting labels to /kaggle/working/runs/detect/train5/labels.jpg...
optimizer: SGD(lr=0.05, momentum=0.937) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to /kaggle/working/runs/detect/train5
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/32      3.37G      3.539       3.02      3.447        145        640: 100% ━━━━━━━━━━━━ 38/38 3.0it/s 12.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5s0.4s
                   all        300       1798          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/32      3.72G      2.239      1.835      2.154        166        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.6it/s 1.4s0.4s
                   all        300       1798          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/32      3.72G      2.148      1.655      2.035        166        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.7it/s 1.8s0.5s
                   all        300       1798      0.276      0.873      0.263     0.0749

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/32      3.72G      1.924      1.384      1.822        136        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.6it/s 2.0s0.5s
                   all        300       1798    0.00312       0.15    0.00179   0.000427

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/32      3.72G      1.714      1.121      1.607        165        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.7it/s 1.8s0.5s
                   all        300       1798     0.0228      0.359     0.0125    0.00272

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/32      3.72G      1.562      1.008      1.499        171        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.6it/s 1.9s0.5s
                   all        300       1798   0.000213    0.00445   5.69e-05   9.72e-06

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/32      3.72G      1.476     0.9226      1.439        167        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.5s0.4s
                   all        300       1798      0.631       0.62      0.591      0.184

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/32      3.72G      1.446     0.8979      1.408        141        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.4it/s 2.1s0.6s
                   all        300       1798          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/32      3.72G      1.424     0.8574       1.41        129        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.6s0.4s
                   all        300       1798      0.715      0.496      0.555      0.174

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/32      3.72G      1.394     0.8186      1.382        153        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6s0.5s
                   all        300       1798       0.13      0.079     0.0231    0.00524

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/32      3.72G      1.374     0.7406       1.36        192        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.6it/s 1.9s0.5s
                   all        300       1798          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/32      3.72G      1.348     0.7375      1.341        186        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.9it/s 1.7s0.5s
                   all        300       1798      0.938       0.94      0.954      0.494

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/32      3.72G       1.34     0.7109      1.356        168        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.8it/s 1.8s0.5s
                   all        300       1798     0.0506     0.0156    0.00276   0.000532

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/32      3.72G      1.313     0.6878      1.328        169        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.8it/s 1.8s0.5s
                   all        300       1798      0.827      0.862      0.899      0.477

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/32      3.72G      1.312     0.6736      1.336        156        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.6it/s 1.9s0.5s
                   all        300       1798    0.00239    0.00278   8.57e-05   1.52e-05

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/32      3.72G      1.317     0.6584      1.337        176        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5s0.4s
                   all        300       1798       0.87      0.629      0.717      0.268

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/32      3.72G        1.3     0.6502      1.313        188        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5s0.4s
                   all        300       1798      0.905      0.907      0.933      0.549

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/32      3.72G      1.286     0.6366      1.309        169        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6s0.4s
                   all        300       1798      0.966      0.971      0.985      0.583

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/32      3.72G      1.286     0.6205      1.297        155        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5s0.4s
                   all        300       1798       0.98      0.974      0.982      0.618

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/32      3.72G      1.262     0.6025      1.294        180        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6s0.4s
                   all        300       1798       0.98      0.968      0.979      0.609

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/32      3.72G      1.254     0.6002      1.296        174        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5s0.4s
                   all        300       1798      0.932      0.944      0.954      0.514

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/32      3.72G      1.241      0.576      1.282        149        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.5it/s 1.4s0.4s
                   all        300       1798      0.989      0.988      0.993       0.65
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/32      3.72G      1.192     0.5443      1.356         96        640: 100% ━━━━━━━━━━━━ 38/38 2.9it/s 13.3s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5s0.4s
                   all        300       1798      0.683      0.587      0.597      0.201

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/32      3.72G      1.183     0.5325      1.355        100        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6s0.4s
                   all        300       1798      0.984      0.972       0.99      0.512

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/32      3.73G      1.181     0.5243      1.352         99        640: 100% ━━━━━━━━━━━━ 38/38 3.3it/s 11.6s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.5it/s 1.4s0.4s
                   all        300       1798      0.988      0.987      0.993      0.684

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/32      3.74G      1.172     0.5108      1.336        100        640: 100% ━━━━━━━━━━━━ 38/38 3.3it/s 11.6s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5s0.4s
                   all        300       1798      0.608      0.296      0.326       0.16

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/32      3.76G      1.151     0.4973      1.317         82        640: 100% ━━━━━━━━━━━━ 38/38 3.3it/s 11.7s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.5it/s 1.4s0.4s
                   all        300       1798      0.992      0.986      0.993      0.636

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/32      3.77G      1.144     0.4911      1.325         92        640: 100% ━━━━━━━━━━━━ 38/38 3.3it/s 11.7s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5s0.4s
                   all        300       1798      0.993       0.99      0.994      0.682

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/32      3.78G      1.136     0.4775      1.317         96        640: 100% ━━━━━━━━━━━━ 38/38 3.3it/s 11.6s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.5it/s 1.4s0.4s
                   all        300       1798      0.984      0.991      0.992      0.658

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/32      3.79G      1.132     0.4705      1.305         89        640: 100% ━━━━━━━━━━━━ 38/38 3.3it/s 11.6s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5s0.4s
                   all        300       1798      0.903      0.808      0.874      0.403

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/32       3.8G      1.118     0.4664      1.298         93        640: 100% ━━━━━━━━━━━━ 38/38 3.3it/s 11.6s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.6it/s 1.4s0.4s
                   all        300       1798      0.989      0.992      0.993        0.7

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/32      3.81G      1.114     0.4624      1.293         99        640: 100% ━━━━━━━━━━━━ 38/38 3.3it/s 11.7s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5s0.4s
                   all        300       1798      0.992      0.991      0.993      0.699

32 epochs completed in 0.122 hours.
Optimizer stripped from /kaggle/working/runs/detect/train5/weights/last.pt, 6.2MB
Optimizer stripped from /kaggle/working/runs/detect/train5/weights/best.pt, 6.2MB

Validating /kaggle/working/runs/detect/train5/weights/best.pt...
Ultralytics 8.3.193 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)

/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        300       1798      0.989      0.992      0.993        0.7
Speed: 0.1ms preprocess, 1.4ms inference, 0.0ms loss, 3.3ms postprocess per image
Results saved to /kaggle/working/runs/detect/train5

🚀 Training with Mish activation...
Ultralytics 8.3.193 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.05, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=/kaggle/working/yolov8n_mish.yaml, momentum=0.937, mosaic=1.0, multi_scale=False, name=train6, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=/kaggle/working/runs/detect/train6, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=1
activation: nn.Mish()

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    751507  ultralytics.nn.modules.head.Detect           [1, [64, 128, 256]]
YOLOv8n_mish summary: 129 layers, 3,011,043 parameters, 3,011,027 gradients, 8.2 GFLOPs

Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 84.2±40.3 MB/s, size: 52.0 KB)
train: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train/labels... 1200 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1200/1200 1.0Kit/s 1.2s0.0s
WARNING ⚠️ train: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 68.1±34.8 MB/s, size: 61.5 KB)
val: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels... 300 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 300/300 540.5it/s 0.6s0.0s
WARNING ⚠️ val: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val is not writeable, cache not saved.
Plotting labels to /kaggle/working/runs/detect/train6/labels.jpg...
optimizer: SGD(lr=0.05, momentum=0.937) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to /kaggle/working/runs/detect/train6
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/32      4.25G      3.493      2.832      3.383        145        640: 100% ━━━━━━━━━━━━ 38/38 2.9it/s 13.2s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.5it/s 1.4s0.4s
                   all        300       1798          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/32       4.6G      2.236      1.875      2.137        166        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.4s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5s0.4s
                   all        300       1798      0.439      0.519      0.398      0.132

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/32       4.6G      2.025      1.774      1.955        166        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.5it/s 2.0s0.5s
                   all        300       1798     0.0886      0.452      0.052     0.0119

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/32       4.6G      1.795      1.516       1.73        136        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.6it/s 1.9s0.5s
                   all        300       1798   0.000432     0.0172   0.000228   5.02e-05

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/32       4.6G      1.644      1.062      1.567        165        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.7it/s 1.9s0.5s
                   all        300       1798    0.00208    0.00167   0.000167   3.01e-05

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/32       4.6G      1.567     0.8936        1.5        171        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.6it/s 1.9s0.5s
                   all        300       1798   2.22e-05    0.00111   1.11e-05   3.89e-06

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/32       4.6G      1.461     0.8131      1.433        167        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.6it/s 1.9s0.5s
                   all        300       1798   0.000353    0.00111   4.71e-05   5.91e-06

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/32       4.6G      1.438     0.8041      1.404        141        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.8it/s 1.8s0.5s
                   all        300       1798     0.0314    0.00723    0.00423   0.000616

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/32       4.6G      1.416     0.7737      1.409        129        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5s0.4s
                   all        300       1798      0.971       0.97      0.975      0.588

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/32       4.6G       1.39     0.7423      1.379        153        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5s0.4s
                   all        300       1798       0.44       0.48      0.422      0.205

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/32       4.6G      1.355     0.6909      1.351        192        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.3s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5s0.4s
                   all        300       1798      0.956      0.958      0.962      0.547

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/32       4.6G       1.33     0.6812      1.328        186        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5s0.4s
                   all        300       1798      0.982      0.972      0.981      0.623

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/32       4.6G      1.333     0.6612      1.352        168        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5s0.4s
                   all        300       1798      0.566      0.492      0.499      0.191

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/32       4.6G      1.306     0.6393      1.321        169        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.5it/s 1.4s0.4s
                   all        300       1798      0.751       0.72      0.768      0.384

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/32       4.6G      1.303     0.6227      1.331        156        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.5it/s 1.4s0.4s
                   all        300       1798      0.968      0.966      0.971      0.556

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/32       4.6G      1.301     0.6186      1.327        176        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5s0.4s
                   all        300       1798      0.989      0.983      0.991      0.649

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/32       4.6G      1.297     0.6111       1.31        188        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5s0.4s
                   all        300       1798      0.843      0.868      0.884       0.41

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/32       4.6G      1.279     0.5933      1.303        169        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.3s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5s0.4s
                   all        300       1798      0.987      0.975      0.989       0.64

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/32       4.6G      1.271     0.5816      1.289        155        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5s0.4s
                   all        300       1798      0.987      0.985      0.992      0.651

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/32       4.6G      1.254     0.5689      1.287        180        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.5it/s 1.4s0.4s
                   all        300       1798      0.714      0.638      0.688      0.283

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/32       4.6G       1.24     0.5624      1.286        174        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5s0.4s
                   all        300       1798      0.984      0.986      0.991      0.644

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/32       4.6G      1.227     0.5487      1.272        149        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5s0.4s
                   all        300       1798      0.991      0.984      0.992      0.662
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/32       4.6G      1.178     0.5139      1.345         96        640: 100% ━━━━━━━━━━━━ 38/38 2.7it/s 13.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5s0.4s
                   all        300       1798      0.988       0.99      0.993      0.664

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/32       4.6G      1.183     0.4947      1.356        100        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5s0.4s
                   all        300       1798      0.993      0.984      0.994      0.638

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/32      4.61G      1.166     0.4914      1.342         99        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.1s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5s0.4s
                   all        300       1798      0.985      0.976      0.991       0.63

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/32      4.62G      1.163     0.4802       1.33        100        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5s0.4s
                   all        300       1798      0.991      0.988      0.992      0.684

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/32      4.63G       1.15     0.4691      1.318         82        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5s0.4s
                   all        300       1798      0.992      0.987      0.994      0.552

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/32      4.64G      1.136     0.4625      1.316         92        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5s0.4s
                   all        300       1798      0.995      0.988      0.994      0.674

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/32      4.65G      1.131     0.4493      1.313         96        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5s0.4s
                   all        300       1798      0.991       0.99      0.992      0.648

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/32      4.67G      1.121      0.446      1.298         89        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.5it/s 1.4s0.4s
                   all        300       1798       0.99      0.991      0.994      0.686

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/32      4.68G      1.102     0.4399      1.288         93        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5s0.4s
                   all        300       1798      0.994       0.99      0.994      0.682

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/32      4.69G      1.096     0.4362       1.28         99        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.5it/s 1.4s0.4s
                   all        300       1798      0.995      0.989      0.995        0.7

32 epochs completed in 0.125 hours.
Optimizer stripped from /kaggle/working/runs/detect/train6/weights/last.pt, 6.2MB
Optimizer stripped from /kaggle/working/runs/detect/train6/weights/best.pt, 6.2MB

Validating /kaggle/working/runs/detect/train6/weights/best.pt...
Ultralytics 8.3.193 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
YOLOv8n_mish summary (fused): 72 layers, 3,005,843 parameters, 0 gradients, 8.1 GFLOPs

/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        300       1798      0.995      0.989      0.995        0.7
Speed: 0.1ms preprocess, 1.5ms inference, 0.0ms loss, 3.0ms postprocess per image
Results saved to /kaggle/working/runs/detect/train6

🚀 Training with SiLU activation...
Ultralytics 8.3.193 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.05, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=/kaggle/working/yolov8n_silu.yaml, momentum=0.937, mosaic=1.0, multi_scale=False, name=train7, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=/kaggle/working/runs/detect/train7, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=1
activation: nn.SiLU()

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    751507  ultralytics.nn.modules.head.Detect           [1, [64, 128, 256]]
YOLOv8n_silu summary: 129 layers, 3,011,043 parameters, 3,011,027 gradients, 8.2 GFLOPs

Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 91.1±35.4 MB/s, size: 52.0 KB)
train: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train/labels... 1200 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1200/1200 934.9it/s 1.3s0.0s
WARNING ⚠️ train: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 81.2±39.0 MB/s, size: 61.5 KB)
val: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels... 300 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 300/300 511.2it/s 0.6s0.1s
WARNING ⚠️ val: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val is not writeable, cache not saved.
Plotting labels to /kaggle/working/runs/detect/train7/labels.jpg...
optimizer: SGD(lr=0.05, momentum=0.937) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to /kaggle/working/runs/detect/train7
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/32      4.27G      3.527      2.897      3.425        145        640: 100% ━━━━━━━━━━━━ 38/38 2.9it/s 13.1s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6s0.4s
                   all        300       1798          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/32      4.61G      2.215       1.75      2.104        166        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.3s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.6it/s 1.4s0.4s
                   all        300       1798          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/32      4.61G       1.98      1.698      1.879        166        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.1s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.8it/s 1.8s0.5s
                   all        300       1798     0.0387      0.977     0.0393     0.0185

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/32      4.61G      1.806      1.768      1.747        136        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.4it/s 2.1s0.5s
                   all        300       1798   5.56e-05    0.00278    2.8e-05   4.47e-06

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/32      4.61G      1.619      1.311      1.567        165        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.6it/s 1.9s0.5s
                   all        300       1798    0.00382      0.191    0.00228   0.000757

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/32      4.61G      1.592     0.9308      1.521        171        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6s0.4s
                   all        300       1798          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/32      4.61G      1.501     0.8285       1.46        167        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7s0.4s
                   all        300       1798      0.294      0.259      0.196     0.0528

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/32      4.61G       1.45     0.8114      1.411        141        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.6s0.4s
                   all        300       1798      0.516      0.474      0.439      0.137

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/32      4.61G      1.428     0.7811      1.417        129        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.6it/s 1.4s0.4s
                   all        300       1798      0.578      0.437      0.446      0.125

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/32      4.61G      1.397     0.7506      1.386        153        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5s0.4s
                   all        300       1798      0.806      0.795      0.822      0.353

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/32      4.61G      1.359     0.7047      1.356        192        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5s0.4s
                   all        300       1798      0.982      0.973      0.983      0.627

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/32      4.61G      1.343     0.6957      1.338        186        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5s0.4s
                   all        300       1798      0.034     0.0367    0.00677    0.00147

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/32      4.61G      1.338     0.6783      1.353        168        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5s0.4s
                   all        300       1798      0.849      0.752      0.824       0.41

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/32      4.61G      1.304     0.6479      1.322        169        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.5s0.4s
                   all        300       1798     0.0241     0.0284    0.00802    0.00301

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/32      4.61G      1.314     0.6331      1.338        156        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.1s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5s0.4s
                   all        300       1798       0.87       0.88      0.893      0.387

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/32      4.61G      1.309     0.6264      1.334        176        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.5it/s 1.4s0.4s
                   all        300       1798       0.98      0.974      0.988      0.618

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/32      4.61G      1.299     0.6109      1.311        188        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5s0.4s
                   all        300       1798      0.976      0.961      0.981       0.59

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/32      4.61G      1.279     0.5994      1.304        169        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5s0.4s
                   all        300       1798       0.99      0.988      0.994      0.652

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/32      4.61G       1.27     0.5876       1.29        155        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5s0.4s
                   all        300       1798      0.991      0.985      0.993      0.646

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/32      4.61G      1.263     0.5684      1.295        180        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.5it/s 1.4s0.4s
                   all        300       1798      0.965      0.962      0.974       0.57

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/32      4.61G      1.247     0.5754      1.292        174        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5s0.4s
                   all        300       1798      0.993      0.992      0.994      0.643

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/32      4.61G      1.229     0.5569      1.275        149        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.6it/s 1.4s0.4s
                   all        300       1798      0.987      0.983      0.992      0.652
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/32      4.61G      1.183     0.5144      1.351         96        640: 100% ━━━━━━━━━━━━ 38/38 2.8it/s 13.7s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5s0.4s
                   all        300       1798      0.988      0.991      0.994      0.667

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/32      4.61G      1.174     0.5036      1.351        100        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5s0.4s
                   all        300       1798       0.99      0.981      0.993      0.646

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/32      4.62G      1.174     0.4888      1.346         99        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.6it/s 1.4s0.4s
                   all        300       1798      0.994      0.989      0.993      0.672

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/32      4.62G      1.174     0.4792      1.336        100        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5s0.4s
                   all        300       1798      0.983      0.981      0.992      0.623

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/32      4.64G      1.151     0.4711      1.318         82        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5s0.4s
                   all        300       1798      0.987      0.987      0.993      0.569

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/32      4.65G      1.138     0.4663      1.321         92        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.6it/s 1.4s0.4s
                   all        300       1798      0.992      0.988      0.994       0.68

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/32      4.66G      1.126      0.451      1.312         96        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.5it/s 1.4s0.4s
                   all        300       1798      0.987      0.989      0.992      0.673

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/32      4.67G      1.122     0.4485      1.299         89        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.5it/s 1.4s0.4s
                   all        300       1798      0.995      0.992      0.994       0.69

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/32      4.68G      1.108     0.4393      1.292         93        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5s0.4s
                   all        300       1798      0.994      0.991      0.993      0.689

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/32      4.69G      1.103     0.4326      1.287         99        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.6it/s 1.4s0.4s
                   all        300       1798      0.994      0.992      0.994      0.706

32 epochs completed in 0.123 hours.
Optimizer stripped from /kaggle/working/runs/detect/train7/weights/last.pt, 6.2MB
Optimizer stripped from /kaggle/working/runs/detect/train7/weights/best.pt, 6.2MB

Validating /kaggle/working/runs/detect/train7/weights/best.pt...
Ultralytics 8.3.193 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
YOLOv8n_silu summary (fused): 72 layers, 3,005,843 parameters, 0 gradients, 8.1 GFLOPs

/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        300       1798      0.994      0.992      0.994      0.706
Speed: 0.1ms preprocess, 1.4ms inference, 0.0ms loss, 3.7ms postprocess per image
Results saved to /kaggle/working/runs/detect/train7

📊 Case 9 Results:

+----+--------------+----------+---------+-------------+-------+----------------+--------------+----------+---------------------+-------------+----------+-----------+----------------+
|    | Activation   |   Epochs |   Batch | Optimizer   |   lr0 |   Weight Decay |   Image Size |   Freeze |   Training Time (s) |   Precision |   Recall |   mAP@0.5 |   mAP@0.5:0.95 |
+====+==============+==========+=========+=============+=======+================+==============+==========+=====================+=============+==========+===========+================+
|  0 | ReLU         |       32 |      32 | SGD         |  0.05 |         0.0005 |          640 |        0 |              452.9  |     0.98989 |  0.99055 |   0.99332 |        0.69765 |
+----+--------------+----------+---------+-------------+-------+----------------+--------------+----------+---------------------+-------------+----------+-----------+----------------+
|  1 | LeakyReLU    |       32 |      32 | SGD         |  0.05 |         0.0005 |          640 |        0 |              454.44 |     0.99188 |  0.99055 |   0.99349 |        0.69943 |
+----+--------------+----------+---------+-------------+-------+----------------+--------------+----------+---------------------+-------------+----------+-----------+----------------+
|  2 | Mish         |       32 |      32 | SGD         |  0.05 |         0.0005 |          640 |        0 |              462.72 |     0.99476 |  0.98943 |   0.99451 |        0.70015 |
+----+--------------+----------+---------+-------------+-------+----------------+--------------+----------+---------------------+-------------+----------+-----------+----------------+
|  3 | SiLU         |       32 |      32 | SGD         |  0.05 |         0.0005 |          640 |        0 |              457.16 |     0.99372 |  0.99166 |   0.99385 |        0.70581 |
+----+--------------+----------+---------+-------------+-------+----------------+--------------+----------+---------------------+-------------+----------+-----------+----------------+

In [16]:
import yaml, copy

def create_activation_yaml(base_yaml="yolov8n.yaml", act_expr="nn.SiLU()", suffix="silu"):
    """
    Create a modified YOLOv8 YAML with a custom activation function.
    Returns the path to the new YAML.
    """
    with open(base_yaml, "r") as f:
        cfg = yaml.safe_load(f)

    # Set activation
    cfg["activation"] = act_expr

    # Build safe filename
    out_path = f"/kaggle/working/{Path(base_yaml).stem}_{suffix}.yaml"
    with open(out_path, "w") as f:
        yaml.dump(cfg, f)

    return out_path

In [17]:
# Case 9: Activation Functions
def case9_activation_functions():
    activations = {
        "ReLU": ("nn.ReLU()", "relu"),
        "LeakyReLU": ("nn.LeakyReLU(0.1)", "leakyrelu"),
        "Mish": ("nn.Mish()", "mish"),
        "SiLU": ("nn.SiLU()", "silu")  # baseline
    }

    for i, (act_name, (act_expr, suffix)) in enumerate(activations.items(), start=1):
        # Create activation-specific yaml
        yaml_path = create_activation_yaml("yolov8n.yaml", act_expr, suffix)

        # Temporarily override model init
        model = YOLO(yaml_path)

        # Run experiment (reuse logging)
        run_with_best("Case 9: Activation Functions", i, f"activation_{act_name}", activation=act_name)

In [18]:
case9_activation_functions()

FileNotFoundError: [Errno 2] No such file or directory: 'yolov8n.yaml'

In [8]:
case5_image_size()

Downloading https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov8n.pt to 'yolov8n.pt': 100% ━━━━━━━━━━━━ 6.2MB 131.1MB/s 0.0s
Ultralytics 8.3.193 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=320, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=/kaggle/working/runs/detect/train, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Downloading https://ultralytics.com/assets/Arial.ttf to '/root/.config/Ultralytics/Arial.ttf': 100% ━━━━━━━━━━━━ 755.1KB 23.2MB/s 0.0s
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    751507  ultralytics.nn.modules.head.Detect           [1, [64, 128, 256]]
Model summary: 129 layers, 3,011,043 parameters, 3,011,027 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
Downloading https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11n.pt to 'yolo11n.pt': 100% ━━━━━━━━━━━━ 5.4MB 102.0MB/s 0.1s
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 16.9±4.3 MB/s, size: 52.0 KB)
train: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train/labels... 1200 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1200/1200 379.4it/s 3.2s0.1s
WARNING ⚠️ train: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 15.9±5.9 MB/s, size: 61.5 KB)
val: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels... 300 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 300/300 312.6it/s 1.0s0.0s
WARNING ⚠️ val: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val is not writeable, cache not saved.
Plotting labels to /kaggle/working/runs/detect/train/labels.jpg...
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 320 train, 320 val
Using 4 dataloader workers
Logging results to /kaggle/working/runs/detect/train
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/32      1.12G      2.158       2.56      1.337        145        320: 100% ━━━━━━━━━━━━ 38/38 5.9it/s 6.5s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.5it/s 2.0s0.4ss
                   all        300       1798       0.99      0.477      0.966      0.514

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/32      1.13G      1.528     0.9473      1.069        166        320: 100% ━━━━━━━━━━━━ 38/38 7.3it/s 5.2s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 4.5it/s 1.1s0.3s
                   all        300       1798      0.987      0.736      0.977      0.561

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/32      1.15G      1.509     0.8799      1.054        166        320: 100% ━━━━━━━━━━━━ 38/38 7.5it/s 5.0s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 4.2it/s 1.2s0.3s
                   all        300       1798      0.947      0.949      0.969      0.445

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/32      1.16G      1.469     0.8305       1.05        137        320: 100% ━━━━━━━━━━━━ 38/38 7.4it/s 5.1s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 4.5it/s 1.1s0.3s
                   all        300       1798      0.966      0.981      0.989      0.575

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/32      1.17G      1.413     0.7815      1.024        165        320: 100% ━━━━━━━━━━━━ 38/38 7.5it/s 5.0s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 4.9it/s 1.0s0.3s
                   all        300       1798      0.961      0.975      0.979      0.528

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/32      1.18G       1.36     0.7373      1.009        170        320: 100% ━━━━━━━━━━━━ 38/38 7.5it/s 5.1s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 4.6it/s 1.1s0.3s
                   all        300       1798      0.985      0.984      0.993      0.606

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/32      1.19G      1.331     0.6849     0.9981        167        320: 100% ━━━━━━━━━━━━ 38/38 7.6it/s 5.0s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 5.1it/s 1.0s0.3s
                   all        300       1798      0.991       0.99      0.993      0.571

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/32      1.21G      1.318     0.6626     0.9911        141        320: 100% ━━━━━━━━━━━━ 38/38 7.7it/s 5.0s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 4.9it/s 1.0s0.3s
                   all        300       1798      0.993      0.988      0.993       0.63

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/32      1.22G      1.294     0.6507     0.9969        129        320: 100% ━━━━━━━━━━━━ 38/38 7.5it/s 5.1s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 5.0it/s 1.0s0.3s
                   all        300       1798      0.981      0.978      0.983      0.417

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/32      1.23G      1.285     0.6203     0.9852        153        320: 100% ━━━━━━━━━━━━ 38/38 7.6it/s 5.0s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 4.9it/s 1.0s0.3s
                   all        300       1798      0.992      0.986      0.993       0.64

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/32      1.24G      1.263     0.6073     0.9786        191        320: 100% ━━━━━━━━━━━━ 38/38 7.6it/s 5.0s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 4.6it/s 1.1s0.3s
                   all        300       1798       0.99      0.984      0.992       0.61

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/32      1.25G      1.239     0.5945     0.9695        186        320: 100% ━━━━━━━━━━━━ 38/38 7.6it/s 5.0s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 5.1it/s 1.0s0.3s
                   all        300       1798      0.989      0.989      0.994      0.664

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/32      1.26G      1.228     0.5795     0.9753        168        320: 100% ━━━━━━━━━━━━ 38/38 7.5it/s 5.0s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 5.0it/s 1.0s0.3s
                   all        300       1798      0.986      0.985      0.994      0.654

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/32      1.28G      1.208     0.5672     0.9642        169        320: 100% ━━━━━━━━━━━━ 38/38 7.6it/s 5.0s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 4.8it/s 1.0s0.3s
                   all        300       1798      0.991      0.991      0.994      0.662

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/32      1.29G      1.209     0.5552     0.9686        156        320: 100% ━━━━━━━━━━━━ 38/38 7.5it/s 5.0s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 5.0it/s 1.0s0.3s
                   all        300       1798      0.994      0.991      0.994      0.665

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/32       1.3G      1.209      0.551     0.9637        176        320: 100% ━━━━━━━━━━━━ 38/38 7.6it/s 5.0s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 5.2it/s 1.0s0.3s
                   all        300       1798      0.991      0.992      0.993      0.623

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/32      1.31G      1.188     0.5434     0.9564        188        320: 100% ━━━━━━━━━━━━ 38/38 7.5it/s 5.1s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 5.0it/s 1.0s0.3s
                   all        300       1798      0.994      0.988      0.994      0.674

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/32      1.32G      1.181     0.5282     0.9556        169        320: 100% ━━━━━━━━━━━━ 38/38 7.7it/s 5.0s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 4.7it/s 1.1s0.3s
                   all        300       1798      0.991       0.99      0.994      0.677

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/32      1.33G      1.166     0.5239     0.9466        155        320: 100% ━━━━━━━━━━━━ 38/38 7.6it/s 5.0s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 5.1it/s 1.0s0.3s
                   all        300       1798      0.992      0.992      0.994       0.66

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/32      1.34G      1.153     0.5167     0.9442        179        320: 100% ━━━━━━━━━━━━ 38/38 7.6it/s 5.0s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 5.3it/s 0.9s0.3s
                   all        300       1798      0.998      0.989      0.994      0.684

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/32      1.36G      1.137      0.507     0.9476        173        320: 100% ━━━━━━━━━━━━ 38/38 7.6it/s 5.0s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 5.3it/s 0.9s0.3s
                   all        300       1798      0.996      0.993      0.994      0.697

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/32      1.37G      1.125     0.5015     0.9416        149        320: 100% ━━━━━━━━━━━━ 38/38 7.6it/s 5.0s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 4.8it/s 1.0s0.3s
                   all        300       1798      0.993      0.992      0.994      0.699
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/32      1.38G      1.099     0.4817     0.9615         96        320: 100% ━━━━━━━━━━━━ 38/38 6.5it/s 5.9s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 5.2it/s 1.0s0.3s
                   all        300       1798      0.992      0.991      0.994      0.666

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/32      1.39G      1.084      0.469     0.9634        100        320: 100% ━━━━━━━━━━━━ 38/38 7.7it/s 4.9s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 5.1it/s 1.0s0.3s
                   all        300       1798      0.995       0.99      0.994      0.703

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/32       1.4G      1.052     0.4552     0.9493         99        320: 100% ━━━━━━━━━━━━ 38/38 7.7it/s 5.0s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 4.8it/s 1.0s0.3s
                   all        300       1798      0.996      0.991      0.994      0.699

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/32      1.41G      1.048     0.4486     0.9438        100        320: 100% ━━━━━━━━━━━━ 38/38 7.8it/s 4.9s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 5.2it/s 1.0s0.3s
                   all        300       1798      0.995      0.993      0.994      0.704

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/32      1.42G      1.027     0.4355     0.9388         82        320: 100% ━━━━━━━━━━━━ 38/38 7.9it/s 4.8s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 5.2it/s 1.0s0.3s
                   all        300       1798      0.998      0.992      0.994      0.674

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/32      1.43G      1.019     0.4355     0.9401         92        320: 100% ━━━━━━━━━━━━ 38/38 7.8it/s 4.9s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 5.1it/s 1.0s0.3s
                   all        300       1798      0.996      0.992      0.994      0.711

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/32      1.45G      1.021     0.4298     0.9394         96        320: 100% ━━━━━━━━━━━━ 38/38 7.8it/s 4.9s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 4.8it/s 1.0s0.3s
                   all        300       1798      0.996      0.993      0.994      0.706

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/32      1.46G      1.013     0.4258     0.9322         89        320: 100% ━━━━━━━━━━━━ 38/38 7.8it/s 4.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 4.7it/s 1.1s0.3s
                   all        300       1798      0.998      0.993      0.995      0.708

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/32      1.47G     0.9954     0.4191     0.9305         93        320: 100% ━━━━━━━━━━━━ 38/38 7.7it/s 4.9s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 5.0it/s 1.0s0.3s
                   all        300       1798      0.997      0.993      0.994      0.719

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/32      1.48G     0.9944     0.4164     0.9283         99        320: 100% ━━━━━━━━━━━━ 38/38 7.8it/s 4.9s0.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 4.9it/s 1.0s0.3s
                   all        300       1798      0.998      0.993      0.994      0.717

32 epochs completed in 0.057 hours.
Optimizer stripped from /kaggle/working/runs/detect/train/weights/last.pt, 6.2MB
Optimizer stripped from /kaggle/working/runs/detect/train/weights/best.pt, 6.2MB

Validating /kaggle/working/runs/detect/train/weights/best.pt...

/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        300       1798      0.997      0.993      0.994      0.719
Speed: 0.0ms preprocess, 0.4ms inference, 0.0ms loss, 1.1ms postprocess per image
Results saved to /kaggle/working/runs/detect/train

,Case,Exp No,Experiment Name,Epochs,Batch,lr0,Weight Decay,Optimizer,Image Size,Dropout,Freeze Layers,Activation,Training Time (s),Precision,Recall,mAP@0.5,mAP@0.5:0.95
0,Case 5: Image Size,1,imgsz_320,32,32,0.01,0.0005,SGD,320,0.0,0,SiLU,226.53,0.99776,0.9931,0.99448,0.71656

Ultralytics 8.3.193 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=512, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train2, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=/kaggle/working/runs/detect/train2, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    751507  ultralytics.nn.modules.head.Detect           [1, [64, 128, 256]]
Model summary: 129 layers, 3,011,043 parameters, 3,011,027 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 88.8±25.3 MB/s, size: 52.0 KB)
train: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train/labels... 1200 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1200/1200 983.7it/s 1.2s0.1s
WARNING ⚠️ train: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 77.2±37.2 MB/s, size: 61.5 KB)
val: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels... 300 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 300/300 504.1it/s 0.6s0.1s
WARNING ⚠️ val: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val is not writeable, cache not saved.
Plotting labels to /kaggle/working/runs/detect/train2/labels.jpg...
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 512 train, 512 val
Using 4 dataloader workers
Logging results to /kaggle/working/runs/detect/train2
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/32      2.77G      2.036      2.575      1.481        144        512: 100% ━━━━━━━━━━━━ 38/38 3.9it/s 9.7s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.8it/s 1.8s0.4s
                   all        300       1798      0.969      0.825      0.951      0.535

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/32      2.77G      1.393      1.017      1.211        166        512: 100% ━━━━━━━━━━━━ 38/38 4.2it/s 9.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.6it/s 1.4s0.4s
                   all        300       1798      0.986      0.916      0.981      0.622

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/32      2.77G       1.37     0.9347      1.168        166        512: 100% ━━━━━━━━━━━━ 38/38 4.3it/s 8.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.7it/s 1.4s0.4s
                   all        300       1798      0.977      0.985      0.992      0.607

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/32      2.77G      1.332     0.8687      1.162        136        512: 100% ━━━━━━━━━━━━ 38/38 4.3it/s 8.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.8it/s 1.3s0.3s
                   all        300       1798      0.964      0.969      0.966       0.39

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/32      2.77G      1.315       0.78      1.136        165        512: 100% ━━━━━━━━━━━━ 38/38 4.3it/s 8.8s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.7it/s 1.3s0.4s
                   all        300       1798      0.982      0.982       0.99      0.543

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/32      2.77G      1.271     0.7316      1.125        171        512: 100% ━━━━━━━━━━━━ 38/38 4.3it/s 8.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 4.0it/s 1.3s0.3s
                   all        300       1798       0.99      0.988      0.993      0.649

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/32      2.77G      1.241     0.6685       1.12        167        512: 100% ━━━━━━━━━━━━ 38/38 4.3it/s 8.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.7it/s 1.3s0.4s
                   all        300       1798       0.98      0.987      0.991      0.582

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/32      2.77G      1.251     0.6416      1.115        141        512: 100% ━━━━━━━━━━━━ 38/38 4.3it/s 8.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 4.1it/s 1.2s0.3s
                   all        300       1798      0.992      0.984      0.992      0.529

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/32      2.77G       1.23     0.6355      1.122        129        512: 100% ━━━━━━━━━━━━ 38/38 4.3it/s 8.8s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.9it/s 1.3s0.4s
                   all        300       1798      0.983       0.98      0.993      0.628

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/32      2.77G       1.22     0.6042      1.117        153        512: 100% ━━━━━━━━━━━━ 38/38 4.3it/s 8.8s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.8it/s 1.3s0.4s
                   all        300       1798      0.988       0.99      0.994      0.644

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/32      2.77G      1.207     0.5776      1.107        192        512: 100% ━━━━━━━━━━━━ 38/38 4.2it/s 9.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.9it/s 1.3s0.3s
                   all        300       1798      0.993      0.988      0.994      0.662

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/32      2.77G      1.179     0.5591      1.099        186        512: 100% ━━━━━━━━━━━━ 38/38 4.3it/s 8.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 4.1it/s 1.2s0.3s
                   all        300       1798      0.989      0.988      0.994      0.648

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/32      2.77G      1.179     0.5424       1.11        168        512: 100% ━━━━━━━━━━━━ 38/38 4.2it/s 9.0s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 4.1it/s 1.2s0.3s
                   all        300       1798      0.988      0.985      0.994      0.676

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/32      2.77G      1.153      0.529      1.095        169        512: 100% ━━━━━━━━━━━━ 38/38 4.3it/s 8.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 4.0it/s 1.3s0.3s
                   all        300       1798      0.989      0.988      0.993       0.65

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/32      2.77G      1.157     0.5263      1.101        156        512: 100% ━━━━━━━━━━━━ 38/38 4.3it/s 8.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 4.0it/s 1.3s0.3s
                   all        300       1798      0.996      0.992      0.995      0.684

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/32      2.78G      1.155     0.5163      1.104        176        512: 100% ━━━━━━━━━━━━ 38/38 4.3it/s 8.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.9it/s 1.3s0.4s
                   all        300       1798      0.993      0.992      0.995      0.667

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/32      2.78G      1.136     0.4982      1.086        188        512: 100% ━━━━━━━━━━━━ 38/38 4.3it/s 8.8s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 4.0it/s 1.2s0.3s
                   all        300       1798      0.992      0.993      0.994      0.667

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/32      2.79G      1.133     0.4984      1.085        169        512: 100% ━━━━━━━━━━━━ 38/38 4.3it/s 8.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 4.0it/s 1.3s0.4s
                   all        300       1798      0.994      0.993      0.994      0.681

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/32       2.8G      1.121     0.4846      1.077        155        512: 100% ━━━━━━━━━━━━ 38/38 4.3it/s 8.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 4.0it/s 1.3s0.3s
                   all        300       1798      0.993      0.993      0.994      0.692

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/32      2.82G       1.11     0.4779      1.078        180        512: 100% ━━━━━━━━━━━━ 38/38 4.3it/s 8.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.9it/s 1.3s0.3s
                   all        300       1798      0.994      0.992      0.994      0.692

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/32      2.83G      1.093      0.473      1.074        173        512: 100% ━━━━━━━━━━━━ 38/38 4.3it/s 8.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 4.1it/s 1.2s0.3s
                   all        300       1798      0.996      0.993      0.994      0.675

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/32      2.84G      1.084     0.4661       1.07        150        512: 100% ━━━━━━━━━━━━ 38/38 4.3it/s 8.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.8it/s 1.3s0.4s
                   all        300       1798      0.995      0.993      0.994      0.696
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/32      2.85G      1.058     0.4445      1.115         96        512: 100% ━━━━━━━━━━━━ 38/38 3.8it/s 10.1s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.8it/s 1.3s0.4s
                   all        300       1798      0.994      0.989      0.994      0.702

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/32      2.86G      1.037     0.4312      1.114        100        512: 100% ━━━━━━━━━━━━ 38/38 4.3it/s 8.8s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.8it/s 1.3s0.4s
                   all        300       1798      0.994      0.993      0.995      0.688

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/32      2.87G      1.024     0.4236      1.104         99        512: 100% ━━━━━━━━━━━━ 38/38 4.3it/s 8.8s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.7it/s 1.3s0.4s
                   all        300       1798      0.997      0.993      0.995      0.706

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/32      2.88G      1.012     0.4152      1.089        100        512: 100% ━━━━━━━━━━━━ 38/38 4.3it/s 8.8s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.8it/s 1.3s0.3s
                   all        300       1798       0.99      0.995      0.995      0.701

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/32       2.9G     0.9972     0.4103      1.084         82        512: 100% ━━━━━━━━━━━━ 38/38 4.4it/s 8.7s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 4.3it/s 1.2s0.3s
                   all        300       1798      0.993      0.991      0.994      0.693

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/32      2.91G     0.9984     0.4096      1.091         92        512: 100% ━━━━━━━━━━━━ 38/38 4.3it/s 8.8s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.6it/s 1.4s0.4s
                   all        300       1798      0.995      0.992      0.994      0.709

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/32      2.92G      0.989     0.3986      1.086         96        512: 100% ━━━━━━━━━━━━ 38/38 4.3it/s 8.8s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.9it/s 1.3s0.3s
                   all        300       1798      0.997      0.994      0.994      0.708

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/32      2.93G     0.9816     0.3927      1.075         89        512: 100% ━━━━━━━━━━━━ 38/38 4.3it/s 8.8s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 4.0it/s 1.2s0.3s
                   all        300       1798      0.997      0.992      0.994      0.721

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/32      2.94G     0.9604     0.3875      1.067         93        512: 100% ━━━━━━━━━━━━ 38/38 4.3it/s 8.9s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.9it/s 1.3s0.4s
                   all        300       1798      0.995      0.994      0.995      0.722

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/32      2.95G     0.9615     0.3836       1.07         99        512: 100% ━━━━━━━━━━━━ 38/38 4.3it/s 8.8s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.9it/s 1.3s0.3s
                   all        300       1798      0.997      0.994      0.995      0.724

32 epochs completed in 0.093 hours.
Optimizer stripped from /kaggle/working/runs/detect/train2/weights/last.pt, 6.2MB
Optimizer stripped from /kaggle/working/runs/detect/train2/weights/best.pt, 6.2MB

Validating /kaggle/working/runs/detect/train2/weights/best.pt...
Ultralytics 8.3.193 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
Model summary (fused): 72 layers, 3,005,843 parameters, 0 gradients, 8.1 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.0it/s 2.5s0.7s

/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        300       1798      0.997      0.994      0.995      0.724
Speed: 0.1ms preprocess, 0.9ms inference, 0.0ms loss, 1.5ms postprocess per image
Results saved to /kaggle/working/runs/detect/train2

,Case,Exp No,Experiment Name,Epochs,Batch,lr0,Weight Decay,Optimizer,Image Size,Dropout,Freeze Layers,Activation,Training Time (s),Precision,Recall,mAP@0.5,mAP@0.5:0.95
0,Case 5: Image Size,1,imgsz_320,32,32,0.01,0.0005,SGD,320,0.0,0,SiLU,226.53,0.99776,0.99310,0.99448,0.71656
1,Case 5: Image Size,2,imgsz_512,32,32,0.01,0.0005,SGD,512,0.0,0,SiLU,348.45,0.99701,0.99388,0.99464,0.72444

Ultralytics 8.3.193 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train3, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=/kaggle/working/runs/detect/train3, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    751507  ultralytics.nn.modules.head.Detect           [1, [64, 128, 256]]
Model summary: 129 layers, 3,011,043 parameters, 3,011,027 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 95.3±35.2 MB/s, size: 52.0 KB)
train: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train/labels... 1200 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1200/1200 956.1it/s 1.3s0.0s
WARNING ⚠️ train: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 75.5±35.8 MB/s, size: 61.5 KB)
val: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels... 300 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 300/300 534.2it/s 0.6s0.1s
WARNING ⚠️ val: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val is not writeable, cache not saved.
Plotting labels to /kaggle/working/runs/detect/train3/labels.jpg...
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to /kaggle/working/runs/detect/train3
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/32      4.26G      1.966      2.539      1.465        145        640: 100% ━━━━━━━━━━━━ 38/38 2.8it/s 13.7s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7s0.4s
                   all        300       1798     0.0199      0.997       0.98       0.59

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/32      4.61G      1.338     0.9955      1.117        166        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.3s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6s0.4s
                   all        300       1798       0.98      0.816      0.954      0.385

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/32      4.61G      1.349     0.8865      1.124        166        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.1s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7s0.4s
                   all        300       1798      0.975      0.972      0.984      0.569

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/32      4.61G      1.312     0.8716      1.113        136        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.5s0.4s
                   all        300       1798      0.979      0.965       0.98      0.411

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/32      4.61G      1.285      0.786      1.102        165        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.5s0.4s
                   all        300       1798      0.986      0.983      0.989       0.63

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/32      4.61G      1.263     0.7234      1.098        171        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5s0.4s
                   all        300       1798      0.987      0.991      0.993      0.639

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/32      4.61G      1.227     0.6684      1.086        167        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6s0.4s
                   all        300       1798      0.988      0.986      0.992      0.572

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/32      4.61G      1.226     0.6448      1.081        141        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5s0.4s
                   all        300       1798       0.99      0.984       0.99      0.662

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/32      4.61G      1.211     0.6304      1.084        129        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6s0.4s
                   all        300       1798      0.988      0.975      0.993       0.61

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/32      4.61G      1.197     0.6118      1.077        153        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5s0.4s
                   all        300       1798      0.994       0.99      0.994      0.671

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/32      4.61G      1.184     0.5853      1.065        192        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6s0.4s
                   all        300       1798      0.993      0.991      0.994      0.668

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/32      4.61G      1.161     0.5678      1.063        186        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.1s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5s0.4s
                   all        300       1798      0.978      0.983       0.99      0.636

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/32      4.61G       1.17     0.5554      1.067        168        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6s0.4s
                   all        300       1798      0.993      0.987      0.994      0.693

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/32      4.61G      1.145     0.5409      1.054        169        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.5s0.4s
                   all        300       1798      0.993      0.993      0.994      0.689

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/32      4.61G      1.139     0.5276      1.058        156        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5s0.4s
                   all        300       1798      0.988      0.985      0.993      0.669

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/32      4.61G      1.144      0.522      1.053        176        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5s0.4s
                   all        300       1798      0.991      0.986      0.994      0.654

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/32      4.61G      1.125      0.511      1.044        188        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.5it/s 1.4s0.4s
                   all        300       1798      0.991      0.993      0.994      0.698

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/32      4.61G      1.115     0.5034       1.04        169        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.5it/s 1.4s0.4s
                   all        300       1798      0.993      0.993      0.994       0.69

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/32      4.61G      1.107     0.4911      1.037        155        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5s0.4s
                   all        300       1798      0.993      0.994      0.994      0.648

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/32      4.61G      1.092     0.4823      1.027        180        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.6it/s 1.4s0.4s
                   all        300       1798      0.995      0.991      0.995      0.703

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/32      4.61G      1.083     0.4775      1.029        174        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5s0.4s
                   all        300       1798      0.994      0.994      0.995      0.703

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/32      4.61G      1.063     0.4712      1.023        149        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.6it/s 1.4s0.4s
                   all        300       1798      0.994      0.993      0.995      0.699
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/32      4.61G      1.043     0.4384      1.018         96        640: 100% ━━━━━━━━━━━━ 38/38 2.8it/s 13.6s0.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6s0.4s
                   all        300       1798      0.993      0.992      0.995      0.694

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/32      4.61G      1.033     0.4367      1.018        100        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5s0.4s
                   all        300       1798      0.996      0.994      0.995        0.7

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/32      4.62G      1.017     0.4239       1.01         99        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.7s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5s0.4s
                   all        300       1798      0.996      0.994      0.995      0.708

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/32      4.63G       1.01     0.4127      1.007        100        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5s0.4s
                   all        300       1798      0.996      0.993      0.995      0.716

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/32      4.64G     0.9908     0.4057      0.996         82        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5s0.4s
                   all        300       1798      0.994      0.995      0.995      0.688

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/32      4.65G     0.9835     0.4029     0.9978         92        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5s0.4s
                   all        300       1798      0.997      0.994      0.995      0.723

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/32      4.67G     0.9802     0.4005     0.9922         96        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5s0.4s
                   all        300       1798      0.995      0.993      0.995      0.706

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/32      4.68G     0.9677     0.3901     0.9839         89        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.5it/s 1.4s0.4s
                   all        300       1798      0.994      0.996      0.995      0.725

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/32      4.69G      0.948     0.3838     0.9809         93        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5s0.4s
                   all        300       1798      0.995      0.996      0.995      0.732

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/32       4.7G     0.9501      0.381      0.979         99        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.6it/s 1.4s0.4s
                   all        300       1798      0.996      0.994      0.995      0.732

32 epochs completed in 0.123 hours.
Optimizer stripped from /kaggle/working/runs/detect/train3/weights/last.pt, 6.2MB
Optimizer stripped from /kaggle/working/runs/detect/train3/weights/best.pt, 6.2MB

Validating /kaggle/working/runs/detect/train3/weights/best.pt...
Ultralytics 8.3.193 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
Model summary (fused): 72 layers, 3,005,843 parameters, 0 gradients, 8.1 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.8it/s 2.8s0.6s

/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        300       1798      0.996      0.994      0.995      0.732
Speed: 0.1ms preprocess, 1.4ms inference, 0.0ms loss, 1.7ms postprocess per image
Results saved to /kaggle/working/runs/detect/train3

,Case,Exp No,Experiment Name,Epochs,Batch,lr0,Weight Decay,Optimizer,Image Size,Dropout,Freeze Layers,Activation,Training Time (s),Precision,Recall,mAP@0.5,mAP@0.5:0.95
0,Case 5: Image Size,1,imgsz_320,32,32,0.01,0.0005,SGD,320,0.0,0,SiLU,226.53,0.99776,0.99310,0.99448,0.71656
1,Case 5: Image Size,2,imgsz_512,32,32,0.01,0.0005,SGD,512,0.0,0,SiLU,348.45,0.99701,0.99388,0.99464,0.72444
2,Case 5: Image Size,3,imgsz_640,32,32,0.01,0.0005,SGD,640,0.0,0,SiLU,456.79,0.99622,0.99444,0.99470,0.73197

In [9]:
import copy, yaml

def create_activation_yaml(base_yaml="yolov8n.yaml", act_expr="nn.SiLU()", suffix="silu"):
    """
    Create a modified YOLOv8 YAML with a custom activation function.
    Returns path to the new YAML.
    """
    with open(base_yaml, "r") as f:
        cfg = yaml.safe_load(f)

    # Update activation in model definition
    cfg["activation"] = act_expr

    out_path = f"/kaggle/working/{Path(base_yaml).stem}_{suffix}.yaml"
    with open(out_path, "w") as f:
        yaml.dump(cfg, f)

    return out_path

In [12]:
!cp /usr/local/lib/python3.10/dist-packages/ultralytics/cfg/models/v8/yolov8n.yaml /kaggle/working/

cp: cannot stat '/usr/local/lib/python3.10/dist-packages/ultralytics/cfg/models/v8/yolov8n.yaml': No such file or directory

In [13]:
# Case 9: Activation Functions
def case9_activation_functions():
    activations = {
        "ReLU": ("nn.ReLU()", "relu"),
        "LeakyReLU": ("nn.LeakyReLU(0.1)", "leakyrelu"),
        "Mish": ("nn.Mish()", "mish"),
        "SiLU": ("nn.SiLU()", "silu")  # baseline
    }

    for i, (act_name, (act_expr, suffix)) in enumerate(activations.items(), start=1):
        yaml_path = create_activation_yaml("yolov8n.yaml", act_expr, suffix)

        # Train with the modified YAML
        model = YOLO(yaml_path)

        run_with_best("Case 9: Activation Functions", i, f"activation_{act_name}", activation=act_name)

In [14]:
case9_activation_functions()

FileNotFoundError: [Errno 2] No such file or directory: 'yolov8n.yaml'

In [23]:
case1_epoch_variation()

Ultralytics 8.3.189 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=16, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train2, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/train2, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    751507  ultralytics.nn.modules.head.Detect           [1, [64, 128, 256]]
Model summary: 129 layers, 3,011,043 parameters, 3,011,027 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 126.4±45.7 MB/s, size: 52.0 KB)
train: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train/labels... 1200 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1200/1200 862.2it/s 1.4s
WARNING ⚠️ train: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 88.0±31.7 MB/s, size: 61.5 KB)
val: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels... 300 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 300/300 516.7it/s 0.6s
WARNING ⚠️ val: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val is not writeable, cache not saved.
Plotting labels to runs/detect/train2/labels.jpg...
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs/detect/train2
Starting training for 16 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/16      3.95G      1.966      2.539      1.465        145        640: 100% ━━━━━━━━━━━━ 38/38 2.9it/s 13.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.9it/s 1.7ss
                   all        300       1798     0.0199      0.997       0.98       0.59

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/16       4.3G      1.342     0.9997      1.118        166        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.6ss
                   all        300       1798      0.988      0.478      0.975      0.566

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/16       4.3G      1.332     0.8853       1.11        166        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7ss
                   all        300       1798      0.986      0.981      0.993      0.529

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/16       4.3G      1.321       0.84      1.117        136        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.9it/s 1.7ss
                   all        300       1798       0.99      0.985      0.992      0.616

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/16       4.3G      1.278     0.7571      1.093        165        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.969       0.98       0.98      0.561

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/16       4.3G      1.245     0.7061      1.086        171        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.996      0.987      0.993      0.612
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/16       4.3G      1.176     0.6558      1.071         96        640: 100% ━━━━━━━━━━━━ 38/38 2.8it/s 13.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.939      0.943      0.969      0.585

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/16       4.3G      1.185     0.6229       1.07         85        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.5ss
                   all        300       1798      0.978      0.937      0.979      0.644

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/16      4.32G       1.16     0.5953      1.055         98        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.971       0.97      0.982      0.586

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/16      4.33G      1.136     0.5547      1.049         94        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798      0.995      0.989      0.993      0.605

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/16      4.34G      1.119     0.5332      1.041         84        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.996       0.99      0.994      0.676

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/16      4.35G      1.107     0.5134      1.035        102        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.996      0.993      0.995      0.687

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/16      4.36G      1.072     0.4981      1.021         93        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.996      0.991      0.994      0.682

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/16      4.37G      1.065      0.483      1.017         99        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798      0.994      0.993      0.994      0.703

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/16      4.38G      1.035     0.4615      1.004         97        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.5it/s 1.4s
                   all        300       1798      0.995      0.994      0.995      0.689

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/16       4.4G      1.027     0.4563     0.9989         89        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.5it/s 1.4s
                   all        300       1798      0.997      0.995      0.995      0.707

16 epochs completed in 0.062 hours.
Optimizer stripped from runs/detect/train2/weights/last.pt, 6.2MB
Optimizer stripped from runs/detect/train2/weights/best.pt, 6.2MB

Validating runs/detect/train2/weights/best.pt...
Ultralytics 8.3.189 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
Model summary (fused): 72 layers, 3,005,843 parameters, 0 gradients, 8.1 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 2.9ss

/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        300       1798      0.997      0.995      0.995      0.707
Speed: 0.1ms preprocess, 1.4ms inference, 0.0ms loss, 2.6ms postprocess per image
Results saved to runs/detect/train2

,Case,Exp No,Experiment Name,Epochs,Batch,lr0,Weight Decay,Optimizer,Image Size,Dropout,Freeze Layers,Activation,Training Time (s),Precision,Recall,mAP@0.5,mAP@0.5:0.95
0,Case 1: Epoch Variation,1,epochs_16,16,32,0.01,0.0005,SGD,640,0.0,0,SiLU,238.37,0.99721,0.99478,0.9946,0.70744

Ultralytics 8.3.189 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train3, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/train3, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    751507  ultralytics.nn.modules.head.Detect           [1, [64, 128, 256]]
Model summary: 129 layers, 3,011,043 parameters, 3,011,027 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 125.8±43.6 MB/s, size: 52.0 KB)
train: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train/labels... 1200 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1200/1200 1112.7it/s 1.1s
WARNING ⚠️ train: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 76.4±37.9 MB/s, size: 61.5 KB)
val: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels... 300 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 300/300 584.7it/s 0.5s
WARNING ⚠️ val: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val is not writeable, cache not saved.
Plotting labels to runs/detect/train3/labels.jpg...
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs/detect/train3
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/32      4.15G      1.966      2.539      1.465        145        640: 100% ━━━━━━━━━━━━ 38/38 2.8it/s 13.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.9it/s 1.7ss
                   all        300       1798     0.0199      0.997       0.98       0.59

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/32       4.5G      1.338     0.9955      1.117        166        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.6ss
                   all        300       1798       0.98      0.816      0.954      0.385

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/32       4.5G      1.349     0.8865      1.124        166        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7ss
                   all        300       1798      0.975      0.972      0.984      0.569

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/32       4.5G      1.312     0.8716      1.113        136        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.979      0.965       0.98      0.411

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/32       4.5G      1.285      0.786      1.102        165        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.6ss
                   all        300       1798      0.986      0.983      0.989       0.63

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/32       4.5G      1.263     0.7234      1.098        171        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.987      0.991      0.993      0.639

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/32       4.5G      1.227     0.6684      1.086        167        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.988      0.986      0.992      0.572

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/32       4.5G      1.226     0.6448      1.081        141        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798       0.99      0.984       0.99      0.662

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/32       4.5G      1.211     0.6304      1.084        129        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.5ss
                   all        300       1798      0.988      0.975      0.993       0.61

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/32       4.5G      1.197     0.6118      1.077        153        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.994       0.99      0.994      0.671

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/32      4.51G      1.184     0.5853      1.065        192        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.993      0.991      0.994      0.668

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/32      4.52G      1.161     0.5678      1.063        186        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.978      0.983       0.99      0.636

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/32      4.53G       1.17     0.5554      1.067        168        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.993      0.987      0.994      0.693

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/32      4.54G      1.145     0.5409      1.054        169        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.993      0.993      0.994      0.689

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/32      4.55G      1.139     0.5276      1.058        156        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.988      0.985      0.993      0.669

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/32      4.57G      1.144      0.522      1.053        176        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.991      0.986      0.994      0.654

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/32      4.58G      1.125      0.511      1.044        188        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.991      0.993      0.994      0.698

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/32      4.59G      1.115     0.5034       1.04        169        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798      0.993      0.993      0.994       0.69

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/32       4.6G      1.107     0.4911      1.037        155        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.993      0.994      0.994      0.648

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/32      4.61G      1.092     0.4823      1.027        180        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.5ss
                   all        300       1798      0.995      0.991      0.995      0.703

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/32      4.62G      1.083     0.4775      1.029        174        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.6ss
                   all        300       1798      0.994      0.994      0.995      0.703

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/32      4.63G      1.063     0.4712      1.023        149        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.994      0.993      0.995      0.699
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/32      4.64G      1.043     0.4384      1.018         96        640: 100% ━━━━━━━━━━━━ 38/38 2.7it/s 13.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.993      0.992      0.995      0.694

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/32      4.65G      1.033     0.4367      1.018        100        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.996      0.994      0.995        0.7

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/32      4.67G      1.017     0.4239       1.01         99        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.996      0.994      0.995      0.708

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/32      4.68G       1.01     0.4127      1.007        100        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.996      0.993      0.995      0.716

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/32      4.69G     0.9908     0.4057      0.996         82        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.994      0.995      0.995      0.688

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/32       4.7G     0.9835     0.4029     0.9978         92        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.997      0.994      0.995      0.723

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/32      4.71G     0.9802     0.4005     0.9922         96        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.995      0.993      0.995      0.706

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/32      4.72G     0.9677     0.3901     0.9839         89        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798      0.994      0.996      0.995      0.725

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/32      4.74G      0.948     0.3838     0.9809         93        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.995      0.996      0.995      0.732

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/32      4.75G     0.9501      0.381      0.979         99        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798      0.996      0.994      0.995      0.732

32 epochs completed in 0.124 hours.
Optimizer stripped from runs/detect/train3/weights/last.pt, 6.2MB
Optimizer stripped from runs/detect/train3/weights/best.pt, 6.2MB

Validating runs/detect/train3/weights/best.pt...
Ultralytics 8.3.189 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
Model summary (fused): 72 layers, 3,005,843 parameters, 0 gradients, 8.1 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.6it/s 3.1ss

/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        300       1798      0.996      0.994      0.995      0.732
Speed: 0.2ms preprocess, 1.8ms inference, 0.0ms loss, 3.2ms postprocess per image
Results saved to runs/detect/train3

,Case,Exp No,Experiment Name,Epochs,Batch,lr0,Weight Decay,Optimizer,Image Size,Dropout,Freeze Layers,Activation,Training Time (s),Precision,Recall,mAP@0.5,mAP@0.5:0.95
0,Case 1: Epoch Variation,1,epochs_16,16,32,0.01,0.0005,SGD,640,0.0,0,SiLU,238.37,0.99721,0.99478,0.9946,0.70744
1,Case 1: Epoch Variation,2,epochs_32,32,32,0.01,0.0005,SGD,640,0.0,0,SiLU,458.60,0.99622,0.99444,0.9947,0.73197

Ultralytics 8.3.189 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=64, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train4, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/train4, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    751507  ultralytics.nn.modules.head.Detect           [1, [64, 128, 256]]
Model summary: 129 layers, 3,011,043 parameters, 3,011,027 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 115.9±45.3 MB/s, size: 52.0 KB)
train: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train/labels... 1200 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1200/1200 1145.4it/s 1.0s
WARNING ⚠️ train: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 64.6±43.0 MB/s, size: 61.5 KB)
val: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels... 300 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 300/300 586.7it/s 0.5s
WARNING ⚠️ val: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val is not writeable, cache not saved.
Plotting labels to runs/detect/train4/labels.jpg...
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs/detect/train4
Starting training for 64 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/64       4.3G      1.966      2.539      1.465        145        640: 100% ━━━━━━━━━━━━ 38/38 2.9it/s 13.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.7it/s 1.8ss
                   all        300       1798     0.0199      0.997       0.98       0.59

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/64      4.65G      1.356      1.005      1.122        166        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.9it/s 1.8ss
                   all        300       1798      0.994      0.482      0.986      0.591

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/64      4.65G       1.32     0.9251      1.112        166        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.9it/s 1.7ss
                   all        300       1798      0.955      0.919      0.957      0.382

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/64      4.65G      1.336      0.847      1.126        136        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7ss
                   all        300       1798      0.989      0.984      0.994      0.602

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/64      4.65G        1.3     0.7943      1.111        165        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.989      0.987      0.991      0.621

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/64      4.65G      1.268     0.7279      1.101        171        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.5ss
                   all        300       1798      0.976      0.975       0.99      0.607

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/64      4.65G      1.232     0.6619      1.082        141        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.5ss
                   all        300       1798       0.99      0.978      0.992      0.645

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/64      4.65G      1.232     0.6451      1.095        129        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.988      0.978      0.993      0.569

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/64      4.65G      1.211     0.6142      1.086        153        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.993      0.992      0.993       0.66

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/64      4.65G      1.206     0.5921      1.081        192        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.901      0.924      0.914       0.42

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/64      4.65G      1.185     0.5743      1.077        186        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5s
                   all        300       1798      0.987      0.987      0.993      0.632

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/64      4.65G      1.187     0.5611      1.079        168        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.989      0.992      0.993      0.676

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/64      4.65G      1.165     0.5516      1.068        169        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.996      0.992      0.994      0.674

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/64      4.65G      1.163     0.5449      1.074        156        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.988      0.992      0.993      0.655

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/64      4.65G       1.17     0.5367      1.067        176        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.995      0.992      0.995      0.649

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/64      4.65G      1.156     0.5275      1.064        188        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.993      0.995      0.995      0.686

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/64      4.65G      1.151     0.5232      1.061        169        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.994      0.993      0.993       0.67

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/64      4.65G      1.134     0.5062      1.053        155        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.5ss
                   all        300       1798      0.994      0.994      0.994       0.64

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/64      4.65G      1.125     0.5003      1.044        180        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798      0.992      0.992      0.994       0.69

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/64      4.65G      1.114     0.4971      1.046        174        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798      0.993      0.995      0.994      0.689

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/64      4.65G      1.102     0.4947      1.046        149        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5s
                   all        300       1798      0.996      0.994      0.994      0.676

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/64      4.65G      1.121     0.4948      1.047        148        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.994      0.992      0.995      0.685

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/64      4.66G      1.114     0.4866      1.041        143        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.992      0.989      0.992      0.673

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/64      4.67G        1.1     0.4833      1.039        165        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798      0.991      0.992      0.993      0.679

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/64      4.68G      1.103      0.482      1.041        141        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798       0.99       0.99      0.993      0.696

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/64      4.69G      1.085     0.4695      1.036        165        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.994      0.994      0.995      0.714

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/64       4.7G      1.095     0.4775      1.039        161        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.992      0.987      0.994      0.698

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/64      4.71G      1.066     0.4625      1.034        184        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.996      0.993      0.995      0.709

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/64      4.73G      1.073     0.4619       1.03        151        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.993      0.993      0.995      0.708

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/64      4.74G      1.073     0.4583      1.026        131        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.994      0.995      0.994      0.706

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/64      4.75G      1.065     0.4523      1.026        146        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.996      0.993      0.994      0.705

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      33/64      4.76G      1.074     0.4539      1.028        166        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.995      0.993      0.995      0.713

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      34/64      4.77G      1.058     0.4488       1.03        201        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.993      0.994      0.994        0.7

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      35/64      4.78G      1.047     0.4457      1.023        201        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.994      0.992      0.994        0.7

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      36/64      4.79G      1.047     0.4479       1.02        166        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.992      0.993      0.994      0.702


/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        300       1798      0.994      0.997      0.995      0.758
Speed: 0.1ms preprocess, 2.0ms inference, 0.0ms loss, 3.5ms postprocess per image
Results saved to runs/detect/train4

,Case,Exp No,Experiment Name,Epochs,Batch,lr0,Weight Decay,Optimizer,Image Size,Dropout,Freeze Layers,Activation,Training Time (s),Precision,Recall,mAP@0.5,mAP@0.5:0.95
0,Case 1: Epoch Variation,1,epochs_16,16,32,0.01,0.0005,SGD,640,0.0,0,SiLU,238.37,0.99721,0.99478,0.99460,0.70744
1,Case 1: Epoch Variation,2,epochs_32,32,32,0.01,0.0005,SGD,640,0.0,0,SiLU,458.60,0.99622,0.99444,0.99470,0.73197
2,Case 1: Epoch Variation,3,epochs_64,64,32,0.01,0.0005,SGD,640,0.0,0,SiLU,902.30,0.99784,0.99333,0.99432,0.75650

In [24]:
BEST_PARAMS["epochs"] = 32
case2_weight_decay()

Ultralytics 8.3.189 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train5, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/train5, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    751507  ultralytics.nn.modules.head.Detect           [1, [64, 128, 256]]
Model summary: 129 layers, 3,011,043 parameters, 3,011,027 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 101.9±71.9 MB/s, size: 52.0 KB)
train: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train/labels... 1200 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1200/1200 810.0it/s 1.5s
WARNING ⚠️ train: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 68.4±55.7 MB/s, size: 61.5 KB)
val: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels... 300 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 300/300 485.6it/s 0.6s
WARNING ⚠️ val: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val is not writeable, cache not saved.
Plotting labels to runs/detect/train5/labels.jpg...
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs/detect/train5
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/32      4.45G      1.966      2.539      1.465        145        640: 100% ━━━━━━━━━━━━ 38/38 2.9it/s 12.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.8it/s 1.8ss
                   all        300       1798     0.0199      0.997       0.98       0.59

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/32       4.8G      1.338     0.9955      1.117        166        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7ss
                   all        300       1798       0.98      0.816      0.954      0.385

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/32       4.8G      1.349     0.8865      1.124        166        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.9it/s 1.7ss
                   all        300       1798      0.975      0.972      0.984      0.569

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/32       4.8G      1.312     0.8716      1.113        136        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.979      0.965       0.98      0.411

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/32       4.8G      1.285      0.786      1.102        165        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.986      0.983      0.989       0.63

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/32       4.8G      1.263     0.7234      1.098        171        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.5ss
                   all        300       1798      0.987      0.991      0.993      0.639

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/32       4.8G      1.227     0.6684      1.086        167        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.988      0.986      0.992      0.572

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/32       4.8G      1.226     0.6448      1.081        141        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798       0.99      0.984       0.99      0.662

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/32       4.8G      1.211     0.6304      1.084        129        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.988      0.975      0.993       0.61

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/32       4.8G      1.197     0.6118      1.077        153        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798      0.994       0.99      0.994      0.671

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/32       4.8G      1.184     0.5853      1.065        192        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.993      0.991      0.994      0.668

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/32       4.8G      1.161     0.5678      1.063        186        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.978      0.983       0.99      0.636

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/32       4.8G       1.17     0.5554      1.067        168        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.5ss
                   all        300       1798      0.993      0.987      0.994      0.693

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/32       4.8G      1.145     0.5409      1.054        169        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.993      0.993      0.994      0.689

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/32       4.8G      1.139     0.5276      1.058        156        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.988      0.985      0.993      0.669

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/32       4.8G      1.144      0.522      1.053        176        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.991      0.986      0.994      0.654

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/32       4.8G      1.125      0.511      1.044        188        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.5ss
                   all        300       1798      0.991      0.993      0.994      0.698

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/32       4.8G      1.115     0.5034       1.04        169        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5s
                   all        300       1798      0.993      0.993      0.994       0.69

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/32       4.8G      1.107     0.4911      1.037        155        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798      0.993      0.994      0.994      0.648

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/32       4.8G      1.092     0.4823      1.027        180        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.995      0.991      0.995      0.703

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/32       4.8G      1.083     0.4775      1.029        174        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.994      0.994      0.995      0.703

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/32       4.8G      1.063     0.4712      1.023        149        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.994      0.993      0.995      0.699
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/32       4.8G      1.043     0.4384      1.018         96        640: 100% ━━━━━━━━━━━━ 38/38 2.7it/s 13.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.993      0.992      0.995      0.694

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/32       4.8G      1.033     0.4367      1.018        100        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.996      0.994      0.995        0.7

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/32       4.8G      1.017     0.4239       1.01         99        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798      0.996      0.994      0.995      0.708

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/32       4.8G       1.01     0.4127      1.007        100        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.996      0.993      0.995      0.716

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/32       4.8G     0.9908     0.4057      0.996         82        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798      0.994      0.995      0.995      0.688

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/32       4.8G     0.9835     0.4029     0.9978         92        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798      0.997      0.994      0.995      0.723

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/32       4.8G     0.9802     0.4005     0.9922         96        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.5ss
                   all        300       1798      0.995      0.993      0.995      0.706

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/32       4.8G     0.9677     0.3901     0.9839         89        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.994      0.996      0.995      0.725

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/32       4.8G      0.948     0.3838     0.9809         93        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798      0.995      0.996      0.995      0.732

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/32       4.8G     0.9501      0.381      0.979         99        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798      0.996      0.994      0.995      0.732

32 epochs completed in 0.123 hours.
Optimizer stripped from runs/detect/train5/weights/last.pt, 6.2MB
Optimizer stripped from runs/detect/train5/weights/best.pt, 6.2MB

Validating runs/detect/train5/weights/best.pt...
Ultralytics 8.3.189 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
Model summary (fused): 72 layers, 3,005,843 parameters, 0 gradients, 8.1 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.6it/s 3.1ss

/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        300       1798      0.996      0.994      0.995      0.732
Speed: 0.1ms preprocess, 1.5ms inference, 0.0ms loss, 3.3ms postprocess per image
Results saved to runs/detect/train5

,Case,Exp No,Experiment Name,Epochs,Batch,lr0,Weight Decay,Optimizer,Image Size,Dropout,Freeze Layers,Activation,Training Time (s),Precision,Recall,mAP@0.5,mAP@0.5:0.95
0,Case 1: Epoch Variation,1,epochs_16,16,32,0.01,0.0005,SGD,640,0.0,0,SiLU,238.37,0.99721,0.99478,0.99460,0.70744
1,Case 1: Epoch Variation,2,epochs_32,32,32,0.01,0.0005,SGD,640,0.0,0,SiLU,458.60,0.99622,0.99444,0.99470,0.73197
2,Case 1: Epoch Variation,3,epochs_64,64,32,0.01,0.0005,SGD,640,0.0,0,SiLU,902.30,0.99784,0.99333,0.99432,0.75650
3,Case 2: Weight Decay,1,wd_0,32,32,0.01,0.0000,SGD,640,0.0,0,SiLU,458.41,0.99622,0.99444,0.99470,0.73197

Ultralytics 8.3.189 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train6, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/train6, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    751507  ultralytics.nn.modules.head.Detect           [1, [64, 128, 256]]
Model summary: 129 layers, 3,011,043 parameters, 3,011,027 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 84.1±41.1 MB/s, size: 52.0 KB)
train: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train/labels... 1200 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1200/1200 920.6it/s 1.3s
WARNING ⚠️ train: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 83.9±42.2 MB/s, size: 61.5 KB)
val: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels... 300 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 300/300 524.9it/s 0.6s
WARNING ⚠️ val: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val is not writeable, cache not saved.
Plotting labels to runs/detect/train6/labels.jpg...
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs/detect/train6
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/32      4.35G      1.966      2.539      1.465        145        640: 100% ━━━━━━━━━━━━ 38/38 2.9it/s 13.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.7it/s 1.8ss
                   all        300       1798     0.0199      0.997       0.98       0.59

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/32      4.69G      1.338     0.9955      1.117        166        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798       0.98      0.816      0.954      0.385

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/32      4.69G      1.349     0.8865      1.124        166        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.8it/s 1.8ss
                   all        300       1798      0.975      0.972      0.984      0.569

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/32      4.69G      1.312     0.8716      1.113        136        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.6ss
                   all        300       1798      0.979      0.965       0.98      0.411

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/32      4.69G      1.285      0.786      1.102        165        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7ss
                   all        300       1798      0.986      0.983      0.989       0.63

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/32      4.69G      1.263     0.7234      1.098        171        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.987      0.991      0.993      0.639

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/32      4.69G      1.227     0.6684      1.086        167        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.988      0.986      0.992      0.572

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/32      4.69G      1.226     0.6448      1.081        141        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7ss
                   all        300       1798       0.99      0.984       0.99      0.662

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/32      4.69G      1.211     0.6304      1.084        129        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.988      0.975      0.993       0.61

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/32      4.69G      1.197     0.6118      1.077        153        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.994       0.99      0.994      0.671

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/32      4.69G      1.184     0.5853      1.065        192        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.993      0.991      0.994      0.668

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/32      4.69G      1.161     0.5678      1.063        186        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.978      0.983       0.99      0.636

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/32      4.69G       1.17     0.5554      1.067        168        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.993      0.987      0.994      0.693

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/32      4.69G      1.145     0.5409      1.054        169        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.993      0.993      0.994      0.689

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/32      4.69G      1.139     0.5276      1.058        156        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.988      0.985      0.993      0.669

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/32      4.69G      1.144      0.522      1.053        176        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.5ss
                   all        300       1798      0.991      0.986      0.994      0.654

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/32      4.69G      1.125      0.511      1.044        188        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.991      0.993      0.994      0.698

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/32      4.69G      1.115     0.5034       1.04        169        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.993      0.993      0.994       0.69

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/32      4.69G      1.107     0.4911      1.037        155        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7ss
                   all        300       1798      0.993      0.994      0.994      0.648

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/32      4.69G      1.092     0.4823      1.027        180        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.995      0.991      0.995      0.703

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/32      4.69G      1.083     0.4775      1.029        174        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.994      0.994      0.995      0.703

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/32      4.69G      1.063     0.4712      1.023        149        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.994      0.993      0.995      0.699
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/32      4.69G      1.043     0.4384      1.018         96        640: 100% ━━━━━━━━━━━━ 38/38 2.8it/s 13.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.993      0.992      0.995      0.694

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/32      4.69G      1.033     0.4367      1.018        100        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.996      0.994      0.995        0.7

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/32      4.69G      1.017     0.4239       1.01         99        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.5it/s 1.4ss
                   all        300       1798      0.996      0.994      0.995      0.708

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/32      4.69G       1.01     0.4127      1.007        100        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.5it/s 1.4ss
                   all        300       1798      0.996      0.993      0.995      0.716

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/32      4.69G     0.9908     0.4057      0.996         82        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798      0.994      0.995      0.995      0.688

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/32       4.7G     0.9835     0.4029     0.9978         92        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798      0.997      0.994      0.995      0.723

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/32      4.71G     0.9802     0.4005     0.9922         96        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5s
                   all        300       1798      0.995      0.993      0.995      0.706

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/32      4.73G     0.9677     0.3901     0.9839         89        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798      0.994      0.996      0.995      0.725

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/32      4.74G      0.948     0.3838     0.9809         93        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798      0.995      0.996      0.995      0.732

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/32      4.75G     0.9501      0.381      0.979         99        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.5ss
                   all        300       1798      0.996      0.994      0.995      0.732

32 epochs completed in 0.123 hours.
Optimizer stripped from runs/detect/train6/weights/last.pt, 6.2MB
Optimizer stripped from runs/detect/train6/weights/best.pt, 6.2MB

Validating runs/detect/train6/weights/best.pt...
Ultralytics 8.3.189 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
Model summary (fused): 72 layers, 3,005,843 parameters, 0 gradients, 8.1 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.6it/s 3.0ss

/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        300       1798      0.996      0.994      0.995      0.732
Speed: 0.2ms preprocess, 2.0ms inference, 0.0ms loss, 3.2ms postprocess per image
Results saved to runs/detect/train6

,Case,Exp No,Experiment Name,Epochs,Batch,lr0,Weight Decay,Optimizer,Image Size,Dropout,Freeze Layers,Activation,Training Time (s),Precision,Recall,mAP@0.5,mAP@0.5:0.95
0,Case 1: Epoch Variation,1,epochs_16,16,32,0.01,0.0005,SGD,640,0.0,0,SiLU,238.37,0.99721,0.99478,0.99460,0.70744
1,Case 1: Epoch Variation,2,epochs_32,32,32,0.01,0.0005,SGD,640,0.0,0,SiLU,458.60,0.99622,0.99444,0.99470,0.73197
2,Case 1: Epoch Variation,3,epochs_64,64,32,0.01,0.0005,SGD,640,0.0,0,SiLU,902.30,0.99784,0.99333,0.99432,0.75650
3,Case 2: Weight Decay,1,wd_0,32,32,0.01,0.0000,SGD,640,0.0,0,SiLU,458.41,0.99622,0.99444,0.99470,0.73197
4,Case 2: Weight Decay,2,wd_0.0001,32,32,0.01,0.0001,SGD,640,0.0,0,SiLU,458.25,0.99622,0.99444,0.99470,0.73197

Ultralytics 8.3.189 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train7, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/train7, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    751507  ultralytics.nn.modules.head.Detect           [1, [64, 128, 256]]
Model summary: 129 layers, 3,011,043 parameters, 3,011,027 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 109.5±39.3 MB/s, size: 52.0 KB)
train: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train/labels... 1200 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1200/1200 1160.8it/s 1.0s
WARNING ⚠️ train: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.1±0.1 ms, read: 91.2±46.0 MB/s, size: 61.5 KB)
val: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels... 300 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 300/300 599.8it/s 0.5s
WARNING ⚠️ val: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val is not writeable, cache not saved.
Plotting labels to runs/detect/train7/labels.jpg...
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs/detect/train7
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/32      4.34G      1.966      2.539      1.465        145        640: 100% ━━━━━━━━━━━━ 38/38 2.8it/s 13.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.9it/s 1.7ss
                   all        300       1798     0.0199      0.997       0.98       0.59

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/32      4.68G      1.338     0.9955      1.117        166        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798       0.98      0.816      0.954      0.385

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/32      4.68G      1.349     0.8865      1.124        166        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7ss
                   all        300       1798      0.975      0.972      0.984      0.569

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/32      4.68G      1.312     0.8716      1.113        136        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.979      0.965       0.98      0.411

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/32      4.68G      1.285      0.786      1.102        165        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.986      0.983      0.989       0.63

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/32      4.68G      1.263     0.7234      1.098        171        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.987      0.991      0.993      0.639

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/32      4.68G      1.227     0.6684      1.086        167        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7ss
                   all        300       1798      0.988      0.986      0.992      0.572

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/32      4.68G      1.226     0.6448      1.081        141        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.5ss
                   all        300       1798       0.99      0.984       0.99      0.662

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/32      4.68G      1.211     0.6304      1.084        129        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.988      0.975      0.993       0.61

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/32      4.68G      1.197     0.6118      1.077        153        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.994       0.99      0.994      0.671

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/32      4.68G      1.184     0.5853      1.065        192        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.993      0.991      0.994      0.668

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/32      4.68G      1.161     0.5678      1.063        186        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.978      0.983       0.99      0.636

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/32      4.68G       1.17     0.5554      1.067        168        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.5ss
                   all        300       1798      0.993      0.987      0.994      0.693

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/32      4.68G      1.145     0.5409      1.054        169        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.993      0.993      0.994      0.689

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/32      4.68G      1.139     0.5276      1.058        156        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.988      0.985      0.993      0.669

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/32      4.68G      1.144      0.522      1.053        176        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.991      0.986      0.994      0.654

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/32      4.68G      1.125      0.511      1.044        188        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.991      0.993      0.994      0.698

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/32      4.68G      1.115     0.5034       1.04        169        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.993      0.993      0.994       0.69

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/32      4.68G      1.107     0.4911      1.037        155        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.993      0.994      0.994      0.648

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/32      4.68G      1.092     0.4823      1.027        180        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.995      0.991      0.995      0.703

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/32      4.68G      1.083     0.4775      1.029        174        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.994      0.994      0.995      0.703

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/32      4.68G      1.063     0.4712      1.023        149        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.994      0.993      0.995      0.699
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/32      4.68G      1.043     0.4384      1.018         96        640: 100% ━━━━━━━━━━━━ 38/38 2.7it/s 13.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.993      0.992      0.995      0.694

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/32      4.68G      1.033     0.4367      1.018        100        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.5ss
                   all        300       1798      0.996      0.994      0.995        0.7

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/32      4.68G      1.017     0.4239       1.01         99        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.996      0.994      0.995      0.708

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/32      4.68G       1.01     0.4127      1.007        100        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.996      0.993      0.995      0.716

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/32      4.69G     0.9908     0.4057      0.996         82        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.994      0.995      0.995      0.688

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/32      4.71G     0.9835     0.4029     0.9978         92        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.5ss
                   all        300       1798      0.997      0.994      0.995      0.723

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/32      4.71G     0.9802     0.4005     0.9922         96        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.995      0.993      0.995      0.706

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/32      4.72G     0.9677     0.3901     0.9839         89        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.5ss
                   all        300       1798      0.994      0.996      0.995      0.725

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/32      4.74G      0.948     0.3838     0.9809         93        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.995      0.996      0.995      0.732

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/32      4.75G     0.9501      0.381      0.979         99        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.996      0.994      0.995      0.732

32 epochs completed in 0.124 hours.
Optimizer stripped from runs/detect/train7/weights/last.pt, 6.2MB
Optimizer stripped from runs/detect/train7/weights/best.pt, 6.2MB

Validating runs/detect/train7/weights/best.pt...
Ultralytics 8.3.189 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
Model summary (fused): 72 layers, 3,005,843 parameters, 0 gradients, 8.1 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0ss

/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        300       1798      0.996      0.994      0.995      0.732
Speed: 0.1ms preprocess, 2.1ms inference, 0.0ms loss, 3.0ms postprocess per image
Results saved to runs/detect/train7

,Case,Exp No,Experiment Name,Epochs,Batch,lr0,Weight Decay,Optimizer,Image Size,Dropout,Freeze Layers,Activation,Training Time (s),Precision,Recall,mAP@0.5,mAP@0.5:0.95
0,Case 1: Epoch Variation,1,epochs_16,16,32,0.01,0.0005,SGD,640,0.0,0,SiLU,238.37,0.99721,0.99478,0.99460,0.70744
1,Case 1: Epoch Variation,2,epochs_32,32,32,0.01,0.0005,SGD,640,0.0,0,SiLU,458.60,0.99622,0.99444,0.99470,0.73197
2,Case 1: Epoch Variation,3,epochs_64,64,32,0.01,0.0005,SGD,640,0.0,0,SiLU,902.30,0.99784,0.99333,0.99432,0.75650
3,Case 2: Weight Decay,1,wd_0,32,32,0.01,0.0000,SGD,640,0.0,0,SiLU,458.41,0.99622,0.99444,0.99470,0.73197
4,Case 2: Weight Decay,2,wd_0.0001,32,32,0.01,0.0001,SGD,640,0.0,0,SiLU,458.25,0.99622,0.99444,0.99470,0.73197
5,Case 2: Weight Decay,3,wd_0.0005,32,32,0.01,0.0005,SGD,640,0.0,0,SiLU,460.87,0.99622,0.99444,0.99470,0.73197

Ultralytics 8.3.189 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train8, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/train8, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    751507  ultralytics.nn.modules.head.Detect           [1, [64, 128, 256]]
Model summary: 129 layers, 3,011,043 parameters, 3,011,027 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 117.5±42.8 MB/s, size: 52.0 KB)
train: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train/labels... 1200 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1200/1200 1071.9it/s 1.1s
WARNING ⚠️ train: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.1 ms, read: 81.3±42.9 MB/s, size: 61.5 KB)
val: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels... 300 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 300/300 511.8it/s 0.6s
WARNING ⚠️ val: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val is not writeable, cache not saved.
Plotting labels to runs/detect/train8/labels.jpg...
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs/detect/train8
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/32      4.34G      1.966      2.539      1.465        145        640: 100% ━━━━━━━━━━━━ 38/38 2.9it/s 13.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.7it/s 1.9ss
                   all        300       1798     0.0199      0.997       0.98       0.59

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/32      4.69G      1.338     0.9955      1.117        166        640: 100% ━━━━━━━━━━━━ 38/38 3.0it/s 12.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7ss
                   all        300       1798       0.98      0.816      0.954      0.385

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/32      4.69G      1.349     0.8865      1.124        166        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7ss
                   all        300       1798      0.975      0.972      0.984      0.569

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/32      4.69G      1.312     0.8716      1.113        136        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.8it/s 1.8ss
                   all        300       1798      0.979      0.965       0.98      0.411

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/32      4.69G      1.285      0.786      1.102        165        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.986      0.983      0.989       0.63

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/32      4.69G      1.263     0.7234      1.098        171        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7ss
                   all        300       1798      0.987      0.991      0.993      0.639

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/32      4.69G      1.227     0.6684      1.086        167        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7ss
                   all        300       1798      0.988      0.986      0.992      0.572

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/32      4.69G      1.226     0.6448      1.081        141        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.6ss
                   all        300       1798       0.99      0.984       0.99      0.662

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/32      4.69G      1.211     0.6304      1.084        129        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7ss
                   all        300       1798      0.988      0.975      0.993       0.61

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/32      4.69G      1.197     0.6118      1.077        153        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.994       0.99      0.994      0.671

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/32      4.69G      1.184     0.5853      1.065        192        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.9it/s 1.7ss
                   all        300       1798      0.993      0.991      0.994      0.668

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/32      4.69G      1.161     0.5678      1.063        186        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7ss
                   all        300       1798      0.978      0.983       0.99      0.636

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/32      4.69G       1.17     0.5554      1.067        168        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7ss
                   all        300       1798      0.993      0.987      0.994      0.693

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/32      4.69G      1.145     0.5409      1.054        169        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.993      0.993      0.994      0.689

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/32      4.69G      1.139     0.5276      1.058        156        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.988      0.985      0.993      0.669

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/32      4.69G      1.144      0.522      1.053        176        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.6ss
                   all        300       1798      0.991      0.986      0.994      0.654

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/32      4.69G      1.125      0.511      1.044        188        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.991      0.993      0.994      0.698

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/32      4.69G      1.115     0.5034       1.04        169        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.993      0.993      0.994       0.69

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/32      4.69G      1.107     0.4911      1.037        155        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7ss
                   all        300       1798      0.993      0.994      0.994      0.648

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/32      4.69G      1.092     0.4823      1.027        180        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.995      0.991      0.995      0.703

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/32      4.69G      1.083     0.4775      1.029        174        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.994      0.994      0.995      0.703

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/32      4.69G      1.063     0.4712      1.023        149        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.994      0.993      0.995      0.699
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/32      4.69G      1.043     0.4384      1.018         96        640: 100% ━━━━━━━━━━━━ 38/38 2.8it/s 13.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.9it/s 1.7ss
                   all        300       1798      0.993      0.992      0.995      0.694

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/32      4.69G      1.033     0.4367      1.018        100        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.996      0.994      0.995        0.7

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/32      4.69G      1.017     0.4239       1.01         99        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.996      0.994      0.995      0.708

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/32      4.69G       1.01     0.4127      1.007        100        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.996      0.993      0.995      0.716

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/32      4.69G     0.9908     0.4057      0.996         82        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.994      0.995      0.995      0.688

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/32       4.7G     0.9835     0.4029     0.9978         92        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.997      0.994      0.995      0.723

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/32      4.71G     0.9802     0.4005     0.9922         96        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.5it/s 1.4ss
                   all        300       1798      0.995      0.993      0.995      0.706

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/32      4.72G     0.9677     0.3901     0.9839         89        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798      0.994      0.996      0.995      0.725

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/32      4.74G      0.948     0.3838     0.9809         93        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.995      0.996      0.995      0.732

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/32      4.75G     0.9501      0.381      0.979         99        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.5it/s 1.4s
                   all        300       1798      0.996      0.994      0.995      0.732

32 epochs completed in 0.125 hours.
Optimizer stripped from runs/detect/train8/weights/last.pt, 6.2MB
Optimizer stripped from runs/detect/train8/weights/best.pt, 6.2MB

Validating runs/detect/train8/weights/best.pt...
Ultralytics 8.3.189 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
Model summary (fused): 72 layers, 3,005,843 parameters, 0 gradients, 8.1 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.8it/s 2.8ss

/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        300       1798      0.996      0.994      0.995      0.732
Speed: 0.1ms preprocess, 1.9ms inference, 0.0ms loss, 2.8ms postprocess per image
Results saved to runs/detect/train8

,Case,Exp No,Experiment Name,Epochs,Batch,lr0,Weight Decay,Optimizer,Image Size,Dropout,Freeze Layers,Activation,Training Time (s),Precision,Recall,mAP@0.5,mAP@0.5:0.95
0,Case 1: Epoch Variation,1,epochs_16,16,32,0.01,0.0005,SGD,640,0.0,0,SiLU,238.37,0.99721,0.99478,0.99460,0.70744
1,Case 1: Epoch Variation,2,epochs_32,32,32,0.01,0.0005,SGD,640,0.0,0,SiLU,458.60,0.99622,0.99444,0.99470,0.73197
2,Case 1: Epoch Variation,3,epochs_64,64,32,0.01,0.0005,SGD,640,0.0,0,SiLU,902.30,0.99784,0.99333,0.99432,0.75650
3,Case 2: Weight Decay,1,wd_0,32,32,0.01,0.0000,SGD,640,0.0,0,SiLU,458.41,0.99622,0.99444,0.99470,0.73197
4,Case 2: Weight Decay,2,wd_0.0001,32,32,0.01,0.0001,SGD,640,0.0,0,SiLU,458.25,0.99622,0.99444,0.99470,0.73197
5,Case 2: Weight Decay,3,wd_0.0005,32,32,0.01,0.0005,SGD,640,0.0,0,SiLU,460.87,0.99622,0.99444,0.99470,0.73197
6,Case 2: Weight Decay,4,wd_0.001,32,32,0.01,0.0010,SGD,640,0.0,0,SiLU,463.15,0.99622,0.99444,0.99470,0.73197

Ultralytics 8.3.189 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train9, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/train9, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    751507  ultralytics.nn.modules.head.Detect           [1, [64, 128, 256]]
Model summary: 129 layers, 3,011,043 parameters, 3,011,027 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 108.7±49.6 MB/s, size: 52.0 KB)
train: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train/labels... 1200 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1200/1200 929.7it/s 1.3s
WARNING ⚠️ train: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 81.4±47.7 MB/s, size: 61.5 KB)
val: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels... 300 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 300/300 566.9it/s 0.5s
WARNING ⚠️ val: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val is not writeable, cache not saved.
Plotting labels to runs/detect/train9/labels.jpg...
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs/detect/train9
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/32      4.34G      1.966      2.539      1.465        145        640: 100% ━━━━━━━━━━━━ 38/38 2.9it/s 13.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.7it/s 1.9ss
                   all        300       1798     0.0199      0.997       0.98       0.59

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/32      4.69G      1.338     0.9955      1.117        166        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.8it/s 1.8ss
                   all        300       1798       0.98      0.816      0.954      0.385

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/32      4.69G      1.349     0.8865      1.124        166        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.8it/s 1.8ss
                   all        300       1798      0.975      0.972      0.984      0.569

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/32      4.69G      1.312     0.8716      1.113        136        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.9it/s 1.7ss
                   all        300       1798      0.979      0.965       0.98      0.411

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/32      4.69G      1.285      0.786      1.102        165        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7ss
                   all        300       1798      0.986      0.983      0.989       0.63

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/32      4.69G      1.263     0.7234      1.098        171        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.6ss
                   all        300       1798      0.987      0.991      0.993      0.639

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/32      4.69G      1.227     0.6684      1.086        167        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.988      0.986      0.992      0.572

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/32      4.69G      1.226     0.6448      1.081        141        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798       0.99      0.984       0.99      0.662

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/32      4.69G      1.211     0.6304      1.084        129        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.988      0.975      0.993       0.61

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/32      4.69G      1.197     0.6118      1.077        153        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.994       0.99      0.994      0.671

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/32      4.69G      1.184     0.5853      1.065        192        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.6ss
                   all        300       1798      0.993      0.991      0.994      0.668

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/32      4.69G      1.161     0.5678      1.063        186        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7ss
                   all        300       1798      0.978      0.983       0.99      0.636

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/32      4.69G       1.17     0.5554      1.067        168        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7ss
                   all        300       1798      0.993      0.987      0.994      0.693

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/32      4.69G      1.145     0.5409      1.054        169        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.993      0.993      0.994      0.689

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/32      4.69G      1.139     0.5276      1.058        156        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.988      0.985      0.993      0.669

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/32      4.69G      1.144      0.522      1.053        176        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7ss
                   all        300       1798      0.991      0.986      0.994      0.654

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/32      4.69G      1.125      0.511      1.044        188        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.991      0.993      0.994      0.698

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/32      4.69G      1.115     0.5034       1.04        169        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.993      0.993      0.994       0.69

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/32      4.69G      1.107     0.4911      1.037        155        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.993      0.994      0.994      0.648

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/32      4.69G      1.092     0.4823      1.027        180        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.995      0.991      0.995      0.703

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/32      4.69G      1.083     0.4775      1.029        174        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.994      0.994      0.995      0.703

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/32      4.69G      1.063     0.4712      1.023        149        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.994      0.993      0.995      0.699
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/32      4.69G      1.043     0.4384      1.018         96        640: 100% ━━━━━━━━━━━━ 38/38 2.8it/s 13.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.993      0.992      0.995      0.694

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/32      4.69G      1.033     0.4367      1.018        100        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.996      0.994      0.995        0.7

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/32      4.69G      1.017     0.4239       1.01         99        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.996      0.994      0.995      0.708

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/32      4.69G       1.01     0.4127      1.007        100        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798      0.996      0.993      0.995      0.716

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/32      4.69G     0.9908     0.4057      0.996         82        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.994      0.995      0.995      0.688

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/32      4.71G     0.9835     0.4029     0.9978         92        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7ss
                   all        300       1798      0.997      0.994      0.995      0.723

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/32      4.71G     0.9802     0.4005     0.9922         96        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.995      0.993      0.995      0.706

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/32      4.72G     0.9677     0.3901     0.9839         89        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.994      0.996      0.995      0.725

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/32      4.74G      0.948     0.3838     0.9809         93        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.995      0.996      0.995      0.732

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/32      4.75G     0.9501      0.381      0.979         99        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.996      0.994      0.995      0.732

32 epochs completed in 0.125 hours.
Optimizer stripped from runs/detect/train9/weights/last.pt, 6.2MB
Optimizer stripped from runs/detect/train9/weights/best.pt, 6.2MB

Validating runs/detect/train9/weights/best.pt...
Ultralytics 8.3.189 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
Model summary (fused): 72 layers, 3,005,843 parameters, 0 gradients, 8.1 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.6it/s 3.0ss

/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        300       1798      0.996      0.994      0.995      0.732
Speed: 0.1ms preprocess, 1.8ms inference, 0.0ms loss, 2.3ms postprocess per image
Results saved to runs/detect/train9

,Case,Exp No,Experiment Name,Epochs,Batch,lr0,Weight Decay,Optimizer,Image Size,Dropout,Freeze Layers,Activation,Training Time (s),Precision,Recall,mAP@0.5,mAP@0.5:0.95
0,Case 1: Epoch Variation,1,epochs_16,16,32,0.01,0.0005,SGD,640,0.0,0,SiLU,238.37,0.99721,0.99478,0.99460,0.70744
1,Case 1: Epoch Variation,2,epochs_32,32,32,0.01,0.0005,SGD,640,0.0,0,SiLU,458.60,0.99622,0.99444,0.99470,0.73197
2,Case 1: Epoch Variation,3,epochs_64,64,32,0.01,0.0005,SGD,640,0.0,0,SiLU,902.30,0.99784,0.99333,0.99432,0.75650
3,Case 2: Weight Decay,1,wd_0,32,32,0.01,0.0000,SGD,640,0.0,0,SiLU,458.41,0.99622,0.99444,0.99470,0.73197
4,Case 2: Weight Decay,2,wd_0.0001,32,32,0.01,0.0001,SGD,640,0.0,0,SiLU,458.25,0.99622,0.99444,0.99470,0.73197
5,Case 2: Weight Decay,3,wd_0.0005,32,32,0.01,0.0005,SGD,640,0.0,0,SiLU,460.87,0.99622,0.99444,0.99470,0.73197
6,Case 2: Weight Decay,4,wd_0.001,32,32,0.01,0.0010,SGD,640,0.0,0,SiLU,463.15,0.99622,0.99444,0.99470,0.73197
7,Case 2: Weight Decay,5,wd_0.005,32,32,0.01,0.0050,SGD,640,0.0,0,SiLU,463.39,0.99622,0.99444,0.99470,0.73197

In [25]:
BEST_PARAMS["epochs"] = 32
BEST_PARAMS["weight_decay"] = 0.0001
case3_batch_size()

Ultralytics 8.3.189 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train10, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/train10, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    751507  ultralytics.nn.modules.head.Detect           [1, [64, 128, 256]]
Model summary: 129 layers, 3,011,043 parameters, 3,011,027 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 98.0±43.0 MB/s, size: 52.0 KB)
train: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train/labels... 1200 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1200/1200 823.2it/s 1.5s
WARNING ⚠️ train: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 49.2±26.6 MB/s, size: 61.5 KB)
val: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels... 300 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 300/300 472.8it/s 0.6s
WARNING ⚠️ val: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val is not writeable, cache not saved.
Plotting labels to runs/detect/train10/labels.jpg...
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs/detect/train10
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/32      2.58G      1.744      2.123      1.359        142        640: 100% ━━━━━━━━━━━━ 75/75 4.8it/s 15.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.5it/s 1.8s
                   all        300       1798      0.994      0.788      0.978      0.494

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/32      2.58G      1.339     0.9498      1.114        164        640: 100% ━━━━━━━━━━━━ 75/75 5.3it/s 14.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.9it/s 1.7s
                   all        300       1798      0.957      0.939      0.973      0.463

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/32      2.58G      1.359     0.8894      1.128        201        640: 100% ━━━━━━━━━━━━ 75/75 5.4it/s 13.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 5.9it/s 1.7s
                   all        300       1798      0.978      0.978      0.987      0.586

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/32      2.58G      1.319     0.8366      1.123        190        640: 100% ━━━━━━━━━━━━ 75/75 5.4it/s 13.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 6.2it/s 1.6s
                   all        300       1798      0.977       0.96      0.968      0.382

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/32      2.58G      1.295      0.785      1.107        182        640: 100% ━━━━━━━━━━━━ 75/75 5.4it/s 13.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 6.2it/s 1.6s
                   all        300       1798      0.992      0.986      0.992      0.635

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/32      2.58G      1.262     0.7164      1.099        145        640: 100% ━━━━━━━━━━━━ 75/75 5.4it/s 13.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 6.2it/s 1.6s
                   all        300       1798       0.99      0.975       0.99      0.622

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/32      2.58G      1.238     0.6745      1.087        120        640: 100% ━━━━━━━━━━━━ 75/75 5.4it/s 13.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 6.4it/s 1.6s
                   all        300       1798      0.994      0.992      0.994      0.603

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/32      2.58G      1.233     0.6477      1.081        198        640: 100% ━━━━━━━━━━━━ 75/75 5.4it/s 13.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 6.3it/s 1.6s
                   all        300       1798      0.992      0.983      0.992      0.653

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/32      2.58G      1.219     0.6302      1.083        162        640: 100% ━━━━━━━━━━━━ 75/75 5.4it/s 13.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 6.3it/s 1.6s
                   all        300       1798      0.992      0.987      0.993      0.661

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/32      2.58G      1.194     0.6125      1.076        122        640: 100% ━━━━━━━━━━━━ 75/75 5.4it/s 13.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 6.5it/s 1.5s
                   all        300       1798      0.992      0.989      0.992      0.666

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/32      2.58G      1.183     0.5752      1.063        148        640: 100% ━━━━━━━━━━━━ 75/75 5.4it/s 13.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 6.4it/s 1.6s
                   all        300       1798       0.99      0.985      0.993      0.635

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/32      2.58G      1.191     0.5754       1.07        156        640: 100% ━━━━━━━━━━━━ 75/75 5.4it/s 13.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 6.4it/s 1.6s
                   all        300       1798      0.996      0.993      0.994      0.681

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/32      2.58G      1.167      0.556      1.068        149        640: 100% ━━━━━━━━━━━━ 75/75 5.4it/s 13.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 6.5it/s 1.5s
                   all        300       1798       0.99      0.992      0.993       0.68

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/32      2.58G      1.166     0.5438      1.065        180        640: 100% ━━━━━━━━━━━━ 75/75 5.4it/s 13.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 6.6it/s 1.5s
                   all        300       1798      0.982      0.992      0.993      0.654

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/32      2.58G      1.147     0.5349      1.057        139        640: 100% ━━━━━━━━━━━━ 75/75 5.4it/s 13.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 6.5it/s 1.5s
                   all        300       1798      0.991      0.991      0.994      0.681

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/32      2.58G       1.15     0.5234      1.054        178        640: 100% ━━━━━━━━━━━━ 75/75 5.4it/s 13.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 6.4it/s 1.6s
                   all        300       1798      0.993      0.996      0.994       0.68

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/32      2.58G      1.134     0.5143       1.05        189        640: 100% ━━━━━━━━━━━━ 75/75 5.4it/s 13.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 6.4it/s 1.6s
                   all        300       1798      0.994      0.995      0.995      0.667

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/32      2.58G      1.121      0.505      1.043        124        640: 100% ━━━━━━━━━━━━ 75/75 5.5it/s 13.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 6.4it/s 1.6s
                   all        300       1798      0.991      0.997      0.995      0.695

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/32      2.58G      1.108     0.4978      1.037        195        640: 100% ━━━━━━━━━━━━ 75/75 5.4it/s 13.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 6.5it/s 1.5s
                   all        300       1798      0.993      0.996      0.994      0.706

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/32      2.58G      1.099     0.4883      1.039        174        640: 100% ━━━━━━━━━━━━ 75/75 5.5it/s 13.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 6.5it/s 1.5s
                   all        300       1798      0.995       0.99      0.995        0.7

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/32      2.58G      1.094     0.4813      1.035        174        640: 100% ━━━━━━━━━━━━ 75/75 5.4it/s 13.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 6.4it/s 1.6s
                   all        300       1798      0.994      0.995      0.995      0.704

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/32      2.58G      1.083     0.4754      1.031        192        640: 100% ━━━━━━━━━━━━ 75/75 5.4it/s 13.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 6.4it/s 1.6s
                   all        300       1798      0.993      0.996      0.995      0.711
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/32      2.58G      1.064     0.4409      1.029         95        640: 100% ━━━━━━━━━━━━ 75/75 5.1it/s 14.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 6.5it/s 1.5s
                   all        300       1798      0.992      0.996      0.994       0.71

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/32      2.58G      1.041     0.4315       1.02         96        640: 100% ━━━━━━━━━━━━ 75/75 5.5it/s 13.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 6.4it/s 1.6s
                   all        300       1798      0.996      0.994      0.995      0.715

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/32      2.58G      1.025     0.4214      1.009        100        640: 100% ━━━━━━━━━━━━ 75/75 5.5it/s 13.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 6.5it/s 1.5s
                   all        300       1798      0.997      0.992      0.995      0.713

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/32      2.58G      1.009     0.4173      1.003        100        640: 100% ━━━━━━━━━━━━ 75/75 5.5it/s 13.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 6.6it/s 1.5s
                   all        300       1798      0.994      0.996      0.994      0.716

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/32      2.59G      1.005     0.4087      1.003         84        640: 100% ━━━━━━━━━━━━ 75/75 5.5it/s 13.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 6.7it/s 1.5s
                   all        300       1798      0.996      0.994      0.994      0.712

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/32       2.6G     0.9915     0.4035     0.9926         93        640: 100% ━━━━━━━━━━━━ 75/75 5.5it/s 13.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 6.7it/s 1.5s
                   all        300       1798      0.997      0.993      0.994      0.729

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/32      2.61G     0.9819     0.3973     0.9903         97        640: 100% ━━━━━━━━━━━━ 75/75 5.5it/s 13.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 6.4it/s 1.6s
                   all        300       1798      0.997      0.993      0.994      0.721

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/32      2.62G     0.9758     0.3919     0.9907         91        640: 100% ━━━━━━━━━━━━ 75/75 5.5it/s 13.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 6.6it/s 1.5s
                   all        300       1798      0.997      0.993      0.994      0.726

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/32      2.63G     0.9715     0.3904     0.9866         93        640: 100% ━━━━━━━━━━━━ 75/75 5.5it/s 13.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 6.6it/s 1.5s
                   all        300       1798      0.995      0.994      0.995      0.724

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/32      2.64G     0.9546     0.3812     0.9817        100        640: 100% ━━━━━━━━━━━━ 75/75 5.5it/s 13.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 6.5it/s 1.5s
                   all        300       1798      0.994      0.996      0.994      0.732

32 epochs completed in 0.139 hours.
Optimizer stripped from runs/detect/train10/weights/last.pt, 6.2MB
Optimizer stripped from runs/detect/train10/weights/best.pt, 6.2MB

Validating runs/detect/train10/weights/best.pt...
Ultralytics 8.3.189 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
Model summary (fused): 72 layers, 3,005,843 parameters, 0 gradients, 8.1 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.6it/s 2.8s

/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        300       1798      0.994      0.996      0.994      0.732
Speed: 0.1ms preprocess, 1.5ms inference, 0.0ms loss, 4.1ms postprocess per image
Results saved to runs/detect/train10

,Case,Exp No,Experiment Name,Epochs,Batch,lr0,Weight Decay,Optimizer,Image Size,Dropout,Freeze Layers,Activation,Training Time (s),Precision,Recall,mAP@0.5,mAP@0.5:0.95
0,Case 1: Epoch Variation,1,epochs_16,16,32,0.01,0.0005,SGD,640,0.0,0,SiLU,238.37,0.99721,0.99478,0.99460,0.70744
1,Case 1: Epoch Variation,2,epochs_32,32,32,0.01,0.0005,SGD,640,0.0,0,SiLU,458.60,0.99622,0.99444,0.99470,0.73197
2,Case 1: Epoch Variation,3,epochs_64,64,32,0.01,0.0005,SGD,640,0.0,0,SiLU,902.30,0.99784,0.99333,0.99432,0.75650
3,Case 2: Weight Decay,1,wd_0,32,32,0.01,0.0000,SGD,640,0.0,0,SiLU,458.41,0.99622,0.99444,0.99470,0.73197
4,Case 2: Weight Decay,2,wd_0.0001,32,32,0.01,0.0001,SGD,640,0.0,0,SiLU,458.25,0.99622,0.99444,0.99470,0.73197
5,Case 2: Weight Decay,3,wd_0.0005,32,32,0.01,0.0005,SGD,640,0.0,0,SiLU,460.87,0.99622,0.99444,0.99470,0.73197
6,Case 2: Weight Decay,4,wd_0.001,32,32,0.01,0.0010,SGD,640,0.0,0,SiLU,463.15,0.99622,0.99444,0.99470,0.73197
7,Case 2: Weight Decay,5,wd_0.005,32,32,0.01,0.0050,SGD,640,0.0,0,SiLU,463.39,0.99622,0.99444,0.99470,0.73197
8,Case 3: Batch Size,1,batch_16,32,16,0.01,0.0001,SGD,640,0.0,0,SiLU,515.74,0.99389,0.99555,0.99444,0.73239

Ultralytics 8.3.189 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train11, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/train11, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    751507  ultralytics.nn.modules.head.Detect           [1, [64, 128, 256]]
Model summary: 129 layers, 3,011,043 parameters, 3,011,027 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 90.2±28.3 MB/s, size: 52.0 KB)
train: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train/labels... 1200 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1200/1200 1144.4it/s 1.0s
WARNING ⚠️ train: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 85.0±43.7 MB/s, size: 61.5 KB)
val: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels... 300 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 300/300 542.3it/s 0.6s
WARNING ⚠️ val: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val is not writeable, cache not saved.
Plotting labels to runs/detect/train11/labels.jpg...
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs/detect/train11
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/32      4.33G      1.966      2.539      1.465        145        640: 100% ━━━━━━━━━━━━ 38/38 2.9it/s 13.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.9it/s 1.7ss
                   all        300       1798     0.0199      0.997       0.98       0.59

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/32      4.68G      1.338     0.9955      1.117        166        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.9it/s 1.7ss
                   all        300       1798       0.98      0.816      0.954      0.385

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/32      4.68G      1.349     0.8865      1.124        166        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.8it/s 1.8ss
                   all        300       1798      0.975      0.972      0.984      0.569

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/32      4.68G      1.312     0.8716      1.113        136        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.979      0.965       0.98      0.411

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/32      4.68G      1.285      0.786      1.102        165        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.8it/s 1.8ss
                   all        300       1798      0.986      0.983      0.989       0.63

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/32      4.68G      1.263     0.7234      1.098        171        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7ss
                   all        300       1798      0.987      0.991      0.993      0.639

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/32      4.68G      1.227     0.6684      1.086        167        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.988      0.986      0.992      0.572

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/32      4.68G      1.226     0.6448      1.081        141        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798       0.99      0.984       0.99      0.662

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/32      4.68G      1.211     0.6304      1.084        129        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.988      0.975      0.993       0.61

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/32      4.68G      1.197     0.6118      1.077        153        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.6ss
                   all        300       1798      0.994       0.99      0.994      0.671

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/32      4.68G      1.184     0.5853      1.065        192        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7ss
                   all        300       1798      0.993      0.991      0.994      0.668

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/32      4.68G      1.161     0.5678      1.063        186        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7ss
                   all        300       1798      0.978      0.983       0.99      0.636

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/32      4.68G       1.17     0.5554      1.067        168        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.993      0.987      0.994      0.693

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/32      4.68G      1.145     0.5409      1.054        169        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.993      0.993      0.994      0.689

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/32      4.68G      1.139     0.5276      1.058        156        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.988      0.985      0.993      0.669

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/32      4.68G      1.144      0.522      1.053        176        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.991      0.986      0.994      0.654

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/32      4.68G      1.125      0.511      1.044        188        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.991      0.993      0.994      0.698

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/32      4.68G      1.115     0.5034       1.04        169        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.993      0.993      0.994       0.69

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/32      4.68G      1.107     0.4911      1.037        155        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.993      0.994      0.994      0.648

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/32      4.68G      1.092     0.4823      1.027        180        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7ss
                   all        300       1798      0.995      0.991      0.995      0.703

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/32      4.68G      1.083     0.4775      1.029        174        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.994      0.994      0.995      0.703

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/32      4.68G      1.063     0.4712      1.023        149        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.994      0.993      0.995      0.699
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/32      4.68G      1.043     0.4384      1.018         96        640: 100% ━━━━━━━━━━━━ 38/38 2.8it/s 13.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.993      0.992      0.995      0.694

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/32      4.68G      1.033     0.4367      1.018        100        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.996      0.994      0.995        0.7

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/32      4.68G      1.017     0.4239       1.01         99        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.996      0.994      0.995      0.708

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/32      4.68G       1.01     0.4127      1.007        100        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.996      0.993      0.995      0.716

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/32      4.69G     0.9908     0.4057      0.996         82        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.994      0.995      0.995      0.688

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/32       4.7G     0.9835     0.4029     0.9978         92        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.997      0.994      0.995      0.723

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/32      4.71G     0.9802     0.4005     0.9922         96        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.995      0.993      0.995      0.706

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/32      4.73G     0.9677     0.3901     0.9839         89        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.994      0.996      0.995      0.725

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/32      4.74G      0.948     0.3838     0.9809         93        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.995      0.996      0.995      0.732

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/32      4.75G     0.9501      0.381      0.979         99        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.996      0.994      0.995      0.732

32 epochs completed in 0.125 hours.
Optimizer stripped from runs/detect/train11/weights/last.pt, 6.2MB
Optimizer stripped from runs/detect/train11/weights/best.pt, 6.2MB

Validating runs/detect/train11/weights/best.pt...
Ultralytics 8.3.189 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
Model summary (fused): 72 layers, 3,005,843 parameters, 0 gradients, 8.1 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.5it/s 3.3ss

/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        300       1798      0.996      0.994      0.995      0.732
Speed: 0.1ms preprocess, 2.0ms inference, 0.0ms loss, 3.5ms postprocess per image
Results saved to runs/detect/train11

,Case,Exp No,Experiment Name,Epochs,Batch,lr0,Weight Decay,Optimizer,Image Size,Dropout,Freeze Layers,Activation,Training Time (s),Precision,Recall,mAP@0.5,mAP@0.5:0.95
0,Case 1: Epoch Variation,1,epochs_16,16,32,0.01,0.0005,SGD,640,0.0,0,SiLU,238.37,0.99721,0.99478,0.99460,0.70744
1,Case 1: Epoch Variation,2,epochs_32,32,32,0.01,0.0005,SGD,640,0.0,0,SiLU,458.60,0.99622,0.99444,0.99470,0.73197
2,Case 1: Epoch Variation,3,epochs_64,64,32,0.01,0.0005,SGD,640,0.0,0,SiLU,902.30,0.99784,0.99333,0.99432,0.75650
3,Case 2: Weight Decay,1,wd_0,32,32,0.01,0.0000,SGD,640,0.0,0,SiLU,458.41,0.99622,0.99444,0.99470,0.73197
4,Case 2: Weight Decay,2,wd_0.0001,32,32,0.01,0.0001,SGD,640,0.0,0,SiLU,458.25,0.99622,0.99444,0.99470,0.73197
5,Case 2: Weight Decay,3,wd_0.0005,32,32,0.01,0.0005,SGD,640,0.0,0,SiLU,460.87,0.99622,0.99444,0.99470,0.73197
6,Case 2: Weight Decay,4,wd_0.001,32,32,0.01,0.0010,SGD,640,0.0,0,SiLU,463.15,0.99622,0.99444,0.99470,0.73197
7,Case 2: Weight Decay,5,wd_0.005,32,32,0.01,0.0050,SGD,640,0.0,0,SiLU,463.39,0.99622,0.99444,0.99470,0.73197
8,Case 3: Batch Size,1,batch_16,32,16,0.01,0.0001,SGD,640,0.0,0,SiLU,515.74,0.99389,0.99555,0.99444,0.73239
9,Case 3: Batch Size,2,batch_32,32,32,0.01,0.0001,SGD,640,0.0,0,SiLU,465.39,0.99622,0.99444,0.99470,0.73197

Ultralytics 8.3.189 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=64, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train12, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/train12, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    751507  ultralytics.nn.modules.head.Detect           [1, [64, 128, 256]]
Model summary: 129 layers, 3,011,043 parameters, 3,011,027 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 118.1±40.4 MB/s, size: 52.0 KB)
train: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train/labels... 1200 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1200/1200 1041.2it/s 1.2s
WARNING ⚠️ train: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.1 ms, read: 58.2±23.6 MB/s, size: 61.5 KB)
val: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels... 300 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 300/300 528.9it/s 0.6s
WARNING ⚠️ val: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val is not writeable, cache not saved.
Plotting labels to runs/detect/train12/labels.jpg...
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs/detect/train12
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/32      7.94G      2.472      3.446      1.727        527        640: 100% ━━━━━━━━━━━━ 19/19 1.1it/s 17.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 0.97it/s 3.1s
                   all        300       1798     0.0199      0.997     0.0462     0.0232

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/32      7.87G      1.389       1.41        1.2        486        640: 100% ━━━━━━━━━━━━ 19/19 1.6it/s 11.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.7it/s 1.8ss
                   all        300       1798     0.0199      0.994      0.983      0.546

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/32      7.86G      1.304      0.996      1.113        492        640: 100% ━━━━━━━━━━━━ 19/19 1.7it/s 11.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.8it/s 1.7ss
                   all        300       1798      0.918      0.976      0.979      0.559

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/32      7.86G      1.318      0.875      1.112        507        640: 100% ━━━━━━━━━━━━ 19/19 1.7it/s 11.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.8it/s 1.6ss
                   all        300       1798      0.987      0.697      0.979        0.6

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/32      7.66G      1.303     0.8591      1.109        453        640: 100% ━━━━━━━━━━━━ 19/19 1.7it/s 11.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.8it/s 1.7ss
                   all        300       1798       0.97      0.889       0.94      0.368

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/32      7.87G      1.289     0.7981      1.105        479        640: 100% ━━━━━━━━━━━━ 19/19 1.7it/s 11.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.8it/s 1.7ss
                   all        300       1798      0.982      0.986      0.992      0.637

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/32      7.88G       1.26     0.7413      1.094        476        640: 100% ━━━━━━━━━━━━ 19/19 1.7it/s 11.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.9it/s 1.6ss
                   all        300       1798      0.959      0.952      0.954      0.393

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/32      7.87G      1.249     0.7137      1.087        492        640: 100% ━━━━━━━━━━━━ 19/19 1.7it/s 11.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.9it/s 1.6ss
                   all        300       1798      0.977      0.984       0.98      0.501

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/32      7.89G      1.223      0.674      1.082        437        640: 100% ━━━━━━━━━━━━ 19/19 1.7it/s 11.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 2.0it/s 1.5ss
                   all        300       1798      0.988      0.986      0.991      0.563

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/32      7.87G      1.216     0.6384      1.082        477        640: 100% ━━━━━━━━━━━━ 19/19 1.7it/s 11.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.9it/s 1.6ss
                   all        300       1798      0.988       0.99      0.991      0.478

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/32      7.85G      1.191      0.606      1.067        471        640: 100% ━━━━━━━━━━━━ 19/19 1.7it/s 11.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.8it/s 1.6ss
                   all        300       1798      0.973      0.975      0.986        0.6

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/32      7.88G      1.177     0.5824      1.063        471        640: 100% ━━━━━━━━━━━━ 19/19 1.7it/s 11.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 2.0it/s 1.5ss
                   all        300       1798      0.991      0.991      0.993      0.656

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/32      7.89G      1.169     0.5718      1.062        495        640: 100% ━━━━━━━━━━━━ 19/19 1.7it/s 11.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.8it/s 1.7ss
                   all        300       1798      0.996      0.991      0.994      0.658

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/32      7.86G      1.155     0.5549      1.064        471        640: 100% ━━━━━━━━━━━━ 19/19 1.7it/s 11.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.9it/s 1.6ss
                   all        300       1798      0.993      0.994      0.994      0.584

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/32      7.84G      1.144     0.5323      1.056        492        640: 100% ━━━━━━━━━━━━ 19/19 1.7it/s 11.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.9it/s 1.6ss
                   all        300       1798      0.983      0.982       0.99      0.553

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/32      7.86G      1.167     0.5406      1.063        495        640: 100% ━━━━━━━━━━━━ 19/19 1.7it/s 11.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.9it/s 1.6ss
                   all        300       1798      0.994      0.991      0.994      0.663

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/32      7.87G      1.138     0.5191      1.047        537        640: 100% ━━━━━━━━━━━━ 19/19 1.7it/s 11.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.8it/s 1.6ss
                   all        300       1798      0.995      0.996      0.995      0.639

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/32      7.88G      1.106     0.5097       1.04        509        640: 100% ━━━━━━━━━━━━ 19/19 1.7it/s 11.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.9it/s 1.6ss
                   all        300       1798      0.994      0.989      0.994       0.68

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/32       7.9G      1.107     0.4953      1.033        483        640: 100% ━━━━━━━━━━━━ 19/19 1.7it/s 11.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.9it/s 1.6ss
                   all        300       1798      0.995       0.99      0.995       0.69

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/32      7.87G      1.101      0.498      1.033        477        640: 100% ━━━━━━━━━━━━ 19/19 1.7it/s 11.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 2.0it/s 1.5ss
                   all        300       1798      0.996      0.989      0.994      0.685

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/32      7.86G      1.087      0.481      1.031        437        640: 100% ━━━━━━━━━━━━ 19/19 1.7it/s 11.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 2.0it/s 1.5ss
                   all        300       1798      0.997      0.994      0.995      0.644

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/32      7.85G      1.102     0.4867      1.035        528        640: 100% ━━━━━━━━━━━━ 19/19 1.7it/s 11.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 2.0it/s 1.5ss
                   all        300       1798      0.993      0.991      0.994       0.65
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/32      8.11G      1.037     0.4483      1.013        284        640: 100% ━━━━━━━━━━━━ 19/19 1.3it/s 14.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.8it/s 1.6ss
                   all        300       1798      0.958      0.944      0.978      0.595

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/32      7.68G      1.053      0.448      1.024        278        640: 100% ━━━━━━━━━━━━ 19/19 1.8it/s 10.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 2.1it/s 1.4ss
                   all        300       1798      0.996      0.992      0.995      0.658

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/32      7.68G      1.031     0.4305      1.011        296        640: 100% ━━━━━━━━━━━━ 19/19 1.7it/s 10.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 2.0it/s 1.5ss
                   all        300       1798      0.995      0.997      0.995      0.702

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/32      7.68G      1.014     0.4229      1.007        303        640: 100% ━━━━━━━━━━━━ 19/19 1.7it/s 10.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 2.1it/s 1.4ss
                   all        300       1798      0.996      0.996      0.994      0.697

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/32      7.68G      1.001     0.4109     0.9977        261        640: 100% ━━━━━━━━━━━━ 19/19 1.7it/s 10.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 2.0it/s 1.5ss
                   all        300       1798      0.996      0.993      0.995      0.698

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/32      7.68G      0.983     0.4029     0.9917        286        640: 100% ━━━━━━━━━━━━ 19/19 1.8it/s 10.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 2.1it/s 1.5ss
                   all        300       1798      0.997      0.993      0.994      0.721

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/32      7.68G     0.9793     0.3999     0.9895        265        640: 100% ━━━━━━━━━━━━ 19/19 1.7it/s 10.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 2.1it/s 1.4ss
                   all        300       1798      0.996      0.994      0.995      0.723

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/32      7.68G     0.9693     0.3951     0.9843        269        640: 100% ━━━━━━━━━━━━ 19/19 1.8it/s 10.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 2.1it/s 1.4ss
                   all        300       1798      0.997      0.993      0.995      0.715

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/32      7.68G     0.9589      0.389     0.9788        290        640: 100% ━━━━━━━━━━━━ 19/19 1.7it/s 10.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 2.1it/s 1.5ss
                   all        300       1798      0.997      0.994      0.994      0.729

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/32      7.68G     0.9526     0.3841     0.9765        283        640: 100% ━━━━━━━━━━━━ 19/19 1.8it/s 10.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.9it/s 1.6ss
                   all        300       1798      0.995      0.996      0.995      0.731

32 epochs completed in 0.121 hours.
Optimizer stripped from runs/detect/train12/weights/last.pt, 6.2MB
Optimizer stripped from runs/detect/train12/weights/best.pt, 6.2MB

Validating runs/detect/train12/weights/best.pt...
Ultralytics 8.3.189 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
Model summary (fused): 72 layers, 3,005,843 parameters, 0 gradients, 8.1 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 3/3 1.1it/s 2.7ss

/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        300       1798      0.995      0.996      0.995      0.731
Speed: 0.1ms preprocess, 1.4ms inference, 0.0ms loss, 2.3ms postprocess per image
Results saved to runs/detect/train12

,Case,Exp No,Experiment Name,Epochs,Batch,lr0,Weight Decay,Optimizer,Image Size,Dropout,Freeze Layers,Activation,Training Time (s),Precision,Recall,mAP@0.5,mAP@0.5:0.95
1,Case 1: Epoch Variation,2,epochs_32,32,32,0.01,0.0005,SGD,640,0.0,0,SiLU,458.60,0.99622,0.99444,0.99470,0.73197
2,Case 1: Epoch Variation,3,epochs_64,64,32,0.01,0.0005,SGD,640,0.0,0,SiLU,902.30,0.99784,0.99333,0.99432,0.75650
3,Case 2: Weight Decay,1,wd_0,32,32,0.01,0.0000,SGD,640,0.0,0,SiLU,458.41,0.99622,0.99444,0.99470,0.73197
4,Case 2: Weight Decay,2,wd_0.0001,32,32,0.01,0.0001,SGD,640,0.0,0,SiLU,458.25,0.99622,0.99444,0.99470,0.73197
5,Case 2: Weight Decay,3,wd_0.0005,32,32,0.01,0.0005,SGD,640,0.0,0,SiLU,460.87,0.99622,0.99444,0.99470,0.73197
6,Case 2: Weight Decay,4,wd_0.001,32,32,0.01,0.0010,SGD,640,0.0,0,SiLU,463.15,0.99622,0.99444,0.99470,0.73197
7,Case 2: Weight Decay,5,wd_0.005,32,32,0.01,0.0050,SGD,640,0.0,0,SiLU,463.39,0.99622,0.99444,0.99470,0.73197
8,Case 3: Batch Size,1,batch_16,32,16,0.01,0.0001,SGD,640,0.0,0,SiLU,515.74,0.99389,0.99555,0.99444,0.73239
9,Case 3: Batch Size,2,batch_32,32,32,0.01,0.0001,SGD,640,0.0,0,SiLU,465.39,0.99622,0.99444,0.99470,0.73197
10,Case 3: Batch Size,3,batch_64,32,64,0.01,0.0001,SGD,640,0.0,0,SiLU,449.77,0.99500,0.99605,0.99455,0.73081

In [ ]:
BEST_PARAMS["epochs"] = 32
BEST_PARAMS["weight_decay"] = 0.0001
BEST_PARAMS["batch"] = 32
case4_dropout()

Ultralytics 8.3.189 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train13, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/train13, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    751507  ultralytics.nn.modules.head.Detect           [1, [64, 128, 256]]
Model summary: 129 layers, 3,011,043 parameters, 3,011,027 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 117.6±41.2 MB/s, size: 52.0 KB)
train: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train/labels... 1200 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1200/1200 913.0it/s 1.3s
WARNING ⚠️ train: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 104.5±26.0 MB/s, size: 61.5 KB)
val: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels... 300 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 300/300 531.9it/s 0.6s
WARNING ⚠️ val: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val is not writeable, cache not saved.
Plotting labels to runs/detect/train13/labels.jpg...
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs/detect/train13
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/32      4.24G      1.966      2.539      1.465        145        640: 100% ━━━━━━━━━━━━ 38/38 2.9it/s 13.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.6it/s 1.9ss
                   all        300       1798     0.0199      0.997       0.98       0.59

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/32      4.59G      1.338     0.9955      1.117        166        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.9it/s 1.7ss
                   all        300       1798       0.98      0.816      0.954      0.385

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/32      4.59G      1.349     0.8865      1.124        166        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.8it/s 1.8ss
                   all        300       1798      0.975      0.972      0.984      0.569

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/32      4.59G      1.312     0.8716      1.113        136        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.9it/s 1.7ss
                   all        300       1798      0.979      0.965       0.98      0.411

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/32      4.59G      1.285      0.786      1.102        165        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7ss
                   all        300       1798      0.986      0.983      0.989       0.63

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/32      4.59G      1.263     0.7234      1.098        171        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.987      0.991      0.993      0.639

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/32      4.59G      1.227     0.6684      1.086        167        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.988      0.986      0.992      0.572

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/32      4.59G      1.226     0.6448      1.081        141        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7ss
                   all        300       1798       0.99      0.984       0.99      0.662

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/32      4.59G      1.211     0.6304      1.084        129        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7ss
                   all        300       1798      0.988      0.975      0.993       0.61

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/32      4.59G      1.197     0.6118      1.077        153        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.994       0.99      0.994      0.671

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/32      4.59G      1.184     0.5853      1.065        192        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.993      0.991      0.994      0.668

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/32      4.59G      1.161     0.5678      1.063        186        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.978      0.983       0.99      0.636

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/32      4.59G       1.17     0.5554      1.067        168        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.6ss
                   all        300       1798      0.993      0.987      0.994      0.693

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/32      4.59G      1.145     0.5409      1.054        169        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7ss
                   all        300       1798      0.993      0.993      0.994      0.689

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/32      4.59G      1.139     0.5276      1.058        156        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7ss
                   all        300       1798      0.988      0.985      0.993      0.669

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/32      4.59G      1.144      0.522      1.053        176        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.3it/s 2.2ss
                   all        300       1798      0.991      0.986      0.994      0.654

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/32      4.59G      1.125      0.511      1.044        188        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.991      0.993      0.994      0.698

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/32      4.59G      1.115     0.5034       1.04        169        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.993      0.993      0.994       0.69

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/32      4.59G      1.107     0.4911      1.037        155        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.993      0.994      0.994      0.648

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/32      4.59G      1.092     0.4823      1.027        180        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.995      0.991      0.995      0.703

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/32      4.59G      1.083     0.4775      1.029        174        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.994      0.994      0.995      0.703

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/32       4.6G      1.063     0.4712      1.023        149        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.6ss
                   all        300       1798      0.994      0.993      0.995      0.699
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/32      4.61G      1.043     0.4384      1.018         96        640: 100% ━━━━━━━━━━━━ 38/38 2.5it/s 15.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.993      0.992      0.995      0.694

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/32      4.62G      1.033     0.4367      1.018        100        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.996      0.994      0.995        0.7

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/32      4.64G      1.017     0.4239       1.01         99        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.996      0.994      0.995      0.708

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/32      4.65G       1.01     0.4127      1.007        100        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.996      0.993      0.995      0.716

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/32      4.66G     0.9908     0.4057      0.996         82        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.5ss
                   all        300       1798      0.994      0.995      0.995      0.688

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/32      4.67G     0.9835     0.4029     0.9978         92        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.997      0.994      0.995      0.723

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/32      4.68G     0.9802     0.4005     0.9922         96        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.4it/s 2.1ss
                   all        300       1798      0.995      0.993      0.995      0.706

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/32       4.7G     0.9677     0.3901     0.9839         89        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.5ss
                   all        300       1798      0.994      0.996      0.995      0.725

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/32      4.71G      0.948     0.3838     0.9809         93        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.995      0.996      0.995      0.732

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/32      4.72G     0.9501      0.381      0.979         99        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7ss
                   all        300       1798      0.996      0.994      0.995      0.732

32 epochs completed in 0.126 hours.
Optimizer stripped from runs/detect/train13/weights/last.pt, 6.2MB
Optimizer stripped from runs/detect/train13/weights/best.pt, 6.2MB

Validating runs/detect/train13/weights/best.pt...
Ultralytics 8.3.189 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
Model summary (fused): 72 layers, 3,005,843 parameters, 0 gradients, 8.1 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.6it/s 3.1ss

/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        300       1798      0.996      0.994      0.995      0.732
Speed: 0.1ms preprocess, 2.0ms inference, 0.0ms loss, 3.3ms postprocess per image
Results saved to runs/detect/train13

,Case,Exp No,Experiment Name,Epochs,Batch,lr0,Weight Decay,Optimizer,Image Size,Dropout,Freeze Layers,Activation,Training Time (s),Precision,Recall,mAP@0.5,mAP@0.5:0.95
2,Case 1: Epoch Variation,3,epochs_64,64,32,0.01,0.0005,SGD,640,0.0,0,SiLU,902.30,0.99784,0.99333,0.99432,0.75650
3,Case 2: Weight Decay,1,wd_0,32,32,0.01,0.0000,SGD,640,0.0,0,SiLU,458.41,0.99622,0.99444,0.99470,0.73197
4,Case 2: Weight Decay,2,wd_0.0001,32,32,0.01,0.0001,SGD,640,0.0,0,SiLU,458.25,0.99622,0.99444,0.99470,0.73197
5,Case 2: Weight Decay,3,wd_0.0005,32,32,0.01,0.0005,SGD,640,0.0,0,SiLU,460.87,0.99622,0.99444,0.99470,0.73197
6,Case 2: Weight Decay,4,wd_0.001,32,32,0.01,0.0010,SGD,640,0.0,0,SiLU,463.15,0.99622,0.99444,0.99470,0.73197
7,Case 2: Weight Decay,5,wd_0.005,32,32,0.01,0.0050,SGD,640,0.0,0,SiLU,463.39,0.99622,0.99444,0.99470,0.73197
8,Case 3: Batch Size,1,batch_16,32,16,0.01,0.0001,SGD,640,0.0,0,SiLU,515.74,0.99389,0.99555,0.99444,0.73239
9,Case 3: Batch Size,2,batch_32,32,32,0.01,0.0001,SGD,640,0.0,0,SiLU,465.39,0.99622,0.99444,0.99470,0.73197
10,Case 3: Batch Size,3,batch_64,32,64,0.01,0.0001,SGD,640,0.0,0,SiLU,449.77,0.99500,0.99605,0.99455,0.73081
11,Case 4: Dropout,1,dropout_0,32,32,0.01,0.0001,SGD,640,0.0,0,SiLU,468.16,0.99622,0.99444,0.99470,0.73197

Ultralytics 8.3.189 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.1, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train14, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/train14, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    751507  ultralytics.nn.modules.head.Detect           [1, [64, 128, 256]]
Model summary: 129 layers, 3,011,043 parameters, 3,011,027 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 80.6±47.9 MB/s, size: 52.0 KB)
train: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train/labels... 1200 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1200/1200 760.0it/s 1.6s
WARNING ⚠️ train: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 71.6±45.9 MB/s, size: 61.5 KB)
val: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels... 300 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 300/300 479.1it/s 0.6s
WARNING ⚠️ val: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val is not writeable, cache not saved.
Plotting labels to runs/detect/train14/labels.jpg...
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs/detect/train14
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/32      4.32G      1.966      2.539      1.465        145        640: 100% ━━━━━━━━━━━━ 38/38 2.9it/s 13.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.8it/s 1.8ss
                   all        300       1798     0.0199      0.997       0.98       0.59

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/32      4.67G      1.338     0.9955      1.117        166        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.9it/s 1.7ss
                   all        300       1798       0.98      0.816      0.954      0.385

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/32      4.67G      1.349     0.8865      1.124        166        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.8it/s 1.8ss
                   all        300       1798      0.975      0.972      0.984      0.569

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/32      4.67G      1.312     0.8716      1.113        136        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7ss
                   all        300       1798      0.979      0.965       0.98      0.411

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/32      4.67G      1.285      0.786      1.102        165        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7ss
                   all        300       1798      0.986      0.983      0.989       0.63

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/32      4.67G      1.263     0.7234      1.098        171        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.987      0.991      0.993      0.639

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/32      4.67G      1.227     0.6684      1.086        167        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.9it/s 1.7ss
                   all        300       1798      0.988      0.986      0.992      0.572

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/32      4.67G      1.226     0.6448      1.081        141        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798       0.99      0.984       0.99      0.662

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/32      4.67G      1.211     0.6304      1.084        129        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.988      0.975      0.993       0.61

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/32      4.67G      1.197     0.6118      1.077        153        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.994       0.99      0.994      0.671

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/32      4.67G      1.184     0.5853      1.065        192        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.993      0.991      0.994      0.668

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/32      4.67G      1.161     0.5678      1.063        186        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.978      0.983       0.99      0.636

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/32      4.67G       1.17     0.5554      1.067        168        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.993      0.987      0.994      0.693

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/32      4.67G      1.145     0.5409      1.054        169        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.993      0.993      0.994      0.689

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/32      4.67G      1.139     0.5276      1.058        156        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.988      0.985      0.993      0.669

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/32      4.67G      1.144      0.522      1.053        176        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.991      0.986      0.994      0.654

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/32      4.67G      1.125      0.511      1.044        188        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.991      0.993      0.994      0.698

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/32      4.67G      1.115     0.5034       1.04        169        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.993      0.993      0.994       0.69

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/32      4.67G      1.107     0.4911      1.037        155        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.993      0.994      0.994      0.648

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/32      4.67G      1.092     0.4823      1.027        180        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.995      0.991      0.995      0.703

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/32      4.67G      1.083     0.4775      1.029        174        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.994      0.994      0.995      0.703

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/32      4.67G      1.063     0.4712      1.023        149        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.994      0.993      0.995      0.699
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/32      4.67G      1.043     0.4384      1.018         96        640: 100% ━━━━━━━━━━━━ 38/38 2.8it/s 13.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.993      0.992      0.995      0.694

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/32      4.67G      1.033     0.4367      1.018        100        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.996      0.994      0.995        0.7

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/32      4.67G      1.017     0.4239       1.01         99        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.996      0.994      0.995      0.708

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/32      4.68G       1.01     0.4127      1.007        100        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.996      0.993      0.995      0.716

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/32       4.7G     0.9908     0.4057      0.996         82        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.994      0.995      0.995      0.688

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/32      4.71G     0.9835     0.4029     0.9978         92        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798      0.997      0.994      0.995      0.723

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/32      4.72G     0.9802     0.4005     0.9922         96        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.995      0.993      0.995      0.706

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/32      4.73G     0.9677     0.3901     0.9839         89        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.994      0.996      0.995      0.725

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/32      4.74G      0.948     0.3838     0.9809         93        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798      0.995      0.996      0.995      0.732

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/32      4.75G     0.9501      0.381      0.979         99        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.996      0.994      0.995      0.732

32 epochs completed in 0.124 hours.
Optimizer stripped from runs/detect/train14/weights/last.pt, 6.2MB
Optimizer stripped from runs/detect/train14/weights/best.pt, 6.2MB

Validating runs/detect/train14/weights/best.pt...
Ultralytics 8.3.189 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
Model summary (fused): 72 layers, 3,005,843 parameters, 0 gradients, 8.1 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0ss

/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        300       1798      0.996      0.994      0.995      0.732
Speed: 0.1ms preprocess, 1.4ms inference, 0.0ms loss, 3.1ms postprocess per image
Results saved to runs/detect/train14

,Case,Exp No,Experiment Name,Epochs,Batch,lr0,Weight Decay,Optimizer,Image Size,Dropout,Freeze Layers,Activation,Training Time (s),Precision,Recall,mAP@0.5,mAP@0.5:0.95
3,Case 2: Weight Decay,1,wd_0,32,32,0.01,0.0000,SGD,640,0.0,0,SiLU,458.41,0.99622,0.99444,0.99470,0.73197
4,Case 2: Weight Decay,2,wd_0.0001,32,32,0.01,0.0001,SGD,640,0.0,0,SiLU,458.25,0.99622,0.99444,0.99470,0.73197
5,Case 2: Weight Decay,3,wd_0.0005,32,32,0.01,0.0005,SGD,640,0.0,0,SiLU,460.87,0.99622,0.99444,0.99470,0.73197
6,Case 2: Weight Decay,4,wd_0.001,32,32,0.01,0.0010,SGD,640,0.0,0,SiLU,463.15,0.99622,0.99444,0.99470,0.73197
7,Case 2: Weight Decay,5,wd_0.005,32,32,0.01,0.0050,SGD,640,0.0,0,SiLU,463.39,0.99622,0.99444,0.99470,0.73197
8,Case 3: Batch Size,1,batch_16,32,16,0.01,0.0001,SGD,640,0.0,0,SiLU,515.74,0.99389,0.99555,0.99444,0.73239
9,Case 3: Batch Size,2,batch_32,32,32,0.01,0.0001,SGD,640,0.0,0,SiLU,465.39,0.99622,0.99444,0.99470,0.73197
10,Case 3: Batch Size,3,batch_64,32,64,0.01,0.0001,SGD,640,0.0,0,SiLU,449.77,0.99500,0.99605,0.99455,0.73081
11,Case 4: Dropout,1,dropout_0,32,32,0.01,0.0001,SGD,640,0.0,0,SiLU,468.16,0.99622,0.99444,0.99470,0.73197
12,Case 4: Dropout,2,dropout_0.1,32,32,0.01,0.0001,SGD,640,0.1,0,SiLU,462.76,0.99622,0.99444,0.99470,0.73197

Ultralytics 8.3.189 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.2, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train15, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/train15, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    751507  ultralytics.nn.modules.head.Detect           [1, [64, 128, 256]]
Model summary: 129 layers, 3,011,043 parameters, 3,011,027 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 72.8±38.2 MB/s, size: 52.0 KB)
train: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train/labels... 1200 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1200/1200 1018.6it/s 1.2s
WARNING ⚠️ train: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 91.1±43.4 MB/s, size: 61.5 KB)
val: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels... 300 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 300/300 522.3it/s 0.6s
WARNING ⚠️ val: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val is not writeable, cache not saved.
Plotting labels to runs/detect/train15/labels.jpg...
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs/detect/train15
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/32      4.35G      1.966      2.539      1.465        145        640: 100% ━━━━━━━━━━━━ 38/38 2.9it/s 13.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.8it/s 1.8ss
                   all        300       1798     0.0199      0.997       0.98       0.59

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/32       4.7G      1.338     0.9955      1.117        166        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7ss
                   all        300       1798       0.98      0.816      0.954      0.385

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/32       4.7G      1.349     0.8865      1.124        166        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.9it/s 1.7ss
                   all        300       1798      0.975      0.972      0.984      0.569

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/32       4.7G      1.312     0.8716      1.113        136        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.9it/s 1.7ss
                   all        300       1798      0.979      0.965       0.98      0.411

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/32       4.7G      1.285      0.786      1.102        165        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.7it/s 1.9ss
                   all        300       1798      0.986      0.983      0.989       0.63

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/32       4.7G      1.263     0.7234      1.098        171        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.987      0.991      0.993      0.639

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/32       4.7G      1.227     0.6684      1.086        167        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.6ss
                   all        300       1798      0.988      0.986      0.992      0.572

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/32       4.7G      1.226     0.6448      1.081        141        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798       0.99      0.984       0.99      0.662

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/32       4.7G      1.211     0.6304      1.084        129        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.8it/s 1.8ss
                   all        300       1798      0.988      0.975      0.993       0.61

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/32       4.7G      1.197     0.6118      1.077        153        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7ss
                   all        300       1798      0.994       0.99      0.994      0.671

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/32       4.7G      1.184     0.5853      1.065        192        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.993      0.991      0.994      0.668

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/32       4.7G      1.161     0.5678      1.063        186        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7ss
                   all        300       1798      0.978      0.983       0.99      0.636

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/32       4.7G       1.17     0.5554      1.067        168        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.993      0.987      0.994      0.693

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/32       4.7G      1.145     0.5409      1.054        169        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.993      0.993      0.994      0.689

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/32       4.7G      1.142     0.5274      1.064        347        640:   5% ╸─────────── 2/38 1.6it/s 1.0ss

In [12]:
BEST_PARAMS["epochs"] = 32
BEST_PARAMS["weight_decay"] = 0.0001
BEST_PARAMS["batch"] = 32
case4_dropout()

Downloading https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov8n.pt to 'yolov8n.pt': 100% ━━━━━━━━━━━━ 6.2/6.2MB 114.9MB/s 0.1s
Ultralytics 8.3.189 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/train, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Downloading https://ultralytics.com/assets/Arial.ttf to '/root/.config/Ultralytics/Arial.ttf': 100% ━━━━━━━━━━━━ 755.1/755.1KB 23.2MB/s 0.0s
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    751507  ultralytics.nn.modules.head.Detect           [1, [64, 128, 256]]
Model summary: 129 layers, 3,011,043 parameters, 3,011,027 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
Downloading https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11n.pt to 'yolo11n.pt': 100% ━━━━━━━━━━━━ 5.4/5.4MB 114.0MB/s 0.0s
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 14.6±5.3 MB/s, size: 52.0 KB)
train: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train/labels... 1200 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1200/1200 348.1it/s 3.4s
WARNING ⚠️ train: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 18.6±8.1 MB/s, size: 61.5 KB)
val: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels... 300 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 300/300 263.1it/s 1.1s
WARNING ⚠️ val: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val is not writeable, cache not saved.
Plotting labels to runs/detect/train/labels.jpg...
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs/detect/train
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/32      3.95G      1.966      2.539      1.465        145        640: 100% ━━━━━━━━━━━━ 38/38 2.8it/s 13.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.0it/s 2.5ss
                   all        300       1798     0.0199      0.997       0.98       0.59

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/32      4.31G      1.338     0.9955      1.117        166        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798       0.98      0.816      0.954      0.385

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/32      4.32G      1.349     0.8865      1.124        166        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.9it/s 1.7ss
                   all        300       1798      0.975      0.972      0.984      0.569

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/32      4.33G      1.312     0.8716      1.113        136        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.979      0.965       0.98      0.411

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/32      4.34G      1.285      0.786      1.102        165        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.6ss
                   all        300       1798      0.986      0.983      0.989       0.63

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/32      4.35G      1.263     0.7234      1.098        171        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.987      0.991      0.993      0.639

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/32      4.36G      1.227     0.6684      1.086        167        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.6ss
                   all        300       1798      0.988      0.986      0.992      0.572

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/32      4.38G      1.226     0.6448      1.081        141        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798       0.99      0.984       0.99      0.662

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/32      4.39G      1.211     0.6304      1.084        129        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.988      0.975      0.993       0.61

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/32       4.4G      1.197     0.6118      1.077        153        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.994       0.99      0.994      0.671

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/32      4.41G      1.184     0.5853      1.065        192        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.993      0.991      0.994      0.668

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/32      4.42G      1.161     0.5678      1.063        186        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.978      0.983       0.99      0.636

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/32      4.43G       1.17     0.5554      1.067        168        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.993      0.987      0.994      0.693

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/32      4.45G      1.145     0.5409      1.054        169        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.993      0.993      0.994      0.689

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/32      4.46G      1.139     0.5276      1.058        156        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.6ss
                   all        300       1798      0.988      0.985      0.993      0.669

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/32      4.47G      1.144      0.522      1.053        176        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.991      0.986      0.994      0.654

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/32      4.48G      1.125      0.511      1.044        188        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7ss
                   all        300       1798      0.991      0.993      0.994      0.698

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/32      4.49G      1.115     0.5034       1.04        169        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.993      0.993      0.994       0.69

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/32       4.5G      1.107     0.4911      1.037        155        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.993      0.994      0.994      0.648

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/32      4.51G      1.092     0.4823      1.027        180        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.995      0.991      0.995      0.703

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/32      4.53G      1.083     0.4775      1.029        174        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.994      0.994      0.995      0.703

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/32      4.54G      1.063     0.4712      1.023        149        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.994      0.993      0.995      0.699
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/32      4.55G      1.043     0.4384      1.018         96        640: 100% ━━━━━━━━━━━━ 38/38 2.8it/s 13.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.993      0.992      0.995      0.694

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/32      4.56G      1.033     0.4367      1.018        100        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.996      0.994      0.995        0.7

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/32      4.57G      1.017     0.4239       1.01         99        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.996      0.994      0.995      0.708

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/32      4.58G       1.01     0.4127      1.007        100        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.5ss
                   all        300       1798      0.996      0.993      0.995      0.716

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/32      4.59G     0.9908     0.4057      0.996         82        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.994      0.995      0.995      0.688

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/32       4.6G     0.9835     0.4029     0.9978         92        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798      0.997      0.994      0.995      0.723

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/32      4.62G     0.9802     0.4005     0.9922         96        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6s
                   all        300       1798      0.995      0.993      0.995      0.706

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/32      4.63G     0.9677     0.3901     0.9839         89        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.994      0.996      0.995      0.725

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/32      4.64G      0.948     0.3838     0.9809         93        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.995      0.996      0.995      0.732

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/32      4.65G     0.9501      0.381      0.979         99        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.996      0.994      0.995      0.732

32 epochs completed in 0.124 hours.
Optimizer stripped from runs/detect/train/weights/last.pt, 6.2MB
Optimizer stripped from runs/detect/train/weights/best.pt, 6.2MB

Validating runs/detect/train/weights/best.pt...
Ultralytics 8.3.189 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
Model summary (fused): 72 layers, 3,005,843 parameters, 0 gradients, 8.1 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 2.9ss

/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        300       1798      0.996      0.994      0.995      0.732
Speed: 0.1ms preprocess, 1.7ms inference, 0.0ms loss, 2.6ms postprocess per image
Results saved to runs/detect/train

,Case,Exp No,Experiment Name,Epochs,Batch,lr0,Weight Decay,Optimizer,Image Size,Dropout,Freeze Layers,Activation,Training Time (s),Precision,Recall,mAP@0.5,mAP@0.5:0.95
0,Case 4: Dropout,1,dropout_0,32,32,0.01,0.0001,SGD,640,0,0,SiLU,471.56,0.99622,0.99444,0.9947,0.73197

Ultralytics 8.3.189 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.1, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train2, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/train2, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    751507  ultralytics.nn.modules.head.Detect           [1, [64, 128, 256]]
Model summary: 129 layers, 3,011,043 parameters, 3,011,027 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 74.2±20.4 MB/s, size: 52.0 KB)
train: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train/labels... 1200 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1200/1200 840.9it/s 1.4s
WARNING ⚠️ train: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 79.9±41.2 MB/s, size: 61.5 KB)
val: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels... 300 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 300/300 470.2it/s 0.6s
WARNING ⚠️ val: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val is not writeable, cache not saved.
Plotting labels to runs/detect/train2/labels.jpg...
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs/detect/train2
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/32      4.15G      1.966      2.539      1.465        145        640: 100% ━━━━━━━━━━━━ 38/38 2.8it/s 13.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.9it/s 1.8ss
                   all        300       1798     0.0199      0.997       0.98       0.59

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/32       4.5G      1.338     0.9955      1.117        166        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.9it/s 1.7ss
                   all        300       1798       0.98      0.816      0.954      0.385

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/32       4.5G      1.349     0.8865      1.124        166        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7ss
                   all        300       1798      0.975      0.972      0.984      0.569

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/32       4.5G      1.312     0.8716      1.113        136        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.8it/s 1.8ss
                   all        300       1798      0.979      0.965       0.98      0.411

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/32       4.5G      1.285      0.786      1.102        165        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.6ss
                   all        300       1798      0.986      0.983      0.989       0.63

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/32       4.5G      1.263     0.7234      1.098        171        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.987      0.991      0.993      0.639

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/32       4.5G      1.227     0.6684      1.086        167        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.988      0.986      0.992      0.572

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/32       4.5G      1.226     0.6448      1.081        141        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798       0.99      0.984       0.99      0.662

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/32       4.5G      1.211     0.6304      1.084        129        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.988      0.975      0.993       0.61

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/32       4.5G      1.197     0.6118      1.077        153        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.994       0.99      0.994      0.671

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/32       4.5G      1.184     0.5853      1.065        192        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.993      0.991      0.994      0.668

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/32       4.5G      1.161     0.5678      1.063        186        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.978      0.983       0.99      0.636

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/32       4.5G       1.17     0.5554      1.067        168        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.5ss
                   all        300       1798      0.993      0.987      0.994      0.693

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/32       4.5G      1.145     0.5409      1.054        169        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.993      0.993      0.994      0.689

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/32       4.5G      1.139     0.5276      1.058        156        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.988      0.985      0.993      0.669

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/32      4.51G      1.144      0.522      1.053        176        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.991      0.986      0.994      0.654

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/32      4.52G      1.125      0.511      1.044        188        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.991      0.993      0.994      0.698

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/32      4.53G      1.115     0.5034       1.04        169        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7ss
                   all        300       1798      0.993      0.993      0.994       0.69

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/32      4.54G      1.107     0.4911      1.037        155        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.993      0.994      0.994      0.648

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/32      4.55G      1.092     0.4823      1.027        180        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7ss
                   all        300       1798      0.995      0.991      0.995      0.703

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/32      4.56G      1.083     0.4775      1.029        174        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.994      0.994      0.995      0.703

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/32      4.58G      1.063     0.4712      1.023        149        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.994      0.993      0.995      0.699
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/32      4.59G      1.043     0.4384      1.018         96        640: 100% ━━━━━━━━━━━━ 38/38 2.7it/s 14.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.993      0.992      0.995      0.694

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/32       4.6G      1.033     0.4367      1.018        100        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.996      0.994      0.995        0.7

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/32      4.61G      1.017     0.4239       1.01         99        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.996      0.994      0.995      0.708

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/32      4.62G       1.01     0.4127      1.007        100        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.996      0.993      0.995      0.716

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/32      4.63G     0.9908     0.4057      0.996         82        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.994      0.995      0.995      0.688

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/32      4.65G     0.9835     0.4029     0.9978         92        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.997      0.994      0.995      0.723

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/32      4.66G     0.9802     0.4005     0.9922         96        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.995      0.993      0.995      0.706

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/32      4.67G     0.9677     0.3901     0.9839         89        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.994      0.996      0.995      0.725

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/32      4.68G      0.948     0.3838     0.9809         93        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.995      0.996      0.995      0.732

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/32      4.69G     0.9501      0.381      0.979         99        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.996      0.994      0.995      0.732

32 epochs completed in 0.125 hours.
Optimizer stripped from runs/detect/train2/weights/last.pt, 6.2MB
Optimizer stripped from runs/detect/train2/weights/best.pt, 6.2MB

Validating runs/detect/train2/weights/best.pt...
Ultralytics 8.3.189 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
Model summary (fused): 72 layers, 3,005,843 parameters, 0 gradients, 8.1 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0ss

/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        300       1798      0.996      0.994      0.995      0.732
Speed: 0.1ms preprocess, 1.4ms inference, 0.0ms loss, 3.2ms postprocess per image
Results saved to runs/detect/train2

,Case,Exp No,Experiment Name,Epochs,Batch,lr0,Weight Decay,Optimizer,Image Size,Dropout,Freeze Layers,Activation,Training Time (s),Precision,Recall,mAP@0.5,mAP@0.5:0.95
0,Case 4: Dropout,1,dropout_0,32,32,0.01,0.0001,SGD,640,0,0,SiLU,471.56,0.99622,0.99444,0.9947,0.73197
1,Case 4: Dropout,2,dropout_0.1,32,32,0.01,0.0001,SGD,640,0.1,0,SiLU,464.40,0.99622,0.99444,0.9947,0.73197

Ultralytics 8.3.189 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.2, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train3, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/train3, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    751507  ultralytics.nn.modules.head.Detect           [1, [64, 128, 256]]
Model summary: 129 layers, 3,011,043 parameters, 3,011,027 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 62.5±39.4 MB/s, size: 52.0 KB)
train: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train/labels... 1200 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1200/1200 812.8it/s 1.5s
WARNING ⚠️ train: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 69.0±22.6 MB/s, size: 61.5 KB)
val: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels... 300 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 300/300 437.3it/s 0.7s
WARNING ⚠️ val: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val is not writeable, cache not saved.
Plotting labels to runs/detect/train3/labels.jpg...
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs/detect/train3
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/32      4.21G      1.966      2.539      1.465        145        640: 100% ━━━━━━━━━━━━ 38/38 2.9it/s 13.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.7it/s 1.9ss
                   all        300       1798     0.0199      0.997       0.98       0.59

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/32      4.56G      1.338     0.9955      1.117        166        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.8it/s 1.8ss
                   all        300       1798       0.98      0.816      0.954      0.385

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/32      4.56G      1.349     0.8865      1.124        166        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.7it/s 1.8ss
                   all        300       1798      0.975      0.972      0.984      0.569

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/32      4.56G      1.312     0.8716      1.113        136        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7ss
                   all        300       1798      0.979      0.965       0.98      0.411

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/32      4.56G      1.285      0.786      1.102        165        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.986      0.983      0.989       0.63

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/32      4.56G      1.263     0.7234      1.098        171        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7ss
                   all        300       1798      0.987      0.991      0.993      0.639

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/32      4.56G      1.227     0.6684      1.086        167        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.6it/s 1.9ss
                   all        300       1798      0.988      0.986      0.992      0.572

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/32      4.56G      1.226     0.6448      1.081        141        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7ss
                   all        300       1798       0.99      0.984       0.99      0.662

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/32      4.56G      1.211     0.6304      1.084        129        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.988      0.975      0.993       0.61

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/32      4.56G      1.197     0.6118      1.077        153        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7ss
                   all        300       1798      0.994       0.99      0.994      0.671

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/32      4.56G      1.184     0.5853      1.065        192        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.993      0.991      0.994      0.668

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/32      4.56G      1.161     0.5678      1.063        186        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7ss
                   all        300       1798      0.978      0.983       0.99      0.636

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/32      4.56G       1.17     0.5554      1.067        168        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.993      0.987      0.994      0.693

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/32      4.56G      1.145     0.5409      1.054        169        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7ss
                   all        300       1798      0.993      0.993      0.994      0.689

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/32      4.56G      1.139     0.5276      1.058        156        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7ss
                   all        300       1798      0.988      0.985      0.993      0.669

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/32      4.56G      1.144      0.522      1.053        176        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.6ss
                   all        300       1798      0.991      0.986      0.994      0.654

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/32      4.56G      1.125      0.511      1.044        188        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.991      0.993      0.994      0.698

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/32      4.56G      1.115     0.5034       1.04        169        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.993      0.993      0.994       0.69

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/32      4.56G      1.107     0.4911      1.037        155        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.5ss
                   all        300       1798      0.993      0.994      0.994      0.648

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/32      4.56G      1.092     0.4823      1.027        180        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.995      0.991      0.995      0.703

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/32      4.57G      1.083     0.4775      1.029        174        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.994      0.994      0.995      0.703

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/32      4.58G      1.063     0.4712      1.023        149        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.5ss
                   all        300       1798      0.994      0.993      0.995      0.699
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/32      4.59G      1.043     0.4384      1.018         96        640: 100% ━━━━━━━━━━━━ 38/38 2.8it/s 13.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.993      0.992      0.995      0.694

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/32       4.6G      1.033     0.4367      1.018        100        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.996      0.994      0.995        0.7

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/32      4.61G      1.017     0.4239       1.01         99        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.5ss
                   all        300       1798      0.996      0.994      0.995      0.708

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/32      4.62G       1.01     0.4127      1.007        100        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.996      0.993      0.995      0.716

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/32      4.63G     0.9908     0.4057      0.996         82        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.5ss
                   all        300       1798      0.994      0.995      0.995      0.688

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/32      4.64G     0.9835     0.4029     0.9978         92        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.997      0.994      0.995      0.723

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/32      4.66G     0.9802     0.4005     0.9922         96        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.995      0.993      0.995      0.706

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/32      4.67G     0.9677     0.3901     0.9839         89        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5s
                   all        300       1798      0.994      0.996      0.995      0.725

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/32      4.68G      0.948     0.3838     0.9809         93        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.995      0.996      0.995      0.732

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/32      4.69G     0.9501      0.381      0.979         99        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.5it/s 1.4s
                   all        300       1798      0.996      0.994      0.995      0.732

32 epochs completed in 0.125 hours.
Optimizer stripped from runs/detect/train3/weights/last.pt, 6.2MB
Optimizer stripped from runs/detect/train3/weights/best.pt, 6.2MB

Validating runs/detect/train3/weights/best.pt...
Ultralytics 8.3.189 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
Model summary (fused): 72 layers, 3,005,843 parameters, 0 gradients, 8.1 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.8it/s 2.8ss

/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        300       1798      0.996      0.994      0.995      0.732
Speed: 0.1ms preprocess, 1.4ms inference, 0.0ms loss, 2.7ms postprocess per image
Results saved to runs/detect/train3

,Case,Exp No,Experiment Name,Epochs,Batch,lr0,Weight Decay,Optimizer,Image Size,Dropout,Freeze Layers,Activation,Training Time (s),Precision,Recall,mAP@0.5,mAP@0.5:0.95
0,Case 4: Dropout,1,dropout_0,32,32,0.01,0.0001,SGD,640,0,0,SiLU,471.56,0.99622,0.99444,0.9947,0.73197
1,Case 4: Dropout,2,dropout_0.1,32,32,0.01,0.0001,SGD,640,0.1,0,SiLU,464.40,0.99622,0.99444,0.9947,0.73197
2,Case 4: Dropout,3,dropout_0.2,32,32,0.01,0.0001,SGD,640,0.2,0,SiLU,463.41,0.99622,0.99444,0.9947,0.73197

Ultralytics 8.3.189 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.3, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train4, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/train4, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    751507  ultralytics.nn.modules.head.Detect           [1, [64, 128, 256]]
Model summary: 129 layers, 3,011,043 parameters, 3,011,027 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 92.6±40.0 MB/s, size: 52.0 KB)
train: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train/labels... 1200 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1200/1200 937.1it/s 1.3s
WARNING ⚠️ train: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 95.8±48.8 MB/s, size: 61.5 KB)
val: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels... 300 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 300/300 528.0it/s 0.6s
WARNING ⚠️ val: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val is not writeable, cache not saved.
Plotting labels to runs/detect/train4/labels.jpg...
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs/detect/train4
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/32      4.25G      1.966      2.539      1.465        145        640: 100% ━━━━━━━━━━━━ 38/38 2.9it/s 13.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7ss
                   all        300       1798     0.0199      0.997       0.98       0.59

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/32       4.6G      1.338     0.9955      1.117        166        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798       0.98      0.816      0.954      0.385

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/32       4.6G      1.349     0.8865      1.124        166        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.975      0.972      0.984      0.569

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/32       4.6G      1.312     0.8716      1.113        136        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7ss
                   all        300       1798      0.979      0.965       0.98      0.411

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/32       4.6G      1.285      0.786      1.102        165        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.9it/s 1.7ss
                   all        300       1798      0.986      0.983      0.989       0.63

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/32       4.6G      1.263     0.7234      1.098        171        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.987      0.991      0.993      0.639

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/32       4.6G      1.227     0.6684      1.086        167        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.988      0.986      0.992      0.572

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/32       4.6G      1.226     0.6448      1.081        141        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798       0.99      0.984       0.99      0.662

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/32       4.6G      1.211     0.6304      1.084        129        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.988      0.975      0.993       0.61

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/32       4.6G      1.197     0.6118      1.077        153        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.994       0.99      0.994      0.671

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/32       4.6G      1.184     0.5853      1.065        192        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.993      0.991      0.994      0.668

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/32       4.6G      1.161     0.5678      1.063        186        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.978      0.983       0.99      0.636

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/32       4.6G       1.17     0.5554      1.067        168        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.993      0.987      0.994      0.693

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/32       4.6G      1.145     0.5409      1.054        169        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.993      0.993      0.994      0.689

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/32       4.6G      1.139     0.5276      1.058        156        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.988      0.985      0.993      0.669

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/32       4.6G      1.144      0.522      1.053        176        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.991      0.986      0.994      0.654

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/32       4.6G      1.125      0.511      1.044        188        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.991      0.993      0.994      0.698

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/32       4.6G      1.115     0.5034       1.04        169        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.993      0.993      0.994       0.69

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/32       4.6G      1.107     0.4911      1.037        155        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.993      0.994      0.994      0.648

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/32       4.6G      1.092     0.4823      1.027        180        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.995      0.991      0.995      0.703

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/32       4.6G      1.083     0.4775      1.029        174        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798      0.994      0.994      0.995      0.703

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/32       4.6G      1.063     0.4712      1.023        149        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798      0.994      0.993      0.995      0.699
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/32       4.6G      1.043     0.4384      1.018         96        640: 100% ━━━━━━━━━━━━ 38/38 2.8it/s 13.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.993      0.992      0.995      0.694

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/32       4.6G      1.033     0.4367      1.018        100        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798      0.996      0.994      0.995        0.7

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/32      4.61G      1.017     0.4239       1.01         99        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798      0.996      0.994      0.995      0.708

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/32      4.62G       1.01     0.4127      1.007        100        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.5it/s 1.4ss
                   all        300       1798      0.996      0.993      0.995      0.716

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/32      4.63G     0.9908     0.4057      0.996         82        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.994      0.995      0.995      0.688

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/32      4.64G     0.9835     0.4029     0.9978         92        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798      0.997      0.994      0.995      0.723

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/32      4.65G     0.9802     0.4005     0.9922         96        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.995      0.993      0.995      0.706

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/32      4.66G     0.9677     0.3901     0.9839         89        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.5ss
                   all        300       1798      0.994      0.996      0.995      0.725

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/32      4.68G      0.948     0.3838     0.9809         93        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798      0.995      0.996      0.995      0.732

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/32      4.69G     0.9501      0.381      0.979         99        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798      0.996      0.994      0.995      0.732

32 epochs completed in 0.123 hours.
Optimizer stripped from runs/detect/train4/weights/last.pt, 6.2MB
Optimizer stripped from runs/detect/train4/weights/best.pt, 6.2MB

Validating runs/detect/train4/weights/best.pt...
Ultralytics 8.3.189 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
Model summary (fused): 72 layers, 3,005,843 parameters, 0 gradients, 8.1 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.6it/s 3.0ss

/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        300       1798      0.996      0.994      0.995      0.732
Speed: 0.1ms preprocess, 1.4ms inference, 0.0ms loss, 2.8ms postprocess per image
Results saved to runs/detect/train4

,Case,Exp No,Experiment Name,Epochs,Batch,lr0,Weight Decay,Optimizer,Image Size,Dropout,Freeze Layers,Activation,Training Time (s),Precision,Recall,mAP@0.5,mAP@0.5:0.95
0,Case 4: Dropout,1,dropout_0,32,32,0.01,0.0001,SGD,640,0,0,SiLU,471.56,0.99622,0.99444,0.9947,0.73197
1,Case 4: Dropout,2,dropout_0.1,32,32,0.01,0.0001,SGD,640,0.1,0,SiLU,464.40,0.99622,0.99444,0.9947,0.73197
2,Case 4: Dropout,3,dropout_0.2,32,32,0.01,0.0001,SGD,640,0.2,0,SiLU,463.41,0.99622,0.99444,0.9947,0.73197
3,Case 4: Dropout,4,dropout_0.3,32,32,0.01,0.0001,SGD,640,0.3,0,SiLU,457.36,0.99622,0.99444,0.9947,0.73197

Ultralytics 8.3.189 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.5, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train5, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/train5, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    751507  ultralytics.nn.modules.head.Detect           [1, [64, 128, 256]]
Model summary: 129 layers, 3,011,043 parameters, 3,011,027 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 5.0±1.2 MB/s, size: 52.0 KB)
train: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train/labels... 1200 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1200/1200 888.9it/s 1.3s
WARNING ⚠️ train: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 8.3±5.1 MB/s, size: 61.5 KB)
val: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels... 300 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 300/300 434.3it/s 0.7s
WARNING ⚠️ val: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val is not writeable, cache not saved.
Plotting labels to runs/detect/train5/labels.jpg...
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs/detect/train5
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/32      4.25G      1.966      2.539      1.465        145        640: 100% ━━━━━━━━━━━━ 38/38 2.9it/s 12.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.9it/s 1.7ss
                   all        300       1798     0.0199      0.997       0.98       0.59

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/32       4.6G      1.338     0.9955      1.117        166        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.6ss
                   all        300       1798       0.98      0.816      0.954      0.385

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/32       4.6G      1.349     0.8865      1.124        166        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7ss
                   all        300       1798      0.975      0.972      0.984      0.569

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/32       4.6G      1.312     0.8716      1.113        136        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.9it/s 1.7ss
                   all        300       1798      0.979      0.965       0.98      0.411

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/32       4.6G      1.285      0.786      1.102        165        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.986      0.983      0.989       0.63

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/32       4.6G      1.263     0.7234      1.098        171        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.5ss
                   all        300       1798      0.987      0.991      0.993      0.639

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/32       4.6G      1.227     0.6684      1.086        167        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.988      0.986      0.992      0.572

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/32       4.6G      1.226     0.6448      1.081        141        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.5ss
                   all        300       1798       0.99      0.984       0.99      0.662

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/32       4.6G      1.211     0.6304      1.084        129        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.988      0.975      0.993       0.61

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/32       4.6G      1.197     0.6118      1.077        153        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.994       0.99      0.994      0.671

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/32       4.6G      1.184     0.5853      1.065        192        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.993      0.991      0.994      0.668

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/32       4.6G      1.161     0.5678      1.063        186        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.978      0.983       0.99      0.636

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/32       4.6G       1.17     0.5554      1.067        168        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.993      0.987      0.994      0.693

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/32       4.6G      1.145     0.5409      1.054        169        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.993      0.993      0.994      0.689

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/32       4.6G      1.139     0.5276      1.058        156        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.988      0.985      0.993      0.669

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/32       4.6G      1.144      0.522      1.053        176        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.991      0.986      0.994      0.654

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/32       4.6G      1.125      0.511      1.044        188        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.991      0.993      0.994      0.698

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/32       4.6G      1.115     0.5034       1.04        169        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.993      0.993      0.994       0.69

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/32       4.6G      1.107     0.4911      1.037        155        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.993      0.994      0.994      0.648

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/32       4.6G      1.092     0.4823      1.027        180        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.995      0.991      0.995      0.703

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/32       4.6G      1.083     0.4775      1.029        174        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798      0.994      0.994      0.995      0.703

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/32       4.6G      1.063     0.4712      1.023        149        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.5ss
                   all        300       1798      0.994      0.993      0.995      0.699
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/32       4.6G      1.043     0.4384      1.018         96        640: 100% ━━━━━━━━━━━━ 38/38 2.8it/s 13.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.993      0.992      0.995      0.694

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/32       4.6G      1.033     0.4367      1.018        100        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.996      0.994      0.995        0.7

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/32      4.61G      1.017     0.4239       1.01         99        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.996      0.994      0.995      0.708

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/32      4.62G       1.01     0.4127      1.007        100        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798      0.996      0.993      0.995      0.716

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/32      4.63G     0.9908     0.4057      0.996         82        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.994      0.995      0.995      0.688

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/32      4.64G     0.9835     0.4029     0.9978         92        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.997      0.994      0.995      0.723

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/32      4.65G     0.9802     0.4005     0.9922         96        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.995      0.993      0.995      0.706

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/32      4.66G     0.9677     0.3901     0.9839         89        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.5ss
                   all        300       1798      0.994      0.996      0.995      0.725

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/32      4.67G      0.948     0.3838     0.9809         93        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798      0.995      0.996      0.995      0.732

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/32      4.69G     0.9501      0.381      0.979         99        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798      0.996      0.994      0.995      0.732

32 epochs completed in 0.124 hours.
Optimizer stripped from runs/detect/train5/weights/last.pt, 6.2MB
Optimizer stripped from runs/detect/train5/weights/best.pt, 6.2MB

Validating runs/detect/train5/weights/best.pt...
Ultralytics 8.3.189 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
Model summary (fused): 72 layers, 3,005,843 parameters, 0 gradients, 8.1 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0ss

/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        300       1798      0.996      0.994      0.995      0.732
Speed: 0.2ms preprocess, 1.4ms inference, 0.0ms loss, 3.4ms postprocess per image
Results saved to runs/detect/train5

,Case,Exp No,Experiment Name,Epochs,Batch,lr0,Weight Decay,Optimizer,Image Size,Dropout,Freeze Layers,Activation,Training Time (s),Precision,Recall,mAP@0.5,mAP@0.5:0.95
0,Case 4: Dropout,1,dropout_0,32,32,0.01,0.0001,SGD,640,0,0,SiLU,471.56,0.99622,0.99444,0.9947,0.73197
1,Case 4: Dropout,2,dropout_0.1,32,32,0.01,0.0001,SGD,640,0.1,0,SiLU,464.40,0.99622,0.99444,0.9947,0.73197
2,Case 4: Dropout,3,dropout_0.2,32,32,0.01,0.0001,SGD,640,0.2,0,SiLU,463.41,0.99622,0.99444,0.9947,0.73197
3,Case 4: Dropout,4,dropout_0.3,32,32,0.01,0.0001,SGD,640,0.3,0,SiLU,457.36,0.99622,0.99444,0.9947,0.73197
4,Case 4: Dropout,5,dropout_0.5,32,32,0.01,0.0001,SGD,640,0.5,0,SiLU,458.67,0.99622,0.99444,0.9947,0.73197

In [13]:
case6_optimizer()

Ultralytics 8.3.189 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train6, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/train6, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    751507  ultralytics.nn.modules.head.Detect           [1, [64, 128, 256]]
Model summary: 129 layers, 3,011,043 parameters, 3,011,027 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 92.5±32.1 MB/s, size: 52.0 KB)
train: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train/labels... 1200 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1200/1200 856.2it/s 1.4s
WARNING ⚠️ train: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 74.0±36.7 MB/s, size: 61.5 KB)
val: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels... 300 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 300/300 465.2it/s 0.6s
WARNING ⚠️ val: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val is not writeable, cache not saved.
Plotting labels to runs/detect/train6/labels.jpg...
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs/detect/train6
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/32      4.24G      1.966      2.539      1.465        145        640: 100% ━━━━━━━━━━━━ 38/38 2.9it/s 12.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.8it/s 1.8ss
                   all        300       1798     0.0199      0.997       0.98       0.59

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/32      4.59G      1.338     0.9955      1.117        166        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7ss
                   all        300       1798       0.98      0.816      0.954      0.385

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/32      4.59G      1.349     0.8865      1.124        166        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7ss
                   all        300       1798      0.975      0.972      0.984      0.569

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/32      4.59G      1.312     0.8716      1.113        136        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.979      0.965       0.98      0.411

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/32      4.59G      1.285      0.786      1.102        165        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.986      0.983      0.989       0.63

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/32      4.59G      1.263     0.7234      1.098        171        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.987      0.991      0.993      0.639

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/32      4.59G      1.227     0.6684      1.086        167        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.5ss
                   all        300       1798      0.988      0.986      0.992      0.572

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/32      4.59G      1.226     0.6448      1.081        141        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.5ss
                   all        300       1798       0.99      0.984       0.99      0.662

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/32      4.59G      1.211     0.6304      1.084        129        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.988      0.975      0.993       0.61

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/32      4.59G      1.197     0.6118      1.077        153        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.994       0.99      0.994      0.671

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/32      4.59G      1.184     0.5853      1.065        192        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.993      0.991      0.994      0.668

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/32      4.59G      1.161     0.5678      1.063        186        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.978      0.983       0.99      0.636

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/32      4.59G       1.17     0.5554      1.067        168        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.993      0.987      0.994      0.693

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/32      4.59G      1.145     0.5409      1.054        169        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.5ss
                   all        300       1798      0.993      0.993      0.994      0.689

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/32      4.59G      1.139     0.5276      1.058        156        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.988      0.985      0.993      0.669

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/32      4.59G      1.144      0.522      1.053        176        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798      0.991      0.986      0.994      0.654

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/32      4.59G      1.125      0.511      1.044        188        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.991      0.993      0.994      0.698

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/32      4.59G      1.115     0.5034       1.04        169        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.993      0.993      0.994       0.69

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/32      4.59G      1.107     0.4911      1.037        155        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.993      0.994      0.994      0.648

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/32      4.59G      1.092     0.4823      1.027        180        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.995      0.991      0.995      0.703

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/32      4.59G      1.083     0.4775      1.029        174        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.994      0.994      0.995      0.703

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/32      4.59G      1.063     0.4712      1.023        149        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.994      0.993      0.995      0.699
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/32      4.59G      1.043     0.4384      1.018         96        640: 100% ━━━━━━━━━━━━ 38/38 2.8it/s 13.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.993      0.992      0.995      0.694

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/32      4.59G      1.033     0.4367      1.018        100        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798      0.996      0.994      0.995        0.7

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/32      4.61G      1.017     0.4239       1.01         99        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798      0.996      0.994      0.995      0.708

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/32      4.62G       1.01     0.4127      1.007        100        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5s
                   all        300       1798      0.996      0.993      0.995      0.716

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/32      4.63G     0.9908     0.4057      0.996         82        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.994      0.995      0.995      0.688

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/32      4.64G     0.9835     0.4029     0.9978         92        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798      0.997      0.994      0.995      0.723

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/32      4.65G     0.9802     0.4005     0.9922         96        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798      0.995      0.993      0.995      0.706

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/32      4.66G     0.9677     0.3901     0.9839         89        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.994      0.996      0.995      0.725

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/32      4.68G      0.948     0.3838     0.9809         93        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798      0.995      0.996      0.995      0.732

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/32      4.69G     0.9501      0.381      0.979         99        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798      0.996      0.994      0.995      0.732

32 epochs completed in 0.123 hours.
Optimizer stripped from runs/detect/train6/weights/last.pt, 6.2MB
Optimizer stripped from runs/detect/train6/weights/best.pt, 6.2MB

Validating runs/detect/train6/weights/best.pt...
Ultralytics 8.3.189 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
Model summary (fused): 72 layers, 3,005,843 parameters, 0 gradients, 8.1 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.6it/s 3.0ss

/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        300       1798      0.996      0.994      0.995      0.732
Speed: 0.1ms preprocess, 1.4ms inference, 0.0ms loss, 2.9ms postprocess per image
Results saved to runs/detect/train6

,Case,Exp No,Experiment Name,Epochs,Batch,lr0,Weight Decay,Optimizer,Image Size,Dropout,Freeze Layers,Activation,Training Time (s),Precision,Recall,mAP@0.5,mAP@0.5:0.95
0,Case 4: Dropout,1,dropout_0,32,32,0.01,0.0001,SGD,640,0,0,SiLU,471.56,0.99622,0.99444,0.9947,0.73197
1,Case 4: Dropout,2,dropout_0.1,32,32,0.01,0.0001,SGD,640,0.1,0,SiLU,464.40,0.99622,0.99444,0.9947,0.73197
2,Case 4: Dropout,3,dropout_0.2,32,32,0.01,0.0001,SGD,640,0.2,0,SiLU,463.41,0.99622,0.99444,0.9947,0.73197
3,Case 4: Dropout,4,dropout_0.3,32,32,0.01,0.0001,SGD,640,0.3,0,SiLU,457.36,0.99622,0.99444,0.9947,0.73197
4,Case 4: Dropout,5,dropout_0.5,32,32,0.01,0.0001,SGD,640,0.5,0,SiLU,458.67,0.99622,0.99444,0.9947,0.73197
5,Case 6: Optimizer,1,optimizer_SGD,32,32,0.01,0.0001,SGD,640,0.0,0,SiLU,457.57,0.99622,0.99444,0.9947,0.73197

Ultralytics 8.3.189 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train7, nbs=64, nms=False, opset=None, optimize=False, optimizer=Adam, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/train7, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    751507  ultralytics.nn.modules.head.Detect           [1, [64, 128, 256]]
Model summary: 129 layers, 3,011,043 parameters, 3,011,027 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 85.7±28.0 MB/s, size: 52.0 KB)
train: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train/labels... 1200 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1200/1200 927.7it/s 1.3s
WARNING ⚠️ train: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 90.7±47.8 MB/s, size: 61.5 KB)
val: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels... 300 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 300/300 575.4it/s 0.5s
WARNING ⚠️ val: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val is not writeable, cache not saved.
Plotting labels to runs/detect/train7/labels.jpg...
optimizer: Adam(lr=0.01, momentum=0.937) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs/detect/train7
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/32      4.25G      1.913      1.893      1.442        145        640: 100% ━━━━━━━━━━━━ 38/38 2.8it/s 13.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.5ss
                   all        300       1798    0.00346      0.173    0.00206    0.00059

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/32       4.6G      1.431     0.9213      1.198        166        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.8it/s 1.8ss
                   all        300       1798     0.0202      0.118    0.00928    0.00494

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/32       4.6G      1.372     0.8251      1.163        166        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.027     0.0423    0.00576    0.00136

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/32       4.6G       1.39     0.8141      1.184        136        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.5it/s 1.4ss
                   all        300       1798      0.879      0.835      0.882      0.358

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/32       4.6G      1.352       0.76      1.166        165        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.169      0.284     0.0906      0.019

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/32       4.6G      1.319     0.7438      1.156        171        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.482      0.614      0.495      0.184

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/32       4.6G      1.349     0.7372      1.172        167        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.774      0.789      0.814      0.405

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/32       4.6G      1.323     0.7151      1.149        141        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.909      0.907      0.938      0.479

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/32       4.6G      1.295     0.6878      1.151        129        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.985      0.974      0.989      0.607

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/32       4.6G      1.283     0.6751      1.139        153        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.951      0.965      0.975      0.551

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/32       4.6G      1.264     0.6354      1.127        192        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.647      0.567      0.586      0.173

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/32       4.6G      1.275     0.6346      1.139        186        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.978      0.975      0.986       0.63

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/32       4.6G      1.255     0.6201       1.14        168        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798       0.98      0.981       0.99      0.594

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/32       4.6G      1.298     0.6322      1.147        169        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.896      0.934      0.935      0.457

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/32       4.6G      1.296     0.6284      1.161        156        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798      0.966      0.912       0.97      0.597

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/32       4.6G      1.259     0.6086      1.144        176        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.898      0.844      0.906      0.523

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/32      4.62G      1.234     0.5847      1.131        188        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.971      0.976      0.974      0.571

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/32      4.63G      1.214     0.5639      1.119        169        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.5it/s 1.4s
                   all        300       1798       0.99      0.981      0.992      0.655

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/32      4.65G      1.238     0.5765      1.131        155        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.986      0.983      0.992      0.643

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/32      4.67G      1.214     0.5554      1.116        180        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798       0.97      0.901      0.959      0.597

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/32      4.68G      1.201     0.5395      1.116        174        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.5it/s 1.4ss
                   all        300       1798      0.985      0.991      0.991      0.673

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/32       4.7G      1.185     0.5287      1.115        149        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.989      0.979      0.988       0.63
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/32      4.72G      1.154     0.5122      1.117         96        640: 100% ━━━━━━━━━━━━ 38/38 2.8it/s 13.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.988      0.984      0.992      0.649

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/32      4.73G       1.16     0.5001      1.108        100        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.992      0.984      0.994      0.664

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/32      4.75G      1.148     0.4931      1.109         99        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.903      0.832      0.912      0.578

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/32      4.77G      1.137     0.4798      1.102        100        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.5it/s 1.4ss
                   all        300       1798      0.995      0.988      0.993      0.674

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/32      4.79G      1.116     0.4542      1.091         82        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.5ss
                   all        300       1798      0.994      0.993      0.994      0.691

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/32       4.8G      1.107      0.443      1.092         92        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.5it/s 1.4ss
                   all        300       1798      0.988       0.99      0.993      0.669

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/32      4.82G      1.107     0.4408      1.088         96        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.993      0.992      0.994      0.691

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/32      4.84G      1.079     0.4274      1.069         89        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.993      0.994      0.994      0.693

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/32      4.86G       1.07     0.4247      1.069         93        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.991      0.992      0.993      0.696

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/32      4.87G      1.069     0.4144      1.068         99        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798      0.993      0.994      0.995      0.714

32 epochs completed in 0.124 hours.
Optimizer stripped from runs/detect/train7/weights/last.pt, 6.2MB
Optimizer stripped from runs/detect/train7/weights/best.pt, 6.2MB

Validating runs/detect/train7/weights/best.pt...
Ultralytics 8.3.189 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
Model summary (fused): 72 layers, 3,005,843 parameters, 0 gradients, 8.1 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0ss

/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        300       1798      0.993      0.994      0.995      0.714
Speed: 0.1ms preprocess, 1.4ms inference, 0.0ms loss, 2.8ms postprocess per image
Results saved to runs/detect/train7

,Case,Exp No,Experiment Name,Epochs,Batch,lr0,Weight Decay,Optimizer,Image Size,Dropout,Freeze Layers,Activation,Training Time (s),Precision,Recall,mAP@0.5,mAP@0.5:0.95
0,Case 4: Dropout,1,dropout_0,32,32,0.01,0.0001,SGD,640,0,0,SiLU,471.56,0.99622,0.99444,0.99470,0.73197
1,Case 4: Dropout,2,dropout_0.1,32,32,0.01,0.0001,SGD,640,0.1,0,SiLU,464.40,0.99622,0.99444,0.99470,0.73197
2,Case 4: Dropout,3,dropout_0.2,32,32,0.01,0.0001,SGD,640,0.2,0,SiLU,463.41,0.99622,0.99444,0.99470,0.73197
3,Case 4: Dropout,4,dropout_0.3,32,32,0.01,0.0001,SGD,640,0.3,0,SiLU,457.36,0.99622,0.99444,0.99470,0.73197
4,Case 4: Dropout,5,dropout_0.5,32,32,0.01,0.0001,SGD,640,0.5,0,SiLU,458.67,0.99622,0.99444,0.99470,0.73197
5,Case 6: Optimizer,1,optimizer_SGD,32,32,0.01,0.0001,SGD,640,0.0,0,SiLU,457.57,0.99622,0.99444,0.99470,0.73197
6,Case 6: Optimizer,2,optimizer_Adam,32,32,0.01,0.0001,Adam,640,0.0,0,SiLU,460.64,0.99253,0.99388,0.99452,0.71447

Ultralytics 8.3.189 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train8, nbs=64, nms=False, opset=None, optimize=False, optimizer=AdamW, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/train8, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    751507  ultralytics.nn.modules.head.Detect           [1, [64, 128, 256]]
Model summary: 129 layers, 3,011,043 parameters, 3,011,027 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 88.1±34.6 MB/s, size: 52.0 KB)
train: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train/labels... 1200 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1200/1200 985.3it/s 1.2s
WARNING ⚠️ train: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 69.5±53.4 MB/s, size: 61.5 KB)
val: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels... 300 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 300/300 535.8it/s 0.6s
WARNING ⚠️ val: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val is not writeable, cache not saved.
Plotting labels to runs/detect/train8/labels.jpg...
optimizer: AdamW(lr=0.01, momentum=0.937) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs/detect/train8
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/32      4.35G      1.906      1.896      1.442        145        640: 100% ━━━━━━━━━━━━ 38/38 2.9it/s 13.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.5it/s 2.0ss
                   all        300       1798    0.00568      0.258    0.00352   0.000967

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/32       4.7G       1.43     0.9433      1.203        166        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.397      0.486      0.364      0.161

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/32       4.7G      1.369     0.8309      1.168        166        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.6it/s 2.0ss
                   all        300       1798    0.00919      0.459    0.00672    0.00203

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/32       4.7G      1.383     0.8458      1.183        136        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.6it/s 1.9ss
                   all        300       1798    0.00324    0.00167    0.00028   4.43e-05

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/32       4.7G      1.337     0.7804      1.161        165        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.7it/s 1.9ss
                   all        300       1798      0.104      0.162     0.0471     0.0141

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/32       4.7G      1.338     0.7378      1.171        171        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.206      0.233      0.134     0.0472

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/32       4.7G      1.342     0.7228      1.181        167        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.961       0.94      0.984      0.557

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/32       4.7G      1.305      0.682      1.156        141        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798      0.918      0.906      0.947      0.553

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/32       4.7G      1.301     0.6702      1.166        129        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.976      0.982      0.993      0.606

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/32       4.7G      1.283     0.6516      1.152        153        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.979       0.98      0.987      0.627

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/32       4.7G      1.271     0.6209      1.142        192        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.971      0.969      0.975      0.573

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/32       4.7G      1.257     0.6128      1.141        186        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.5ss
                   all        300       1798      0.951      0.957      0.963       0.53

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/32       4.7G      1.273      0.608      1.154        168        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.933      0.915      0.953      0.539

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/32       4.7G      1.261      0.603      1.144        169        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.989      0.988      0.992       0.61

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/32       4.7G      1.247     0.5913      1.145        156        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.991      0.982      0.989      0.657

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/32       4.7G      1.227     0.5665      1.142        176        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.993      0.986      0.992      0.602

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/32       4.7G      1.236      0.565      1.134        188        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798      0.964      0.945       0.97      0.566

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/32       4.7G      1.213     0.5462      1.125        169        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.989      0.986       0.99      0.659

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/32       4.7G      1.236     0.5504      1.134        155        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.6ss
                   all        300       1798      0.989      0.989      0.993       0.64

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/32       4.7G      1.192     0.5228      1.115        180        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798       0.99      0.985      0.993      0.636

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/32       4.7G      1.174     0.5153      1.106        174        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.975      0.975      0.989      0.639

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/32      4.71G       1.17     0.5122      1.107        149        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.993      0.988      0.992      0.664
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/32      4.73G      1.148     0.4746      1.117         96        640: 100% ━━━━━━━━━━━━ 38/38 2.8it/s 13.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.5ss
                   all        300       1798      0.875      0.873      0.915      0.545

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/32      4.75G      1.158     0.4786      1.119        100        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798       0.99      0.984      0.992      0.661

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/32      4.76G      1.118     0.4687      1.096         99        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798      0.989      0.988      0.995      0.662

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/32      4.78G      1.122     0.4571      1.095        100        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.993      0.992      0.994      0.682

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/32       4.8G      1.083     0.4397      1.076         82        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.992      0.987      0.994      0.682

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/32      4.81G      1.087     0.4309      1.084         92        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.991       0.99      0.995      0.694

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/32      4.83G      1.077     0.4258      1.084         96        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798      0.996      0.992      0.994      0.711

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/32      4.85G      1.057     0.4196      1.074         89        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.996      0.996      0.994      0.717

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/32      4.87G      1.048     0.4113      1.072         93        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.995      0.994      0.994       0.72

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/32      4.88G      1.046     0.4014      1.066         99        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798      0.994      0.995      0.994      0.724

32 epochs completed in 0.125 hours.
Optimizer stripped from runs/detect/train8/weights/last.pt, 6.2MB
Optimizer stripped from runs/detect/train8/weights/best.pt, 6.2MB

Validating runs/detect/train8/weights/best.pt...
Ultralytics 8.3.189 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
Model summary (fused): 72 layers, 3,005,843 parameters, 0 gradients, 8.1 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0ss

/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        300       1798      0.993      0.995      0.994      0.724
Speed: 0.1ms preprocess, 1.4ms inference, 0.0ms loss, 3.0ms postprocess per image
Results saved to runs/detect/train8

,Case,Exp No,Experiment Name,Epochs,Batch,lr0,Weight Decay,Optimizer,Image Size,Dropout,Freeze Layers,Activation,Training Time (s),Precision,Recall,mAP@0.5,mAP@0.5:0.95
0,Case 4: Dropout,1,dropout_0,32,32,0.01,0.0001,SGD,640,0,0,SiLU,471.56,0.99622,0.99444,0.99470,0.73197
1,Case 4: Dropout,2,dropout_0.1,32,32,0.01,0.0001,SGD,640,0.1,0,SiLU,464.40,0.99622,0.99444,0.99470,0.73197
2,Case 4: Dropout,3,dropout_0.2,32,32,0.01,0.0001,SGD,640,0.2,0,SiLU,463.41,0.99622,0.99444,0.99470,0.73197
3,Case 4: Dropout,4,dropout_0.3,32,32,0.01,0.0001,SGD,640,0.3,0,SiLU,457.36,0.99622,0.99444,0.99470,0.73197
4,Case 4: Dropout,5,dropout_0.5,32,32,0.01,0.0001,SGD,640,0.5,0,SiLU,458.67,0.99622,0.99444,0.99470,0.73197
5,Case 6: Optimizer,1,optimizer_SGD,32,32,0.01,0.0001,SGD,640,0.0,0,SiLU,457.57,0.99622,0.99444,0.99470,0.73197
6,Case 6: Optimizer,2,optimizer_Adam,32,32,0.01,0.0001,Adam,640,0.0,0,SiLU,460.64,0.99253,0.99388,0.99452,0.71447
7,Case 6: Optimizer,3,optimizer_AdamW,32,32,0.01,0.0001,AdamW,640,0.0,0,SiLU,463.93,0.99375,0.99499,0.99433,0.72401

Ultralytics 8.3.189 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train9, nbs=64, nms=False, opset=None, optimize=False, optimizer=RMSProp, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/train9, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    751507  ultralytics.nn.modules.head.Detect           [1, [64, 128, 256]]
Model summary: 129 layers, 3,011,043 parameters, 3,011,027 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 72.1±30.8 MB/s, size: 52.0 KB)
train: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train/labels... 1200 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1200/1200 813.6it/s 1.5s
WARNING ⚠️ train: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 46.7±35.9 MB/s, size: 61.5 KB)
val: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels... 300 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 300/300 462.1it/s 0.6s
WARNING ⚠️ val: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val is not writeable, cache not saved.
Plotting labels to runs/detect/train9/labels.jpg...
optimizer: RMSprop(lr=0.01, momentum=0.937) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs/detect/train9
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/32      4.36G      3.052      4.547      2.747        145        640: 100% ━━━━━━━━━━━━ 38/38 2.8it/s 13.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 5.1it/s 1.0s
                   all        300       1798          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/32      4.71G      2.563      2.149      2.155        166        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798   0.000256    0.00834   0.000131   3.68e-05

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/32      4.71G      2.324       1.74      1.967        166        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.5it/s 2.0ss
                   all        300       1798     0.0054       0.27    0.00345   0.000646

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/32      4.71G      2.354      1.674      2.019        136        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.5it/s 1.4ss
                   all        300       1798          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/32      4.71G      2.095      1.606      1.823        165        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/32      4.71G      2.009      1.475      1.743        171        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.7it/s 1.9ss
                   all        300       1798     0.0105    0.00222   0.000396   8.46e-05

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/32      4.71G      1.998      1.476      1.747        167        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798     0.0023      0.115    0.00132   0.000295

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/32      4.71G      1.904      1.426      1.668        141        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.5ss
                   all        300       1798          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/32      4.71G      1.873      1.348      1.643        129        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798      0.116      0.462      0.124      0.035

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/32      4.71G      1.856      1.249      1.651        153        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.4it/s 2.1ss
                   all        300       1798   0.000282    0.00278   5.73e-05    8.1e-06

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/32      4.71G      1.776      1.193      1.574        192        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/32      4.71G      1.831      1.247      1.612        186        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.2it/s 2.2ss
                   all        300       1798    0.00245      0.121    0.00741    0.00105

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/32      4.71G      1.754      1.142      1.597        168        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.5it/s 2.0ss
                   all        300       1798    0.00577     0.0128    0.00162   0.000467

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/32      4.71G      1.663       1.04      1.523        169        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.5it/s 1.4ss
                   all        300       1798          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/32      4.71G      1.611     0.9923      1.497        156        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798    0.00694     0.0267    0.00158   0.000383

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/32      4.71G       1.58     0.9651      1.468        176        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798      0.582      0.739      0.646      0.251

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/32      4.71G      1.564     0.9494      1.432        188        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.772       0.81      0.805      0.322

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/32      4.71G       1.54     0.9312      1.422        169        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.812      0.847      0.866      0.427

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/32      4.71G      1.546     0.9144      1.417        155        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798     0.0527      0.524     0.0957     0.0201

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/32      4.71G      1.495     0.8778      1.386        180        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798    0.00224     0.0451    0.00119   0.000345

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/32      4.71G      1.504     0.8831       1.39        174        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.271      0.245      0.134     0.0295

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/32      4.72G      1.476     0.8503      1.375        149        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.245      0.315      0.144     0.0338
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/32      4.74G      1.431     0.8813      1.427         96        640: 100% ━━━━━━━━━━━━ 38/38 2.8it/s 13.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798   0.000702       0.02   0.000364   7.03e-05

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/32      4.75G      1.431     0.8312      1.413        100        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.7it/s 1.4s
                   all        300       1798          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/32      4.77G      1.404     0.8014      1.405         99        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798     0.0197     0.0245    0.00458    0.00098

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/32      4.79G      1.399      0.786      1.391        100        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798      0.824      0.838      0.898       0.43

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/32       4.8G      1.382       0.76      1.363         82        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6s
                   all        300       1798       0.92      0.889       0.95      0.504

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/32      4.82G      1.368     0.7504      1.377         92        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.914      0.925       0.96      0.513

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/32      4.84G      1.356     0.7274      1.361         96        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.859      0.922      0.867      0.318

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/32      4.86G      1.339     0.7178      1.344         89        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.941      0.931      0.959      0.565

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/32      4.87G      1.325     0.6917      1.342         93        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.945      0.937      0.967      0.595

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/32      4.89G      1.321     0.6896      1.328         99        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798      0.966      0.945      0.978      0.543

32 epochs completed in 0.125 hours.
Optimizer stripped from runs/detect/train9/weights/last.pt, 6.2MB
Optimizer stripped from runs/detect/train9/weights/best.pt, 6.2MB

Validating runs/detect/train9/weights/best.pt...
Ultralytics 8.3.189 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
Model summary (fused): 72 layers, 3,005,843 parameters, 0 gradients, 8.1 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 2.9ss

/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        300       1798      0.948      0.937      0.968      0.595
Speed: 0.1ms preprocess, 1.4ms inference, 0.0ms loss, 3.2ms postprocess per image
Results saved to runs/detect/train9

,Case,Exp No,Experiment Name,Epochs,Batch,lr0,Weight Decay,Optimizer,Image Size,Dropout,Freeze Layers,Activation,Training Time (s),Precision,Recall,mAP@0.5,mAP@0.5:0.95
0,Case 4: Dropout,1,dropout_0,32,32,0.01,0.0001,SGD,640,0,0,SiLU,471.56,0.99622,0.99444,0.99470,0.73197
1,Case 4: Dropout,2,dropout_0.1,32,32,0.01,0.0001,SGD,640,0.1,0,SiLU,464.40,0.99622,0.99444,0.99470,0.73197
2,Case 4: Dropout,3,dropout_0.2,32,32,0.01,0.0001,SGD,640,0.2,0,SiLU,463.41,0.99622,0.99444,0.99470,0.73197
3,Case 4: Dropout,4,dropout_0.3,32,32,0.01,0.0001,SGD,640,0.3,0,SiLU,457.36,0.99622,0.99444,0.99470,0.73197
4,Case 4: Dropout,5,dropout_0.5,32,32,0.01,0.0001,SGD,640,0.5,0,SiLU,458.67,0.99622,0.99444,0.99470,0.73197
5,Case 6: Optimizer,1,optimizer_SGD,32,32,0.01,0.0001,SGD,640,0.0,0,SiLU,457.57,0.99622,0.99444,0.99470,0.73197
6,Case 6: Optimizer,2,optimizer_Adam,32,32,0.01,0.0001,Adam,640,0.0,0,SiLU,460.64,0.99253,0.99388,0.99452,0.71447
7,Case 6: Optimizer,3,optimizer_AdamW,32,32,0.01,0.0001,AdamW,640,0.0,0,SiLU,463.93,0.99375,0.99499,0.99433,0.72401
8,Case 6: Optimizer,4,optimizer_RMSProp,32,32,0.01,0.0001,RMSProp,640,0.0,0,SiLU,463.36,0.96645,0.94514,0.97844,0.54309

Ultralytics 8.3.189 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train10, nbs=64, nms=False, opset=None, optimize=False, optimizer=Adamax, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/train10, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    751507  ultralytics.nn.modules.head.Detect           [1, [64, 128, 256]]
Model summary: 129 layers, 3,011,043 parameters, 3,011,027 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 94.5±29.8 MB/s, size: 52.0 KB)
train: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train/labels... 1200 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1200/1200 1000.6it/s 1.2s
WARNING ⚠️ train: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 98.5±22.1 MB/s, size: 61.5 KB)
val: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels... 300 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 300/300 545.9it/s 0.5s
WARNING ⚠️ val: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val is not writeable, cache not saved.
Plotting labels to runs/detect/train10/labels.jpg...
optimizer: Adamax(lr=0.01, momentum=0.937) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs/detect/train10
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/32      4.36G      1.843      1.852      1.396        145        640: 100% ━━━━━━━━━━━━ 38/38 2.9it/s 13.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.499      0.411      0.398      0.163

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/32      4.71G      1.371     0.8895      1.146        166        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.5ss
                   all        300       1798      0.967      0.952      0.981      0.528

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/32      4.71G       1.33     0.7894      1.116        166        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.876      0.856      0.906       0.43

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/32      4.71G      1.327      0.751      1.117        136        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798      0.965      0.957      0.961      0.385

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/32      4.71G      1.313     0.7198      1.108        165        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.5ss
                   all        300       1798      0.973      0.979      0.984       0.62

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/32      4.71G      1.296      0.692      1.111        171        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798       0.89      0.934       0.94      0.511

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/32      4.71G      1.284     0.6687      1.106        167        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.995      0.984      0.993      0.607

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/32      4.71G      1.239     0.6257      1.088        141        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.985      0.981       0.99      0.619

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/32      4.71G      1.257     0.6291      1.101        129        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.5ss
                   all        300       1798      0.991      0.989      0.994      0.648

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/32      4.71G      1.238     0.6139      1.094        153        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.992      0.984      0.993      0.647

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/32      4.71G      1.209     0.5842      1.078        192        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.949      0.971      0.977      0.625

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/32      4.71G      1.224     0.5925      1.081        186        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.5ss
                   all        300       1798       0.99      0.979      0.993      0.635

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/32      4.71G      1.221     0.5716      1.087        168        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.5ss
                   all        300       1798      0.992      0.989      0.993      0.669

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/32      4.71G      1.237     0.5695      1.094        169        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.987      0.983      0.988      0.638

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/32      4.71G      1.229     0.5653      1.092        156        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.991      0.989      0.992      0.665

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/32      4.71G      1.195     0.5389       1.08        176        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798       0.99      0.986      0.993      0.643

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/32      4.71G      1.205     0.5321      1.081        188        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798      0.992      0.992      0.994      0.667

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/32      4.71G      1.176     0.5196      1.068        169        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.991      0.991      0.993       0.68

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/32      4.71G      1.176     0.5076       1.07        155        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.993      0.995      0.993      0.669

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/32      4.71G      1.151     0.4941      1.057        180        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.989      0.991      0.994      0.672

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/32      4.71G      1.137     0.4903      1.051        174        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.994      0.992      0.994      0.662

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/32      4.71G      1.125     0.4859      1.054        149        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.994      0.994      0.994      0.694
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/32      4.73G       1.11     0.4571      1.051         96        640: 100% ━━━━━━━━━━━━ 38/38 2.8it/s 13.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.994      0.993      0.993      0.679

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/32      4.75G      1.112     0.4453      1.052        100        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798      0.995      0.989      0.993      0.666

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/32      4.76G      1.086     0.4315      1.039         99        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.992       0.99      0.994      0.685

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/32      4.78G      1.065     0.4197      1.027        100        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.995      0.992      0.994      0.709

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/32       4.8G      1.048     0.4088      1.019         82        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.993      0.995      0.993      0.708

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/32      4.81G      1.043     0.4115       1.02         92        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.996      0.993      0.994      0.715

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/32      4.83G       1.04     0.4055      1.018         96        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.3it/s 1.5ss
                   all        300       1798      0.995      0.994      0.993      0.719

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/32      4.85G      1.032     0.3972      1.012         89        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798      0.995      0.994      0.994      0.726

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/32      4.87G      1.015     0.3909      1.007         93        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.4it/s 1.5ss
                   all        300       1798      0.994      0.995      0.994      0.729

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/32      4.88G      1.008     0.3831      1.004         99        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.6it/s 1.4ss
                   all        300       1798      0.996      0.994      0.994      0.732

32 epochs completed in 0.124 hours.
Optimizer stripped from runs/detect/train10/weights/last.pt, 6.2MB
Optimizer stripped from runs/detect/train10/weights/best.pt, 6.2MB

Validating runs/detect/train10/weights/best.pt...
Ultralytics 8.3.189 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
Model summary (fused): 72 layers, 3,005,843 parameters, 0 gradients, 8.1 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0ss

/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        300       1798      0.995      0.994      0.994      0.732
Speed: 0.1ms preprocess, 1.5ms inference, 0.0ms loss, 3.0ms postprocess per image
Results saved to runs/detect/train10

,Case,Exp No,Experiment Name,Epochs,Batch,lr0,Weight Decay,Optimizer,Image Size,Dropout,Freeze Layers,Activation,Training Time (s),Precision,Recall,mAP@0.5,mAP@0.5:0.95
0,Case 4: Dropout,1,dropout_0,32,32,0.01,0.0001,SGD,640,0,0,SiLU,471.56,0.99622,0.99444,0.99470,0.73197
1,Case 4: Dropout,2,dropout_0.1,32,32,0.01,0.0001,SGD,640,0.1,0,SiLU,464.40,0.99622,0.99444,0.99470,0.73197
2,Case 4: Dropout,3,dropout_0.2,32,32,0.01,0.0001,SGD,640,0.2,0,SiLU,463.41,0.99622,0.99444,0.99470,0.73197
3,Case 4: Dropout,4,dropout_0.3,32,32,0.01,0.0001,SGD,640,0.3,0,SiLU,457.36,0.99622,0.99444,0.99470,0.73197
4,Case 4: Dropout,5,dropout_0.5,32,32,0.01,0.0001,SGD,640,0.5,0,SiLU,458.67,0.99622,0.99444,0.99470,0.73197
5,Case 6: Optimizer,1,optimizer_SGD,32,32,0.01,0.0001,SGD,640,0.0,0,SiLU,457.57,0.99622,0.99444,0.99470,0.73197
6,Case 6: Optimizer,2,optimizer_Adam,32,32,0.01,0.0001,Adam,640,0.0,0,SiLU,460.64,0.99253,0.99388,0.99452,0.71447
7,Case 6: Optimizer,3,optimizer_AdamW,32,32,0.01,0.0001,AdamW,640,0.0,0,SiLU,463.93,0.99375,0.99499,0.99433,0.72401
8,Case 6: Optimizer,4,optimizer_RMSProp,32,32,0.01,0.0001,RMSProp,640,0.0,0,SiLU,463.36,0.96645,0.94514,0.97844,0.54309
9,Case 6: Optimizer,5,optimizer_Adamax,32,32,0.01,0.0001,Adamax,640,0.0,0,SiLU,458.61,0.99553,0.99388,0.99399,0.73196

In [16]:
BEST_PARAMS["epochs"] = 32
BEST_PARAMS["weight_decay"] = 0.0001
BEST_PARAMS["batch"] = 32
BEST_PARAMS["optimizer"] = "SGD"   # keep optimizer locked in from Case 6

case7_learning_rate()

Ultralytics 8.3.189 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.001, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train11, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/train11, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    751507  ultralytics.nn.modules.head.Detect           [1, [64, 128, 256]]
Model summary: 129 layers, 3,011,043 parameters, 3,011,027 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 87.8±28.9 MB/s, size: 52.0 KB)
train: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train/labels... 1200 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1200/1200 671.7it/s 1.8s
WARNING ⚠️ train: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 87.0±41.9 MB/s, size: 61.5 KB)
val: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels... 300 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 300/300 433.7it/s 0.7s
WARNING ⚠️ val: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val is not writeable, cache not saved.
Plotting labels to runs/detect/train11/labels.jpg...
optimizer: SGD(lr=0.001, momentum=0.937) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs/detect/train11
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/32      4.35G      2.416      3.422      1.682        145        640: 100% ━━━━━━━━━━━━ 38/38 2.9it/s 13.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.0it/s 2.5ss
                   all        300       1798     0.0196      0.979     0.0373     0.0192

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/32       4.7G      1.408      1.825      1.175        166        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.1it/s 2.4ss
                   all        300       1798      0.987      0.835      0.978      0.536

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/32       4.7G      1.296      1.136      1.112        166        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.6it/s 1.9ss
                   all        300       1798      0.983      0.972      0.988      0.623

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/32       4.7G      1.251     0.9619       1.08        136        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.7it/s 1.9ss
                   all        300       1798      0.981      0.985      0.989      0.643

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/32       4.7G       1.23     0.8751       1.06        165        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.7it/s 1.9ss
                   all        300       1798      0.989      0.991      0.993      0.625

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/32       4.7G      1.203     0.8267      1.046        171        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.7it/s 1.8ss
                   all        300       1798      0.991      0.989      0.993      0.655

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/32       4.7G      1.189     0.7783      1.037        167        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.8it/s 1.8ss
                   all        300       1798      0.993      0.989      0.993      0.653

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/32       4.7G      1.188     0.7624      1.031        141        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.7it/s 1.9ss
                   all        300       1798      0.991      0.992      0.992      0.668

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/32       4.7G      1.177     0.7572      1.034        129        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.7it/s 1.9ss
                   all        300       1798      0.993      0.992      0.993      0.675

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/32       4.7G      1.173     0.7381      1.031        153        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.7it/s 1.8ss
                   all        300       1798      0.991      0.988      0.992      0.659

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/32       4.7G      1.157     0.6971       1.02        192        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.7it/s 1.8ss
                   all        300       1798      0.987      0.983      0.987      0.593

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/32       4.7G      1.154     0.6869      1.018        186        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.9it/s 1.8ss
                   all        300       1798      0.994      0.994      0.994      0.673

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/32       4.7G      1.149     0.6719      1.022        168        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.7it/s 1.8ss
                   all        300       1798      0.995      0.993      0.994      0.685

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/32       4.7G      1.141     0.6589      1.013        169        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.8it/s 1.8ss
                   all        300       1798      0.996      0.993      0.994      0.679

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/32       4.7G      1.135      0.646      1.017        156        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.7it/s 1.8ss
                   all        300       1798      0.993      0.993      0.994      0.688

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/32       4.7G      1.128     0.6412      1.012        176        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.9it/s 1.7ss
                   all        300       1798      0.994      0.992      0.993      0.686

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/32       4.7G      1.133      0.628      1.012        188        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7ss
                   all        300       1798      0.993      0.992      0.993      0.666

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/32       4.7G      1.124     0.6237      1.007        169        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.9it/s 1.8ss
                   all        300       1798      0.994      0.994      0.994      0.694

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/32       4.7G      1.118     0.6129      1.005        155        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.7it/s 1.9ss
                   all        300       1798      0.994      0.992      0.994      0.695

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/32       4.7G      1.102     0.6034     0.9989        180        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.7it/s 1.8ss
                   all        300       1798      0.995      0.993      0.994      0.695

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/32       4.7G      1.103     0.5999      1.005        174        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.8it/s 1.8ss
                   all        300       1798      0.996      0.992      0.994      0.699

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/32       4.7G      1.091     0.5943      0.998        149        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.8it/s 1.8ss
                   all        300       1798      0.995      0.991      0.994      0.693
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/32       4.7G      1.069     0.6123     0.9941         96        640: 100% ━━━━━━━━━━━━ 38/38 2.7it/s 14.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.6it/s 1.9ss
                   all        300       1798      0.996      0.994      0.994      0.698

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/32       4.7G      1.063     0.5926     0.9962        100        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.8it/s 1.8ss
                   all        300       1798      0.997      0.994      0.993      0.698

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/32       4.7G      1.044     0.5807      0.986         99        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.7it/s 1.8ss
                   all        300       1798      0.997      0.994      0.993      0.699

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/32       4.7G       1.04     0.5687     0.9825        100        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.7it/s 1.9ss
                   all        300       1798      0.997      0.994      0.994        0.7

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/32       4.7G      1.028     0.5599     0.9763         82        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.7it/s 1.9ss
                   all        300       1798      0.997      0.994      0.994      0.692

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/32       4.7G      1.028     0.5613      0.984         92        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.8it/s 1.8ss
                   all        300       1798      0.997      0.994      0.994      0.696

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/32       4.7G      1.033     0.5565     0.9814         96        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.8it/s 1.8ss
                   all        300       1798      0.997      0.994      0.993      0.702

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/32       4.7G      1.026     0.5527     0.9762         89        640: 100% ━━━━━━━━━━━━ 38/38 2.9it/s 13.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.3it/s 2.2ss
                   all        300       1798      0.996      0.994      0.993      0.702

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/32       4.7G      1.017     0.5508     0.9758         93        640: 100% ━━━━━━━━━━━━ 38/38 2.9it/s 13.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.2it/s 2.3ss
                   all        300       1798      0.996      0.994      0.994      0.704

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/32       4.7G      1.021     0.5471     0.9768         99        640: 100% ━━━━━━━━━━━━ 38/38 2.9it/s 13.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.3it/s 2.2ss
                   all        300       1798      0.997      0.993      0.994      0.704

32 epochs completed in 0.129 hours.
Optimizer stripped from runs/detect/train11/weights/last.pt, 6.2MB
Optimizer stripped from runs/detect/train11/weights/best.pt, 6.2MB

Validating runs/detect/train11/weights/best.pt...
Ultralytics 8.3.189 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
Model summary (fused): 72 layers, 3,005,843 parameters, 0 gradients, 8.1 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.2it/s 4.3ss

/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        300       1798      0.997      0.993      0.994      0.705
Speed: 0.1ms preprocess, 1.4ms inference, 0.0ms loss, 3.5ms postprocess per image
Results saved to runs/detect/train11

,Case,Exp No,Experiment Name,Epochs,Batch,lr0,Weight Decay,Optimizer,Image Size,Dropout,Freeze Layers,Activation,Training Time (s),Precision,Recall,mAP@0.5,mAP@0.5:0.95
1,Case 4: Dropout,2,dropout_0.1,32,32,0.010,0.0001,SGD,640,0.1,0,SiLU,464.40,0.99622,0.99444,0.99470,0.73197
2,Case 4: Dropout,3,dropout_0.2,32,32,0.010,0.0001,SGD,640,0.2,0,SiLU,463.41,0.99622,0.99444,0.99470,0.73197
3,Case 4: Dropout,4,dropout_0.3,32,32,0.010,0.0001,SGD,640,0.3,0,SiLU,457.36,0.99622,0.99444,0.99470,0.73197
4,Case 4: Dropout,5,dropout_0.5,32,32,0.010,0.0001,SGD,640,0.5,0,SiLU,458.67,0.99622,0.99444,0.99470,0.73197
5,Case 6: Optimizer,1,optimizer_SGD,32,32,0.010,0.0001,SGD,640,0.0,0,SiLU,457.57,0.99622,0.99444,0.99470,0.73197
6,Case 6: Optimizer,2,optimizer_Adam,32,32,0.010,0.0001,Adam,640,0.0,0,SiLU,460.64,0.99253,0.99388,0.99452,0.71447
7,Case 6: Optimizer,3,optimizer_AdamW,32,32,0.010,0.0001,AdamW,640,0.0,0,SiLU,463.93,0.99375,0.99499,0.99433,0.72401
8,Case 6: Optimizer,4,optimizer_RMSProp,32,32,0.010,0.0001,RMSProp,640,0.0,0,SiLU,463.36,0.96645,0.94514,0.97844,0.54309
9,Case 6: Optimizer,5,optimizer_Adamax,32,32,0.010,0.0001,Adamax,640,0.0,0,SiLU,458.61,0.99553,0.99388,0.99399,0.73196
10,Case 7: Learning Rate,1,lr_0.001,32,32,0.001,0.0001,SGD,640,0.0,0,SiLU,483.19,0.99727,0.99333,0.99369,0.70411

Ultralytics 8.3.189 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.005, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train12, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/train12, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    751507  ultralytics.nn.modules.head.Detect           [1, [64, 128, 256]]
Model summary: 129 layers, 3,011,043 parameters, 3,011,027 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 75.4±21.6 MB/s, size: 52.0 KB)
train: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train/labels... 1200 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1200/1200 584.0it/s 2.1s
WARNING ⚠️ train: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 69.3±37.4 MB/s, size: 61.5 KB)
val: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels... 300 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 300/300 378.3it/s 0.8s
WARNING ⚠️ val: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val is not writeable, cache not saved.
Plotting labels to runs/detect/train12/labels.jpg...
optimizer: SGD(lr=0.005, momentum=0.937) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs/detect/train12
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/32      4.36G      2.071      2.839      1.514        145        640: 100% ━━━━━━━━━━━━ 38/38 2.6it/s 14.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.0it/s 2.5ss
                   all        300       1798     0.0199      0.994      0.981      0.539

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/32      4.71G      1.314      1.071      1.112        166        640: 100% ━━━━━━━━━━━━ 38/38 3.0it/s 12.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.5it/s 2.0ss
                   all        300       1798      0.977      0.912      0.977      0.589

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/32      4.71G      1.275     0.8974      1.083        166        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.7it/s 1.9ss
                   all        300       1798      0.989      0.986      0.994      0.582

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/32      4.71G      1.263     0.8357      1.082        136        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.7it/s 1.9ss
                   all        300       1798       0.99      0.989      0.994      0.591

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/32      4.71G      1.255     0.7636      1.072        165        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.7it/s 1.9ss
                   all        300       1798      0.979      0.985      0.987       0.61

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/32      4.71G      1.229     0.7225      1.062        171        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.7it/s 1.9ss
                   all        300       1798      0.995      0.992      0.994       0.65

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/32      4.71G      1.203     0.6747      1.056        167        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.7it/s 1.8ss
                   all        300       1798      0.993      0.989      0.993      0.618

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/32      4.71G      1.194     0.6504      1.048        141        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.4it/s 2.0ss
                   all        300       1798      0.991      0.991      0.992      0.669

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/32      4.71G      1.188     0.6473      1.053        129        640: 100% ━━━━━━━━━━━━ 38/38 2.8it/s 13.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.2it/s 2.2ss
                   all        300       1798      0.997      0.992      0.993      0.678

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/32      4.71G      1.173      0.618      1.046        153        640: 100% ━━━━━━━━━━━━ 38/38 2.8it/s 13.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.1it/s 2.4ss
                   all        300       1798      0.994      0.994      0.993      0.675

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/32      4.71G      1.163     0.5967      1.033        192        640: 100% ━━━━━━━━━━━━ 38/38 2.9it/s 13.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.2it/s 2.2ss
                   all        300       1798      0.993      0.994      0.993      0.678

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/32      4.71G      1.145      0.585      1.031        186        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.7it/s 1.9ss
                   all        300       1798      0.997      0.994      0.994      0.681

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/32      4.71G      1.138     0.5657      1.033        168        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.8it/s 1.8ss
                   all        300       1798      0.996      0.994      0.993      0.687

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/32      4.71G      1.126     0.5504      1.024        169        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.8it/s 1.8ss
                   all        300       1798      0.994      0.994      0.993      0.692

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/32      4.71G      1.115     0.5386      1.024        156        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.8it/s 1.8ss
                   all        300       1798      0.996      0.994      0.994      0.686

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/32      4.71G      1.121     0.5321      1.021        176        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.9it/s 1.8ss
                   all        300       1798      0.996      0.993      0.994      0.666

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/32      4.71G      1.102     0.5188      1.015        188        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.8it/s 1.8ss
                   all        300       1798      0.994      0.995      0.994      0.688

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/32      4.71G      1.102     0.5151      1.013        169        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.8it/s 1.8ss
                   all        300       1798      0.996      0.996      0.994      0.697

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/32      4.71G      1.085     0.5065      1.008        155        640: 100% ━━━━━━━━━━━━ 38/38 2.9it/s 13.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.2it/s 2.3ss
                   all        300       1798      0.997      0.995      0.994      0.697

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/32      4.71G      1.073     0.4941      1.001        180        640: 100% ━━━━━━━━━━━━ 38/38 2.8it/s 13.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.2it/s 2.2ss
                   all        300       1798      0.996      0.994      0.994       0.67

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/32      4.71G      1.066     0.4894      1.004        174        640: 100% ━━━━━━━━━━━━ 38/38 2.8it/s 13.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.3it/s 2.1ss
                   all        300       1798      0.996      0.994      0.994      0.703

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/32      4.71G      1.054     0.4838          1        149        640: 100% ━━━━━━━━━━━━ 38/38 2.9it/s 13.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.6it/s 1.9ss
                   all        300       1798      0.997      0.993      0.994      0.702
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/32      4.71G      1.036     0.4639     0.9969         96        640: 100% ━━━━━━━━━━━━ 38/38 2.6it/s 14.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.5it/s 2.0ss
                   all        300       1798      0.995      0.992      0.994      0.686

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/32      4.71G      1.021     0.4486     0.9917        100        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.7it/s 1.8ss
                   all        300       1798      0.996      0.992      0.994      0.695

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/32      4.72G      1.002     0.4378     0.9827         99        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.7it/s 1.8ss
                   all        300       1798      0.996      0.995      0.995      0.708

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/32      4.73G     0.9954     0.4309     0.9795        100        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.7it/s 1.9ss
                   all        300       1798      0.997      0.992      0.995      0.705

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/32      4.74G     0.9756       0.42     0.9686         82        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.6it/s 1.9ss
                   all        300       1798      0.996      0.993      0.995      0.707

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/32      4.75G     0.9747     0.4201     0.9774         92        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.7it/s 1.9ss
                   all        300       1798      0.998      0.993      0.995      0.698

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/32      4.76G     0.9753     0.4156     0.9736         96        640: 100% ━━━━━━━━━━━━ 38/38 2.9it/s 12.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.3it/s 2.2ss
                   all        300       1798      0.998      0.993      0.994       0.71

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/32      4.78G     0.9655     0.4115     0.9674         89        640: 100% ━━━━━━━━━━━━ 38/38 2.9it/s 13.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.5it/s 2.0ss
                   all        300       1798      0.998      0.995      0.994      0.718

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/32      4.79G       0.95     0.4034     0.9641         93        640: 100% ━━━━━━━━━━━━ 38/38 2.9it/s 13.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.4it/s 2.0ss
                   all        300       1798      0.997      0.996      0.995      0.721

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/32       4.8G     0.9525     0.4012     0.9622         99        640: 100% ━━━━━━━━━━━━ 38/38 2.9it/s 12.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.7it/s 1.9ss
                   all        300       1798      0.997      0.995      0.995      0.721

32 epochs completed in 0.134 hours.
Optimizer stripped from runs/detect/train12/weights/last.pt, 6.2MB
Optimizer stripped from runs/detect/train12/weights/best.pt, 6.2MB

Validating runs/detect/train12/weights/best.pt...
Ultralytics 8.3.189 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
Model summary (fused): 72 layers, 3,005,843 parameters, 0 gradients, 8.1 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.5it/s 3.4ss

/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        300       1798      0.997      0.996      0.995      0.721
Speed: 0.1ms preprocess, 1.8ms inference, 0.0ms loss, 2.8ms postprocess per image
Results saved to runs/detect/train12

,Case,Exp No,Experiment Name,Epochs,Batch,lr0,Weight Decay,Optimizer,Image Size,Dropout,Freeze Layers,Activation,Training Time (s),Precision,Recall,mAP@0.5,mAP@0.5:0.95
2,Case 4: Dropout,3,dropout_0.2,32,32,0.010,0.0001,SGD,640,0.2,0,SiLU,463.41,0.99622,0.99444,0.99470,0.73197
3,Case 4: Dropout,4,dropout_0.3,32,32,0.010,0.0001,SGD,640,0.3,0,SiLU,457.36,0.99622,0.99444,0.99470,0.73197
4,Case 4: Dropout,5,dropout_0.5,32,32,0.010,0.0001,SGD,640,0.5,0,SiLU,458.67,0.99622,0.99444,0.99470,0.73197
5,Case 6: Optimizer,1,optimizer_SGD,32,32,0.010,0.0001,SGD,640,0.0,0,SiLU,457.57,0.99622,0.99444,0.99470,0.73197
6,Case 6: Optimizer,2,optimizer_Adam,32,32,0.010,0.0001,Adam,640,0.0,0,SiLU,460.64,0.99253,0.99388,0.99452,0.71447
7,Case 6: Optimizer,3,optimizer_AdamW,32,32,0.010,0.0001,AdamW,640,0.0,0,SiLU,463.93,0.99375,0.99499,0.99433,0.72401
8,Case 6: Optimizer,4,optimizer_RMSProp,32,32,0.010,0.0001,RMSProp,640,0.0,0,SiLU,463.36,0.96645,0.94514,0.97844,0.54309
9,Case 6: Optimizer,5,optimizer_Adamax,32,32,0.010,0.0001,Adamax,640,0.0,0,SiLU,458.61,0.99553,0.99388,0.99399,0.73196
10,Case 7: Learning Rate,1,lr_0.001,32,32,0.001,0.0001,SGD,640,0.0,0,SiLU,483.19,0.99727,0.99333,0.99369,0.70411
11,Case 7: Learning Rate,2,lr_0.005,32,32,0.005,0.0001,SGD,640,0.0,0,SiLU,500.17,0.99666,0.99532,0.99466,0.72074

Ultralytics 8.3.189 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train13, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/train13, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    751507  ultralytics.nn.modules.head.Detect           [1, [64, 128, 256]]
Model summary: 129 layers, 3,011,043 parameters, 3,011,027 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 22.7±16.4 MB/s, size: 52.0 KB)
train: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train/labels... 1200 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1200/1200 647.4it/s 1.9s
WARNING ⚠️ train: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 82.6±42.0 MB/s, size: 61.5 KB)
val: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels... 300 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 300/300 415.5it/s 0.7s
WARNING ⚠️ val: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val is not writeable, cache not saved.
Plotting labels to runs/detect/train13/labels.jpg...
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs/detect/train13
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/32      4.24G      1.966      2.539      1.465        145        640: 100% ━━━━━━━━━━━━ 38/38 2.8it/s 13.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.5it/s 2.0ss
                   all        300       1798     0.0199      0.997       0.98       0.59

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/32      4.59G      1.338     0.9955      1.117        166        640: 100% ━━━━━━━━━━━━ 38/38 3.0it/s 12.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.5it/s 2.0ss
                   all        300       1798       0.98      0.816      0.954      0.385

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/32      4.59G      1.349     0.8865      1.124        166        640: 100% ━━━━━━━━━━━━ 38/38 3.0it/s 12.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.6it/s 1.9ss
                   all        300       1798      0.975      0.972      0.984      0.569

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/32      4.59G      1.312     0.8716      1.113        136        640: 100% ━━━━━━━━━━━━ 38/38 3.0it/s 12.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.5it/s 2.0ss
                   all        300       1798      0.979      0.965       0.98      0.411

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/32      4.59G      1.285      0.786      1.102        165        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.7it/s 1.8ss
                   all        300       1798      0.986      0.983      0.989       0.63

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/32      4.59G      1.263     0.7234      1.098        171        640: 100% ━━━━━━━━━━━━ 38/38 2.9it/s 13.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.2it/s 2.3ss
                   all        300       1798      0.987      0.991      0.993      0.639

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/32      4.59G      1.227     0.6684      1.086        167        640: 100% ━━━━━━━━━━━━ 38/38 2.8it/s 13.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.0it/s 2.5ss
                   all        300       1798      0.988      0.986      0.992      0.572

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/32      4.59G      1.226     0.6448      1.081        141        640: 100% ━━━━━━━━━━━━ 38/38 2.9it/s 13.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.2it/s 2.3ss
                   all        300       1798       0.99      0.984       0.99      0.662

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/32      4.59G      1.211     0.6304      1.084        129        640: 100% ━━━━━━━━━━━━ 38/38 2.9it/s 12.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.8it/s 1.8ss
                   all        300       1798      0.988      0.975      0.993       0.61

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/32      4.59G      1.197     0.6118      1.077        153        640: 100% ━━━━━━━━━━━━ 38/38 3.0it/s 12.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.7it/s 1.8ss
                   all        300       1798      0.994       0.99      0.994      0.671

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/32      4.59G      1.184     0.5853      1.065        192        640: 100% ━━━━━━━━━━━━ 38/38 3.0it/s 12.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.8it/s 1.8ss
                   all        300       1798      0.993      0.991      0.994      0.668

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/32      4.59G      1.161     0.5678      1.063        186        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.9it/s 1.7ss
                   all        300       1798      0.978      0.983       0.99      0.636

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/32      4.59G       1.17     0.5554      1.067        168        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.9it/s 1.7ss
                   all        300       1798      0.993      0.987      0.994      0.693

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/32      4.59G      1.145     0.5409      1.054        169        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.9it/s 1.7ss
                   all        300       1798      0.993      0.993      0.994      0.689

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/32      4.59G      1.139     0.5276      1.058        156        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.8it/s 1.8ss
                   all        300       1798      0.988      0.985      0.993      0.669

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/32      4.59G      1.144      0.522      1.053        176        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.7it/s 1.8ss
                   all        300       1798      0.991      0.986      0.994      0.654

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/32      4.59G      1.125      0.511      1.044        188        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.7it/s 1.8ss
                   all        300       1798      0.991      0.993      0.994      0.698

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/32      4.59G      1.115     0.5034       1.04        169        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.8it/s 1.8ss
                   all        300       1798      0.993      0.993      0.994       0.69

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/32      4.59G      1.107     0.4911      1.037        155        640: 100% ━━━━━━━━━━━━ 38/38 2.9it/s 13.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.3it/s 2.2ss
                   all        300       1798      0.993      0.994      0.994      0.648

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/32      4.59G      1.092     0.4823      1.027        180        640: 100% ━━━━━━━━━━━━ 38/38 2.9it/s 13.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.4it/s 2.0ss
                   all        300       1798      0.995      0.991      0.995      0.703

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/32      4.59G      1.083     0.4775      1.029        174        640: 100% ━━━━━━━━━━━━ 38/38 2.9it/s 13.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.3it/s 2.1ss
                   all        300       1798      0.994      0.994      0.995      0.703

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/32      4.59G      1.063     0.4712      1.023        149        640: 100% ━━━━━━━━━━━━ 38/38 2.9it/s 13.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.4it/s 2.1ss
                   all        300       1798      0.994      0.993      0.995      0.699
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/32      4.59G      1.043     0.4384      1.018         96        640: 100% ━━━━━━━━━━━━ 38/38 2.6it/s 14.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.7it/s 1.9ss
                   all        300       1798      0.993      0.992      0.995      0.694

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/32       4.6G      1.033     0.4367      1.018        100        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.8it/s 1.8ss
                   all        300       1798      0.996      0.994      0.995        0.7

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/32      4.61G      1.017     0.4239       1.01         99        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7ss
                   all        300       1798      0.996      0.994      0.995      0.708

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/32      4.62G       1.01     0.4127      1.007        100        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.8it/s 1.8ss
                   all        300       1798      0.996      0.993      0.995      0.716

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/32      4.63G     0.9908     0.4057      0.996         82        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7ss
                   all        300       1798      0.994      0.995      0.995      0.688

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/32      4.64G     0.9835     0.4029     0.9978         92        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.9it/s 1.7ss
                   all        300       1798      0.997      0.994      0.995      0.723

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/32      4.65G     0.9802     0.4005     0.9922         96        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.9it/s 1.7ss
                   all        300       1798      0.995      0.993      0.995      0.706

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/32      4.66G     0.9677     0.3901     0.9839         89        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.9it/s 1.8ss
                   all        300       1798      0.994      0.996      0.995      0.725

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/32      4.68G      0.948     0.3838     0.9809         93        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.9it/s 1.7ss
                   all        300       1798      0.995      0.996      0.995      0.732

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/32      4.69G     0.9501      0.381      0.979         99        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.4it/s 2.1ss
                   all        300       1798      0.996      0.994      0.995      0.732

32 epochs completed in 0.133 hours.
Optimizer stripped from runs/detect/train13/weights/last.pt, 6.2MB
Optimizer stripped from runs/detect/train13/weights/best.pt, 6.2MB

Validating runs/detect/train13/weights/best.pt...
Ultralytics 8.3.189 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
Model summary (fused): 72 layers, 3,005,843 parameters, 0 gradients, 8.1 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.2it/s 4.2ss

/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        300       1798      0.996      0.994      0.995      0.732
Speed: 0.2ms preprocess, 1.9ms inference, 0.0ms loss, 4.0ms postprocess per image
Results saved to runs/detect/train13

,Case,Exp No,Experiment Name,Epochs,Batch,lr0,Weight Decay,Optimizer,Image Size,Dropout,Freeze Layers,Activation,Training Time (s),Precision,Recall,mAP@0.5,mAP@0.5:0.95
3,Case 4: Dropout,4,dropout_0.3,32,32,0.010,0.0001,SGD,640,0.3,0,SiLU,457.36,0.99622,0.99444,0.99470,0.73197
4,Case 4: Dropout,5,dropout_0.5,32,32,0.010,0.0001,SGD,640,0.5,0,SiLU,458.67,0.99622,0.99444,0.99470,0.73197
5,Case 6: Optimizer,1,optimizer_SGD,32,32,0.010,0.0001,SGD,640,0.0,0,SiLU,457.57,0.99622,0.99444,0.99470,0.73197
6,Case 6: Optimizer,2,optimizer_Adam,32,32,0.010,0.0001,Adam,640,0.0,0,SiLU,460.64,0.99253,0.99388,0.99452,0.71447
7,Case 6: Optimizer,3,optimizer_AdamW,32,32,0.010,0.0001,AdamW,640,0.0,0,SiLU,463.93,0.99375,0.99499,0.99433,0.72401
8,Case 6: Optimizer,4,optimizer_RMSProp,32,32,0.010,0.0001,RMSProp,640,0.0,0,SiLU,463.36,0.96645,0.94514,0.97844,0.54309
9,Case 6: Optimizer,5,optimizer_Adamax,32,32,0.010,0.0001,Adamax,640,0.0,0,SiLU,458.61,0.99553,0.99388,0.99399,0.73196
10,Case 7: Learning Rate,1,lr_0.001,32,32,0.001,0.0001,SGD,640,0.0,0,SiLU,483.19,0.99727,0.99333,0.99369,0.70411
11,Case 7: Learning Rate,2,lr_0.005,32,32,0.005,0.0001,SGD,640,0.0,0,SiLU,500.17,0.99666,0.99532,0.99466,0.72074
12,Case 7: Learning Rate,3,lr_0.01,32,32,0.010,0.0001,SGD,640,0.0,0,SiLU,494.95,0.99622,0.99444,0.99470,0.73197

Ultralytics 8.3.189 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.05, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train14, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/train14, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    751507  ultralytics.nn.modules.head.Detect           [1, [64, 128, 256]]
Model summary: 129 layers, 3,011,043 parameters, 3,011,027 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 42.9±27.0 MB/s, size: 52.0 KB)
train: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train/labels... 1200 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1200/1200 603.4it/s 2.0s
WARNING ⚠️ train: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 67.2±29.1 MB/s, size: 61.5 KB)
val: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels... 300 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 300/300 341.4it/s 0.9s
WARNING ⚠️ val: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val is not writeable, cache not saved.
Plotting labels to runs/detect/train14/labels.jpg...
optimizer: SGD(lr=0.05, momentum=0.937) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs/detect/train14
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/32      4.24G      1.961       2.17      1.441        145        640: 100% ━━━━━━━━━━━━ 38/38 2.6it/s 14.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.1it/s 2.4ss
                   all        300       1798     0.0199      0.996      0.813      0.393

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/32      4.59G      1.574      1.259      1.257        166        640: 100% ━━━━━━━━━━━━ 38/38 2.8it/s 13.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.4it/s 2.0ss
                   all        300       1798      0.813      0.468      0.749      0.338

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/32      4.59G      1.647      1.481      1.343        166        640: 100% ━━━━━━━━━━━━ 38/38 3.0it/s 12.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.4it/s 2.1ss
                   all        300       1798      0.379      0.957      0.385      0.192

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/32      4.59G      1.616      1.252      1.336        136        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.8it/s 1.8ss
                   all        300       1798     0.0293     0.0239    0.00957    0.00183

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/32      4.59G      1.476     0.9966      1.221        165        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.7it/s 1.9ss
                   all        300       1798       0.84      0.833      0.895      0.454

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/32      4.59G      1.405     0.8106      1.211        171        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.8it/s 1.8ss
                   all        300       1798      0.832      0.796      0.847      0.362

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/32      4.59G      1.357     0.7175      1.187        167        640: 100% ━━━━━━━━━━━━ 38/38 3.0it/s 12.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.8it/s 1.8ss
                   all        300       1798      0.913      0.853       0.91      0.463

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/32      4.59G      1.342     0.6834      1.176        141        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.926      0.838      0.903      0.457

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/32      4.59G      1.337     0.6696      1.186        129        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.9it/s 1.7ss
                   all        300       1798      0.852      0.682      0.715       0.23

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/32      4.59G      1.311     0.6414      1.177        153        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.9it/s 1.7ss
                   all        300       1798      0.526      0.435      0.438      0.182

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/32      4.59G      1.283     0.6104      1.165        192        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.8it/s 1.8ss
                   all        300       1798       0.84      0.819      0.849       0.34

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/32      4.59G       1.26      0.589      1.149        186        640: 100% ━━━━━━━━━━━━ 38/38 2.9it/s 13.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.5it/s 2.0ss
                   all        300       1798      0.285      0.242      0.177      0.061

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/32      4.59G      1.257     0.5774      1.158        168        640: 100% ━━━━━━━━━━━━ 38/38 2.8it/s 13.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.2it/s 2.3ss
                   all        300       1798      0.988      0.982      0.992      0.668

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/32      4.59G      1.229     0.5555      1.144        169        640: 100% ━━━━━━━━━━━━ 38/38 2.8it/s 13.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.4it/s 2.1ss
                   all        300       1798       0.99      0.986      0.993      0.636

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/32      4.59G      1.226     0.5503      1.145        156        640: 100% ━━━━━━━━━━━━ 38/38 2.9it/s 13.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.7it/s 1.8ss
                   all        300       1798      0.986      0.986      0.991      0.657

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/32      4.59G      1.225     0.5417      1.149        176        640: 100% ━━━━━━━━━━━━ 38/38 3.0it/s 12.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.7it/s 1.8ss
                   all        300       1798       0.97      0.963      0.987      0.579

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/32      4.59G      1.205     0.5322      1.133        188        640: 100% ━━━━━━━━━━━━ 38/38 3.0it/s 12.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.8it/s 1.8ss
                   all        300       1798      0.987       0.98      0.992      0.648

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/32      4.59G      1.203     0.5261      1.134        169        640: 100% ━━━━━━━━━━━━ 38/38 3.0it/s 12.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.9it/s 1.7ss
                   all        300       1798      0.988      0.977      0.992      0.643

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/32      4.59G      1.174     0.5084      1.121        155        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.8it/s 1.8ss
                   all        300       1798       0.99      0.989      0.993      0.665

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/32      4.59G      1.167     0.5041      1.113        180        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.2it/s 1.6ss
                   all        300       1798      0.985      0.989      0.992      0.673

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/32      4.59G      1.157     0.5002      1.113        174        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.6ss
                   all        300       1798      0.992      0.992      0.993      0.671

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/32      4.59G      1.141     0.4881       1.11        149        640: 100% ━━━━━━━━━━━━ 38/38 3.0it/s 12.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.0it/s 1.7ss
                   all        300       1798      0.993      0.992      0.994      0.684
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/32      4.59G      1.109     0.4538      1.111         96        640: 100% ━━━━━━━━━━━━ 38/38 2.7it/s 14.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798       0.99      0.985      0.994      0.671

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/32       4.6G      1.098     0.4531      1.103        100        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.8it/s 1.8ss
                   all        300       1798      0.991      0.992      0.993      0.691

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/32      4.61G      1.071     0.4398       1.09         99        640: 100% ━━━━━━━━━━━━ 38/38 2.9it/s 12.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.4it/s 2.1ss
                   all        300       1798      0.993      0.986      0.992      0.682

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/32      4.62G      1.075     0.4374      1.089        100        640: 100% ━━━━━━━━━━━━ 38/38 2.9it/s 12.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.5it/s 2.0ss
                   all        300       1798      0.991      0.991      0.993      0.691

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/32      4.63G      1.056     0.4273      1.075         82        640: 100% ━━━━━━━━━━━━ 38/38 2.9it/s 12.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.8it/s 1.8ss
                   all        300       1798      0.991      0.993      0.994      0.689

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/32      4.64G      1.047     0.4229      1.074         92        640: 100% ━━━━━━━━━━━━ 38/38 3.0it/s 12.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.8it/s 1.8ss
                   all        300       1798      0.996      0.992      0.994      0.725

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/32      4.65G       1.04     0.4123      1.075         96        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.6it/s 1.9ss
                   all        300       1798      0.993      0.995      0.994      0.716

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/32      4.66G      1.033     0.4058      1.069         89        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 3.1it/s 1.6ss
                   all        300       1798      0.993      0.996      0.993      0.718

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/32      4.68G      1.019     0.3981      1.064         93        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.7it/s 1.8ss
                   all        300       1798      0.993      0.995      0.993      0.723

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/32      4.69G      1.015     0.3935      1.058         99        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.8it/s 1.8ss
                   all        300       1798      0.994      0.994      0.994      0.733

32 epochs completed in 0.132 hours.
Optimizer stripped from runs/detect/train14/weights/last.pt, 6.2MB
Optimizer stripped from runs/detect/train14/weights/best.pt, 6.2MB

Validating runs/detect/train14/weights/best.pt...
Ultralytics 8.3.189 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
Model summary (fused): 72 layers, 3,005,843 parameters, 0 gradients, 8.1 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.5it/s 3.4ss

/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        300       1798      0.994      0.994      0.994      0.733
Speed: 0.1ms preprocess, 2.1ms inference, 0.0ms loss, 3.5ms postprocess per image
Results saved to runs/detect/train14

,Case,Exp No,Experiment Name,Epochs,Batch,lr0,Weight Decay,Optimizer,Image Size,Dropout,Freeze Layers,Activation,Training Time (s),Precision,Recall,mAP@0.5,mAP@0.5:0.95
4,Case 4: Dropout,5,dropout_0.5,32,32,0.010,0.0001,SGD,640,0.5,0,SiLU,458.67,0.99622,0.99444,0.99470,0.73197
5,Case 6: Optimizer,1,optimizer_SGD,32,32,0.010,0.0001,SGD,640,0.0,0,SiLU,457.57,0.99622,0.99444,0.99470,0.73197
6,Case 6: Optimizer,2,optimizer_Adam,32,32,0.010,0.0001,Adam,640,0.0,0,SiLU,460.64,0.99253,0.99388,0.99452,0.71447
7,Case 6: Optimizer,3,optimizer_AdamW,32,32,0.010,0.0001,AdamW,640,0.0,0,SiLU,463.93,0.99375,0.99499,0.99433,0.72401
8,Case 6: Optimizer,4,optimizer_RMSProp,32,32,0.010,0.0001,RMSProp,640,0.0,0,SiLU,463.36,0.96645,0.94514,0.97844,0.54309
9,Case 6: Optimizer,5,optimizer_Adamax,32,32,0.010,0.0001,Adamax,640,0.0,0,SiLU,458.61,0.99553,0.99388,0.99399,0.73196
10,Case 7: Learning Rate,1,lr_0.001,32,32,0.001,0.0001,SGD,640,0.0,0,SiLU,483.19,0.99727,0.99333,0.99369,0.70411
11,Case 7: Learning Rate,2,lr_0.005,32,32,0.005,0.0001,SGD,640,0.0,0,SiLU,500.17,0.99666,0.99532,0.99466,0.72074
12,Case 7: Learning Rate,3,lr_0.01,32,32,0.010,0.0001,SGD,640,0.0,0,SiLU,494.95,0.99622,0.99444,0.99470,0.73197
13,Case 7: Learning Rate,4,lr_0.05,32,32,0.050,0.0001,SGD,640,0.0,0,SiLU,493.74,0.99392,0.99444,0.99389,0.73307

In [17]:
BEST_PARAMS["epochs"] = 32
BEST_PARAMS["weight_decay"] = 0.0001
BEST_PARAMS["batch"] = 32
BEST_PARAMS["optimizer"] = "SGD"
BEST_PARAMS["lr0"] = 0.01   # keep best LR

case8_freeze_layers()

Ultralytics 8.3.189 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train15, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/train15, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    751507  ultralytics.nn.modules.head.Detect           [1, [64, 128, 256]]
Model summary: 129 layers, 3,011,043 parameters, 3,011,027 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 57.7±40.2 MB/s, size: 52.0 KB)
train: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train/labels... 1200 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1200/1200 521.9it/s 2.3s
WARNING ⚠️ train: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 50.9±28.2 MB/s, size: 61.5 KB)
val: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels... 300 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 300/300 359.9it/s 0.8s
WARNING ⚠️ val: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val is not writeable, cache not saved.
Plotting labels to runs/detect/train15/labels.jpg...
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs/detect/train15
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/32      4.25G      1.966      2.539      1.465        145        640: 100% ━━━━━━━━━━━━ 38/38 2.6it/s 14.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.4it/s 2.0ss
                   all        300       1798     0.0199      0.997       0.98       0.59

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/32       4.6G      1.338     0.9955      1.117        166        640: 100% ━━━━━━━━━━━━ 38/38 2.9it/s 13.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.4it/s 2.1ss
                   all        300       1798       0.98      0.816      0.954      0.385

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/32       4.6G      1.349     0.8865      1.124        166        640: 100% ━━━━━━━━━━━━ 38/38 2.9it/s 13.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.5it/s 2.0ss
                   all        300       1798      0.975      0.972      0.984      0.569

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/32       4.6G      1.312     0.8716      1.113        136        640: 100% ━━━━━━━━━━━━ 38/38 2.9it/s 13.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.4it/s 2.1ss
                   all        300       1798      0.979      0.965       0.98      0.411

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/32       4.6G      1.285      0.786      1.102        165        640: 100% ━━━━━━━━━━━━ 38/38 2.8it/s 13.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.1it/s 2.4ss
                   all        300       1798      0.986      0.983      0.989       0.63

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/32       4.6G      1.263     0.7234      1.098        171        640: 100% ━━━━━━━━━━━━ 38/38 2.9it/s 13.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.4it/s 2.1ss
                   all        300       1798      0.987      0.991      0.993      0.639

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/32       4.6G      1.227     0.6684      1.086        167        640: 100% ━━━━━━━━━━━━ 38/38 2.8it/s 13.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.4it/s 2.0ss
                   all        300       1798      0.988      0.986      0.992      0.572

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/32       4.6G      1.226     0.6448      1.081        141        640: 100% ━━━━━━━━━━━━ 38/38 2.9it/s 13.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.5it/s 2.0ss
                   all        300       1798       0.99      0.984       0.99      0.662

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/32       4.6G      1.211     0.6304      1.084        129        640: 100% ━━━━━━━━━━━━ 38/38 3.0it/s 12.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.6it/s 1.9ss
                   all        300       1798      0.988      0.975      0.993       0.61

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/32       4.6G      1.197     0.6118      1.077        153        640: 100% ━━━━━━━━━━━━ 38/38 2.9it/s 13.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.5it/s 2.0ss
                   all        300       1798      0.994       0.99      0.994      0.671

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/32       4.6G      1.184     0.5853      1.065        192        640: 100% ━━━━━━━━━━━━ 38/38 2.9it/s 12.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.7it/s 1.9ss
                   all        300       1798      0.993      0.991      0.994      0.668

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/32       4.6G      1.161     0.5678      1.063        186        640: 100% ━━━━━━━━━━━━ 38/38 3.0it/s 12.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.7it/s 1.9ss
                   all        300       1798      0.978      0.983       0.99      0.636

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/32       4.6G       1.17     0.5554      1.067        168        640: 100% ━━━━━━━━━━━━ 38/38 3.0it/s 12.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.7it/s 1.8ss
                   all        300       1798      0.993      0.987      0.994      0.693

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/32       4.6G      1.145     0.5409      1.054        169        640: 100% ━━━━━━━━━━━━ 38/38 2.9it/s 13.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.3it/s 2.2ss
                   all        300       1798      0.993      0.993      0.994      0.689

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/32       4.6G      1.139     0.5276      1.058        156        640: 100% ━━━━━━━━━━━━ 38/38 2.8it/s 13.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.1it/s 2.3ss
                   all        300       1798      0.988      0.985      0.993      0.669

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/32       4.6G      1.144      0.522      1.053        176        640: 100% ━━━━━━━━━━━━ 38/38 2.9it/s 13.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.3it/s 2.1ss
                   all        300       1798      0.991      0.986      0.994      0.654

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/32       4.6G      1.125      0.511      1.044        188        640: 100% ━━━━━━━━━━━━ 38/38 2.9it/s 13.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.5it/s 2.0ss
                   all        300       1798      0.991      0.993      0.994      0.698

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/32       4.6G      1.115     0.5034       1.04        169        640: 100% ━━━━━━━━━━━━ 38/38 2.9it/s 13.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.5it/s 2.0ss
                   all        300       1798      0.993      0.993      0.994       0.69

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/32       4.6G      1.107     0.4911      1.037        155        640: 100% ━━━━━━━━━━━━ 38/38 2.9it/s 13.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.6it/s 2.0ss
                   all        300       1798      0.993      0.994      0.994      0.648

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/32       4.6G      1.092     0.4823      1.027        180        640: 100% ━━━━━━━━━━━━ 38/38 2.9it/s 13.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.5it/s 2.0ss
                   all        300       1798      0.995      0.991      0.995      0.703

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/32       4.6G      1.083     0.4775      1.029        174        640: 100% ━━━━━━━━━━━━ 38/38 3.0it/s 12.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.8it/s 1.8ss
                   all        300       1798      0.994      0.994      0.995      0.703

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/32       4.6G      1.063     0.4712      1.023        149        640: 100% ━━━━━━━━━━━━ 38/38 3.0it/s 12.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.6it/s 1.9ss
                   all        300       1798      0.994      0.993      0.995      0.699
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/32       4.6G      1.043     0.4384      1.018         96        640: 100% ━━━━━━━━━━━━ 38/38 2.4it/s 16.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.2it/s 2.3ss
                   all        300       1798      0.993      0.992      0.995      0.694

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/32       4.6G      1.033     0.4367      1.018        100        640: 100% ━━━━━━━━━━━━ 38/38 2.9it/s 13.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.6it/s 2.0ss
                   all        300       1798      0.996      0.994      0.995        0.7

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/32      4.61G      1.017     0.4239       1.01         99        640: 100% ━━━━━━━━━━━━ 38/38 3.0it/s 12.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.6it/s 1.9ss
                   all        300       1798      0.996      0.994      0.995      0.708

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/32      4.62G       1.01     0.4127      1.007        100        640: 100% ━━━━━━━━━━━━ 38/38 3.0it/s 12.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.7it/s 1.9ss
                   all        300       1798      0.996      0.993      0.995      0.716

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/32      4.63G     0.9908     0.4057      0.996         82        640: 100% ━━━━━━━━━━━━ 38/38 3.0it/s 12.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.7it/s 1.8ss
                   all        300       1798      0.994      0.995      0.995      0.688

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/32      4.64G     0.9835     0.4029     0.9978         92        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.7it/s 1.9ss
                   all        300       1798      0.997      0.994      0.995      0.723

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/32      4.65G     0.9802     0.4005     0.9922         96        640: 100% ━━━━━━━━━━━━ 38/38 3.0it/s 12.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.8it/s 1.8ss
                   all        300       1798      0.995      0.993      0.995      0.706

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/32      4.66G     0.9677     0.3901     0.9839         89        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.7it/s 1.8ss
                   all        300       1798      0.994      0.996      0.995      0.725

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/32      4.68G      0.948     0.3838     0.9809         93        640: 100% ━━━━━━━━━━━━ 38/38 3.0it/s 12.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.4it/s 2.1ss
                   all        300       1798      0.995      0.996      0.995      0.732

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/32      4.69G     0.9501      0.381      0.979         99        640: 100% ━━━━━━━━━━━━ 38/38 2.9it/s 13.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.6it/s 1.9ss
                   all        300       1798      0.996      0.994      0.995      0.732

32 epochs completed in 0.137 hours.
Optimizer stripped from runs/detect/train15/weights/last.pt, 6.2MB
Optimizer stripped from runs/detect/train15/weights/best.pt, 6.2MB

Validating runs/detect/train15/weights/best.pt...
Ultralytics 8.3.189 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
Model summary (fused): 72 layers, 3,005,843 parameters, 0 gradients, 8.1 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.3it/s 3.8ss

/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        300       1798      0.996      0.994      0.995      0.732
Speed: 0.1ms preprocess, 1.4ms inference, 0.0ms loss, 4.5ms postprocess per image
Results saved to runs/detect/train15

,Case,Exp No,Experiment Name,Epochs,Batch,lr0,Weight Decay,Optimizer,Image Size,Dropout,Freeze Layers,Activation,Training Time (s),Precision,Recall,mAP@0.5,mAP@0.5:0.95
5,Case 6: Optimizer,1,optimizer_SGD,32,32,0.010,0.0001,SGD,640,0.0,0,SiLU,457.57,0.99622,0.99444,0.99470,0.73197
6,Case 6: Optimizer,2,optimizer_Adam,32,32,0.010,0.0001,Adam,640,0.0,0,SiLU,460.64,0.99253,0.99388,0.99452,0.71447
7,Case 6: Optimizer,3,optimizer_AdamW,32,32,0.010,0.0001,AdamW,640,0.0,0,SiLU,463.93,0.99375,0.99499,0.99433,0.72401
8,Case 6: Optimizer,4,optimizer_RMSProp,32,32,0.010,0.0001,RMSProp,640,0.0,0,SiLU,463.36,0.96645,0.94514,0.97844,0.54309
9,Case 6: Optimizer,5,optimizer_Adamax,32,32,0.010,0.0001,Adamax,640,0.0,0,SiLU,458.61,0.99553,0.99388,0.99399,0.73196
10,Case 7: Learning Rate,1,lr_0.001,32,32,0.001,0.0001,SGD,640,0.0,0,SiLU,483.19,0.99727,0.99333,0.99369,0.70411
11,Case 7: Learning Rate,2,lr_0.005,32,32,0.005,0.0001,SGD,640,0.0,0,SiLU,500.17,0.99666,0.99532,0.99466,0.72074
12,Case 7: Learning Rate,3,lr_0.01,32,32,0.010,0.0001,SGD,640,0.0,0,SiLU,494.95,0.99622,0.99444,0.99470,0.73197
13,Case 7: Learning Rate,4,lr_0.05,32,32,0.050,0.0001,SGD,640,0.0,0,SiLU,493.74,0.99392,0.99444,0.99389,0.73307
14,Case 8: Freeze Layers,1,freeze_0,32,32,0.010,0.0001,SGD,640,0.0,0,SiLU,513.66,0.99622,0.99444,0.99470,0.73197

Ultralytics 8.3.189 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=10, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train16, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/train16, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    751507  ultralytics.nn.modules.head.Detect           [1, [64, 128, 256]]
Model summary: 129 layers, 3,011,043 parameters, 3,011,027 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights
Freezing layer 'model.0.conv.weight'
Freezing layer 'model.0.bn.weight'
Freezing layer 'model.0.bn.bias'
Freezing layer 'model.1.conv.weight'
Freezing layer 'model.1.bn.weight'
Freezing layer 'model.1.bn.bias'
Freezing layer 'model.2.cv1.conv.weight'
Freezing layer 'model.2.cv1.bn.weight'
Freezing layer 'model.2.cv1.bn.bias'
Freezing layer 'model.2.cv2.conv.weight'
Freezing layer 'model.2.cv2.bn.weight'
Freezing layer 'model.2.cv2.bn.bias'
Freezing layer 'model.2.m.0.cv1.conv.weight'
Freezing layer 'model.2.m.0.cv1.bn.weight'
Freezing layer 'model.2.m.0.cv1.bn.bias'
Freezing layer 'model.2.m.0.cv2.conv.weight'
Freezing layer 'model.2.m.0.cv2.bn.weight'
Freezing layer 'model.2.m.0.cv2.bn.bias'
Freezing layer 'model.3.conv.weight'
Freezing layer 'model.3.bn.weight'
Freezing layer 'model.3.bn.bias'
Freezing layer 'model.4.cv1.conv.weight'
Freezing layer 'model.4.cv1.bn.weight'
Freezing layer 'model.4.cv1.bn.bias'
Freezing layer 'model.4.cv2.conv.weight'
Freezing layer 'model.4.cv2.bn.weight'
Freezing layer 'model.4.cv2.bn.bias'
Freezing layer 'model.4.m.0.cv1.conv.weight'
Freezing layer 'model.4.m.0.cv1.bn.weight'
Freezing layer 'model.4.m.0.cv1.bn.bias'
Freezing layer 'model.4.m.0.cv2.conv.weight'
Freezing layer 'model.4.m.0.cv2.bn.weight'
Freezing layer 'model.4.m.0.cv2.bn.bias'
Freezing layer 'model.4.m.1.cv1.conv.weight'
Freezing layer 'model.4.m.1.cv1.bn.weight'
Freezing layer 'model.4.m.1.cv1.bn.bias'
Freezing layer 'model.4.m.1.cv2.conv.weight'
Freezing layer 'model.4.m.1.cv2.bn.weight'
Freezing layer 'model.4.m.1.cv2.bn.bias'
Freezing layer 'model.5.conv.weight'
Freezing layer 'model.5.bn.weight'
Freezing layer 'model.5.bn.bias'
Freezing layer 'model.6.cv1.conv.weight'
Freezing layer 'model.6.cv1.bn.weight'
Freezing layer 'model.6.cv1.bn.bias'
Freezing layer 'model.6.cv2.conv.weight'
Freezing layer 'model.6.cv2.bn.weight'
Freezing layer 'model.6.cv2.bn.bias'
Freezing layer 'model.6.m.0.cv1.conv.weight'
Freezing layer 'model.6.m.0.cv1.bn.weight'
Freezing layer 'model.6.m.0.cv1.bn.bias'
Freezing layer 'model.6.m.0.cv2.conv.weight'
Freezing layer 'model.6.m.0.cv2.bn.weight'
Freezing layer 'model.6.m.0.cv2.bn.bias'
Freezing layer 'model.6.m.1.cv1.conv.weight'
Freezing layer 'model.6.m.1.cv1.bn.weight'
Freezing layer 'model.6.m.1.cv1.bn.bias'
Freezing layer 'model.6.m.1.cv2.conv.weight'
Freezing layer 'model.6.m.1.cv2.bn.weight'
Freezing layer 'model.6.m.1.cv2.bn.bias'
Freezing layer 'model.7.conv.weight'
Freezing layer 'model.7.bn.weight'
Freezing layer 'model.7.bn.bias'
Freezing layer 'model.8.cv1.conv.weight'
Freezing layer 'model.8.cv1.bn.weight'
Freezing layer 'model.8.cv1.bn.bias'
Freezing layer 'model.8.cv2.conv.weight'
Freezing layer 'model.8.cv2.bn.weight'
Freezing layer 'model.8.cv2.bn.bias'
Freezing layer 'model.8.m.0.cv1.conv.weight'
Freezing layer 'model.8.m.0.cv1.bn.weight'
Freezing layer 'model.8.m.0.cv1.bn.bias'
Freezing layer 'model.8.m.0.cv2.conv.weight'
Freezing layer 'model.8.m.0.cv2.bn.weight'
Freezing layer 'model.8.m.0.cv2.bn.bias'
Freezing layer 'model.9.cv1.conv.weight'
Freezing layer 'model.9.cv1.bn.weight'
Freezing layer 'model.9.cv1.bn.bias'
Freezing layer 'model.9.cv2.conv.weight'
Freezing layer 'model.9.cv2.bn.weight'
Freezing layer 'model.9.cv2.bn.bias'
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 76.9±35.4 MB/s, size: 52.0 KB)
train: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train/labels... 1200 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1200/1200 633.9it/s 1.9s
WARNING ⚠️ train: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 87.2±19.8 MB/s, size: 61.5 KB)
val: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels... 300 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 300/300 387.1it/s 0.8s
WARNING ⚠️ val: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val is not writeable, cache not saved.
Plotting labels to runs/detect/train16/labels.jpg...
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs/detect/train16
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/32      2.57G      1.907      2.354      1.389        145        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 12.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.6it/s 3.1ss
                   all        300       1798     0.0199      0.997      0.977      0.558

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/32      2.92G      1.371      1.064      1.105        166        640: 100% ━━━━━━━━━━━━ 38/38 3.4it/s 11.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.8it/s 2.8ss
                   all        300       1798      0.995      0.721      0.991       0.57

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/32      2.92G      1.361      1.008      1.102        166        640: 100% ━━━━━━━━━━━━ 38/38 3.6it/s 10.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0ss
                   all        300       1798      0.982      0.984      0.992      0.592

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/32      2.92G      1.339     0.9522      1.107        136        640: 100% ━━━━━━━━━━━━ 38/38 3.5it/s 10.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.8it/s 2.7ss
                   all        300       1798      0.982      0.986      0.989      0.534

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/32      2.92G      1.308      0.886       1.09        165        640: 100% ━━━━━━━━━━━━ 38/38 4.0it/s 9.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.0it/s 2.5ss
                   all        300       1798       0.98      0.981      0.985      0.601

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/32      2.92G      1.283     0.8257      1.088        171        640: 100% ━━━━━━━━━━━━ 38/38 3.9it/s 9.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.9it/s 2.7ss
                   all        300       1798      0.991      0.988      0.993       0.62

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/32      2.92G      1.267     0.7472       1.09        167        640: 100% ━━━━━━━━━━━━ 38/38 3.7it/s 10.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.0it/s 2.6ss
                   all        300       1798      0.989      0.991      0.991      0.637

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/32      2.92G      1.257      0.748      1.079        141        640: 100% ━━━━━━━━━━━━ 38/38 3.6it/s 10.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.6it/s 3.2ss
                   all        300       1798      0.991      0.991      0.992      0.632

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/32      2.92G      1.256     0.7374      1.086        129        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0ss
                   all        300       1798      0.995      0.994      0.992      0.605

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/32      2.92G      1.237     0.7182      1.074        153        640: 100% ━━━━━━━━━━━━ 38/38 3.5it/s 10.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 2.9ss
                   all        300       1798      0.993      0.993      0.992      0.652

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/32      2.92G      1.227     0.6774      1.066        192        640: 100% ━━━━━━━━━━━━ 38/38 3.6it/s 10.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.9it/s 2.7ss
                   all        300       1798      0.992       0.99      0.991      0.647

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/32      2.92G      1.219     0.6656       1.07        186        640: 100% ━━━━━━━━━━━━ 38/38 3.8it/s 10.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.8it/s 2.7ss
                   all        300       1798      0.985      0.994      0.988      0.632

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/32      2.92G      1.215       0.66      1.068        168        640: 100% ━━━━━━━━━━━━ 38/38 3.7it/s 10.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.1it/s 2.4ss
                   all        300       1798      0.994      0.993      0.994      0.632

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/32      2.92G      1.204     0.6377      1.055        169        640: 100% ━━━━━━━━━━━━ 38/38 3.7it/s 10.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.8it/s 2.7ss
                   all        300       1798      0.991      0.993      0.992      0.662

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/32      2.92G      1.203      0.619      1.063        156        640: 100% ━━━━━━━━━━━━ 38/38 3.6it/s 10.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.9it/s 2.6ss
                   all        300       1798      0.989      0.984      0.989      0.652

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/32      2.92G      1.205     0.6292       1.06        176        640: 100% ━━━━━━━━━━━━ 38/38 3.5it/s 10.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.8it/s 2.7ss
                   all        300       1798      0.993      0.992      0.993      0.663

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/32      2.92G      1.193     0.6185      1.055        188        640: 100% ━━━━━━━━━━━━ 38/38 3.7it/s 10.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.9it/s 2.7ss
                   all        300       1798      0.992      0.993      0.991      0.662

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/32      2.92G      1.182     0.6101      1.048        169        640: 100% ━━━━━━━━━━━━ 38/38 3.5it/s 11.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0ss
                   all        300       1798      0.993      0.991      0.993      0.661

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/32      2.92G      1.177     0.6021      1.045        155        640: 100% ━━━━━━━━━━━━ 38/38 3.3it/s 11.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.8it/s 2.8ss
                   all        300       1798      0.995      0.993      0.993       0.65

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/32      2.92G      1.165     0.5896      1.036        180        640: 100% ━━━━━━━━━━━━ 38/38 3.5it/s 11.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 2.9ss
                   all        300       1798      0.978       0.99      0.986      0.669

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/32      2.92G      1.163     0.5896      1.039        174        640: 100% ━━━━━━━━━━━━ 38/38 3.6it/s 10.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.8it/s 2.8ss
                   all        300       1798      0.991       0.99      0.993      0.681

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/32      2.92G      1.138     0.5746      1.032        149        640: 100% ━━━━━━━━━━━━ 38/38 3.6it/s 10.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.8it/s 2.8ss
                   all        300       1798      0.991      0.989      0.992      0.684
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/32      2.92G      1.096     0.5318      1.018         96        640: 100% ━━━━━━━━━━━━ 38/38 2.8it/s 13.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.1it/s 2.3ss
                   all        300       1798      0.992      0.991       0.99      0.678

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/32      2.92G      1.097     0.5245       1.02        100        640: 100% ━━━━━━━━━━━━ 38/38 3.9it/s 9.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.9it/s 2.6ss
                   all        300       1798      0.994      0.991      0.992      0.681

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/32      2.92G      1.094     0.5224      1.017         99        640: 100% ━━━━━━━━━━━━ 38/38 3.8it/s 9.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.0it/s 2.5ss
                   all        300       1798      0.988      0.989      0.992      0.678

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/32      2.92G      1.079     0.5182       1.01        100        640: 100% ━━━━━━━━━━━━ 38/38 3.9it/s 9.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.0it/s 2.5ss
                   all        300       1798      0.984       0.99      0.987      0.687

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/32      2.92G      1.072      0.501      1.004         82        640: 100% ━━━━━━━━━━━━ 38/38 4.0it/s 9.5s

/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        300       1798      0.994      0.993      0.992      0.699
Speed: 0.1ms preprocess, 1.4ms inference, 0.0ms loss, 4.3ms postprocess per image
Results saved to runs/detect/train16

,Case,Exp No,Experiment Name,Epochs,Batch,lr0,Weight Decay,Optimizer,Image Size,Dropout,Freeze Layers,Activation,Training Time (s),Precision,Recall,mAP@0.5,mAP@0.5:0.95
6,Case 6: Optimizer,2,optimizer_Adam,32,32,0.010,0.0001,Adam,640,0.0,0,SiLU,460.64,0.99253,0.99388,0.99452,0.71447
7,Case 6: Optimizer,3,optimizer_AdamW,32,32,0.010,0.0001,AdamW,640,0.0,0,SiLU,463.93,0.99375,0.99499,0.99433,0.72401
8,Case 6: Optimizer,4,optimizer_RMSProp,32,32,0.010,0.0001,RMSProp,640,0.0,0,SiLU,463.36,0.96645,0.94514,0.97844,0.54309
9,Case 6: Optimizer,5,optimizer_Adamax,32,32,0.010,0.0001,Adamax,640,0.0,0,SiLU,458.61,0.99553,0.99388,0.99399,0.73196
10,Case 7: Learning Rate,1,lr_0.001,32,32,0.001,0.0001,SGD,640,0.0,0,SiLU,483.19,0.99727,0.99333,0.99369,0.70411
11,Case 7: Learning Rate,2,lr_0.005,32,32,0.005,0.0001,SGD,640,0.0,0,SiLU,500.17,0.99666,0.99532,0.99466,0.72074
12,Case 7: Learning Rate,3,lr_0.01,32,32,0.010,0.0001,SGD,640,0.0,0,SiLU,494.95,0.99622,0.99444,0.99470,0.73197
13,Case 7: Learning Rate,4,lr_0.05,32,32,0.050,0.0001,SGD,640,0.0,0,SiLU,493.74,0.99392,0.99444,0.99389,0.73307
14,Case 8: Freeze Layers,1,freeze_0,32,32,0.010,0.0001,SGD,640,0.0,0,SiLU,513.66,0.99622,0.99444,0.99470,0.73197
15,Case 8: Freeze Layers,2,freeze_10,32,32,0.010,0.0001,SGD,640,0.0,10,SiLU,452.43,0.99376,0.99333,0.99165,0.69899

Ultralytics 8.3.189 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=15, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train17, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/train17, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    751507  ultralytics.nn.modules.head.Detect           [1, [64, 128, 256]]
Model summary: 129 layers, 3,011,043 parameters, 3,011,027 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights
Freezing layer 'model.0.conv.weight'
Freezing layer 'model.0.bn.weight'
Freezing layer 'model.0.bn.bias'
Freezing layer 'model.1.conv.weight'
Freezing layer 'model.1.bn.weight'
Freezing layer 'model.1.bn.bias'
Freezing layer 'model.2.cv1.conv.weight'
Freezing layer 'model.2.cv1.bn.weight'
Freezing layer 'model.2.cv1.bn.bias'
Freezing layer 'model.2.cv2.conv.weight'
Freezing layer 'model.2.cv2.bn.weight'
Freezing layer 'model.2.cv2.bn.bias'
Freezing layer 'model.2.m.0.cv1.conv.weight'
Freezing layer 'model.2.m.0.cv1.bn.weight'
Freezing layer 'model.2.m.0.cv1.bn.bias'
Freezing layer 'model.2.m.0.cv2.conv.weight'
Freezing layer 'model.2.m.0.cv2.bn.weight'
Freezing layer 'model.2.m.0.cv2.bn.bias'
Freezing layer 'model.3.conv.weight'
Freezing layer 'model.3.bn.weight'
Freezing layer 'model.3.bn.bias'
Freezing layer 'model.4.cv1.conv.weight'
Freezing layer 'model.4.cv1.bn.weight'
Freezing layer 'model.4.cv1.bn.bias'
Freezing layer 'model.4.cv2.conv.weight'
Freezing layer 'model.4.cv2.bn.weight'
Freezing layer 'model.4.cv2.bn.bias'
Freezing layer 'model.4.m.0.cv1.conv.weight'
Freezing layer 'model.4.m.0.cv1.bn.weight'
Freezing layer 'model.4.m.0.cv1.bn.bias'
Freezing layer 'model.4.m.0.cv2.conv.weight'
Freezing layer 'model.4.m.0.cv2.bn.weight'
Freezing layer 'model.4.m.0.cv2.bn.bias'
Freezing layer 'model.4.m.1.cv1.conv.weight'
Freezing layer 'model.4.m.1.cv1.bn.weight'
Freezing layer 'model.4.m.1.cv1.bn.bias'
Freezing layer 'model.4.m.1.cv2.conv.weight'
Freezing layer 'model.4.m.1.cv2.bn.weight'
Freezing layer 'model.4.m.1.cv2.bn.bias'
Freezing layer 'model.5.conv.weight'
Freezing layer 'model.5.bn.weight'
Freezing layer 'model.5.bn.bias'
Freezing layer 'model.6.cv1.conv.weight'
Freezing layer 'model.6.cv1.bn.weight'
Freezing layer 'model.6.cv1.bn.bias'
Freezing layer 'model.6.cv2.conv.weight'
Freezing layer 'model.6.cv2.bn.weight'
Freezing layer 'model.6.cv2.bn.bias'
Freezing layer 'model.6.m.0.cv1.conv.weight'
Freezing layer 'model.6.m.0.cv1.bn.weight'
Freezing layer 'model.6.m.0.cv1.bn.bias'
Freezing layer 'model.6.m.0.cv2.conv.weight'
Freezing layer 'model.6.m.0.cv2.bn.weight'
Freezing layer 'model.6.m.0.cv2.bn.bias'
Freezing layer 'model.6.m.1.cv1.conv.weight'
Freezing layer 'model.6.m.1.cv1.bn.weight'
Freezing layer 'model.6.m.1.cv1.bn.bias'
Freezing layer 'model.6.m.1.cv2.conv.weight'
Freezing layer 'model.6.m.1.cv2.bn.weight'
Freezing layer 'model.6.m.1.cv2.bn.bias'
Freezing layer 'model.7.conv.weight'
Freezing layer 'model.7.bn.weight'
Freezing layer 'model.7.bn.bias'
Freezing layer 'model.8.cv1.conv.weight'
Freezing layer 'model.8.cv1.bn.weight'
Freezing layer 'model.8.cv1.bn.bias'
Freezing layer 'model.8.cv2.conv.weight'
Freezing layer 'model.8.cv2.bn.weight'
Freezing layer 'model.8.cv2.bn.bias'
Freezing layer 'model.8.m.0.cv1.conv.weight'
Freezing layer 'model.8.m.0.cv1.bn.weight'
Freezing layer 'model.8.m.0.cv1.bn.bias'
Freezing layer 'model.8.m.0.cv2.conv.weight'
Freezing layer 'model.8.m.0.cv2.bn.weight'
Freezing layer 'model.8.m.0.cv2.bn.bias'
Freezing layer 'model.9.cv1.conv.weight'
Freezing layer 'model.9.cv1.bn.weight'
Freezing layer 'model.9.cv1.bn.bias'
Freezing layer 'model.9.cv2.conv.weight'
Freezing layer 'model.9.cv2.bn.weight'
Freezing layer 'model.9.cv2.bn.bias'
Freezing layer 'model.12.cv1.conv.weight'
Freezing layer 'model.12.cv1.bn.weight'
Freezing layer 'model.12.cv1.bn.bias'
Freezing layer 'model.12.cv2.conv.weight'
Freezing layer 'model.12.cv2.bn.weight'
Freezing layer 'model.12.cv2.bn.bias'
Freezing layer 'model.12.m.0.cv1.conv.weight'
Freezing layer 'model.12.m.0.cv1.bn.weight'
Freezing layer 'model.12.m.0.cv1.bn.bias'
Freezing layer 'model.12.m.0.cv2.conv.weight'
Freezing layer 'model.12.m.0.cv2.bn.weight'
Freezing layer 'model.12.m.0.cv2.bn.bias'
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 95.1±29.8 MB/s, size: 52.0 KB)
train: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train/labels... 1200 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1200/1200 814.0it/s 1.5s
WARNING ⚠️ train: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 46.9±38.1 MB/s, size: 61.5 KB)
val: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels... 300 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 300/300 442.2it/s 0.7s
WARNING ⚠️ val: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val is not writeable, cache not saved.
Plotting labels to runs/detect/train17/labels.jpg...
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs/detect/train17
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/32      2.31G      1.919      2.367      1.367        145        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.8it/s 2.8ss
                   all        300       1798     0.0199      0.998      0.945      0.496

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/32      2.66G      1.408      1.126      1.107        166        640: 100% ━━━━━━━━━━━━ 38/38 3.5it/s 11.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.8it/s 2.7ss
                   all        300       1798      0.994      0.515      0.984      0.556

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/32      2.66G      1.393      1.052        1.1        166        640: 100% ━━━━━━━━━━━━ 38/38 3.8it/s 9.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 2.9ss
                   all        300       1798      0.964      0.979      0.987      0.554

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/32      2.66G      1.377      1.001      1.094        136        640: 100% ━━━━━━━━━━━━ 38/38 3.7it/s 10.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0ss
                   all        300       1798       0.98      0.985      0.989      0.555

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/32      2.66G      1.349     0.9465      1.077        165        640: 100% ━━━━━━━━━━━━ 38/38 3.3it/s 11.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0ss
                   all        300       1798      0.971      0.971      0.981      0.575

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/32      2.66G      1.322     0.8893       1.07        171        640: 100% ━━━━━━━━━━━━ 38/38 3.4it/s 11.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.6it/s 3.1ss
                   all        300       1798      0.981      0.987       0.99      0.606

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/32      2.66G      1.299     0.8396      1.065        167        640: 100% ━━━━━━━━━━━━ 38/38 3.5it/s 11.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 2.9ss
                   all        300       1798      0.982      0.989       0.99      0.613

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/32      2.66G      1.286     0.8306      1.053        141        640: 100% ━━━━━━━━━━━━ 38/38 3.5it/s 11.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 2.9ss
                   all        300       1798      0.979      0.979       0.99      0.625

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/32      2.66G      1.285     0.8105      1.056        129        640: 100% ━━━━━━━━━━━━ 38/38 3.4it/s 11.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 2.9ss
                   all        300       1798      0.987      0.989      0.992      0.632

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/32      2.66G      1.269       0.78      1.047        153        640: 100% ━━━━━━━━━━━━ 38/38 3.4it/s 11.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.8it/s 2.8ss
                   all        300       1798      0.983      0.984       0.99      0.645

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/32      2.66G      1.255     0.7462      1.041        192        640: 100% ━━━━━━━━━━━━ 38/38 3.4it/s 11.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.8it/s 2.8ss
                   all        300       1798      0.978      0.986      0.988      0.645

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/32      2.66G      1.239     0.7394      1.038        186        640: 100% ━━━━━━━━━━━━ 38/38 3.5it/s 10.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.8it/s 2.7ss
                   all        300       1798      0.985      0.985      0.989       0.65

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/32      2.66G      1.239     0.7194      1.041        168        640: 100% ━━━━━━━━━━━━ 38/38 3.4it/s 11.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.0it/s 2.6ss
                   all        300       1798      0.982      0.984      0.991       0.66

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/32      2.66G      1.228     0.7046       1.03        169        640: 100% ━━━━━━━━━━━━ 38/38 3.2it/s 11.8s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.6it/s 3.1ss
                   all        300       1798      0.988      0.992      0.993      0.645

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/32      2.66G      1.225     0.6878       1.03        156        640: 100% ━━━━━━━━━━━━ 38/38 3.4it/s 11.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.0it/s 2.5ss
                   all        300       1798       0.97      0.973      0.984      0.612

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/32      2.66G      1.225     0.7006      1.026        176        640: 100% ━━━━━━━━━━━━ 38/38 3.4it/s 11.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.9it/s 2.7ss
                   all        300       1798      0.952      0.989      0.981      0.651

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/32      2.66G      1.214     0.6804      1.023        188        640: 100% ━━━━━━━━━━━━ 38/38 3.6it/s 10.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 2.9ss
                   all        300       1798      0.977      0.989      0.989      0.658

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/32      2.66G      1.206     0.6704      1.016        169        640: 100% ━━━━━━━━━━━━ 38/38 3.4it/s 11.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.0it/s 2.5ss
                   all        300       1798      0.985      0.983       0.99      0.664

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/32      2.66G      1.202     0.6676      1.016        155        640: 100% ━━━━━━━━━━━━ 38/38 3.7it/s 10.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.8it/s 2.8ss
                   all        300       1798      0.988      0.986      0.992      0.663

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/32      2.66G      1.186     0.6552      1.008        180        640: 100% ━━━━━━━━━━━━ 38/38 3.8it/s 10.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.9it/s 2.6ss
                   all        300       1798      0.965      0.979      0.984      0.641

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/32      2.66G      1.188     0.6508      1.015        174        640: 100% ━━━━━━━━━━━━ 38/38 4.0it/s 9.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.9it/s 2.6ss
                   all        300       1798      0.986      0.988      0.991       0.67

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/32      2.66G      1.167     0.6371      1.006        149        640: 100% ━━━━━━━━━━━━ 38/38 3.8it/s 10.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.9it/s 2.6ss
                   all        300       1798      0.977      0.989      0.989      0.668
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/32      2.66G      1.126      0.589     0.9974         96        640: 100% ━━━━━━━━━━━━ 38/38 2.7it/s 14.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.0it/s 2.5ss
                   all        300       1798      0.984      0.987      0.991      0.673

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/32      2.66G      1.115     0.5835     0.9956        100        640: 100% ━━━━━━━━━━━━ 38/38 3.4it/s 11.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.9it/s 2.6ss
                   all        300       1798      0.965      0.988      0.984      0.673

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/32      2.66G      1.113     0.5756     0.9925         99        640: 100% ━━━━━━━━━━━━ 38/38 3.6it/s 10.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.0it/s 2.5ss
                   all        300       1798      0.987      0.989      0.992      0.668

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        300       1798      0.985      0.991      0.991      0.689
Speed: 0.1ms preprocess, 1.4ms inference, 0.0ms loss, 3.8ms postprocess per image
Results saved to runs/detect/train17

,Case,Exp No,Experiment Name,Epochs,Batch,lr0,Weight Decay,Optimizer,Image Size,Dropout,Freeze Layers,Activation,Training Time (s),Precision,Recall,mAP@0.5,mAP@0.5:0.95
7,Case 6: Optimizer,3,optimizer_AdamW,32,32,0.010,0.0001,AdamW,640,0.0,0,SiLU,463.93,0.99375,0.99499,0.99433,0.72401
8,Case 6: Optimizer,4,optimizer_RMSProp,32,32,0.010,0.0001,RMSProp,640,0.0,0,SiLU,463.36,0.96645,0.94514,0.97844,0.54309
9,Case 6: Optimizer,5,optimizer_Adamax,32,32,0.010,0.0001,Adamax,640,0.0,0,SiLU,458.61,0.99553,0.99388,0.99399,0.73196
10,Case 7: Learning Rate,1,lr_0.001,32,32,0.001,0.0001,SGD,640,0.0,0,SiLU,483.19,0.99727,0.99333,0.99369,0.70411
11,Case 7: Learning Rate,2,lr_0.005,32,32,0.005,0.0001,SGD,640,0.0,0,SiLU,500.17,0.99666,0.99532,0.99466,0.72074
12,Case 7: Learning Rate,3,lr_0.01,32,32,0.010,0.0001,SGD,640,0.0,0,SiLU,494.95,0.99622,0.99444,0.99470,0.73197
13,Case 7: Learning Rate,4,lr_0.05,32,32,0.050,0.0001,SGD,640,0.0,0,SiLU,493.74,0.99392,0.99444,0.99389,0.73307
14,Case 8: Freeze Layers,1,freeze_0,32,32,0.010,0.0001,SGD,640,0.0,0,SiLU,513.66,0.99622,0.99444,0.99470,0.73197
15,Case 8: Freeze Layers,2,freeze_10,32,32,0.010,0.0001,SGD,640,0.0,10,SiLU,452.43,0.99376,0.99333,0.99165,0.69899
16,Case 8: Freeze Layers,3,freeze_15,32,32,0.010,0.0001,SGD,640,0.0,15,SiLU,455.12,0.98482,0.99055,0.99111,0.68906

Ultralytics 8.3.189 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=22, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8n.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train18, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/train18, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      7360  ultralytics.nn.modules.block.C2f             [32, 32, 1, True]
  3                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  4                  -1  2     49664  ultralytics.nn.modules.block.C2f             [64, 64, 2, True]
  5                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  6                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    460288  ultralytics.nn.modules.block.C2f             [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1     37248  ultralytics.nn.modules.block.C2f             [192, 64, 1]
 16                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    123648  ultralytics.nn.modules.block.C2f             [192, 128, 1]
 19                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 22        [15, 18, 21]  1    751507  ultralytics.nn.modules.head.Detect           [1, [64, 128, 256]]
Model summary: 129 layers, 3,011,043 parameters, 3,011,027 gradients, 8.2 GFLOPs

Transferred 319/355 items from pretrained weights
Freezing layer 'model.0.conv.weight'
Freezing layer 'model.0.bn.weight'
Freezing layer 'model.0.bn.bias'
Freezing layer 'model.1.conv.weight'
Freezing layer 'model.1.bn.weight'
Freezing layer 'model.1.bn.bias'
Freezing layer 'model.2.cv1.conv.weight'
Freezing layer 'model.2.cv1.bn.weight'
Freezing layer 'model.2.cv1.bn.bias'
Freezing layer 'model.2.cv2.conv.weight'
Freezing layer 'model.2.cv2.bn.weight'
Freezing layer 'model.2.cv2.bn.bias'
Freezing layer 'model.2.m.0.cv1.conv.weight'
Freezing layer 'model.2.m.0.cv1.bn.weight'
Freezing layer 'model.2.m.0.cv1.bn.bias'
Freezing layer 'model.2.m.0.cv2.conv.weight'
Freezing layer 'model.2.m.0.cv2.bn.weight'
Freezing layer 'model.2.m.0.cv2.bn.bias'
Freezing layer 'model.3.conv.weight'
Freezing layer 'model.3.bn.weight'
Freezing layer 'model.3.bn.bias'
Freezing layer 'model.4.cv1.conv.weight'
Freezing layer 'model.4.cv1.bn.weight'
Freezing layer 'model.4.cv1.bn.bias'
Freezing layer 'model.4.cv2.conv.weight'
Freezing layer 'model.4.cv2.bn.weight'
Freezing layer 'model.4.cv2.bn.bias'
Freezing layer 'model.4.m.0.cv1.conv.weight'
Freezing layer 'model.4.m.0.cv1.bn.weight'
Freezing layer 'model.4.m.0.cv1.bn.bias'
Freezing layer 'model.4.m.0.cv2.conv.weight'
Freezing layer 'model.4.m.0.cv2.bn.weight'
Freezing layer 'model.4.m.0.cv2.bn.bias'
Freezing layer 'model.4.m.1.cv1.conv.weight'
Freezing layer 'model.4.m.1.cv1.bn.weight'
Freezing layer 'model.4.m.1.cv1.bn.bias'
Freezing layer 'model.4.m.1.cv2.conv.weight'
Freezing layer 'model.4.m.1.cv2.bn.weight'
Freezing layer 'model.4.m.1.cv2.bn.bias'
Freezing layer 'model.5.conv.weight'
Freezing layer 'model.5.bn.weight'
Freezing layer 'model.5.bn.bias'
Freezing layer 'model.6.cv1.conv.weight'
Freezing layer 'model.6.cv1.bn.weight'
Freezing layer 'model.6.cv1.bn.bias'
Freezing layer 'model.6.cv2.conv.weight'
Freezing layer 'model.6.cv2.bn.weight'
Freezing layer 'model.6.cv2.bn.bias'
Freezing layer 'model.6.m.0.cv1.conv.weight'
Freezing layer 'model.6.m.0.cv1.bn.weight'
Freezing layer 'model.6.m.0.cv1.bn.bias'
Freezing layer 'model.6.m.0.cv2.conv.weight'
Freezing layer 'model.6.m.0.cv2.bn.weight'
Freezing layer 'model.6.m.0.cv2.bn.bias'
Freezing layer 'model.6.m.1.cv1.conv.weight'
Freezing layer 'model.6.m.1.cv1.bn.weight'
Freezing layer 'model.6.m.1.cv1.bn.bias'
Freezing layer 'model.6.m.1.cv2.conv.weight'
Freezing layer 'model.6.m.1.cv2.bn.weight'
Freezing layer 'model.6.m.1.cv2.bn.bias'
Freezing layer 'model.7.conv.weight'
Freezing layer 'model.7.bn.weight'
Freezing layer 'model.7.bn.bias'
Freezing layer 'model.8.cv1.conv.weight'
Freezing layer 'model.8.cv1.bn.weight'
Freezing layer 'model.8.cv1.bn.bias'
Freezing layer 'model.8.cv2.conv.weight'
Freezing layer 'model.8.cv2.bn.weight'
Freezing layer 'model.8.cv2.bn.bias'
Freezing layer 'model.8.m.0.cv1.conv.weight'
Freezing layer 'model.8.m.0.cv1.bn.weight'
Freezing layer 'model.8.m.0.cv1.bn.bias'
Freezing layer 'model.8.m.0.cv2.conv.weight'
Freezing layer 'model.8.m.0.cv2.bn.weight'
Freezing layer 'model.8.m.0.cv2.bn.bias'
Freezing layer 'model.9.cv1.conv.weight'
Freezing layer 'model.9.cv1.bn.weight'
Freezing layer 'model.9.cv1.bn.bias'
Freezing layer 'model.9.cv2.conv.weight'
Freezing layer 'model.9.cv2.bn.weight'
Freezing layer 'model.9.cv2.bn.bias'
Freezing layer 'model.12.cv1.conv.weight'
Freezing layer 'model.12.cv1.bn.weight'
Freezing layer 'model.12.cv1.bn.bias'
Freezing layer 'model.12.cv2.conv.weight'
Freezing layer 'model.12.cv2.bn.weight'
Freezing layer 'model.12.cv2.bn.bias'
Freezing layer 'model.12.m.0.cv1.conv.weight'
Freezing layer 'model.12.m.0.cv1.bn.weight'
Freezing layer 'model.12.m.0.cv1.bn.bias'
Freezing layer 'model.12.m.0.cv2.conv.weight'
Freezing layer 'model.12.m.0.cv2.bn.weight'
Freezing layer 'model.12.m.0.cv2.bn.bias'
Freezing layer 'model.15.cv1.conv.weight'
Freezing layer 'model.15.cv1.bn.weight'
Freezing layer 'model.15.cv1.bn.bias'
Freezing layer 'model.15.cv2.conv.weight'
Freezing layer 'model.15.cv2.bn.weight'
Freezing layer 'model.15.cv2.bn.bias'
Freezing layer 'model.15.m.0.cv1.conv.weight'
Freezing layer 'model.15.m.0.cv1.bn.weight'
Freezing layer 'model.15.m.0.cv1.bn.bias'
Freezing layer 'model.15.m.0.cv2.conv.weight'
Freezing layer 'model.15.m.0.cv2.bn.weight'
Freezing layer 'model.15.m.0.cv2.bn.bias'
Freezing layer 'model.16.conv.weight'
Freezing layer 'model.16.bn.weight'
Freezing layer 'model.16.bn.bias'
Freezing layer 'model.18.cv1.conv.weight'
Freezing layer 'model.18.cv1.bn.weight'
Freezing layer 'model.18.cv1.bn.bias'
Freezing layer 'model.18.cv2.conv.weight'
Freezing layer 'model.18.cv2.bn.weight'
Freezing layer 'model.18.cv2.bn.bias'
Freezing layer 'model.18.m.0.cv1.conv.weight'
Freezing layer 'model.18.m.0.cv1.bn.weight'
Freezing layer 'model.18.m.0.cv1.bn.bias'
Freezing layer 'model.18.m.0.cv2.conv.weight'
Freezing layer 'model.18.m.0.cv2.bn.weight'
Freezing layer 'model.18.m.0.cv2.bn.bias'
Freezing layer 'model.19.conv.weight'
Freezing layer 'model.19.bn.weight'
Freezing layer 'model.19.bn.bias'
Freezing layer 'model.21.cv1.conv.weight'
Freezing layer 'model.21.cv1.bn.weight'
Freezing layer 'model.21.cv1.bn.bias'
Freezing layer 'model.21.cv2.conv.weight'
Freezing layer 'model.21.cv2.bn.weight'
Freezing layer 'model.21.cv2.bn.bias'
Freezing layer 'model.21.m.0.cv1.conv.weight'
Freezing layer 'model.21.m.0.cv1.bn.weight'
Freezing layer 'model.21.m.0.cv1.bn.bias'
Freezing layer 'model.21.m.0.cv2.conv.weight'
Freezing layer 'model.21.m.0.cv2.bn.weight'
Freezing layer 'model.21.m.0.cv2.bn.bias'
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 63.8±23.2 MB/s, size: 52.0 KB)
train: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train/labels... 1200 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1200/1200 665.8it/s 1.8s
WARNING ⚠️ train: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 62.9±38.2 MB/s, size: 61.5 KB)
val: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels... 300 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 300/300 367.5it/s 0.8s
WARNING ⚠️ val: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val is not writeable, cache not saved.
Plotting labels to runs/detect/train18/labels.jpg...
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs/detect/train18
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/32      2.02G      2.147      2.558      1.529        145        640: 100% ━━━━━━━━━━━━ 38/38 3.1it/s 12.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.6it/s 3.2ss
                   all        300       1798     0.0197      0.984      0.771      0.381

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/32      2.37G      1.581      1.391      1.288        166        640: 100% ━━━━━━━━━━━━ 38/38 3.6it/s 10.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.9it/s 2.7ss
                   all        300       1798     0.0198      0.991      0.853      0.447

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/32      2.37G      1.522      1.262      1.257        166        640: 100% ━━━━━━━━━━━━ 38/38 3.8it/s 10.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.8it/s 2.8ss
                   all        300       1798      0.885      0.793      0.914      0.484

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/32      2.37G      1.499      1.199      1.249        136        640: 100% ━━━━━━━━━━━━ 38/38 3.7it/s 10.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.0it/s 2.5ss
                   all        300       1798      0.747      0.786      0.838       0.44

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/32      2.37G      1.479       1.12      1.236        165        640: 100% ━━━━━━━━━━━━ 38/38 3.8it/s 10.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.0it/s 2.5ss
                   all        300       1798      0.807      0.862      0.894      0.477

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/32      2.37G      1.444      1.082      1.221        171        640: 100% ━━━━━━━━━━━━ 38/38 3.6it/s 10.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.9it/s 2.6ss
                   all        300       1798      0.837      0.901      0.927      0.512

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/32      2.37G      1.422      1.028      1.208        167        640: 100% ━━━━━━━━━━━━ 38/38 3.6it/s 10.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 2.9ss
                   all        300       1798       0.87      0.921      0.952      0.537

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/32      2.37G      1.416      1.013      1.197        141        640: 100% ━━━━━━━━━━━━ 38/38 3.6it/s 10.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.9it/s 2.6ss
                   all        300       1798      0.908      0.922      0.961      0.557

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/32      2.37G      1.415     0.9991      1.208        129        640: 100% ━━━━━━━━━━━━ 38/38 3.6it/s 10.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.6it/s 3.2ss
                   all        300       1798      0.895      0.928      0.961      0.549

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/32      2.37G      1.402     0.9781      1.196        153        640: 100% ━━━━━━━━━━━━ 38/38 3.5it/s 10.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 2.9ss
                   all        300       1798      0.905      0.929      0.962      0.562

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/32      2.37G      1.388     0.9386      1.183        192        640: 100% ━━━━━━━━━━━━ 38/38 3.6it/s 10.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.9it/s 2.6ss
                   all        300       1798      0.888      0.931      0.948      0.543

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/32      2.37G       1.38     0.9269      1.184        186        640: 100% ━━━━━━━━━━━━ 38/38 3.8it/s 10.1s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.9it/s 2.6ss
                   all        300       1798      0.884      0.927      0.961       0.56

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/32      2.37G      1.373     0.9232      1.186        168        640: 100% ━━━━━━━━━━━━ 38/38 3.7it/s 10.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.1it/s 2.4ss
                   all        300       1798      0.928      0.941       0.97      0.573

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/32      2.37G      1.361     0.8968      1.175        169        640: 100% ━━━━━━━━━━━━ 38/38 3.9it/s 9.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.1it/s 2.4ss
                   all        300       1798      0.899      0.942      0.965      0.564

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/32      2.37G      1.362     0.8977      1.184        156        640: 100% ━━━━━━━━━━━━ 38/38 3.7it/s 10.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.0it/s 2.5ss
                   all        300       1798      0.853      0.937      0.945      0.548

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/32      2.37G       1.36     0.9028      1.175        176        640: 100% ━━━━━━━━━━━━ 38/38 3.8it/s 10.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.9it/s 2.6ss
                   all        300       1798      0.935      0.938      0.976      0.571

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/32      2.37G      1.356     0.8817      1.172        188        640: 100% ━━━━━━━━━━━━ 38/38 3.9it/s 9.9s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.8it/s 2.7ss
                   all        300       1798      0.898      0.943      0.963       0.57

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/32      2.37G      1.348     0.8746      1.165        169        640: 100% ━━━━━━━━━━━━ 38/38 3.7it/s 10.2s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.6it/s 3.1ss
                   all        300       1798       0.89      0.937      0.961      0.562

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/32      2.37G      1.349      0.869      1.167        155        640: 100% ━━━━━━━━━━━━ 38/38 3.3it/s 11.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.9it/s 2.7ss
                   all        300       1798      0.911      0.955       0.97      0.584

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/32      2.37G      1.336     0.8562      1.156        180        640: 100% ━━━━━━━━━━━━ 38/38 3.6it/s 10.6s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 2.0it/s 2.4ss
                   all        300       1798      0.913      0.948      0.967      0.583

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/32      2.37G      1.328     0.8631       1.16        174        640: 100% ━━━━━━━━━━━━ 38/38 3.9it/s 9.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.8it/s 2.8ss
                   all        300       1798      0.913      0.947      0.973      0.579

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/32      2.37G      1.319      0.845      1.156        149        640: 100% ━━━━━━━━━━━━ 38/38 3.8it/s 9.9s

/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        300       1798      0.952      0.961      0.984      0.607
Speed: 0.1ms preprocess, 1.9ms inference, 0.0ms loss, 3.9ms postprocess per image
Results saved to runs/detect/train18

,Case,Exp No,Experiment Name,Epochs,Batch,lr0,Weight Decay,Optimizer,Image Size,Dropout,Freeze Layers,Activation,Training Time (s),Precision,Recall,mAP@0.5,mAP@0.5:0.95
8,Case 6: Optimizer,4,optimizer_RMSProp,32,32,0.010,0.0001,RMSProp,640,0.0,0,SiLU,463.36,0.96645,0.94514,0.97844,0.54309
9,Case 6: Optimizer,5,optimizer_Adamax,32,32,0.010,0.0001,Adamax,640,0.0,0,SiLU,458.61,0.99553,0.99388,0.99399,0.73196
10,Case 7: Learning Rate,1,lr_0.001,32,32,0.001,0.0001,SGD,640,0.0,0,SiLU,483.19,0.99727,0.99333,0.99369,0.70411
11,Case 7: Learning Rate,2,lr_0.005,32,32,0.005,0.0001,SGD,640,0.0,0,SiLU,500.17,0.99666,0.99532,0.99466,0.72074
12,Case 7: Learning Rate,3,lr_0.01,32,32,0.010,0.0001,SGD,640,0.0,0,SiLU,494.95,0.99622,0.99444,0.99470,0.73197
13,Case 7: Learning Rate,4,lr_0.05,32,32,0.050,0.0001,SGD,640,0.0,0,SiLU,493.74,0.99392,0.99444,0.99389,0.73307
14,Case 8: Freeze Layers,1,freeze_0,32,32,0.010,0.0001,SGD,640,0.0,0,SiLU,513.66,0.99622,0.99444,0.99470,0.73197
15,Case 8: Freeze Layers,2,freeze_10,32,32,0.010,0.0001,SGD,640,0.0,10,SiLU,452.43,0.99376,0.99333,0.99165,0.69899
16,Case 8: Freeze Layers,3,freeze_15,32,32,0.010,0.0001,SGD,640,0.0,15,SiLU,455.12,0.98482,0.99055,0.99111,0.68906
17,Case 8: Freeze Layers,4,freeze_22,32,32,0.010,0.0001,SGD,640,0.0,22,SiLU,439.20,0.95175,0.96107,0.98368,0.60693

ValueError: Invalid export format='yaml'. Valid formats are ('torchscript', 'onnx', 'openvino', 'engine', 'coreml', 'saved_model', 'pb', 'tflite', 'edgetpu', 'tfjs', 'paddle', 'mnn', 'ncnn', 'imx', 'rknn')

In [18]:
import re
from pathlib import Path

# Path to the exported yaml
base_yaml = Path("yolov8n.yaml").read_text()

# List of activations to test
activations = ["SiLU", "ReLU", "LeakyReLU", "Mish", "GELU"]

# Prepare custom yaml files
for act in activations:
    custom_yaml = re.sub(r"act:\s*\w+", f"act: {act}", base_yaml)
    out_file = f"yolov8n_{act}.yaml"
    Path(out_file).write_text(custom_yaml)
    print(f"Saved {out_file}")

FileNotFoundError: [Errno 2] No such file or directory: 'yolov8n.yaml'