In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/yolo-component-data/YOLO_component-dataset/data.yaml
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit1025.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit1047.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit486.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit728.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit1013.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit282.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit687.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit889.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit554.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit772.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit305.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit831.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit606.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit210.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit255.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit809.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit754.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit397.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit463.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit905.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit686.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit635.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit1.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit197.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit1100.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit763.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit82.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit256.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit1045.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit186.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit490.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit1036.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit591.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit79.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit1038.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit297.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit801.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit1081.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit366.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit597.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit1142.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit465.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit259.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit1011.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit650.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit764.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit565.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit252.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit850.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit678.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit757.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit166.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit1088.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit191.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit530.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit1042.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit1094.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit699.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit607.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit266.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit218.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit695.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit23.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit775.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit943.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit1083.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit1010.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit563.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit405.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit608.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit573.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit549.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit577.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit988.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit1112.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit116.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit969.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit327.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit1129.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit894.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit2.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit1109.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit215.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit73.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit104.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit135.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit332.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit97.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit19.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit1087.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit416.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit838.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit313.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit16.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit1043.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit236.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit884.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit88.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit99.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit529.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit318.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit279.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit753.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit333.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit1120.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit952.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit335.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit827.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit277.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit246.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit527.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit113.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit38.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit878.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit87.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit963.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit222.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit114.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit1064.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit169.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit330.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit575.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit311.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit815.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit351.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit1133.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit464 (1).txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit101.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit581.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit1101.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit389.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit189.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit1125.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit866.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit121.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit356.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit454.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit275.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit498.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit183.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit675.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit1050.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit533.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit168.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit239.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit253.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit946.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit286.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit298.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit1105.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit780.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit537.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit588.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit251.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit1030.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit1000.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit593.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit50.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit871.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit999.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit521.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit263.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit722.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit109.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit1020.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit1026.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit1110.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit1117.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit526.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit1002.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit1014.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit200.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit1015.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit849.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit725.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit497.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit720.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit961.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit449.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit170.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit796.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit33.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit206.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit108.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit536.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit604.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit433.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit450.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit53.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit212.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit525.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit960.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit58.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit499.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit773.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit598.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit1107.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit679.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit895.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit357.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit80.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit933.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit622.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit320.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit872.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit65.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit567.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit226.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit750.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit538.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit195.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit990.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit1072.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit854.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit25.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit86.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit589.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit514.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit912.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit219.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit760.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit910.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit267.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit417.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit35.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit390.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit225.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit45.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit60.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels/circuit789.txt
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/images/circuit780.jpg
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/images/circuit537.jpg
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/images/circuit750.jpg
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/images/circuit499.jpg
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/images/circuit1036.jpg
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/images/circuit801.jpg
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/images/circuit635.jpg
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/images/circuit318.jpg
/kaggle/input/yolo-component-data/YOLO_component-dataset/val/images/circuit1015.jpg

In [1]:
!pip install ultralytics --quiet

import os, time, pandas as pd, torch, gc
from ultralytics import YOLO

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 29.8 MB/s eta 0:00:0000:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 4.8 MB/s eta 0:00:00:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 99.6 MB/s eta 0:00:00:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 78.6 MB/s eta 0:00:00:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 43.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.6 MB/s eta 0:00:00:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 5.8 MB/s eta 0:00:00:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 31.2 MB/s eta 0:00:00:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 13.5 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 2.0 MB/s eta 0:00:00:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 83.2 MB/s eta 0:00:00:00:0100:01
Creating new Ultralytics Settings v0.0.6 file ✅
View Ultralytics Settings with 'yolo settings' or at '/root/.config/Ultralytics/settings.json'
Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/quickstart/#ultralytics-settings.

In [2]:
# ===============================
# Kaggle Notebook: YOLOv8 Ablation Study
# ===============================


# -------------------------------
# Dataset path
# -------------------------------
data_yaml = '/kaggle/input/yolo-component-data/YOLO_component-dataset/data.yaml'

# -------------------------------
# Base Parameters (default setup)
# -------------------------------
base_params = {
    "epochs": 32,
    "batch": 32,
    "lr0": 0.01,
    "weight_decay": 0.001,
    "optimizer": "SGD",
    "imgsz": 640,
    "dropout": 0.0,
    "freeze": 0,
    "activation": "SiLU"
}

# -------------------------------
# Initialize Results File
# -------------------------------
results_file = "ablation_results.csv"
if not os.path.exists(results_file):
    pd.DataFrame(columns=[
        "Case", "Experiment No", "Experiment Name",
        "Epochs", "Batch", "lr0", "Weight Decay", "Optimizer",
        "Image Size", "Dropout", "Freeze Layers", "Activation",
        "Training Time (s)", "Precision", "Recall", "mAP@0.5", "mAP@0.5:0.95"
    ]).to_csv(results_file, index=False)

# -------------------------------
# Logging Function
# -------------------------------
def log_result(case, exp_no, exp_name, params, results, train_time, error=False):
    df = pd.read_csv(results_file)

    if error or results is None:
        new_row = {
            "Case": case,
            "Experiment No": exp_no,
            "Experiment Name": exp_name,
            "Epochs": params["epochs"],
            "Batch": params["batch"],
            "lr0": params["lr0"],
            "Weight Decay": params["weight_decay"],
            "Optimizer": params["optimizer"],
            "Image Size": params["imgsz"],
            "Dropout": params["dropout"],
            "Freeze Layers": params["freeze"],
            "Activation": params["activation"],
            "Training Time (s)": "Error",
            "Precision": "Error",
            "Recall": "Error",
            "mAP@0.5": "Error",
            "mAP@0.5:0.95": "Error",
        }
    else:
        new_row = {
            "Case": case,
            "Experiment No": exp_no,
            "Experiment Name": exp_name,
            "Epochs": params["epochs"],
            "Batch": params["batch"],
            "lr0": params["lr0"],
            "Weight Decay": params["weight_decay"],
            "Optimizer": params["optimizer"],
            "Image Size": params["imgsz"],
            "Dropout": params["dropout"],
            "Freeze Layers": params["freeze"],
            "Activation": params["activation"],
            "Training Time (s)": round(train_time, 2),
            "Precision": results.results_dict["metrics/precision(B)"],
            "Recall": results.results_dict["metrics/recall(B)"],
            "mAP@0.5": results.results_dict["metrics/mAP50(B)"],
            "mAP@0.5:0.95": results.results_dict["metrics/mAP50-95(B)"],
        }

    df = pd.concat([df, pd.DataFrame([new_row])], ignore_index=True)
    df.to_csv(results_file, index=False)

# -------------------------------
# Run Ablation Function
# -------------------------------
def run_ablation(case_name, param_name, param_values):
    """
    Run experiments by varying param_name over param_values.
    """
    for i, val in enumerate(param_values, start=1):
        # copy base params
        params = base_params.copy()
        params[param_name] = val

        print(f"\n🚀 {case_name} | Experiment {i}: {param_name}={val}")
        gc.collect(); torch.cuda.empty_cache()
        model = YOLO("yolov8m.pt")

        start_time = time.time()
        try:
            results = model.train(
                data=data_yaml,
                epochs=params["epochs"],
                batch=params["batch"],
                lr0=params["lr0"],
                optimizer=params["optimizer"],
                imgsz=params["imgsz"],
                weight_decay=params["weight_decay"],
                dropout=params["dropout"],   # only works if dropout is supported
                freeze=params["freeze"]
            )
            end_time = time.time()
            log_result(case_name, i, f"{param_name}_{val}", params, results, end_time - start_time)

        except Exception as e:
            print(f"❌ Error in {param_name}={val}: {e}")
            log_result(case_name, i, f"{param_name}_{val}", params, None, 0, error=True)

    # show final table
    df = pd.read_csv(results_file)
    display(df)

In [4]:
# Case 4: Varying Dropout
run_ablation("Case 4: Dropout", "dropout", [0, 0.1, 0.2, 0.3, 0.5])

🚀 Case 4: Dropout | Experiment 1: dropout=0

Downloading https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov8m.pt to 'yolov8m.pt': 100%|██████████| 49.7M/49.7M [00:01<00:00, 33.9MB/s]

Ultralytics 8.3.185 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-component-data/YOLO_component-dataset/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8m.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/train, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.001, workers=8, workspace=None

Downloading https://ultralytics.com/assets/Arial.ttf to '/root/.config/Ultralytics/Arial.ttf': 100%|██████████| 755k/755k [00:00<00:00, 51.8MB/s]

Overriding model.yaml nc=80 with nc=6

                   from  n    params  module                                       arguments
  0                  -1  1      1392  ultralytics.nn.modules.conv.Conv             [3, 48, 3, 2]
  1                  -1  1     41664  ultralytics.nn.modules.conv.Conv             [48, 96, 3, 2]
  2                  -1  2    111360  ultralytics.nn.modules.block.C2f             [96, 96, 2, True]
  3                  -1  1    166272  ultralytics.nn.modules.conv.Conv             [96, 192, 3, 2]
  4                  -1  4    813312  ultralytics.nn.modules.block.C2f             [192, 192, 4, True]
  5                  -1  1    664320  ultralytics.nn.modules.conv.Conv             [192, 384, 3, 2]
  6                  -1  4   3248640  ultralytics.nn.modules.block.C2f             [384, 384, 4, True]
  7                  -1  1   1991808  ultralytics.nn.modules.conv.Conv             [384, 576, 3, 2]
  8                  -1  2   3985920  ultralytics.nn.modules.block.C2f             [576, 576, 2, True]
  9                  -1  1    831168  ultralytics.nn.modules.block.SPPF            [576, 576, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  2   1993728  ultralytics.nn.modules.block.C2f             [960, 384, 2]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  2    517632  ultralytics.nn.modules.block.C2f             [576, 192, 2]
 16                  -1  1    332160  ultralytics.nn.modules.conv.Conv             [192, 192, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  2   1846272  ultralytics.nn.modules.block.C2f             [576, 384, 2]
 19                  -1  1   1327872  ultralytics.nn.modules.conv.Conv             [384, 384, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  2   4207104  ultralytics.nn.modules.block.C2f             [960, 576, 2]
 22        [15, 18, 21]  1   3779170  ultralytics.nn.modules.head.Detect           [6, [192, 384, 576]]
Model summary: 169 layers, 25,859,794 parameters, 25,859,778 gradients, 79.1 GFLOPs

Transferred 469/475 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...

Downloading https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11n.pt to 'yolo11n.pt': 100%|██████████| 5.35M/5.35M [00:00<00:00, 143MB/s]

AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 6.2±5.3 MB/s, size: 51.9 KB)

train: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/train/labels... 919 images, 0 backgrounds, 0 corrupt: 100%|██████████| 919/919 [00:06<00:00, 145.16it/s]

WARNING ⚠️ train: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 3.9±1.7 MB/s, size: 35.4 KB)

val: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels... 230 images, 0 backgrounds, 0 corrupt: 100%|██████████| 230/230 [00:01<00:00, 138.98it/s]

WARNING ⚠️ val: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/val is not writeable, cache not saved.

Plotting labels to runs/detect/train/labels.jpg...
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 77 weight(decay=0.0), 84 weight(decay=0.001), 83 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs/detect/train
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       1/32      13.7G      2.554      3.684       2.06        249        640: 100%|██████████| 29/29 [00:32<00:00,  1.14s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:03<00:00,  1.05it/s]

                   all        230       1440       0.67      0.688      0.714      0.407

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       2/32      13.9G      1.388      1.031      1.284        222        640: 100%|██████████| 29/29 [00:32<00:00,  1.11s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.57it/s]

                   all        230       1440       0.91      0.943      0.972      0.576

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       3/32      13.9G      1.354     0.8712      1.258        203        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.957      0.975      0.979      0.623

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       4/32      13.9G      1.343     0.7808      1.244        242        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440       0.98       0.98      0.988      0.651

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       5/32      13.9G        1.3     0.6796      1.231        250        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.974      0.964      0.982      0.648

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       6/32      13.9G      1.286     0.6039      1.235        251        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.984      0.983      0.986      0.627

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       7/32      13.9G      1.259     0.5836      1.216        257        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440       0.98      0.982      0.982       0.64

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       8/32      13.9G      1.262     0.5733      1.217        273        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440      0.976       0.98      0.982      0.605

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       9/32      13.9G      1.258     0.5537      1.221        265        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.969      0.978      0.984      0.655

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      10/32      13.9G      1.232     0.5539      1.202        233        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440      0.988      0.982      0.987      0.633

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      11/32      13.9G      1.223     0.5346      1.214        282        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.60it/s]

                   all        230       1440      0.989      0.984      0.988      0.655

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      12/32      13.9G      1.217     0.5251      1.219        205        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.987      0.986      0.988      0.662

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      13/32      13.9G      1.186     0.5148      1.194        219        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.61it/s]

                   all        230       1440       0.99      0.986      0.989      0.652

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      14/32      13.9G      1.191     0.5082      1.204        239        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440      0.985      0.985      0.986       0.66

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      15/32      13.9G      1.197     0.4964      1.214        254        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.61it/s]

                   all        230       1440      0.982      0.983      0.987      0.672

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      16/32      13.9G      1.158     0.4899      1.211        231        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.61it/s]

                   all        230       1440      0.985      0.989      0.987      0.676

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      17/32      13.9G       1.16     0.4824      1.211        275        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.981       0.98      0.986      0.671

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      18/32      13.9G       1.15     0.4686      1.222        261        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.59it/s]

                   all        230       1440      0.987      0.983      0.985      0.678

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      19/32      13.9G      1.145     0.4676      1.219        187        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.61it/s]

                   all        230       1440      0.987      0.984      0.987      0.669

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      20/32      13.9G      1.118     0.4547       1.18        223        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.59it/s]

                   all        230       1440      0.989      0.983      0.988      0.677

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      21/32      13.9G      1.107     0.4494      1.184        232        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440      0.989      0.989      0.987      0.686

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      22/32      13.9G      1.095     0.4451      1.168        242        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.61it/s]

                   all        230       1440      0.988      0.986      0.988      0.684

Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      23/32      13.9G      1.089     0.4029      1.238        147        640: 100%|██████████| 29/29 [00:33<00:00,  1.14s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.60it/s]

                   all        230       1440       0.99      0.989      0.988       0.68

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      24/32      13.9G      1.068     0.3902       1.23        127        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.61it/s]

                   all        230       1440      0.989      0.986      0.987      0.678

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      25/32      13.9G      1.051     0.3857      1.227        121        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.61it/s]

                   all        230       1440      0.987      0.987      0.988       0.67

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      26/32      13.9G      1.031      0.373      1.204        141        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.987      0.989      0.987      0.685

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      27/32      13.9G      1.016      0.371      1.199        138        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.60it/s]

                   all        230       1440       0.99      0.989      0.986      0.687

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      28/32      13.9G      1.004     0.3684      1.199        136        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440       0.99      0.989      0.988      0.689

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      29/32      13.9G     0.9873     0.3578      1.192        145        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.61it/s]

                   all        230       1440      0.992      0.989      0.988       0.69

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      30/32      13.9G     0.9779     0.3549      1.177        140        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.991       0.99      0.987      0.685

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      31/32      13.9G     0.9527     0.3435      1.178        124        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.991       0.99      0.987      0.691

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      32/32      13.9G     0.9411      0.342      1.159        142        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.60it/s]

                   all        230       1440      0.991      0.989      0.988      0.691

32 epochs completed in 0.317 hours.
Optimizer stripped from runs/detect/train/weights/last.pt, 52.0MB
Optimizer stripped from runs/detect/train/weights/best.pt, 52.0MB

Validating runs/detect/train/weights/best.pt...
Ultralytics 8.3.185 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
Model summary (fused): 92 layers, 25,843,234 parameters, 0 gradients, 78.7 GFLOPs

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:04<00:00,  1.07s/it]
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        230       1440      0.991      0.991      0.987      0.692
     DC Voltage Source        103        144          1      0.979      0.984       0.76
              Resistor        183        605      0.985      0.992      0.987      0.649
        Current Source        113        150      0.982          1      0.984      0.739
              Inductor        117        177      0.994      0.988       0.99      0.647
             Capacitor        115        184      0.993      0.989      0.985      0.639
     AC Voltage Source         65        180      0.993      0.994      0.995      0.717
Speed: 0.1ms preprocess, 8.3ms inference, 0.0ms loss, 5.3ms postprocess per image
Results saved to runs/detect/train

🚀 Case 4: Dropout | Experiment 2: dropout=0.1
Ultralytics 8.3.185 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-component-data/YOLO_component-dataset/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.1, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8m.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train2, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/train2, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.001, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=6

                   from  n    params  module                                       arguments
  0                  -1  1      1392  ultralytics.nn.modules.conv.Conv             [3, 48, 3, 2]
  1                  -1  1     41664  ultralytics.nn.modules.conv.Conv             [48, 96, 3, 2]
  2                  -1  2    111360  ultralytics.nn.modules.block.C2f             [96, 96, 2, True]
  3                  -1  1    166272  ultralytics.nn.modules.conv.Conv             [96, 192, 3, 2]
  4                  -1  4    813312  ultralytics.nn.modules.block.C2f             [192, 192, 4, True]
  5                  -1  1    664320  ultralytics.nn.modules.conv.Conv             [192, 384, 3, 2]
  6                  -1  4   3248640  ultralytics.nn.modules.block.C2f             [384, 384, 4, True]
  7                  -1  1   1991808  ultralytics.nn.modules.conv.Conv             [384, 576, 3, 2]
  8                  -1  2   3985920  ultralytics.nn.modules.block.C2f             [576, 576, 2, True]
  9                  -1  1    831168  ultralytics.nn.modules.block.SPPF            [576, 576, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  2   1993728  ultralytics.nn.modules.block.C2f             [960, 384, 2]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  2    517632  ultralytics.nn.modules.block.C2f             [576, 192, 2]
 16                  -1  1    332160  ultralytics.nn.modules.conv.Conv             [192, 192, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  2   1846272  ultralytics.nn.modules.block.C2f             [576, 384, 2]
 19                  -1  1   1327872  ultralytics.nn.modules.conv.Conv             [384, 384, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  2   4207104  ultralytics.nn.modules.block.C2f             [960, 576, 2]
 22        [15, 18, 21]  1   3779170  ultralytics.nn.modules.head.Detect           [6, [192, 384, 576]]
Model summary: 169 layers, 25,859,794 parameters, 25,859,778 gradients, 79.1 GFLOPs

Transferred 469/475 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 46.7±37.7 MB/s, size: 51.9 KB)

train: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/train/labels... 919 images, 0 backgrounds, 0 corrupt: 100%|██████████| 919/919 [00:01<00:00, 532.84it/s]

WARNING ⚠️ train: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 29.4±14.3 MB/s, size: 35.4 KB)

val: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels... 230 images, 0 backgrounds, 0 corrupt: 100%|██████████| 230/230 [00:00<00:00, 353.02it/s]

WARNING ⚠️ val: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/val is not writeable, cache not saved.

Plotting labels to runs/detect/train2/labels.jpg...
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 77 weight(decay=0.0), 84 weight(decay=0.001), 83 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs/detect/train2
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       1/32        14G      2.554      3.684       2.06        249        640: 100%|██████████| 29/29 [00:32<00:00,  1.12s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:03<00:00,  1.32it/s]

                   all        230       1440       0.67      0.688      0.714      0.407

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       2/32      13.9G      1.388      1.031      1.284        222        640: 100%|██████████| 29/29 [00:32<00:00,  1.11s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.57it/s]

                   all        230       1440       0.91      0.943      0.972      0.576

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       3/32      13.9G      1.354     0.8712      1.258        203        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440      0.957      0.975      0.979      0.623

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       4/32      13.9G      1.343     0.7808      1.244        242        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440       0.98       0.98      0.988      0.651

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       5/32      13.9G        1.3     0.6796      1.231        250        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.974      0.964      0.982      0.648

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       6/32      13.9G      1.286     0.6039      1.235        251        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440      0.984      0.983      0.986      0.627

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       7/32      13.9G      1.259     0.5836      1.216        257        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440       0.98      0.982      0.982       0.64

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       8/32      13.9G      1.262     0.5733      1.217        273        640: 100%|██████████| 29/29 [00:32<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.61it/s]

                   all        230       1440      0.976       0.98      0.982      0.605

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       9/32      13.9G      1.258     0.5537      1.221        265        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.60it/s]

                   all        230       1440      0.969      0.978      0.984      0.655

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      10/32      13.9G      1.232     0.5539      1.202        233        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.988      0.982      0.987      0.633

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      11/32      13.4G      1.223     0.5346      1.214        282        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.989      0.984      0.988      0.655

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      12/32        14G      1.217     0.5251      1.219        205        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.60it/s]

                   all        230       1440      0.987      0.986      0.988      0.662

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      13/32      13.9G      1.186     0.5148      1.194        219        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440       0.99      0.986      0.989      0.652

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      14/32        14G      1.191     0.5082      1.204        239        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.985      0.985      0.986       0.66

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      15/32      13.9G      1.197     0.4964      1.214        254        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.982      0.983      0.987      0.672

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      16/32      13.9G      1.158     0.4899      1.211        231        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.61it/s]

                   all        230       1440      0.985      0.989      0.987      0.676

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      17/32      13.9G       1.16     0.4824      1.211        275        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.981       0.98      0.986      0.671

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      18/32      13.9G       1.15     0.4686      1.222        261        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440      0.987      0.983      0.985      0.678

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      19/32      13.9G      1.145     0.4676      1.219        187        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.987      0.984      0.987      0.669

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      20/32      13.9G      1.118     0.4547       1.18        223        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.989      0.983      0.988      0.677

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      21/32      13.9G      1.107     0.4494      1.184        232        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440      0.989      0.989      0.987      0.686

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      22/32        14G      1.095     0.4451      1.168        242        640: 100%|██████████| 29/29 [00:32<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.988      0.986      0.988      0.684

Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      23/32      13.9G      1.089     0.4029      1.238        147        640: 100%|██████████| 29/29 [00:33<00:00,  1.14s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440       0.99      0.989      0.988       0.68

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      24/32      13.9G      1.068     0.3902       1.23        127        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.989      0.986      0.987      0.678

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      25/32      13.9G      1.051     0.3857      1.227        121        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.987      0.987      0.988       0.67

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      26/32      13.9G      1.031      0.373      1.204        141        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.987      0.989      0.987      0.685

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      27/32      13.9G      1.016      0.371      1.199        138        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440       0.99      0.989      0.986      0.687

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      28/32      13.9G      1.004     0.3684      1.199        136        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440       0.99      0.989      0.988      0.689

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      29/32      13.9G     0.9873     0.3578      1.192        145        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.61it/s]

                   all        230       1440      0.992      0.989      0.988       0.69

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      30/32      13.9G     0.9779     0.3549      1.177        140        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.991       0.99      0.987      0.685

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      31/32      13.9G     0.9527     0.3435      1.178        124        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.991       0.99      0.987      0.691

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      32/32      13.9G     0.9411      0.342      1.159        142        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440      0.991      0.989      0.988      0.691

32 epochs completed in 0.317 hours.
Optimizer stripped from runs/detect/train2/weights/last.pt, 52.0MB
Optimizer stripped from runs/detect/train2/weights/best.pt, 52.0MB

Validating runs/detect/train2/weights/best.pt...
Ultralytics 8.3.185 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
Model summary (fused): 92 layers, 25,843,234 parameters, 0 gradients, 78.7 GFLOPs

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:04<00:00,  1.09s/it]
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        230       1440      0.991      0.991      0.987      0.692
     DC Voltage Source        103        144          1      0.979      0.984       0.76
              Resistor        183        605      0.985      0.992      0.987      0.649
        Current Source        113        150      0.982          1      0.984      0.739
              Inductor        117        177      0.994      0.988       0.99      0.647
             Capacitor        115        184      0.993      0.989      0.985      0.639
     AC Voltage Source         65        180      0.993      0.994      0.995      0.717
Speed: 0.1ms preprocess, 8.3ms inference, 0.0ms loss, 4.5ms postprocess per image
Results saved to runs/detect/train2

🚀 Case 4: Dropout | Experiment 3: dropout=0.2
Ultralytics 8.3.185 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-component-data/YOLO_component-dataset/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.2, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8m.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train3, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/train3, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.001, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=6

                   from  n    params  module                                       arguments
  0                  -1  1      1392  ultralytics.nn.modules.conv.Conv             [3, 48, 3, 2]
  1                  -1  1     41664  ultralytics.nn.modules.conv.Conv             [48, 96, 3, 2]
  2                  -1  2    111360  ultralytics.nn.modules.block.C2f             [96, 96, 2, True]
  3                  -1  1    166272  ultralytics.nn.modules.conv.Conv             [96, 192, 3, 2]
  4                  -1  4    813312  ultralytics.nn.modules.block.C2f             [192, 192, 4, True]
  5                  -1  1    664320  ultralytics.nn.modules.conv.Conv             [192, 384, 3, 2]
  6                  -1  4   3248640  ultralytics.nn.modules.block.C2f             [384, 384, 4, True]
  7                  -1  1   1991808  ultralytics.nn.modules.conv.Conv             [384, 576, 3, 2]
  8                  -1  2   3985920  ultralytics.nn.modules.block.C2f             [576, 576, 2, True]
  9                  -1  1    831168  ultralytics.nn.modules.block.SPPF            [576, 576, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  2   1993728  ultralytics.nn.modules.block.C2f             [960, 384, 2]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  2    517632  ultralytics.nn.modules.block.C2f             [576, 192, 2]
 16                  -1  1    332160  ultralytics.nn.modules.conv.Conv             [192, 192, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  2   1846272  ultralytics.nn.modules.block.C2f             [576, 384, 2]
 19                  -1  1   1327872  ultralytics.nn.modules.conv.Conv             [384, 384, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  2   4207104  ultralytics.nn.modules.block.C2f             [960, 576, 2]
 22        [15, 18, 21]  1   3779170  ultralytics.nn.modules.head.Detect           [6, [192, 384, 576]]
Model summary: 169 layers, 25,859,794 parameters, 25,859,778 gradients, 79.1 GFLOPs

Transferred 469/475 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 43.7±40.9 MB/s, size: 51.9 KB)

train: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/train/labels... 919 images, 0 backgrounds, 0 corrupt: 100%|██████████| 919/919 [00:01<00:00, 478.56it/s]

WARNING ⚠️ train: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 26.5±11.9 MB/s, size: 35.4 KB)

val: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels... 230 images, 0 backgrounds, 0 corrupt: 100%|██████████| 230/230 [00:00<00:00, 323.13it/s]

WARNING ⚠️ val: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/val is not writeable, cache not saved.
Plotting labels to runs/detect/train3/labels.jpg...
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 77 weight(decay=0.0), 84 weight(decay=0.001), 83 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs/detect/train3
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       1/32        14G      2.554      3.684       2.06        249        640: 100%|██████████| 29/29 [00:32<00:00,  1.12s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:03<00:00,  1.33it/s]

                   all        230       1440       0.67      0.688      0.714      0.407

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       2/32      13.9G      1.388      1.031      1.284        222        640: 100%|██████████| 29/29 [00:32<00:00,  1.11s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.60it/s]

                   all        230       1440       0.91      0.943      0.972      0.576

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       3/32      13.9G      1.354     0.8712      1.258        203        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.59it/s]

                   all        230       1440      0.957      0.975      0.979      0.623

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       4/32      13.9G      1.343     0.7808      1.244        242        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440       0.98       0.98      0.988      0.651

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       5/32      13.9G        1.3     0.6796      1.231        250        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.974      0.964      0.982      0.648

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       6/32      13.9G      1.286     0.6039      1.235        251        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.51it/s]

                   all        230       1440      0.984      0.983      0.986      0.627

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       7/32      13.9G      1.259     0.5836      1.216        257        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440       0.98      0.982      0.982       0.64

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       8/32      13.9G      1.262     0.5733      1.217        273        640: 100%|██████████| 29/29 [00:32<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.976       0.98      0.982      0.605

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       9/32      13.9G      1.258     0.5537      1.221        265        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.969      0.978      0.984      0.655

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      10/32      13.9G      1.232     0.5539      1.202        233        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.988      0.982      0.987      0.633

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      11/32        14G      1.223     0.5346      1.214        282        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.989      0.984      0.988      0.655

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      12/32      13.9G      1.217     0.5251      1.219        205        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.987      0.986      0.988      0.662

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      13/32      13.9G      1.186     0.5148      1.194        219        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440       0.99      0.986      0.989      0.652

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      14/32      13.9G      1.191     0.5082      1.204        239        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.985      0.985      0.986       0.66

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      15/32      13.9G      1.197     0.4964      1.214        254        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.982      0.983      0.987      0.672

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      16/32      13.9G      1.158     0.4899      1.211        231        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.985      0.989      0.987      0.676

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      17/32      13.9G       1.16     0.4824      1.211        275        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.981       0.98      0.986      0.671

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      18/32      13.9G       1.15     0.4686      1.222        261        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.987      0.983      0.985      0.678

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      19/32      13.9G      1.145     0.4676      1.219        187        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440      0.987      0.984      0.987      0.669

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      20/32      13.9G      1.118     0.4547       1.18        223        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.989      0.983      0.988      0.677

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      21/32      13.9G      1.107     0.4494      1.184        232        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440      0.989      0.989      0.987      0.686

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      22/32      13.9G      1.095     0.4451      1.168        242        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.988      0.986      0.988      0.684

Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      23/32      13.9G      1.089     0.4029      1.238        147        640: 100%|██████████| 29/29 [00:33<00:00,  1.14s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440       0.99      0.989      0.988       0.68

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      24/32        14G      1.068     0.3902       1.23        127        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.989      0.986      0.987      0.678

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      25/32      13.9G      1.051     0.3857      1.227        121        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440      0.987      0.987      0.988       0.67

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      26/32        14G      1.031      0.373      1.204        141        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.61it/s]

                   all        230       1440      0.987      0.989      0.987      0.685

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      27/32      13.9G      1.016      0.371      1.199        138        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440       0.99      0.989      0.986      0.687

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      28/32      13.9G      1.004     0.3684      1.199        136        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.60it/s]

                   all        230       1440       0.99      0.989      0.988      0.689

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      29/32      13.9G     0.9873     0.3578      1.192        145        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440      0.992      0.989      0.988       0.69

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      30/32      13.9G     0.9779     0.3549      1.177        140        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.60it/s]

                   all        230       1440      0.991       0.99      0.987      0.685

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      31/32      13.9G     0.9527     0.3435      1.178        124        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.991       0.99      0.987      0.691

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      32/32      13.9G     0.9411      0.342      1.159        142        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.991      0.989      0.988      0.691

32 epochs completed in 0.317 hours.
Optimizer stripped from runs/detect/train3/weights/last.pt, 52.0MB
Optimizer stripped from runs/detect/train3/weights/best.pt, 52.0MB

Validating runs/detect/train3/weights/best.pt...
Ultralytics 8.3.185 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
Model summary (fused): 92 layers, 25,843,234 parameters, 0 gradients, 78.7 GFLOPs

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:04<00:00,  1.05s/it]
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        230       1440      0.991      0.991      0.987      0.692
     DC Voltage Source        103        144          1      0.979      0.984       0.76
              Resistor        183        605      0.985      0.992      0.987      0.649
        Current Source        113        150      0.982          1      0.984      0.739
              Inductor        117        177      0.994      0.988       0.99      0.647
             Capacitor        115        184      0.993      0.989      0.985      0.639
     AC Voltage Source         65        180      0.993      0.994      0.995      0.717
Speed: 0.1ms preprocess, 8.1ms inference, 0.0ms loss, 2.3ms postprocess per image
Results saved to runs/detect/train3

🚀 Case 4: Dropout | Experiment 4: dropout=0.3
Ultralytics 8.3.185 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-component-data/YOLO_component-dataset/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.3, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8m.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train4, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/train4, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.001, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=6

                   from  n    params  module                                       arguments
  0                  -1  1      1392  ultralytics.nn.modules.conv.Conv             [3, 48, 3, 2]
  1                  -1  1     41664  ultralytics.nn.modules.conv.Conv             [48, 96, 3, 2]
  2                  -1  2    111360  ultralytics.nn.modules.block.C2f             [96, 96, 2, True]
  3                  -1  1    166272  ultralytics.nn.modules.conv.Conv             [96, 192, 3, 2]
  4                  -1  4    813312  ultralytics.nn.modules.block.C2f             [192, 192, 4, True]
  5                  -1  1    664320  ultralytics.nn.modules.conv.Conv             [192, 384, 3, 2]
  6                  -1  4   3248640  ultralytics.nn.modules.block.C2f             [384, 384, 4, True]
  7                  -1  1   1991808  ultralytics.nn.modules.conv.Conv             [384, 576, 3, 2]
  8                  -1  2   3985920  ultralytics.nn.modules.block.C2f             [576, 576, 2, True]
  9                  -1  1    831168  ultralytics.nn.modules.block.SPPF            [576, 576, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  2   1993728  ultralytics.nn.modules.block.C2f             [960, 384, 2]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  2    517632  ultralytics.nn.modules.block.C2f             [576, 192, 2]
 16                  -1  1    332160  ultralytics.nn.modules.conv.Conv             [192, 192, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  2   1846272  ultralytics.nn.modules.block.C2f             [576, 384, 2]
 19                  -1  1   1327872  ultralytics.nn.modules.conv.Conv             [384, 384, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  2   4207104  ultralytics.nn.modules.block.C2f             [960, 576, 2]
 22        [15, 18, 21]  1   3779170  ultralytics.nn.modules.head.Detect           [6, [192, 384, 576]]
Model summary: 169 layers, 25,859,794 parameters, 25,859,778 gradients, 79.1 GFLOPs

Transferred 469/475 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 55.4±39.5 MB/s, size: 51.9 KB)

train: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/train/labels... 919 images, 0 backgrounds, 0 corrupt: 100%|██████████| 919/919 [00:01<00:00, 579.15it/s]

WARNING ⚠️ train: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 27.8±15.2 MB/s, size: 35.4 KB)

val: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels... 230 images, 0 backgrounds, 0 corrupt: 100%|██████████| 230/230 [00:00<00:00, 356.90it/s]

WARNING ⚠️ val: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/val is not writeable, cache not saved.

Plotting labels to runs/detect/train4/labels.jpg...
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 77 weight(decay=0.0), 84 weight(decay=0.001), 83 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs/detect/train4
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       1/32      14.1G      2.554      3.684       2.06        249        640: 100%|██████████| 29/29 [00:32<00:00,  1.12s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:03<00:00,  1.32it/s]

                   all        230       1440       0.67      0.688      0.714      0.407

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       2/32      13.9G      1.388      1.031      1.284        222        640: 100%|██████████| 29/29 [00:32<00:00,  1.11s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.58it/s]

                   all        230       1440       0.91      0.943      0.972      0.576

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       3/32      13.9G      1.354     0.8712      1.258        203        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.61it/s]

                   all        230       1440      0.957      0.975      0.979      0.623

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       4/32      13.9G      1.343     0.7808      1.244        242        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440       0.98       0.98      0.988      0.651

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       5/32      13.9G        1.3     0.6796      1.231        250        640: 100%|██████████| 29/29 [00:32<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440      0.974      0.964      0.982      0.648

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       6/32      13.9G      1.286     0.6039      1.235        251        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.984      0.983      0.986      0.627

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       7/32      13.9G      1.259     0.5836      1.216        257        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440       0.98      0.982      0.982       0.64

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       8/32      13.9G      1.262     0.5733      1.217        273        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440      0.976       0.98      0.982      0.605

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       9/32      13.9G      1.258     0.5537      1.221        265        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.969      0.978      0.984      0.655

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      10/32      13.9G      1.232     0.5539      1.202        233        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.61it/s]

                   all        230       1440      0.988      0.982      0.987      0.633

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      11/32      13.9G      1.223     0.5346      1.214        282        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.989      0.984      0.988      0.655

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      12/32      13.9G      1.217     0.5251      1.219        205        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.987      0.986      0.988      0.662

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      13/32      13.9G      1.186     0.5148      1.194        219        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440       0.99      0.986      0.989      0.652

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      14/32      13.9G      1.191     0.5082      1.204        239        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.60it/s]

                   all        230       1440      0.985      0.985      0.986       0.66

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      15/32      13.9G      1.197     0.4964      1.214        254        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.982      0.983      0.987      0.672

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      16/32        14G      1.158     0.4899      1.211        231        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.985      0.989      0.987      0.676

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      17/32      13.9G       1.16     0.4824      1.211        275        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.981       0.98      0.986      0.671

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      18/32      13.9G       1.15     0.4686      1.222        261        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.987      0.983      0.985      0.678

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      19/32      13.9G      1.145     0.4676      1.219        187        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.59it/s]

                   all        230       1440      0.987      0.984      0.987      0.669

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      20/32      13.9G      1.118     0.4547       1.18        223        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440      0.989      0.983      0.988      0.677

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      21/32      13.9G      1.107     0.4494      1.184        232        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440      0.989      0.989      0.987      0.686

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      22/32      13.9G      1.095     0.4451      1.168        242        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.988      0.986      0.988      0.684

Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      23/32      13.9G      1.089     0.4029      1.238        147        640: 100%|██████████| 29/29 [00:33<00:00,  1.14s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440       0.99      0.989      0.988       0.68

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      24/32      13.9G      1.068     0.3902       1.23        127        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.59it/s]

                   all        230       1440      0.989      0.986      0.987      0.678

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      25/32      13.9G      1.051     0.3857      1.227        121        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.987      0.987      0.988       0.67

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      26/32        14G      1.031      0.373      1.204        141        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440      0.987      0.989      0.987      0.685

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      27/32      13.9G      1.016      0.371      1.199        138        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440       0.99      0.989      0.986      0.687

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      28/32        14G      1.004     0.3684      1.199        136        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.59it/s]

                   all        230       1440       0.99      0.989      0.988      0.689

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      29/32      13.9G     0.9873     0.3578      1.192        145        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440      0.992      0.989      0.988       0.69

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      30/32      13.9G     0.9779     0.3549      1.177        140        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.991       0.99      0.987      0.685

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      31/32      13.9G     0.9527     0.3435      1.178        124        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.991       0.99      0.987      0.691

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      32/32      13.9G     0.9411      0.342      1.159        142        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.61it/s]

                   all        230       1440      0.991      0.989      0.988      0.691

32 epochs completed in 0.317 hours.
Optimizer stripped from runs/detect/train4/weights/last.pt, 52.0MB
Optimizer stripped from runs/detect/train4/weights/best.pt, 52.0MB

Validating runs/detect/train4/weights/best.pt...
Ultralytics 8.3.185 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
Model summary (fused): 92 layers, 25,843,234 parameters, 0 gradients, 78.7 GFLOPs

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:03<00:00,  1.02it/s]
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        230       1440      0.991      0.991      0.987      0.692
     DC Voltage Source        103        144          1      0.979      0.984       0.76
              Resistor        183        605      0.985      0.992      0.987      0.649
        Current Source        113        150      0.982          1      0.984      0.739
              Inductor        117        177      0.994      0.988       0.99      0.647
             Capacitor        115        184      0.993      0.989      0.985      0.639
     AC Voltage Source         65        180      0.993      0.994      0.995      0.717
Speed: 0.1ms preprocess, 8.2ms inference, 0.0ms loss, 2.8ms postprocess per image
Results saved to runs/detect/train4

🚀 Case 4: Dropout | Experiment 5: dropout=0.5
Ultralytics 8.3.185 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-component-data/YOLO_component-dataset/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.5, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8m.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train5, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/train5, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.001, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=6

                   from  n    params  module                                       arguments
  0                  -1  1      1392  ultralytics.nn.modules.conv.Conv             [3, 48, 3, 2]
  1                  -1  1     41664  ultralytics.nn.modules.conv.Conv             [48, 96, 3, 2]
  2                  -1  2    111360  ultralytics.nn.modules.block.C2f             [96, 96, 2, True]
  3                  -1  1    166272  ultralytics.nn.modules.conv.Conv             [96, 192, 3, 2]
  4                  -1  4    813312  ultralytics.nn.modules.block.C2f             [192, 192, 4, True]
  5                  -1  1    664320  ultralytics.nn.modules.conv.Conv             [192, 384, 3, 2]
  6                  -1  4   3248640  ultralytics.nn.modules.block.C2f             [384, 384, 4, True]
  7                  -1  1   1991808  ultralytics.nn.modules.conv.Conv             [384, 576, 3, 2]
  8                  -1  2   3985920  ultralytics.nn.modules.block.C2f             [576, 576, 2, True]
  9                  -1  1    831168  ultralytics.nn.modules.block.SPPF            [576, 576, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  2   1993728  ultralytics.nn.modules.block.C2f             [960, 384, 2]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  2    517632  ultralytics.nn.modules.block.C2f             [576, 192, 2]
 16                  -1  1    332160  ultralytics.nn.modules.conv.Conv             [192, 192, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  2   1846272  ultralytics.nn.modules.block.C2f             [576, 384, 2]
 19                  -1  1   1327872  ultralytics.nn.modules.conv.Conv             [384, 384, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  2   4207104  ultralytics.nn.modules.block.C2f             [960, 576, 2]
 22        [15, 18, 21]  1   3779170  ultralytics.nn.modules.head.Detect           [6, [192, 384, 576]]
Model summary: 169 layers, 25,859,794 parameters, 25,859,778 gradients, 79.1 GFLOPs

Transferred 469/475 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 53.4±38.0 MB/s, size: 51.9 KB)

train: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/train/labels... 919 images, 0 backgrounds, 0 corrupt: 100%|██████████| 919/919 [00:02<00:00, 431.12it/s]

WARNING ⚠️ train: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 23.5±11.1 MB/s, size: 35.4 KB)

val: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels... 230 images, 0 backgrounds, 0 corrupt: 100%|██████████| 230/230 [00:00<00:00, 364.51it/s]

WARNING ⚠️ val: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/val is not writeable, cache not saved.

Plotting labels to runs/detect/train5/labels.jpg...
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 77 weight(decay=0.0), 84 weight(decay=0.001), 83 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs/detect/train5
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       1/32      14.1G      2.554      3.684       2.06        249        640: 100%|██████████| 29/29 [00:32<00:00,  1.12s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:03<00:00,  1.32it/s]

                   all        230       1440       0.67      0.688      0.714      0.407

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       2/32      13.9G      1.388      1.031      1.284        222        640: 100%|██████████| 29/29 [00:32<00:00,  1.11s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.57it/s]

                   all        230       1440       0.91      0.943      0.972      0.576

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       3/32      13.9G      1.354     0.8712      1.258        203        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.60it/s]

                   all        230       1440      0.957      0.975      0.979      0.623

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       4/32      13.9G      1.343     0.7808      1.244        242        640: 100%|██████████| 29/29 [00:32<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440       0.98       0.98      0.988      0.651

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       5/32      13.9G        1.3     0.6796      1.231        250        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440      0.974      0.964      0.982      0.648

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       6/32      13.9G      1.286     0.6039      1.235        251        640: 100%|██████████| 29/29 [00:32<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.61it/s]

                   all        230       1440      0.984      0.983      0.986      0.627

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       7/32      13.9G      1.259     0.5836      1.216        257        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.61it/s]

                   all        230       1440       0.98      0.982      0.982       0.64

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       8/32      13.9G      1.262     0.5733      1.217        273        640: 100%|██████████| 29/29 [00:32<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.976       0.98      0.982      0.605

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       9/32      13.9G      1.258     0.5537      1.221        265        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440      0.969      0.978      0.984      0.655

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      10/32      13.9G      1.232     0.5539      1.202        233        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.61it/s]

                   all        230       1440      0.988      0.982      0.987      0.633

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      11/32      13.9G      1.223     0.5346      1.214        282        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.61it/s]

                   all        230       1440      0.989      0.984      0.988      0.655

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      12/32      13.9G      1.217     0.5251      1.219        205        640: 100%|██████████| 29/29 [00:32<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440      0.987      0.986      0.988      0.662

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      13/32      13.9G      1.186     0.5148      1.194        219        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440       0.99      0.986      0.989      0.652

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      14/32      13.9G      1.191     0.5082      1.204        239        640: 100%|██████████| 29/29 [00:32<00:00,  1.11s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.60it/s]

                   all        230       1440      0.985      0.985      0.986       0.66

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      15/32      13.9G      1.197     0.4964      1.214        254        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.61it/s]

                   all        230       1440      0.982      0.983      0.987      0.672

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      16/32      13.9G      1.158     0.4899      1.211        231        640: 100%|██████████| 29/29 [00:32<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440      0.985      0.989      0.987      0.676

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      17/32      13.9G       1.16     0.4824      1.211        275        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.61it/s]

                   all        230       1440      0.981       0.98      0.986      0.671

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      18/32      13.9G       1.15     0.4686      1.222        261        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.60it/s]

                   all        230       1440      0.987      0.983      0.985      0.678

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      19/32      13.9G      1.145     0.4676      1.219        187        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.61it/s]

                   all        230       1440      0.987      0.984      0.987      0.669

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      20/32      13.9G      1.118     0.4547       1.18        223        640: 100%|██████████| 29/29 [00:32<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440      0.989      0.983      0.988      0.677

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      21/32      13.9G      1.107     0.4494      1.184        232        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.989      0.989      0.987      0.686

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      22/32      13.9G      1.095     0.4451      1.168        242        640: 100%|██████████| 29/29 [00:32<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.61it/s]

                   all        230       1440      0.988      0.986      0.988      0.684

Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      23/32      13.9G      1.089     0.4029      1.238        147        640: 100%|██████████| 29/29 [00:33<00:00,  1.14s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.61it/s]

                   all        230       1440       0.99      0.989      0.988       0.68

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      24/32      13.9G      1.068     0.3902       1.23        127        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.61it/s]

                   all        230       1440      0.989      0.986      0.987      0.678

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      25/32      13.9G      1.051     0.3857      1.227        121        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.987      0.987      0.988       0.67

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      26/32      13.9G      1.031      0.373      1.204        141        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.61it/s]

                   all        230       1440      0.987      0.989      0.987      0.685

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      27/32      13.9G      1.016      0.371      1.199        138        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.60it/s]

                   all        230       1440       0.99      0.989      0.986      0.687

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      28/32      13.9G      1.004     0.3684      1.199        136        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440       0.99      0.989      0.988      0.689

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      29/32      13.9G     0.9873     0.3578      1.192        145        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.60it/s]

                   all        230       1440      0.992      0.989      0.988       0.69

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      30/32      13.9G     0.9779     0.3549      1.177        140        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440      0.991       0.99      0.987      0.685

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      31/32      13.9G     0.9527     0.3435      1.178        124        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440      0.991       0.99      0.987      0.691

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      32/32      13.9G     0.9411      0.342      1.159        142        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.61it/s]

                   all        230       1440      0.991      0.989      0.988      0.691

32 epochs completed in 0.318 hours.
Optimizer stripped from runs/detect/train5/weights/last.pt, 52.0MB
Optimizer stripped from runs/detect/train5/weights/best.pt, 52.0MB

Validating runs/detect/train5/weights/best.pt...
Ultralytics 8.3.185 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
Model summary (fused): 92 layers, 25,843,234 parameters, 0 gradients, 78.7 GFLOPs

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:03<00:00,  1.00it/s]
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        230       1440      0.991      0.991      0.987      0.692
     DC Voltage Source        103        144          1      0.979      0.984       0.76
              Resistor        183        605      0.985      0.992      0.987      0.649
        Current Source        113        150      0.982          1      0.984      0.739
              Inductor        117        177      0.994      0.988       0.99      0.647
             Capacitor        115        184      0.993      0.989      0.985      0.639
     AC Voltage Source         65        180      0.993      0.994      0.995      0.717
Speed: 0.1ms preprocess, 8.2ms inference, 0.0ms loss, 2.8ms postprocess per image
Results saved to runs/detect/train5

,Case,Experiment No,Experiment Name,Epochs,Batch,lr0,Weight Decay,Optimizer,Image Size,Dropout,Freeze Layers,Activation,Training Time (s),Precision,Recall,mAP@0.5,mAP@0.5:0.95
0,Case 4: Dropout,1,dropout_0,32,32,0.01,0.001,SGD,640,0.0,0,SiLU,1176.32,0.991306,0.990508,0.987335,0.69197
1,Case 4: Dropout,2,dropout_0.1,32,32,0.01,0.001,SGD,640,0.1,0,SiLU,1161.46,0.991306,0.990508,0.987335,0.69197
2,Case 4: Dropout,3,dropout_0.2,32,32,0.01,0.001,SGD,640,0.2,0,SiLU,1161.13,0.991306,0.990508,0.987335,0.69197
3,Case 4: Dropout,4,dropout_0.3,32,32,0.01,0.001,SGD,640,0.3,0,SiLU,1160.67,0.991306,0.990508,0.987335,0.69197
4,Case 4: Dropout,5,dropout_0.5,32,32,0.01,0.001,SGD,640,0.5,0,SiLU,1164.58,0.991306,0.990508,0.987335,0.69197

In [5]:
# Case 6: Different Optimizers
run_ablation("Case 6: Optimizer", "optimizer", ["SGD", "Adam", "AdamW", "RMSProp", "Adamax"])

🚀 Case 6: Optimizer | Experiment 1: optimizer=SGD
Ultralytics 8.3.185 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-component-data/YOLO_component-dataset/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8m.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train6, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/train6, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.001, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=6

                   from  n    params  module                                       arguments
  0                  -1  1      1392  ultralytics.nn.modules.conv.Conv             [3, 48, 3, 2]
  1                  -1  1     41664  ultralytics.nn.modules.conv.Conv             [48, 96, 3, 2]
  2                  -1  2    111360  ultralytics.nn.modules.block.C2f             [96, 96, 2, True]
  3                  -1  1    166272  ultralytics.nn.modules.conv.Conv             [96, 192, 3, 2]
  4                  -1  4    813312  ultralytics.nn.modules.block.C2f             [192, 192, 4, True]
  5                  -1  1    664320  ultralytics.nn.modules.conv.Conv             [192, 384, 3, 2]
  6                  -1  4   3248640  ultralytics.nn.modules.block.C2f             [384, 384, 4, True]
  7                  -1  1   1991808  ultralytics.nn.modules.conv.Conv             [384, 576, 3, 2]
  8                  -1  2   3985920  ultralytics.nn.modules.block.C2f             [576, 576, 2, True]
  9                  -1  1    831168  ultralytics.nn.modules.block.SPPF            [576, 576, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  2   1993728  ultralytics.nn.modules.block.C2f             [960, 384, 2]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  2    517632  ultralytics.nn.modules.block.C2f             [576, 192, 2]
 16                  -1  1    332160  ultralytics.nn.modules.conv.Conv             [192, 192, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  2   1846272  ultralytics.nn.modules.block.C2f             [576, 384, 2]
 19                  -1  1   1327872  ultralytics.nn.modules.conv.Conv             [384, 384, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  2   4207104  ultralytics.nn.modules.block.C2f             [960, 576, 2]
 22        [15, 18, 21]  1   3779170  ultralytics.nn.modules.head.Detect           [6, [192, 384, 576]]
Model summary: 169 layers, 25,859,794 parameters, 25,859,778 gradients, 79.1 GFLOPs

Transferred 469/475 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 52.6±35.4 MB/s, size: 51.9 KB)

train: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/train/labels... 919 images, 0 backgrounds, 0 corrupt: 100%|██████████| 919/919 [00:01<00:00, 505.92it/s]

WARNING ⚠️ train: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 31.3±9.7 MB/s, size: 35.4 KB)

val: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels... 230 images, 0 backgrounds, 0 corrupt: 100%|██████████| 230/230 [00:00<00:00, 341.58it/s]

WARNING ⚠️ val: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/val is not writeable, cache not saved.

Plotting labels to runs/detect/train6/labels.jpg...
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 77 weight(decay=0.0), 84 weight(decay=0.001), 83 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs/detect/train6
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       1/32      13.7G      2.554      3.684       2.06        249        640: 100%|██████████| 29/29 [00:32<00:00,  1.12s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.33it/s]

                   all        230       1440       0.67      0.688      0.714      0.407

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       2/32      13.9G      1.388      1.031      1.284        222        640: 100%|██████████| 29/29 [00:32<00:00,  1.11s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.57it/s]

                   all        230       1440       0.91      0.943      0.972      0.576

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       3/32      13.9G      1.354     0.8712      1.258        203        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440      0.957      0.975      0.979      0.623

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       4/32      13.9G      1.343     0.7808      1.244        242        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440       0.98       0.98      0.988      0.651

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       5/32      13.9G        1.3     0.6796      1.231        250        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.974      0.964      0.982      0.648

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       6/32      13.9G      1.286     0.6039      1.235        251        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.984      0.983      0.986      0.627

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       7/32      13.9G      1.259     0.5836      1.216        257        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440       0.98      0.982      0.982       0.64

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       8/32        14G      1.262     0.5733      1.217        273        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.61it/s]

                   all        230       1440      0.976       0.98      0.982      0.605

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       9/32      13.9G      1.258     0.5537      1.221        265        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440      0.969      0.978      0.984      0.655

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      10/32      13.9G      1.232     0.5539      1.202        233        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.61it/s]

                   all        230       1440      0.988      0.982      0.987      0.633

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      11/32      13.9G      1.223     0.5346      1.214        282        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.61it/s]

                   all        230       1440      0.989      0.984      0.988      0.655

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      12/32      13.9G      1.217     0.5251      1.219        205        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.987      0.986      0.988      0.662

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      13/32      13.9G      1.186     0.5148      1.194        219        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440       0.99      0.986      0.989      0.652

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      14/32      13.9G      1.191     0.5082      1.204        239        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440      0.985      0.985      0.986       0.66

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      15/32      13.9G      1.197     0.4964      1.214        254        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.982      0.983      0.987      0.672

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      16/32      13.9G      1.158     0.4899      1.211        231        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.985      0.989      0.987      0.676

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      17/32      13.9G       1.16     0.4824      1.211        275        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.981       0.98      0.986      0.671

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      18/32      13.9G       1.15     0.4686      1.222        261        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.61it/s]

                   all        230       1440      0.987      0.983      0.985      0.678

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      19/32      13.9G      1.145     0.4676      1.219        187        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440      0.987      0.984      0.987      0.669

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      20/32        14G      1.118     0.4547       1.18        223        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.61it/s]

                   all        230       1440      0.989      0.983      0.988      0.677

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      21/32      13.9G      1.107     0.4494      1.184        232        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440      0.989      0.989      0.987      0.686

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      22/32      13.9G      1.095     0.4451      1.168        242        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440      0.988      0.986      0.988      0.684

Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      23/32      13.9G      1.089     0.4029      1.238        147        640: 100%|██████████| 29/29 [00:33<00:00,  1.14s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440       0.99      0.989      0.988       0.68

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      24/32      13.9G      1.068     0.3902       1.23        127        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.989      0.986      0.987      0.678

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      25/32      13.9G      1.051     0.3857      1.227        121        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440      0.987      0.987      0.988       0.67

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      26/32      13.9G      1.031      0.373      1.204        141        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.987      0.989      0.987      0.685

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      27/32      13.9G      1.016      0.371      1.199        138        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440       0.99      0.989      0.986      0.687

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      28/32        14G      1.004     0.3684      1.199        136        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440       0.99      0.989      0.988      0.689

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      29/32      13.9G     0.9873     0.3578      1.192        145        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440      0.992      0.989      0.988       0.69

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      30/32      13.9G     0.9779     0.3549      1.177        140        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440      0.991       0.99      0.987      0.685

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      31/32      13.9G     0.9527     0.3435      1.178        124        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.991       0.99      0.987      0.691

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      32/32      13.9G     0.9411      0.342      1.159        142        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.991      0.989      0.988      0.691

32 epochs completed in 0.317 hours.
Optimizer stripped from runs/detect/train6/weights/last.pt, 52.0MB
Optimizer stripped from runs/detect/train6/weights/best.pt, 52.0MB

Validating runs/detect/train6/weights/best.pt...
Ultralytics 8.3.185 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
Model summary (fused): 92 layers, 25,843,234 parameters, 0 gradients, 78.7 GFLOPs

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:04<00:00,  1.03s/it]
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        230       1440      0.991      0.991      0.987      0.692
     DC Voltage Source        103        144          1      0.979      0.984       0.76
              Resistor        183        605      0.985      0.992      0.987      0.649
        Current Source        113        150      0.982          1      0.984      0.739
              Inductor        117        177      0.994      0.988       0.99      0.647
             Capacitor        115        184      0.993      0.989      0.985      0.639
     AC Voltage Source         65        180      0.993      0.994      0.995      0.717
Speed: 0.1ms preprocess, 8.1ms inference, 0.0ms loss, 2.1ms postprocess per image
Results saved to runs/detect/train6

🚀 Case 6: Optimizer | Experiment 2: optimizer=Adam
Ultralytics 8.3.185 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-component-data/YOLO_component-dataset/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8m.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train7, nbs=64, nms=False, opset=None, optimize=False, optimizer=Adam, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/train7, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.001, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=6

                   from  n    params  module                                       arguments
  0                  -1  1      1392  ultralytics.nn.modules.conv.Conv             [3, 48, 3, 2]
  1                  -1  1     41664  ultralytics.nn.modules.conv.Conv             [48, 96, 3, 2]
  2                  -1  2    111360  ultralytics.nn.modules.block.C2f             [96, 96, 2, True]
  3                  -1  1    166272  ultralytics.nn.modules.conv.Conv             [96, 192, 3, 2]
  4                  -1  4    813312  ultralytics.nn.modules.block.C2f             [192, 192, 4, True]
  5                  -1  1    664320  ultralytics.nn.modules.conv.Conv             [192, 384, 3, 2]
  6                  -1  4   3248640  ultralytics.nn.modules.block.C2f             [384, 384, 4, True]
  7                  -1  1   1991808  ultralytics.nn.modules.conv.Conv             [384, 576, 3, 2]
  8                  -1  2   3985920  ultralytics.nn.modules.block.C2f             [576, 576, 2, True]
  9                  -1  1    831168  ultralytics.nn.modules.block.SPPF            [576, 576, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  2   1993728  ultralytics.nn.modules.block.C2f             [960, 384, 2]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  2    517632  ultralytics.nn.modules.block.C2f             [576, 192, 2]
 16                  -1  1    332160  ultralytics.nn.modules.conv.Conv             [192, 192, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  2   1846272  ultralytics.nn.modules.block.C2f             [576, 384, 2]
 19                  -1  1   1327872  ultralytics.nn.modules.conv.Conv             [384, 384, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  2   4207104  ultralytics.nn.modules.block.C2f             [960, 576, 2]
 22        [15, 18, 21]  1   3779170  ultralytics.nn.modules.head.Detect           [6, [192, 384, 576]]
Model summary: 169 layers, 25,859,794 parameters, 25,859,778 gradients, 79.1 GFLOPs

Transferred 469/475 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 52.7±34.7 MB/s, size: 51.9 KB)

train: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/train/labels... 919 images, 0 backgrounds, 0 corrupt: 100%|██████████| 919/919 [00:01<00:00, 502.68it/s]

WARNING ⚠️ train: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 25.1±13.8 MB/s, size: 35.4 KB)

val: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels... 230 images, 0 backgrounds, 0 corrupt: 100%|██████████| 230/230 [00:01<00:00, 161.44it/s]

WARNING ⚠️ val: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/val is not writeable, cache not saved.
Plotting labels to runs/detect/train7/labels.jpg...
optimizer: Adam(lr=0.01, momentum=0.937) with parameter groups 77 weight(decay=0.0), 84 weight(decay=0.001), 83 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs/detect/train7
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       1/32        14G      2.527      4.962      2.092        249        640: 100%|██████████| 29/29 [00:32<00:00,  1.12s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.89it/s]

                   all        230       1440          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       2/32        14G      1.576      1.671      1.541        222        640: 100%|██████████| 29/29 [00:32<00:00,  1.11s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.88it/s]

                   all        230       1440          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       3/32        14G      1.497      1.296      1.467        203        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.89it/s]

                   all        230       1440          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       4/32        14G      1.435      1.102      1.405        242        640: 100%|██████████| 29/29 [00:32<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.43it/s]

                   all        230       1440      0.164      0.459       0.37      0.189

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       5/32      14.1G      1.409     0.9682       1.39        250        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.53it/s]

                   all        230       1440       0.46       0.57      0.455      0.277

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       6/32        14G      1.383     0.8813      1.384        251        640: 100%|██████████| 29/29 [00:32<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.46it/s]

                   all        230       1440      0.789      0.703      0.872      0.552

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       7/32        14G      1.387     0.8277      1.375        257        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.57it/s]

                   all        230       1440       0.75      0.733      0.791      0.424

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       8/32        14G      1.375     0.7934      1.365        273        640: 100%|██████████| 29/29 [00:32<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.45it/s]

                   all        230       1440      0.905      0.769      0.889        0.5

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       9/32        14G      1.338     0.7441      1.348        265        640: 100%|██████████| 29/29 [00:32<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440      0.377      0.496      0.421      0.231

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      10/32        14G      1.353     0.7321      1.343        233        640: 100%|██████████| 29/29 [00:32<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440      0.784      0.918      0.943      0.577

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      11/32      14.1G      1.324     0.7266      1.339        282        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.571      0.745      0.744      0.337

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      12/32        14G      1.337     0.7024      1.352        205        640: 100%|██████████| 29/29 [00:32<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.66it/s]

                   all        230       1440      0.778      0.285      0.368      0.241

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      13/32      14.1G      1.328     0.6839      1.336        219        640: 100%|██████████| 29/29 [00:32<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.78it/s]

                   all        230       1440     0.0167    0.00116    0.00914    0.00274

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      14/32        14G      1.319     0.6776      1.326        239        640: 100%|██████████| 29/29 [00:32<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440       0.95      0.916      0.959      0.559

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      15/32        14G      1.313     0.6496      1.312        254        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.61it/s]

                   all        230       1440      0.828       0.71      0.829      0.491

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      16/32        14G      1.312     0.6338      1.333        231        640: 100%|██████████| 29/29 [00:32<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.977      0.976       0.98       0.61

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      17/32        14G      1.293     0.6278      1.313        275        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.961      0.969      0.983       0.64

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      18/32        14G      1.277     0.5996      1.313        261        640: 100%|██████████| 29/29 [00:32<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.68it/s]

                   all        230       1440      0.862      0.406      0.519      0.295

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      19/32        14G      1.292     0.6062      1.325        187        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.71it/s]

                   all        230       1440      0.671     0.0118     0.0174     0.0104

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      20/32        14G      1.261     0.5886       1.29        223        640: 100%|██████████| 29/29 [00:32<00:00,  1.11s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.981      0.983      0.986      0.656

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      21/32        14G      1.253     0.5903      1.293        232        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.977       0.98      0.986      0.659

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      22/32        14G      1.253     0.5717      1.282        242        640: 100%|██████████| 29/29 [00:32<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440       0.97      0.968      0.982      0.642

Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      23/32        14G      1.236     0.5272      1.378        147        640: 100%|██████████| 29/29 [00:33<00:00,  1.14s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.58it/s]

                   all        230       1440      0.967      0.977       0.98      0.607

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      24/32        14G      1.241     0.5207      1.383        127        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440      0.973      0.979      0.985      0.609

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      25/32      14.1G      1.238     0.5107      1.385        121        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.893      0.509      0.611      0.367

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      26/32      14.1G      1.225     0.4992      1.364        141        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.966      0.913       0.95      0.619

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      27/32        14G      1.218      0.483      1.369        138        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.902      0.913      0.949      0.564

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      28/32      14.1G      1.216     0.4847      1.369        136        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440      0.983      0.982      0.986      0.662

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      29/32        14G      1.203     0.4726      1.364        145        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.58it/s]

                   all        230       1440      0.981      0.984      0.988      0.673

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      30/32        14G       1.19     0.4679      1.347        140        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440       0.98      0.986      0.987      0.677

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      31/32      14.1G      1.184     0.4593      1.363        124        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.983      0.983      0.987       0.68

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      32/32        14G      1.175     0.4506      1.344        142        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440      0.986      0.987      0.987      0.681

32 epochs completed in 0.320 hours.
Optimizer stripped from runs/detect/train7/weights/last.pt, 52.0MB
Optimizer stripped from runs/detect/train7/weights/best.pt, 52.0MB

Validating runs/detect/train7/weights/best.pt...
Ultralytics 8.3.185 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
Model summary (fused): 92 layers, 25,843,234 parameters, 0 gradients, 78.7 GFLOPs

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:04<00:00,  1.11s/it]
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        230       1440      0.986      0.987      0.987      0.681
     DC Voltage Source        103        144      0.997      0.972      0.984      0.754
              Resistor        183        605      0.982      0.988      0.985      0.643
        Current Source        113        150      0.964          1       0.98      0.725
              Inductor        117        177      0.992      0.989       0.99      0.638
             Capacitor        115        184      0.989      0.989       0.99      0.614
     AC Voltage Source         65        180      0.994      0.983      0.992      0.714
Speed: 0.1ms preprocess, 8.3ms inference, 0.0ms loss, 6.1ms postprocess per image
Results saved to runs/detect/train7

🚀 Case 6: Optimizer | Experiment 3: optimizer=AdamW
Ultralytics 8.3.185 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-component-data/YOLO_component-dataset/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8m.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train8, nbs=64, nms=False, opset=None, optimize=False, optimizer=AdamW, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/train8, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.001, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=6

                   from  n    params  module                                       arguments
  0                  -1  1      1392  ultralytics.nn.modules.conv.Conv             [3, 48, 3, 2]
  1                  -1  1     41664  ultralytics.nn.modules.conv.Conv             [48, 96, 3, 2]
  2                  -1  2    111360  ultralytics.nn.modules.block.C2f             [96, 96, 2, True]
  3                  -1  1    166272  ultralytics.nn.modules.conv.Conv             [96, 192, 3, 2]
  4                  -1  4    813312  ultralytics.nn.modules.block.C2f             [192, 192, 4, True]
  5                  -1  1    664320  ultralytics.nn.modules.conv.Conv             [192, 384, 3, 2]
  6                  -1  4   3248640  ultralytics.nn.modules.block.C2f             [384, 384, 4, True]
  7                  -1  1   1991808  ultralytics.nn.modules.conv.Conv             [384, 576, 3, 2]
  8                  -1  2   3985920  ultralytics.nn.modules.block.C2f             [576, 576, 2, True]
  9                  -1  1    831168  ultralytics.nn.modules.block.SPPF            [576, 576, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  2   1993728  ultralytics.nn.modules.block.C2f             [960, 384, 2]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  2    517632  ultralytics.nn.modules.block.C2f             [576, 192, 2]
 16                  -1  1    332160  ultralytics.nn.modules.conv.Conv             [192, 192, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  2   1846272  ultralytics.nn.modules.block.C2f             [576, 384, 2]
 19                  -1  1   1327872  ultralytics.nn.modules.conv.Conv             [384, 384, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  2   4207104  ultralytics.nn.modules.block.C2f             [960, 576, 2]
 22        [15, 18, 21]  1   3779170  ultralytics.nn.modules.head.Detect           [6, [192, 384, 576]]
Model summary: 169 layers, 25,859,794 parameters, 25,859,778 gradients, 79.1 GFLOPs

Transferred 469/475 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 53.3±37.3 MB/s, size: 51.9 KB)

train: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/train/labels... 919 images, 0 backgrounds, 0 corrupt: 100%|██████████| 919/919 [00:01<00:00, 521.04it/s]

WARNING ⚠️ train: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 24.5±13.9 MB/s, size: 35.4 KB)

val: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels... 230 images, 0 backgrounds, 0 corrupt: 100%|██████████| 230/230 [00:00<00:00, 365.04it/s]

WARNING ⚠️ val: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/val is not writeable, cache not saved.

Plotting labels to runs/detect/train8/labels.jpg...
optimizer: AdamW(lr=0.01, momentum=0.937) with parameter groups 77 weight(decay=0.0), 84 weight(decay=0.001), 83 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs/detect/train8
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       1/32      14.1G       2.53      4.938      2.101        249        640: 100%|██████████| 29/29 [00:32<00:00,  1.12s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.87it/s]

                   all        230       1440          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       2/32        14G      1.566      1.712      1.535        222        640: 100%|██████████| 29/29 [00:32<00:00,  1.11s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.88it/s]

                   all        230       1440          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       3/32        14G      1.455      1.277      1.443        203        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.87it/s]

                   all        230       1440          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       4/32        14G      1.436      1.095      1.405        242        640: 100%|██████████| 29/29 [00:32<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.44it/s]

                   all        230       1440      0.604      0.114      0.165     0.0718

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       5/32        14G      1.401     0.9864      1.388        250        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.90it/s]

                   all        230       1440          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       6/32        14G      1.379     0.9257      1.378        251        640: 100%|██████████| 29/29 [00:32<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.91it/s]

                   all        230       1440          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       7/32        14G      1.349     0.8384      1.357        257        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.92it/s]

                   all        230       1440          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       8/32      14.1G      1.378     0.8041      1.366        273        640: 100%|██████████| 29/29 [00:32<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.89it/s]

                   all        230       1440          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       9/32        14G      1.345     0.7268      1.351        265        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440       0.62      0.474      0.523      0.224

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      10/32        14G      1.355      0.728      1.339        233        640: 100%|██████████| 29/29 [00:32<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440      0.906      0.907      0.954      0.518

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      11/32      14.1G       1.34     0.6853      1.341        282        640: 100%|██████████| 29/29 [00:32<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.61it/s]

                   all        230       1440      0.958      0.959      0.982      0.586

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      12/32      14.1G      1.322     0.6674       1.34        205        640: 100%|██████████| 29/29 [00:32<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.824      0.809      0.812      0.426

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      13/32        14G      1.303     0.6457       1.32        219        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440       0.97      0.973      0.983      0.647

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      14/32        14G      1.304     0.6449      1.316        239        640: 100%|██████████| 29/29 [00:32<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440       0.97      0.965      0.976      0.625

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      15/32        14G      1.315     0.6189      1.313        254        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.61it/s]

                   all        230       1440       0.95       0.97       0.98      0.552

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      16/32      14.2G      1.278     0.6135      1.313        231        640: 100%|██████████| 29/29 [00:32<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.61it/s]

                   all        230       1440      0.955      0.975       0.98      0.625

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      17/32        14G      1.262     0.5961      1.297        275        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440       0.97      0.978      0.983      0.646

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      18/32      14.1G      1.245     0.5703      1.293        261        640: 100%|██████████| 29/29 [00:32<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440       0.98      0.985      0.985      0.657

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      19/32        14G       1.26     0.5768      1.304        187        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.977      0.982      0.985      0.664

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      20/32        14G      1.223      0.553      1.266        223        640: 100%|██████████| 29/29 [00:32<00:00,  1.11s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.61it/s]

                   all        230       1440      0.985      0.984      0.987      0.663

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      21/32        14G      1.225     0.5524      1.274        232        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.985      0.983      0.987      0.673

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      22/32        14G       1.23     0.5557      1.269        242        640: 100%|██████████| 29/29 [00:32<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440       0.98      0.982      0.986      0.646

Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      23/32      14.1G      1.219     0.5036      1.361        147        640: 100%|██████████| 29/29 [00:33<00:00,  1.14s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.61it/s]

                   all        230       1440      0.986      0.979      0.986       0.66

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      24/32        14G      1.224     0.4873      1.373        127        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440       0.97      0.972      0.987      0.623

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      25/32        14G      1.228     0.4877      1.375        121        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.982      0.982      0.987      0.638

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      26/32        14G      1.207     0.4748      1.353        141        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.984       0.98      0.987      0.662

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      27/32      14.1G       1.19     0.4689      1.348        138        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.989      0.986      0.988      0.674

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      28/32        14G        1.2      0.476      1.355        136        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.987      0.986      0.987      0.675

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      29/32        14G      1.175     0.4532      1.346        145        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.989      0.988      0.988      0.681

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      30/32        14G      1.171     0.4534      1.335        140        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.987      0.989      0.986      0.674

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      31/32        14G      1.159     0.4342      1.343        124        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.988      0.988      0.988      0.686

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      32/32        14G      1.149     0.4295      1.327        142        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.986      0.985      0.988      0.687

32 epochs completed in 0.319 hours.
Optimizer stripped from runs/detect/train8/weights/last.pt, 52.0MB
Optimizer stripped from runs/detect/train8/weights/best.pt, 52.0MB

Validating runs/detect/train8/weights/best.pt...
Ultralytics 8.3.185 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
Model summary (fused): 92 layers, 25,843,234 parameters, 0 gradients, 78.7 GFLOPs

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:03<00:00,  1.02it/s]
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        230       1440      0.986      0.985      0.988      0.687
     DC Voltage Source        103        144      0.995      0.972      0.983      0.754
              Resistor        183        605      0.984       0.99      0.987      0.654
        Current Source        113        150      0.968      0.998      0.988       0.72
              Inductor        117        177      0.988      0.989      0.992      0.645
             Capacitor        115        184      0.988      0.989      0.988       0.62
     AC Voltage Source         65        180      0.994      0.975      0.991      0.729
Speed: 0.1ms preprocess, 8.1ms inference, 0.0ms loss, 2.5ms postprocess per image
Results saved to runs/detect/train8

🚀 Case 6: Optimizer | Experiment 4: optimizer=RMSProp
Ultralytics 8.3.185 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-component-data/YOLO_component-dataset/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8m.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train9, nbs=64, nms=False, opset=None, optimize=False, optimizer=RMSProp, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/train9, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.001, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=6

                   from  n    params  module                                       arguments
  0                  -1  1      1392  ultralytics.nn.modules.conv.Conv             [3, 48, 3, 2]
  1                  -1  1     41664  ultralytics.nn.modules.conv.Conv             [48, 96, 3, 2]
  2                  -1  2    111360  ultralytics.nn.modules.block.C2f             [96, 96, 2, True]
  3                  -1  1    166272  ultralytics.nn.modules.conv.Conv             [96, 192, 3, 2]
  4                  -1  4    813312  ultralytics.nn.modules.block.C2f             [192, 192, 4, True]
  5                  -1  1    664320  ultralytics.nn.modules.conv.Conv             [192, 384, 3, 2]
  6                  -1  4   3248640  ultralytics.nn.modules.block.C2f             [384, 384, 4, True]
  7                  -1  1   1991808  ultralytics.nn.modules.conv.Conv             [384, 576, 3, 2]
  8                  -1  2   3985920  ultralytics.nn.modules.block.C2f             [576, 576, 2, True]
  9                  -1  1    831168  ultralytics.nn.modules.block.SPPF            [576, 576, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  2   1993728  ultralytics.nn.modules.block.C2f             [960, 384, 2]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  2    517632  ultralytics.nn.modules.block.C2f             [576, 192, 2]
 16                  -1  1    332160  ultralytics.nn.modules.conv.Conv             [192, 192, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  2   1846272  ultralytics.nn.modules.block.C2f             [576, 384, 2]
 19                  -1  1   1327872  ultralytics.nn.modules.conv.Conv             [384, 384, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  2   4207104  ultralytics.nn.modules.block.C2f             [960, 576, 2]
 22        [15, 18, 21]  1   3779170  ultralytics.nn.modules.head.Detect           [6, [192, 384, 576]]
Model summary: 169 layers, 25,859,794 parameters, 25,859,778 gradients, 79.1 GFLOPs

Transferred 469/475 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 51.3±36.5 MB/s, size: 51.9 KB)

train: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/train/labels... 919 images, 0 backgrounds, 0 corrupt: 100%|██████████| 919/919 [00:01<00:00, 521.74it/s]

WARNING ⚠️ train: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 27.1±11.9 MB/s, size: 35.4 KB)

val: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels... 230 images, 0 backgrounds, 0 corrupt: 100%|██████████| 230/230 [00:00<00:00, 357.20it/s]

WARNING ⚠️ val: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/val is not writeable, cache not saved.

Plotting labels to runs/detect/train9/labels.jpg...
optimizer: RMSprop(lr=0.01, momentum=0.937) with parameter groups 77 weight(decay=0.0), 84 weight(decay=0.001), 83 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs/detect/train9
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       1/32      14.2G      3.598      10.74      3.389        249        640: 100%|██████████| 29/29 [00:32<00:00,  1.12s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.87it/s]

                   all        230       1440          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       2/32      14.1G      3.561      3.683      2.773        222        640: 100%|██████████| 29/29 [00:32<00:00,  1.11s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.167    0.00222   3.68e-06   5.11e-07

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       3/32      14.1G      3.462      3.261      2.653        203        640: 100%|██████████| 29/29 [00:32<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440   2.42e-06    0.00111   1.22e-06   2.43e-07

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       4/32      14.1G      3.161      3.025      2.487        242        640: 100%|██████████| 29/29 [00:32<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440   0.000436     0.0441   0.000251   4.55e-05

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       5/32        14G      2.895      11.31      2.466        250        640: 100%|██████████| 29/29 [00:32<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.65it/s]

                   all        230       1440   0.000597    0.00287   0.000304   6.08e-05

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       6/32      14.1G      2.768      3.044      2.388        251        640: 100%|██████████| 29/29 [00:32<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:15<00:00,  3.80s/it]

                   all        230       1440          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       7/32      14.1G       2.64      2.778      2.265        257        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:03<00:00,  1.03it/s]

                   all        230       1440   0.000244     0.0278   0.000143   2.38e-05

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       8/32        14G      2.487      2.528      2.198        273        640: 100%|██████████| 29/29 [00:32<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.67it/s]

                   all        230       1440          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       9/32      14.1G      2.366      2.382      2.157        265        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.65it/s]

                   all        230       1440          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      10/32      14.1G      2.307       2.33      2.056        233        640: 100%|██████████| 29/29 [00:32<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:04<00:00,  1.03s/it]

                   all        230       1440          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      11/32        14G      2.147      2.108      1.982        282        640: 100%|██████████| 29/29 [00:32<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:06<00:00,  1.50s/it]

                   all        230       1440   6.76e-05     0.0264   4.06e-05    7.2e-06

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      12/32        14G      2.112      2.061      1.951        205        640: 100%|██████████| 29/29 [00:32<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:20<00:00,  5.21s/it]

                   all        230       1440          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      13/32      14.1G      2.064       1.96      1.903        219        640: 100%|██████████| 29/29 [00:32<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.70it/s]

                   all        230       1440          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      14/32      14.1G      2.024      1.918      1.859        239        640: 100%|██████████| 29/29 [00:32<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.61it/s]

                   all        230       1440          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      15/32        14G      1.971      2.073      1.825        254        640: 100%|██████████| 29/29 [00:32<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.67it/s]

                   all        230       1440          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      16/32        14G      1.963      1.754      1.829        231        640: 100%|██████████| 29/29 [00:32<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.66it/s]

                   all        230       1440          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      17/32        14G      1.889      1.706      1.781        275        640: 100%|██████████| 29/29 [00:32<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.37it/s]

                   all        230       1440   0.000198     0.0759   0.000144   4.74e-05

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      18/32        14G      1.856      1.613      1.765        261        640: 100%|██████████| 29/29 [00:32<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.68it/s]

                   all        230       1440          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      19/32      14.1G      1.838      1.606       1.76        187        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      20/32      14.1G      1.791       1.53       1.71        223        640: 100%|██████████| 29/29 [00:32<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      21/32      14.1G      1.774      1.487      1.701        232        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.55it/s]

                   all        230       1440   9.96e-05    0.00912   5.19e-05   7.76e-06

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      22/32        14G      1.747      1.434       1.67        242        640: 100%|██████████| 29/29 [00:32<00:00,  1.11s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:03<00:00,  1.14it/s]

                   all        230       1440   0.000563     0.0336   0.000268   6.01e-05

Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      23/32        14G      1.686      1.364      1.767        147        640: 100%|██████████| 29/29 [00:33<00:00,  1.14s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:13<00:00,  3.41s/it]

                   all        230       1440      0.206      0.204     0.0461     0.0173

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      24/32        14G      1.653      1.287      1.754        127        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.67it/s]

                   all        230       1440          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      25/32      14.1G      1.638      1.278      1.744        121        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.255      0.073     0.0654     0.0217

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      26/32        14G      1.617      1.222       1.72        141        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.68it/s]

                   all        230       1440          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      27/32        14G      1.589      1.193      1.708        138        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.70it/s]

                   all        230       1440    0.00518    0.00303    0.00296   0.000394

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      28/32      14.1G       1.59       1.17       1.71        136        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.84it/s]

                   all        230       1440    0.00725   0.000551    0.00372   0.000372

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      29/32      14.1G      1.544      1.116      1.684        145        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.68it/s]

                   all        230       1440      0.195      0.104      0.141     0.0598

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      30/32        14G       1.53      1.105      1.663        140        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.52it/s]

                   all        230       1440      0.523      0.146       0.22      0.068

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      31/32      14.1G       1.51      1.078      1.671        124        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440      0.286      0.287      0.278      0.159

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      32/32      14.2G      1.502      1.058       1.65        142        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.236      0.249      0.258      0.111

32 epochs completed in 0.333 hours.
Optimizer stripped from runs/detect/train9/weights/last.pt, 52.0MB
Optimizer stripped from runs/detect/train9/weights/best.pt, 52.0MB

Validating runs/detect/train9/weights/best.pt...
Ultralytics 8.3.185 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
Model summary (fused): 92 layers, 25,843,234 parameters, 0 gradients, 78.7 GFLOPs

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:03<00:00,  1.04it/s]
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        230       1440      0.285      0.291      0.278      0.159
     DC Voltage Source        103        144      0.196      0.722      0.304        0.2
              Resistor        183        605      0.815      0.549      0.794      0.423
        Current Source        113        150      0.234      0.333      0.224      0.137
              Inductor        117        177     0.0675      0.107     0.0576     0.0317
             Capacitor        115        184     0.0973     0.0272     0.0352     0.0184
     AC Voltage Source         65        180        0.3    0.00556      0.253      0.144
Speed: 0.1ms preprocess, 8.1ms inference, 0.0ms loss, 2.1ms postprocess per image
Results saved to runs/detect/train9

🚀 Case 6: Optimizer | Experiment 5: optimizer=Adamax
Ultralytics 8.3.185 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-component-data/YOLO_component-dataset/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8m.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train10, nbs=64, nms=False, opset=None, optimize=False, optimizer=Adamax, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/train10, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.001, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=6

                   from  n    params  module                                       arguments
  0                  -1  1      1392  ultralytics.nn.modules.conv.Conv             [3, 48, 3, 2]
  1                  -1  1     41664  ultralytics.nn.modules.conv.Conv             [48, 96, 3, 2]
  2                  -1  2    111360  ultralytics.nn.modules.block.C2f             [96, 96, 2, True]
  3                  -1  1    166272  ultralytics.nn.modules.conv.Conv             [96, 192, 3, 2]
  4                  -1  4    813312  ultralytics.nn.modules.block.C2f             [192, 192, 4, True]
  5                  -1  1    664320  ultralytics.nn.modules.conv.Conv             [192, 384, 3, 2]
  6                  -1  4   3248640  ultralytics.nn.modules.block.C2f             [384, 384, 4, True]
  7                  -1  1   1991808  ultralytics.nn.modules.conv.Conv             [384, 576, 3, 2]
  8                  -1  2   3985920  ultralytics.nn.modules.block.C2f             [576, 576, 2, True]
  9                  -1  1    831168  ultralytics.nn.modules.block.SPPF            [576, 576, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  2   1993728  ultralytics.nn.modules.block.C2f             [960, 384, 2]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  2    517632  ultralytics.nn.modules.block.C2f             [576, 192, 2]
 16                  -1  1    332160  ultralytics.nn.modules.conv.Conv             [192, 192, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  2   1846272  ultralytics.nn.modules.block.C2f             [576, 384, 2]
 19                  -1  1   1327872  ultralytics.nn.modules.conv.Conv             [384, 384, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  2   4207104  ultralytics.nn.modules.block.C2f             [960, 576, 2]
 22        [15, 18, 21]  1   3779170  ultralytics.nn.modules.head.Detect           [6, [192, 384, 576]]
Model summary: 169 layers, 25,859,794 parameters, 25,859,778 gradients, 79.1 GFLOPs

Transferred 469/475 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 50.3±35.7 MB/s, size: 51.9 KB)

train: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/train/labels... 919 images, 0 backgrounds, 0 corrupt: 100%|██████████| 919/919 [00:01<00:00, 490.44it/s]

WARNING ⚠️ train: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 23.6±12.3 MB/s, size: 35.4 KB)

val: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels... 230 images, 0 backgrounds, 0 corrupt: 100%|██████████| 230/230 [00:00<00:00, 333.16it/s]

WARNING ⚠️ val: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/val is not writeable, cache not saved.

Plotting labels to runs/detect/train10/labels.jpg...
optimizer: Adamax(lr=0.01, momentum=0.937) with parameter groups 77 weight(decay=0.0), 84 weight(decay=0.001), 83 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs/detect/train10
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       1/32      14.1G       2.38      4.234          2        249        640: 100%|██████████| 29/29 [00:32<00:00,  1.12s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.86it/s]

                   all        230       1440          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       2/32      14.1G      1.454      1.366      1.455        222        640: 100%|██████████| 29/29 [00:32<00:00,  1.11s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:03<00:00,  1.33it/s]

                   all        230       1440   2.46e-06    0.00111   1.24e-06   7.46e-07

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       3/32        14G      1.388      1.006      1.384        203        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:05<00:00,  1.43s/it]

                   all        230       1440    0.00157    0.00248    0.00163    0.00111

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       4/32        14G      1.349     0.8344      1.346        242        640: 100%|██████████| 29/29 [00:32<00:00,  1.11s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.60it/s]

                   all        230       1440      0.873      0.862      0.926      0.528

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       5/32        14G       1.33     0.7855      1.337        250        640: 100%|██████████| 29/29 [00:32<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.567      0.646      0.565      0.212

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       6/32        14G      1.308     0.7234       1.33        251        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.937      0.949       0.98      0.599

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       7/32        14G       1.29     0.6725      1.314        257        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.956      0.962      0.978      0.628

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       8/32        14G      1.311     0.6576      1.324        273        640: 100%|██████████| 29/29 [00:32<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.976      0.978      0.985      0.635

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       9/32        14G      1.287     0.6221      1.315        265        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.61it/s]

                   all        230       1440      0.957      0.959      0.979      0.629

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      10/32      14.1G       1.31     0.6241       1.31        233        640: 100%|██████████| 29/29 [00:32<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.948      0.951      0.962      0.489

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      11/32      14.2G      1.276     0.6002      1.307        282        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.60it/s]

                   all        230       1440      0.889      0.911      0.945      0.444

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      12/32      14.1G      1.291     0.5993      1.321        205        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.65it/s]

                   all        230       1440        0.9      0.859      0.905      0.427

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      13/32        14G      1.257     0.5917      1.288        219        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.982      0.985      0.988      0.666

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      14/32        14G      1.261     0.5824      1.287        239        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.958      0.969      0.973      0.645

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      15/32      14.1G       1.27     0.5679      1.284        254        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.65it/s]

                   all        230       1440      0.977       0.98      0.986      0.639

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      16/32      14.1G       1.24     0.5561      1.289        231        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.987      0.982      0.988      0.663

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      17/32      14.1G      1.237     0.5491       1.28        275        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.979      0.982      0.986      0.662

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      18/32      14.1G       1.23     0.5365      1.284        261        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.984      0.983      0.986       0.64

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      19/32        14G      1.225      0.536      1.284        187        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.65it/s]

                   all        230       1440      0.977      0.973      0.985      0.676

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      20/32        14G      1.203     0.5176      1.253        223        640: 100%|██████████| 29/29 [00:32<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.987      0.986      0.988      0.672

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      21/32        14G      1.202     0.5167       1.26        232        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.56it/s]

                   all        230       1440      0.986      0.985      0.987      0.664

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      22/32      14.1G      1.206     0.5109      1.253        242        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440       0.98      0.982      0.988      0.662

Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      23/32        14G      1.199     0.4763      1.346        147        640: 100%|██████████| 29/29 [00:33<00:00,  1.14s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.979      0.986      0.988      0.677

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      24/32      14.1G      1.195     0.4625      1.353        127        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440      0.985      0.976      0.985       0.61

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      25/32        14G      1.199     0.4614      1.355        121        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440       0.99      0.985      0.988      0.675

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      26/32      14.1G      1.179     0.4484      1.331        141        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.984      0.988      0.986      0.656

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      27/32        14G      1.165     0.4402      1.332        138        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.984      0.985      0.987      0.684

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      28/32        14G      1.169     0.4425      1.334        136        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.65it/s]

                   all        230       1440      0.987      0.991      0.987      0.681

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      29/32        14G      1.143     0.4278      1.323        145        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.58it/s]

                   all        230       1440      0.988      0.984      0.988      0.682

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      30/32      14.1G      1.142     0.4256      1.314        140        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.988      0.988      0.988      0.682

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      31/32        14G      1.134     0.4153      1.326        124        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.989      0.987      0.988      0.691

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      32/32      14.1G       1.12     0.4109      1.307        142        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.989      0.985      0.988      0.691

32 epochs completed in 0.320 hours.
Optimizer stripped from runs/detect/train10/weights/last.pt, 52.0MB
Optimizer stripped from runs/detect/train10/weights/best.pt, 52.0MB

Validating runs/detect/train10/weights/best.pt...
Ultralytics 8.3.185 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
Model summary (fused): 92 layers, 25,843,234 parameters, 0 gradients, 78.7 GFLOPs

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:04<00:00,  1.05s/it]
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        230       1440      0.989      0.987      0.988      0.691
     DC Voltage Source        103        144      0.993      0.976      0.985      0.762
              Resistor        183        605      0.984      0.991      0.983      0.649
        Current Source        113        150      0.981      0.993      0.989      0.738
              Inductor        117        177      0.993      0.989      0.989      0.644
             Capacitor        115        184      0.992      0.989       0.99      0.624
     AC Voltage Source         65        180      0.989      0.985      0.994      0.731
Speed: 0.1ms preprocess, 8.5ms inference, 0.0ms loss, 2.1ms postprocess per image
Results saved to runs/detect/train10

,Case,Experiment No,Experiment Name,Epochs,Batch,lr0,Weight Decay,Optimizer,Image Size,Dropout,Freeze Layers,Activation,Training Time (s),Precision,Recall,mAP@0.5,mAP@0.5:0.95
0,Case 4: Dropout,1,dropout_0,32,32,0.01,0.001,SGD,640,0.0,0,SiLU,1176.32,0.991306,0.990508,0.987335,0.691970
1,Case 4: Dropout,2,dropout_0.1,32,32,0.01,0.001,SGD,640,0.1,0,SiLU,1161.46,0.991306,0.990508,0.987335,0.691970
2,Case 4: Dropout,3,dropout_0.2,32,32,0.01,0.001,SGD,640,0.2,0,SiLU,1161.13,0.991306,0.990508,0.987335,0.691970
3,Case 4: Dropout,4,dropout_0.3,32,32,0.01,0.001,SGD,640,0.3,0,SiLU,1160.67,0.991306,0.990508,0.987335,0.691970
4,Case 4: Dropout,5,dropout_0.5,32,32,0.01,0.001,SGD,640,0.5,0,SiLU,1164.58,0.991306,0.990508,0.987335,0.691970
5,Case 6: Optimizer,1,optimizer_SGD,32,32,0.01,0.001,SGD,640,0.0,0,SiLU,1161.23,0.991306,0.990508,0.987335,0.691970
6,Case 6: Optimizer,2,optimizer_Adam,32,32,0.01,0.001,Adam,640,0.0,0,SiLU,1172.61,0.986126,0.986969,0.987008,0.681319
7,Case 6: Optimizer,3,optimizer_AdamW,32,32,0.01,0.001,AdamW,640,0.0,0,SiLU,1168.31,0.986241,0.985495,0.988257,0.687184
8,Case 6: Optimizer,4,optimizer_RMSProp,32,32,0.01,0.001,RMSProp,640,0.0,0,SiLU,1219.09,0.284918,0.290732,0.277995,0.159001
9,Case 6: Optimizer,5,optimizer_Adamax,32,32,0.01,0.001,Adamax,640,0.0,0,SiLU,1171.89,0.988610,0.987190,0.988335,0.691340

In [6]:
# Case 5: Varying Image Size
run_ablation("Case 5: Image Size", "imgsz", [320, 512, 640])

🚀 Case 5: Image Size | Experiment 1: imgsz=320
Ultralytics 8.3.185 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-component-data/YOLO_component-dataset/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=320, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8m.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train11, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/train11, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.001, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=6

                   from  n    params  module                                       arguments
  0                  -1  1      1392  ultralytics.nn.modules.conv.Conv             [3, 48, 3, 2]
  1                  -1  1     41664  ultralytics.nn.modules.conv.Conv             [48, 96, 3, 2]
  2                  -1  2    111360  ultralytics.nn.modules.block.C2f             [96, 96, 2, True]
  3                  -1  1    166272  ultralytics.nn.modules.conv.Conv             [96, 192, 3, 2]
  4                  -1  4    813312  ultralytics.nn.modules.block.C2f             [192, 192, 4, True]
  5                  -1  1    664320  ultralytics.nn.modules.conv.Conv             [192, 384, 3, 2]
  6                  -1  4   3248640  ultralytics.nn.modules.block.C2f             [384, 384, 4, True]
  7                  -1  1   1991808  ultralytics.nn.modules.conv.Conv             [384, 576, 3, 2]
  8                  -1  2   3985920  ultralytics.nn.modules.block.C2f             [576, 576, 2, True]
  9                  -1  1    831168  ultralytics.nn.modules.block.SPPF            [576, 576, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  2   1993728  ultralytics.nn.modules.block.C2f             [960, 384, 2]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  2    517632  ultralytics.nn.modules.block.C2f             [576, 192, 2]
 16                  -1  1    332160  ultralytics.nn.modules.conv.Conv             [192, 192, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  2   1846272  ultralytics.nn.modules.block.C2f             [576, 384, 2]
 19                  -1  1   1327872  ultralytics.nn.modules.conv.Conv             [384, 384, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  2   4207104  ultralytics.nn.modules.block.C2f             [960, 576, 2]
 22        [15, 18, 21]  1   3779170  ultralytics.nn.modules.head.Detect           [6, [192, 384, 576]]
Model summary: 169 layers, 25,859,794 parameters, 25,859,778 gradients, 79.1 GFLOPs

Transferred 469/475 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 51.2±37.2 MB/s, size: 51.9 KB)

train: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/train/labels... 919 images, 0 backgrounds, 0 corrupt: 100%|██████████| 919/919 [00:01<00:00, 512.76it/s]

WARNING ⚠️ train: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 16.0±10.5 MB/s, size: 35.4 KB)

val: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels... 230 images, 0 backgrounds, 0 corrupt: 100%|██████████| 230/230 [00:00<00:00, 377.81it/s]

WARNING ⚠️ val: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/val is not writeable, cache not saved.

Plotting labels to runs/detect/train11/labels.jpg...
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 77 weight(decay=0.0), 84 weight(decay=0.001), 83 bias(decay=0.0)
Image sizes 320 train, 320 val
Using 4 dataloader workers
Logging results to runs/detect/train11
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       1/32      3.81G      2.346      3.259      1.478        248        320: 100%|██████████| 29/29 [00:09<00:00,  3.01it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  2.89it/s]

                   all        230       1440      0.575      0.758      0.692      0.384

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       2/32      3.87G      1.397     0.9754      1.036        221        320: 100%|██████████| 29/29 [00:09<00:00,  3.12it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.28it/s]

                   all        230       1440      0.915      0.939      0.971      0.613

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       3/32       3.9G      1.416     0.8589      1.024        204        320: 100%|██████████| 29/29 [00:09<00:00,  3.19it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.30it/s]

                   all        230       1440      0.769      0.796      0.896      0.548

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       4/32      3.95G      1.408     0.7903      1.013        241        320: 100%|██████████| 29/29 [00:09<00:00,  3.18it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.37it/s]

                   all        230       1440      0.893      0.925      0.975      0.611

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       5/32      3.99G       1.36     0.7778       1.01        251        320: 100%|██████████| 29/29 [00:09<00:00,  3.20it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.14it/s]

                   all        230       1440      0.905      0.925      0.977      0.632

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       6/32      4.04G       1.35     0.6605      1.008        249        320: 100%|██████████| 29/29 [00:09<00:00,  3.19it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.26it/s]

                   all        230       1440       0.94      0.945      0.975      0.619

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       7/32      4.08G      1.308     0.6522     0.9931        257        320: 100%|██████████| 29/29 [00:09<00:00,  3.20it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.45it/s]

                   all        230       1440      0.977      0.974      0.981      0.574

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       8/32      4.64G        1.3     0.6316     0.9921        273        320: 100%|██████████| 29/29 [00:09<00:00,  3.19it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.37it/s]

                   all        230       1440      0.968      0.957      0.983      0.601

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       9/32      4.68G      1.296     0.6157     0.9931        264        320: 100%|██████████| 29/29 [00:09<00:00,  3.20it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.42it/s]

                   all        230       1440      0.943      0.954      0.982      0.621

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      10/32      4.73G      1.269     0.6116     0.9798        234        320: 100%|██████████| 29/29 [00:09<00:00,  3.17it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.41it/s]

                   all        230       1440      0.983      0.981      0.987      0.631

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      11/32      4.77G      1.238     0.5908     0.9759        282        320: 100%|██████████| 29/29 [00:09<00:00,  3.19it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.43it/s]

                   all        230       1440      0.978      0.978      0.986      0.645

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      12/32      4.82G      1.246     0.5763     0.9804        206        320: 100%|██████████| 29/29 [00:09<00:00,  3.18it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.33it/s]

                   all        230       1440      0.988      0.988      0.986      0.671

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      13/32      4.86G      1.207     0.5735     0.9628        219        320: 100%|██████████| 29/29 [00:09<00:00,  3.19it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.24it/s]

                   all        230       1440      0.983      0.979      0.987      0.638

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      14/32       4.9G      1.217     0.5679      0.967        239        320: 100%|██████████| 29/29 [00:09<00:00,  3.18it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.34it/s]

                   all        230       1440      0.977      0.981      0.984      0.651

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      15/32      4.94G      1.221     0.5489      0.964        254        320: 100%|██████████| 29/29 [00:09<00:00,  3.20it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.40it/s]

                   all        230       1440      0.981      0.982      0.989      0.634

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      16/32      4.99G      1.189     0.5378     0.9632        231        320: 100%|██████████| 29/29 [00:09<00:00,  3.18it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.23it/s]

                   all        230       1440      0.987      0.976      0.989      0.674

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      17/32      5.03G      1.185     0.5402     0.9638        275        320: 100%|██████████| 29/29 [00:09<00:00,  3.19it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.45it/s]

                   all        230       1440      0.976       0.98      0.987      0.662

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      18/32      5.59G      1.177     0.5232     0.9544        261        320: 100%|██████████| 29/29 [00:09<00:00,  3.18it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.47it/s]

                   all        230       1440      0.984      0.977      0.987      0.674

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      19/32      5.63G      1.164     0.5094     0.9592        187        320: 100%|██████████| 29/29 [00:09<00:00,  3.20it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.45it/s]

                   all        230       1440      0.977      0.973      0.985      0.664

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      20/32      5.68G       1.14     0.5064     0.9471        221        320: 100%|██████████| 29/29 [00:09<00:00,  3.20it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.25it/s]

                   all        230       1440      0.975       0.97      0.983      0.678

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      21/32      5.72G      1.135     0.5052     0.9475        232        320: 100%|██████████| 29/29 [00:09<00:00,  3.20it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.41it/s]

                   all        230       1440      0.978      0.978      0.986      0.678

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      22/32      5.77G      1.136     0.5003     0.9417        243        320: 100%|██████████| 29/29 [00:09<00:00,  3.19it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.38it/s]

                   all        230       1440      0.984      0.982      0.985      0.677

Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      23/32      5.81G      1.126     0.4492     0.9713        147        320: 100%|██████████| 29/29 [00:09<00:00,  2.99it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.40it/s]

                   all        230       1440      0.955      0.968      0.979      0.663

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      24/32      5.86G      1.114     0.4444     0.9668        127        320: 100%|██████████| 29/29 [00:09<00:00,  3.19it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.37it/s]

                   all        230       1440      0.982      0.981      0.987      0.669

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      25/32      5.89G      1.099     0.4417     0.9703        121        320: 100%|██████████| 29/29 [00:09<00:00,  3.21it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.20it/s]

                   all        230       1440      0.985      0.982      0.987      0.676

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      26/32      5.94G      1.077       0.42     0.9562        141        320: 100%|██████████| 29/29 [00:09<00:00,  3.21it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.36it/s]

                   all        230       1440      0.986      0.986      0.987      0.678

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      27/32      6.49G      1.063     0.4185     0.9529        138        320: 100%|██████████| 29/29 [00:09<00:00,  3.21it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.38it/s]

                   all        230       1440      0.982      0.989      0.986      0.681

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      28/32      6.54G      1.048     0.4158     0.9499        136        320: 100%|██████████| 29/29 [00:09<00:00,  3.19it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.34it/s]

                   all        230       1440      0.989      0.989      0.989      0.687

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      29/32      6.58G      1.028      0.399     0.9439        145        320: 100%|██████████| 29/29 [00:09<00:00,  3.20it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.38it/s]

                   all        230       1440      0.989       0.99       0.99      0.691

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      30/32      6.63G      1.024     0.3985     0.9438        140        320: 100%|██████████| 29/29 [00:09<00:00,  3.19it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.44it/s]

                   all        230       1440       0.99      0.989      0.989      0.691

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      31/32      6.67G      1.001     0.3841      0.943        124        320: 100%|██████████| 29/29 [00:09<00:00,  3.20it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.48it/s]

                   all        230       1440      0.988      0.989      0.989      0.693

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      32/32      6.72G     0.9993     0.3812     0.9395        142        320: 100%|██████████| 29/29 [00:09<00:00,  3.20it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  3.36it/s]

                   all        230       1440      0.991      0.987      0.988      0.693

32 epochs completed in 0.097 hours.
Optimizer stripped from runs/detect/train11/weights/last.pt, 52.0MB
Optimizer stripped from runs/detect/train11/weights/best.pt, 52.0MB

Validating runs/detect/train11/weights/best.pt...
Ultralytics 8.3.185 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
Model summary (fused): 92 layers, 25,843,234 parameters, 0 gradients, 78.7 GFLOPs

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.53it/s]
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        230       1440      0.991      0.987      0.988      0.693
     DC Voltage Source        103        144          1      0.968      0.983      0.778
              Resistor        183        605      0.984      0.991      0.985      0.652
        Current Source        113        150      0.984      0.993      0.989      0.742
              Inductor        117        177      0.994      0.989      0.989      0.637
             Capacitor        115        184      0.994      0.989      0.988      0.642
     AC Voltage Source         65        180      0.991      0.994      0.993      0.706
Speed: 0.0ms preprocess, 2.4ms inference, 0.0ms loss, 1.8ms postprocess per image
Results saved to runs/detect/train11

🚀 Case 5: Image Size | Experiment 2: imgsz=512
Ultralytics 8.3.185 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-component-data/YOLO_component-dataset/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=512, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8m.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train12, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/train12, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.001, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=6

                   from  n    params  module                                       arguments
  0                  -1  1      1392  ultralytics.nn.modules.conv.Conv             [3, 48, 3, 2]
  1                  -1  1     41664  ultralytics.nn.modules.conv.Conv             [48, 96, 3, 2]
  2                  -1  2    111360  ultralytics.nn.modules.block.C2f             [96, 96, 2, True]
  3                  -1  1    166272  ultralytics.nn.modules.conv.Conv             [96, 192, 3, 2]
  4                  -1  4    813312  ultralytics.nn.modules.block.C2f             [192, 192, 4, True]
  5                  -1  1    664320  ultralytics.nn.modules.conv.Conv             [192, 384, 3, 2]
  6                  -1  4   3248640  ultralytics.nn.modules.block.C2f             [384, 384, 4, True]
  7                  -1  1   1991808  ultralytics.nn.modules.conv.Conv             [384, 576, 3, 2]
  8                  -1  2   3985920  ultralytics.nn.modules.block.C2f             [576, 576, 2, True]
  9                  -1  1    831168  ultralytics.nn.modules.block.SPPF            [576, 576, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  2   1993728  ultralytics.nn.modules.block.C2f             [960, 384, 2]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  2    517632  ultralytics.nn.modules.block.C2f             [576, 192, 2]
 16                  -1  1    332160  ultralytics.nn.modules.conv.Conv             [192, 192, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  2   1846272  ultralytics.nn.modules.block.C2f             [576, 384, 2]
 19                  -1  1   1327872  ultralytics.nn.modules.conv.Conv             [384, 384, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  2   4207104  ultralytics.nn.modules.block.C2f             [960, 576, 2]
 22        [15, 18, 21]  1   3779170  ultralytics.nn.modules.head.Detect           [6, [192, 384, 576]]
Model summary: 169 layers, 25,859,794 parameters, 25,859,778 gradients, 79.1 GFLOPs

Transferred 469/475 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 52.7±41.1 MB/s, size: 51.9 KB)

train: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/train/labels... 919 images, 0 backgrounds, 0 corrupt: 100%|██████████| 919/919 [00:01<00:00, 600.24it/s]

WARNING ⚠️ train: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/train is not writeable, cache not saved.

albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 22.0±13.2 MB/s, size: 35.4 KB)

val: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels... 230 images, 0 backgrounds, 0 corrupt: 100%|██████████| 230/230 [00:00<00:00, 363.93it/s]

WARNING ⚠️ val: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/val is not writeable, cache not saved.

Plotting labels to runs/detect/train12/labels.jpg...
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 77 weight(decay=0.0), 84 weight(decay=0.001), 83 bias(decay=0.0)
Image sizes 512 train, 512 val
Using 4 dataloader workers
Logging results to runs/detect/train12
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       1/32      11.7G      2.507       3.51      1.883        249        512: 100%|██████████| 29/29 [00:26<00:00,  1.09it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.70it/s]

                   all        230       1440      0.603      0.766      0.696      0.382

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       2/32      11.5G      1.366      1.034      1.189        222        512: 100%|██████████| 29/29 [00:26<00:00,  1.10it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  2.03it/s]

                   all        230       1440      0.929       0.94      0.976      0.615

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       3/32      11.4G      1.395     0.7965      1.185        203        512: 100%|██████████| 29/29 [00:26<00:00,  1.11it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  2.16it/s]

                   all        230       1440      0.826      0.839      0.906       0.56

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       4/32      11.6G      1.342     0.7825      1.164        242        512: 100%|██████████| 29/29 [00:26<00:00,  1.11it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  2.15it/s]

                   all        230       1440      0.953      0.968      0.983      0.638

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       5/32      11.4G      1.324      0.664      1.157        251        512: 100%|██████████| 29/29 [00:26<00:00,  1.11it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  2.13it/s]

                   all        230       1440      0.884      0.855       0.89      0.569

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       6/32      11.6G      1.304     0.6016      1.161        252        512: 100%|██████████| 29/29 [00:26<00:00,  1.11it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  2.13it/s]

                   all        230       1440      0.945      0.965      0.976      0.615

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       7/32      11.4G      1.254     0.5992      1.141        257        512: 100%|██████████| 29/29 [00:26<00:00,  1.11it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  2.16it/s]

                   all        230       1440      0.982      0.984      0.981       0.58

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       8/32      11.6G      1.276     0.5738      1.154        273        512: 100%|██████████| 29/29 [00:26<00:00,  1.11it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  2.14it/s]

                   all        230       1440      0.983      0.987      0.984      0.631

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       9/32      11.4G      1.263     0.5702      1.152        265        512: 100%|██████████| 29/29 [00:26<00:00,  1.11it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  2.18it/s]

                   all        230       1440      0.985      0.982      0.986      0.648

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      10/32      11.6G      1.231     0.5653      1.129        233        512: 100%|██████████| 29/29 [00:26<00:00,  1.11it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  2.18it/s]

                   all        230       1440       0.98      0.986      0.982      0.638

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      11/32      11.4G      1.219     0.5324       1.13        281        512: 100%|██████████| 29/29 [00:26<00:00,  1.11it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  2.13it/s]

                   all        230       1440      0.988      0.986      0.988      0.648

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      12/32      11.6G      1.215     0.5293      1.136        205        512: 100%|██████████| 29/29 [00:26<00:00,  1.11it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  2.17it/s]

                   all        230       1440      0.984      0.982      0.988      0.673

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      13/32      11.4G      1.191     0.5202      1.113        219        512: 100%|██████████| 29/29 [00:26<00:00,  1.11it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  2.17it/s]

                   all        230       1440      0.982      0.986      0.986      0.649

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      14/32      11.6G      1.193     0.5209      1.114        240        512: 100%|██████████| 29/29 [00:26<00:00,  1.11it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  2.18it/s]

                   all        230       1440      0.977      0.979      0.986      0.661

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      15/32      11.4G      1.192     0.5057      1.106        254        512: 100%|██████████| 29/29 [00:26<00:00,  1.11it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  2.13it/s]

                   all        230       1440      0.984      0.977      0.988      0.669

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      16/32      11.6G      1.163     0.4932      1.111        231        512: 100%|██████████| 29/29 [00:26<00:00,  1.11it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  2.18it/s]

                   all        230       1440      0.989      0.988      0.986       0.66

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      17/32      11.4G      1.163       0.49      1.107        275        512: 100%|██████████| 29/29 [00:26<00:00,  1.11it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  2.14it/s]

                   all        230       1440      0.972       0.98      0.984      0.644

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      18/32      11.6G      1.152     0.4737      1.107        260        512: 100%|██████████| 29/29 [00:26<00:00,  1.11it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  2.15it/s]

                   all        230       1440      0.984      0.981      0.986      0.674

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      19/32      11.4G      1.151     0.4753      1.108        187        512: 100%|██████████| 29/29 [00:26<00:00,  1.11it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  2.17it/s]

                   all        230       1440      0.982      0.978      0.984      0.665

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      20/32      11.6G      1.123     0.4675      1.084        223        512: 100%|██████████| 29/29 [00:26<00:00,  1.11it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  2.17it/s]

                   all        230       1440      0.986      0.985      0.985      0.677

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      21/32      11.4G      1.111     0.4591      1.085        232        512: 100%|██████████| 29/29 [00:26<00:00,  1.11it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  2.14it/s]

                   all        230       1440      0.988      0.987      0.988       0.67

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      22/32      11.6G      1.102     0.4551      1.072        242        512: 100%|██████████| 29/29 [00:26<00:00,  1.11it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  2.17it/s]

                   all        230       1440      0.989      0.987      0.989      0.681

Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      23/32      11.5G      1.094     0.4081       1.14        147        512: 100%|██████████| 29/29 [00:26<00:00,  1.08it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  2.15it/s]

                   all        230       1440      0.989      0.988      0.987      0.676

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      24/32      11.6G      1.076     0.3957      1.131        127        512: 100%|██████████| 29/29 [00:26<00:00,  1.12it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  2.19it/s]

                   all        230       1440      0.987      0.984      0.988      0.677

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      25/32      11.4G      1.058     0.3899      1.126        121        512: 100%|██████████| 29/29 [00:26<00:00,  1.11it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  2.17it/s]

                   all        230       1440      0.981      0.987      0.986      0.676

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      26/32      11.6G      1.036     0.3796      1.104        141        512: 100%|██████████| 29/29 [00:26<00:00,  1.12it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  2.21it/s]

                   all        230       1440      0.989      0.988      0.986      0.682

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      27/32      11.5G      1.026     0.3762      1.104        138        512: 100%|██████████| 29/29 [00:25<00:00,  1.12it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  2.18it/s]

                   all        230       1440      0.989      0.988      0.987      0.686

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      28/32      11.6G      1.012     0.3763      1.098        136        512: 100%|██████████| 29/29 [00:26<00:00,  1.11it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  2.16it/s]

                   all        230       1440      0.989      0.988      0.988      0.693

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      29/32      11.4G      0.992     0.3615      1.094        145        512: 100%|██████████| 29/29 [00:26<00:00,  1.12it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  2.17it/s]

                   all        230       1440      0.987      0.987      0.987       0.69

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      30/32      11.6G     0.9793     0.3581      1.086        140        512: 100%|██████████| 29/29 [00:26<00:00,  1.12it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  2.16it/s]

                   all        230       1440      0.989      0.988      0.987      0.686

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      31/32      11.4G     0.9599      0.349      1.078        124        512: 100%|██████████| 29/29 [00:25<00:00,  1.12it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  2.19it/s]

                   all        230       1440      0.988      0.988      0.987      0.688

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      32/32      11.6G     0.9476     0.3451      1.072        142        512: 100%|██████████| 29/29 [00:26<00:00,  1.11it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:01<00:00,  2.16it/s]

                   all        230       1440       0.99      0.988      0.988      0.692

32 epochs completed in 0.257 hours.
Optimizer stripped from runs/detect/train12/weights/last.pt, 52.0MB
Optimizer stripped from runs/detect/train12/weights/best.pt, 52.0MB

Validating runs/detect/train12/weights/best.pt...
Ultralytics 8.3.185 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
Model summary (fused): 92 layers, 25,843,234 parameters, 0 gradients, 78.7 GFLOPs

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:03<00:00,  1.24it/s]
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        230       1440      0.989      0.988      0.988      0.693
     DC Voltage Source        103        144          1      0.966      0.985      0.769
              Resistor        183        605      0.985      0.992      0.987      0.663
        Current Source        113        150      0.967          1      0.982      0.736
              Inductor        117        177      0.993      0.989      0.992      0.639
             Capacitor        115        184      0.993      0.989      0.988      0.629
     AC Voltage Source         65        180      0.994       0.99      0.993      0.719
Speed: 0.1ms preprocess, 5.4ms inference, 0.0ms loss, 1.8ms postprocess per image
Results saved to runs/detect/train12

🚀 Case 5: Image Size | Experiment 3: imgsz=640
Ultralytics 8.3.185 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-component-data/YOLO_component-dataset/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8m.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train13, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/train13, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.001, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=6

                   from  n    params  module                                       arguments
  0                  -1  1      1392  ultralytics.nn.modules.conv.Conv             [3, 48, 3, 2]
  1                  -1  1     41664  ultralytics.nn.modules.conv.Conv             [48, 96, 3, 2]
  2                  -1  2    111360  ultralytics.nn.modules.block.C2f             [96, 96, 2, True]
  3                  -1  1    166272  ultralytics.nn.modules.conv.Conv             [96, 192, 3, 2]
  4                  -1  4    813312  ultralytics.nn.modules.block.C2f             [192, 192, 4, True]
  5                  -1  1    664320  ultralytics.nn.modules.conv.Conv             [192, 384, 3, 2]
  6                  -1  4   3248640  ultralytics.nn.modules.block.C2f             [384, 384, 4, True]
  7                  -1  1   1991808  ultralytics.nn.modules.conv.Conv             [384, 576, 3, 2]
  8                  -1  2   3985920  ultralytics.nn.modules.block.C2f             [576, 576, 2, True]
  9                  -1  1    831168  ultralytics.nn.modules.block.SPPF            [576, 576, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  2   1993728  ultralytics.nn.modules.block.C2f             [960, 384, 2]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  2    517632  ultralytics.nn.modules.block.C2f             [576, 192, 2]
 16                  -1  1    332160  ultralytics.nn.modules.conv.Conv             [192, 192, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  2   1846272  ultralytics.nn.modules.block.C2f             [576, 384, 2]
 19                  -1  1   1327872  ultralytics.nn.modules.conv.Conv             [384, 384, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  2   4207104  ultralytics.nn.modules.block.C2f             [960, 576, 2]
 22        [15, 18, 21]  1   3779170  ultralytics.nn.modules.head.Detect           [6, [192, 384, 576]]
Model summary: 169 layers, 25,859,794 parameters, 25,859,778 gradients, 79.1 GFLOPs

Transferred 469/475 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 51.1±35.7 MB/s, size: 51.9 KB)

train: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/train/labels... 919 images, 0 backgrounds, 0 corrupt: 100%|██████████| 919/919 [00:01<00:00, 535.51it/s]

WARNING ⚠️ train: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 25.3±13.3 MB/s, size: 35.4 KB)

val: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels... 230 images, 0 backgrounds, 0 corrupt: 100%|██████████| 230/230 [00:00<00:00, 376.33it/s]

WARNING ⚠️ val: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/val is not writeable, cache not saved.

Plotting labels to runs/detect/train13/labels.jpg...
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 77 weight(decay=0.0), 84 weight(decay=0.001), 83 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs/detect/train13
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       1/32      14.1G      2.554      3.684       2.06        249        640: 100%|██████████| 29/29 [00:32<00:00,  1.12s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:03<00:00,  1.33it/s]

                   all        230       1440       0.67      0.688      0.714      0.407

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       2/32      13.9G      1.388      1.031      1.284        222        640: 100%|██████████| 29/29 [00:32<00:00,  1.11s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.59it/s]

                   all        230       1440       0.91      0.943      0.972      0.576

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       3/32      13.9G      1.354     0.8712      1.258        203        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.61it/s]

                   all        230       1440      0.957      0.975      0.979      0.623

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       4/32        14G      1.343     0.7808      1.244        242        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.61it/s]

                   all        230       1440       0.98       0.98      0.988      0.651

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       5/32      13.9G        1.3     0.6796      1.231        250        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.61it/s]

                   all        230       1440      0.974      0.964      0.982      0.648

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       6/32        14G      1.286     0.6039      1.235        251        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.984      0.983      0.986      0.627

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       7/32      13.9G      1.259     0.5836      1.216        257        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440       0.98      0.982      0.982       0.64

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       8/32      13.9G      1.262     0.5733      1.217        273        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.976       0.98      0.982      0.605

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       9/32      13.9G      1.258     0.5537      1.221        265        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.969      0.978      0.984      0.655

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      10/32        14G      1.232     0.5539      1.202        233        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.65it/s]

                   all        230       1440      0.988      0.982      0.987      0.633

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      11/32      13.9G      1.223     0.5346      1.214        282        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.65it/s]

                   all        230       1440      0.989      0.984      0.988      0.655

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      12/32        14G      1.217     0.5251      1.219        205        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.65it/s]

                   all        230       1440      0.987      0.986      0.988      0.662

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      13/32      13.9G      1.186     0.5148      1.194        219        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.65it/s]

                   all        230       1440       0.99      0.986      0.989      0.652

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      14/32        14G      1.191     0.5082      1.204        239        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440      0.985      0.985      0.986       0.66

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      15/32      13.9G      1.197     0.4964      1.214        254        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.982      0.983      0.987      0.672

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      16/32        14G      1.158     0.4899      1.211        231        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.985      0.989      0.987      0.676

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      17/32      13.9G       1.16     0.4824      1.211        275        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.981       0.98      0.986      0.671

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      18/32        14G       1.15     0.4686      1.222        261        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.987      0.983      0.985      0.678

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      19/32      13.9G      1.145     0.4676      1.219        187        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.987      0.984      0.987      0.669

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      20/32        14G      1.118     0.4547       1.18        223        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440      0.989      0.983      0.988      0.677

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      21/32      13.9G      1.107     0.4494      1.184        232        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.65it/s]

                   all        230       1440      0.989      0.989      0.987      0.686

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      22/32        14G      1.095     0.4451      1.168        242        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.61it/s]

                   all        230       1440      0.988      0.986      0.988      0.684

Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      23/32      13.9G      1.089     0.4029      1.238        147        640: 100%|██████████| 29/29 [00:33<00:00,  1.16s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440       0.99      0.989      0.988       0.68

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      24/32        14G      1.068     0.3902       1.23        127        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.989      0.986      0.987      0.678

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      25/32      13.9G      1.051     0.3857      1.227        121        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.987      0.987      0.988       0.67

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      26/32        14G      1.031      0.373      1.204        141        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.987      0.989      0.987      0.685

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      27/32      13.9G      1.016      0.371      1.199        138        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440       0.99      0.989      0.986      0.687

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      28/32      13.9G      1.004     0.3684      1.199        136        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.65it/s]

                   all        230       1440       0.99      0.989      0.988      0.689

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      29/32      13.9G     0.9873     0.3578      1.192        145        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.992      0.989      0.988       0.69

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      30/32        14G     0.9779     0.3549      1.177        140        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.991       0.99      0.987      0.685

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      31/32      13.9G     0.9527     0.3435      1.178        124        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.991       0.99      0.987      0.691

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      32/32        14G     0.9411      0.342      1.159        142        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.65it/s]

                   all        230       1440      0.991      0.989      0.988      0.691

32 epochs completed in 0.316 hours.
Optimizer stripped from runs/detect/train13/weights/last.pt, 52.0MB
Optimizer stripped from runs/detect/train13/weights/best.pt, 52.0MB

Validating runs/detect/train13/weights/best.pt...
Ultralytics 8.3.185 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
Model summary (fused): 92 layers, 25,843,234 parameters, 0 gradients, 78.7 GFLOPs

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:03<00:00,  1.05it/s]
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        230       1440      0.991      0.991      0.987      0.692
     DC Voltage Source        103        144          1      0.979      0.984       0.76
              Resistor        183        605      0.985      0.992      0.987      0.649
        Current Source        113        150      0.982          1      0.984      0.739
              Inductor        117        177      0.994      0.988       0.99      0.647
             Capacitor        115        184      0.993      0.989      0.985      0.639
     AC Voltage Source         65        180      0.993      0.994      0.995      0.717
Speed: 0.1ms preprocess, 8.2ms inference, 0.0ms loss, 3.2ms postprocess per image
Results saved to runs/detect/train13

,Case,Experiment No,Experiment Name,Epochs,Batch,lr0,Weight Decay,Optimizer,Image Size,Dropout,Freeze Layers,Activation,Training Time (s),Precision,Recall,mAP@0.5,mAP@0.5:0.95
0,Case 4: Dropout,1,dropout_0,32,32,0.01,0.001,SGD,640,0.0,0,SiLU,1176.32,0.991306,0.990508,0.987335,0.691970
1,Case 4: Dropout,2,dropout_0.1,32,32,0.01,0.001,SGD,640,0.1,0,SiLU,1161.46,0.991306,0.990508,0.987335,0.691970
2,Case 4: Dropout,3,dropout_0.2,32,32,0.01,0.001,SGD,640,0.2,0,SiLU,1161.13,0.991306,0.990508,0.987335,0.691970
3,Case 4: Dropout,4,dropout_0.3,32,32,0.01,0.001,SGD,640,0.3,0,SiLU,1160.67,0.991306,0.990508,0.987335,0.691970
4,Case 4: Dropout,5,dropout_0.5,32,32,0.01,0.001,SGD,640,0.5,0,SiLU,1164.58,0.991306,0.990508,0.987335,0.691970
5,Case 6: Optimizer,1,optimizer_SGD,32,32,0.01,0.001,SGD,640,0.0,0,SiLU,1161.23,0.991306,0.990508,0.987335,0.691970
6,Case 6: Optimizer,2,optimizer_Adam,32,32,0.01,0.001,Adam,640,0.0,0,SiLU,1172.61,0.986126,0.986969,0.987008,0.681319
7,Case 6: Optimizer,3,optimizer_AdamW,32,32,0.01,0.001,AdamW,640,0.0,0,SiLU,1168.31,0.986241,0.985495,0.988257,0.687184
8,Case 6: Optimizer,4,optimizer_RMSProp,32,32,0.01,0.001,RMSProp,640,0.0,0,SiLU,1219.09,0.284918,0.290732,0.277995,0.159001
9,Case 6: Optimizer,5,optimizer_Adamax,32,32,0.01,0.001,Adamax,640,0.0,0,SiLU,1171.89,0.988610,0.987190,0.988335,0.691340
10,Case 5: Image Size,1,imgsz_320,32,32,0.01,0.001,SGD,320,0.0,0,SiLU,366.28,0.991036,0.987418,0.987867,0.693141
11,Case 5: Image Size,2,imgsz_512,32,32,0.01,0.001,SGD,512,0.0,0,SiLU,944.04,0.988780,0.987842,0.988072,0.692527
12,Case 5: Image Size,3,imgsz_640,32,32,0.01,0.001,SGD,640,0.0,0,SiLU,1156.88,0.991306,0.990508,0.987335,0.691970

In [ ]:
# Case 8: Freeze Layers
run_ablation("Case 8: Freeze Layers", "freeze", [0, 10, 15, 22])

🚀 Case 8: Freeze Layers | Experiment 1: freeze=0
Ultralytics 8.3.185 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-component-data/YOLO_component-dataset/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8m.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train14, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/train14, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.001, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=6

                   from  n    params  module                                       arguments
  0                  -1  1      1392  ultralytics.nn.modules.conv.Conv             [3, 48, 3, 2]
  1                  -1  1     41664  ultralytics.nn.modules.conv.Conv             [48, 96, 3, 2]
  2                  -1  2    111360  ultralytics.nn.modules.block.C2f             [96, 96, 2, True]
  3                  -1  1    166272  ultralytics.nn.modules.conv.Conv             [96, 192, 3, 2]
  4                  -1  4    813312  ultralytics.nn.modules.block.C2f             [192, 192, 4, True]
  5                  -1  1    664320  ultralytics.nn.modules.conv.Conv             [192, 384, 3, 2]
  6                  -1  4   3248640  ultralytics.nn.modules.block.C2f             [384, 384, 4, True]
  7                  -1  1   1991808  ultralytics.nn.modules.conv.Conv             [384, 576, 3, 2]
  8                  -1  2   3985920  ultralytics.nn.modules.block.C2f             [576, 576, 2, True]
  9                  -1  1    831168  ultralytics.nn.modules.block.SPPF            [576, 576, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  2   1993728  ultralytics.nn.modules.block.C2f             [960, 384, 2]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  2    517632  ultralytics.nn.modules.block.C2f             [576, 192, 2]
 16                  -1  1    332160  ultralytics.nn.modules.conv.Conv             [192, 192, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  2   1846272  ultralytics.nn.modules.block.C2f             [576, 384, 2]
 19                  -1  1   1327872  ultralytics.nn.modules.conv.Conv             [384, 384, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  2   4207104  ultralytics.nn.modules.block.C2f             [960, 576, 2]
 22        [15, 18, 21]  1   3779170  ultralytics.nn.modules.head.Detect           [6, [192, 384, 576]]
Model summary: 169 layers, 25,859,794 parameters, 25,859,778 gradients, 79.1 GFLOPs

Transferred 469/475 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 44.3±35.5 MB/s, size: 51.9 KB)

train: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/train/labels... 919 images, 0 backgrounds, 0 corrupt: 100%|██████████| 919/919 [00:02<00:00, 434.15it/s]

WARNING ⚠️ train: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 22.7±12.4 MB/s, size: 35.4 KB)

val: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels... 230 images, 0 backgrounds, 0 corrupt: 100%|██████████| 230/230 [00:00<00:00, 282.31it/s]

WARNING ⚠️ val: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/val is not writeable, cache not saved.

Plotting labels to runs/detect/train14/labels.jpg...
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 77 weight(decay=0.0), 84 weight(decay=0.001), 83 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs/detect/train14
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       1/32      13.7G      2.554      3.684       2.06        249        640: 100%|██████████| 29/29 [00:32<00:00,  1.12s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.34it/s]

                   all        230       1440       0.67      0.688      0.714      0.407

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       2/32      13.9G      1.388      1.031      1.284        222        640: 100%|██████████| 29/29 [00:32<00:00,  1.11s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.60it/s]

                   all        230       1440       0.91      0.943      0.972      0.576

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       3/32      13.9G      1.354     0.8712      1.258        203        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440      0.957      0.975      0.979      0.623

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       4/32      13.9G      1.343     0.7808      1.244        242        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440       0.98       0.98      0.988      0.651

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       5/32      13.9G        1.3     0.6796      1.231        250        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440      0.974      0.964      0.982      0.648

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       6/32      13.9G      1.286     0.6039      1.235        251        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.984      0.983      0.986      0.627

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       7/32      13.9G      1.259     0.5836      1.216        257        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440       0.98      0.982      0.982       0.64

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       8/32        14G      1.262     0.5733      1.217        273        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.65it/s]

                   all        230       1440      0.976       0.98      0.982      0.605

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       9/32      13.9G      1.258     0.5537      1.221        265        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.969      0.978      0.984      0.655

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      10/32      13.9G      1.232     0.5539      1.202        233        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.988      0.982      0.987      0.633

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      11/32      13.9G      1.223     0.5346      1.214        282        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440      0.989      0.984      0.988      0.655

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      12/32      13.9G      1.217     0.5251      1.219        205        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.987      0.986      0.988      0.662

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      13/32      13.9G      1.186     0.5148      1.194        219        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440       0.99      0.986      0.989      0.652

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      14/32      13.9G      1.191     0.5082      1.204        239        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.985      0.985      0.986       0.66

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      15/32      13.9G      1.197     0.4964      1.214        254        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.982      0.983      0.987      0.672

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      16/32      13.9G      1.158     0.4899      1.211        231        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.985      0.989      0.987      0.676

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      17/32      13.9G       1.16     0.4824      1.211        275        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.65it/s]

                   all        230       1440      0.981       0.98      0.986      0.671

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      18/32      13.9G       1.15     0.4686      1.222        261        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.66it/s]

                   all        230       1440      0.987      0.983      0.985      0.678

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      19/32      13.9G      1.145     0.4676      1.219        187        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.65it/s]

                   all        230       1440      0.987      0.984      0.987      0.669

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      20/32      13.9G      1.118     0.4547       1.18        223        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440      0.989      0.983      0.988      0.677

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      21/32      13.9G      1.107     0.4494      1.184        232        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.60it/s]

                   all        230       1440      0.989      0.989      0.987      0.686

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      22/32      13.9G      1.095     0.4451      1.168        242        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.988      0.986      0.988      0.684

Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      23/32      13.9G      1.089     0.4029      1.238        147        640: 100%|██████████| 29/29 [00:33<00:00,  1.14s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440       0.99      0.989      0.988       0.68

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      24/32      13.9G      1.068     0.3902       1.23        127        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.989      0.986      0.987      0.678

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      25/32      13.9G      1.051     0.3857      1.227        121        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.66it/s]

                   all        230       1440      0.987      0.987      0.988       0.67

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      26/32      13.9G      1.031      0.373      1.204        141        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.65it/s]

                   all        230       1440      0.987      0.989      0.987      0.685

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      27/32      13.9G      1.016      0.371      1.199        138        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.66it/s]

                   all        230       1440       0.99      0.989      0.986      0.687

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      28/32      13.9G      1.004     0.3684      1.199        136        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440       0.99      0.989      0.988      0.689

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      29/32      13.9G     0.9873     0.3578      1.192        145        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.65it/s]

                   all        230       1440      0.992      0.989      0.988       0.69

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      30/32      13.9G     0.9779     0.3549      1.177        140        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.991       0.99      0.987      0.685

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      31/32      13.9G     0.9527     0.3435      1.178        124        640: 100%|██████████| 29/29 [00:31<00:00,  1.09s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.65it/s]

                   all        230       1440      0.991       0.99      0.987      0.691

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      32/32      13.9G     0.9411      0.342      1.159        142        640: 100%|██████████| 29/29 [00:31<00:00,  1.10s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.991      0.989      0.988      0.691

32 epochs completed in 0.316 hours.
Optimizer stripped from runs/detect/train14/weights/last.pt, 52.0MB
Optimizer stripped from runs/detect/train14/weights/best.pt, 52.0MB

Validating runs/detect/train14/weights/best.pt...
Ultralytics 8.3.185 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
Model summary (fused): 92 layers, 25,843,234 parameters, 0 gradients, 78.7 GFLOPs

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:03<00:00,  1.06it/s]
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        230       1440      0.991      0.991      0.987      0.692
     DC Voltage Source        103        144          1      0.979      0.984       0.76
              Resistor        183        605      0.985      0.992      0.987      0.649
        Current Source        113        150      0.982          1      0.984      0.739
              Inductor        117        177      0.994      0.988       0.99      0.647
             Capacitor        115        184      0.993      0.989      0.985      0.639
     AC Voltage Source         65        180      0.993      0.994      0.995      0.717
Speed: 0.1ms preprocess, 8.1ms inference, 0.0ms loss, 3.3ms postprocess per image
Results saved to runs/detect/train14

🚀 Case 8: Freeze Layers | Experiment 2: freeze=10
Ultralytics 8.3.185 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-component-data/YOLO_component-dataset/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=10, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8m.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train15, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/train15, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.001, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=6

                   from  n    params  module                                       arguments
  0                  -1  1      1392  ultralytics.nn.modules.conv.Conv             [3, 48, 3, 2]
  1                  -1  1     41664  ultralytics.nn.modules.conv.Conv             [48, 96, 3, 2]
  2                  -1  2    111360  ultralytics.nn.modules.block.C2f             [96, 96, 2, True]
  3                  -1  1    166272  ultralytics.nn.modules.conv.Conv             [96, 192, 3, 2]
  4                  -1  4    813312  ultralytics.nn.modules.block.C2f             [192, 192, 4, True]
  5                  -1  1    664320  ultralytics.nn.modules.conv.Conv             [192, 384, 3, 2]
  6                  -1  4   3248640  ultralytics.nn.modules.block.C2f             [384, 384, 4, True]
  7                  -1  1   1991808  ultralytics.nn.modules.conv.Conv             [384, 576, 3, 2]
  8                  -1  2   3985920  ultralytics.nn.modules.block.C2f             [576, 576, 2, True]
  9                  -1  1    831168  ultralytics.nn.modules.block.SPPF            [576, 576, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  2   1993728  ultralytics.nn.modules.block.C2f             [960, 384, 2]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  2    517632  ultralytics.nn.modules.block.C2f             [576, 192, 2]
 16                  -1  1    332160  ultralytics.nn.modules.conv.Conv             [192, 192, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  2   1846272  ultralytics.nn.modules.block.C2f             [576, 384, 2]
 19                  -1  1   1327872  ultralytics.nn.modules.conv.Conv             [384, 384, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  2   4207104  ultralytics.nn.modules.block.C2f             [960, 576, 2]
 22        [15, 18, 21]  1   3779170  ultralytics.nn.modules.head.Detect           [6, [192, 384, 576]]
Model summary: 169 layers, 25,859,794 parameters, 25,859,778 gradients, 79.1 GFLOPs

Transferred 469/475 items from pretrained weights
Freezing layer 'model.0.conv.weight'
Freezing layer 'model.0.bn.weight'
Freezing layer 'model.0.bn.bias'
Freezing layer 'model.1.conv.weight'
Freezing layer 'model.1.bn.weight'
Freezing layer 'model.1.bn.bias'
Freezing layer 'model.2.cv1.conv.weight'
Freezing layer 'model.2.cv1.bn.weight'
Freezing layer 'model.2.cv1.bn.bias'
Freezing layer 'model.2.cv2.conv.weight'
Freezing layer 'model.2.cv2.bn.weight'
Freezing layer 'model.2.cv2.bn.bias'
Freezing layer 'model.2.m.0.cv1.conv.weight'
Freezing layer 'model.2.m.0.cv1.bn.weight'
Freezing layer 'model.2.m.0.cv1.bn.bias'
Freezing layer 'model.2.m.0.cv2.conv.weight'
Freezing layer 'model.2.m.0.cv2.bn.weight'
Freezing layer 'model.2.m.0.cv2.bn.bias'
Freezing layer 'model.2.m.1.cv1.conv.weight'
Freezing layer 'model.2.m.1.cv1.bn.weight'
Freezing layer 'model.2.m.1.cv1.bn.bias'
Freezing layer 'model.2.m.1.cv2.conv.weight'
Freezing layer 'model.2.m.1.cv2.bn.weight'
Freezing layer 'model.2.m.1.cv2.bn.bias'
Freezing layer 'model.3.conv.weight'
Freezing layer 'model.3.bn.weight'
Freezing layer 'model.3.bn.bias'
Freezing layer 'model.4.cv1.conv.weight'
Freezing layer 'model.4.cv1.bn.weight'
Freezing layer 'model.4.cv1.bn.bias'
Freezing layer 'model.4.cv2.conv.weight'
Freezing layer 'model.4.cv2.bn.weight'
Freezing layer 'model.4.cv2.bn.bias'
Freezing layer 'model.4.m.0.cv1.conv.weight'
Freezing layer 'model.4.m.0.cv1.bn.weight'
Freezing layer 'model.4.m.0.cv1.bn.bias'
Freezing layer 'model.4.m.0.cv2.conv.weight'
Freezing layer 'model.4.m.0.cv2.bn.weight'
Freezing layer 'model.4.m.0.cv2.bn.bias'
Freezing layer 'model.4.m.1.cv1.conv.weight'
Freezing layer 'model.4.m.1.cv1.bn.weight'
Freezing layer 'model.4.m.1.cv1.bn.bias'
Freezing layer 'model.4.m.1.cv2.conv.weight'
Freezing layer 'model.4.m.1.cv2.bn.weight'
Freezing layer 'model.4.m.1.cv2.bn.bias'
Freezing layer 'model.4.m.2.cv1.conv.weight'
Freezing layer 'model.4.m.2.cv1.bn.weight'
Freezing layer 'model.4.m.2.cv1.bn.bias'
Freezing layer 'model.4.m.2.cv2.conv.weight'
Freezing layer 'model.4.m.2.cv2.bn.weight'
Freezing layer 'model.4.m.2.cv2.bn.bias'
Freezing layer 'model.4.m.3.cv1.conv.weight'
Freezing layer 'model.4.m.3.cv1.bn.weight'
Freezing layer 'model.4.m.3.cv1.bn.bias'
Freezing layer 'model.4.m.3.cv2.conv.weight'
Freezing layer 'model.4.m.3.cv2.bn.weight'
Freezing layer 'model.4.m.3.cv2.bn.bias'
Freezing layer 'model.5.conv.weight'
Freezing layer 'model.5.bn.weight'
Freezing layer 'model.5.bn.bias'
Freezing layer 'model.6.cv1.conv.weight'
Freezing layer 'model.6.cv1.bn.weight'
Freezing layer 'model.6.cv1.bn.bias'
Freezing layer 'model.6.cv2.conv.weight'
Freezing layer 'model.6.cv2.bn.weight'
Freezing layer 'model.6.cv2.bn.bias'
Freezing layer 'model.6.m.0.cv1.conv.weight'
Freezing layer 'model.6.m.0.cv1.bn.weight'
Freezing layer 'model.6.m.0.cv1.bn.bias'
Freezing layer 'model.6.m.0.cv2.conv.weight'
Freezing layer 'model.6.m.0.cv2.bn.weight'
Freezing layer 'model.6.m.0.cv2.bn.bias'
Freezing layer 'model.6.m.1.cv1.conv.weight'
Freezing layer 'model.6.m.1.cv1.bn.weight'
Freezing layer 'model.6.m.1.cv1.bn.bias'
Freezing layer 'model.6.m.1.cv2.conv.weight'
Freezing layer 'model.6.m.1.cv2.bn.weight'
Freezing layer 'model.6.m.1.cv2.bn.bias'
Freezing layer 'model.6.m.2.cv1.conv.weight'
Freezing layer 'model.6.m.2.cv1.bn.weight'
Freezing layer 'model.6.m.2.cv1.bn.bias'
Freezing layer 'model.6.m.2.cv2.conv.weight'
Freezing layer 'model.6.m.2.cv2.bn.weight'
Freezing layer 'model.6.m.2.cv2.bn.bias'
Freezing layer 'model.6.m.3.cv1.conv.weight'
Freezing layer 'model.6.m.3.cv1.bn.weight'
Freezing layer 'model.6.m.3.cv1.bn.bias'
Freezing layer 'model.6.m.3.cv2.conv.weight'
Freezing layer 'model.6.m.3.cv2.bn.weight'
Freezing layer 'model.6.m.3.cv2.bn.bias'
Freezing layer 'model.7.conv.weight'
Freezing layer 'model.7.bn.weight'
Freezing layer 'model.7.bn.bias'
Freezing layer 'model.8.cv1.conv.weight'
Freezing layer 'model.8.cv1.bn.weight'
Freezing layer 'model.8.cv1.bn.bias'
Freezing layer 'model.8.cv2.conv.weight'
Freezing layer 'model.8.cv2.bn.weight'
Freezing layer 'model.8.cv2.bn.bias'
Freezing layer 'model.8.m.0.cv1.conv.weight'
Freezing layer 'model.8.m.0.cv1.bn.weight'
Freezing layer 'model.8.m.0.cv1.bn.bias'
Freezing layer 'model.8.m.0.cv2.conv.weight'
Freezing layer 'model.8.m.0.cv2.bn.weight'
Freezing layer 'model.8.m.0.cv2.bn.bias'
Freezing layer 'model.8.m.1.cv1.conv.weight'
Freezing layer 'model.8.m.1.cv1.bn.weight'
Freezing layer 'model.8.m.1.cv1.bn.bias'
Freezing layer 'model.8.m.1.cv2.conv.weight'
Freezing layer 'model.8.m.1.cv2.bn.weight'
Freezing layer 'model.8.m.1.cv2.bn.bias'
Freezing layer 'model.9.cv1.conv.weight'
Freezing layer 'model.9.cv1.bn.weight'
Freezing layer 'model.9.cv1.bn.bias'
Freezing layer 'model.9.cv2.conv.weight'
Freezing layer 'model.9.cv2.bn.weight'
Freezing layer 'model.9.cv2.bn.bias'
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 51.2±35.0 MB/s, size: 51.9 KB)

train: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/train/labels... 919 images, 0 backgrounds, 0 corrupt: 100%|██████████| 919/919 [00:01<00:00, 474.83it/s]

WARNING ⚠️ train: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 25.5±13.5 MB/s, size: 35.4 KB)

val: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels... 230 images, 0 backgrounds, 0 corrupt: 100%|██████████| 230/230 [00:01<00:00, 184.98it/s]

WARNING ⚠️ val: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/val is not writeable, cache not saved.

Plotting labels to runs/detect/train15/labels.jpg...
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 77 weight(decay=0.0), 84 weight(decay=0.001), 83 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs/detect/train15
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       1/32      5.96G      2.462      3.019       2.12        249        640: 100%|██████████| 29/29 [00:18<00:00,  1.58it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.45it/s]

                   all        230       1440      0.795      0.733      0.858      0.513

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       2/32      7.74G      1.353      1.057      1.262        222        640: 100%|██████████| 29/29 [00:17<00:00,  1.61it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.938      0.945      0.975      0.628

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       3/32      7.78G      1.356     0.8849      1.262        203        640: 100%|██████████| 29/29 [00:17<00:00,  1.63it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.65it/s]

                   all        230       1440      0.908      0.973      0.981      0.611

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       4/32      7.82G       1.32     0.8511      1.233        242        640: 100%|██████████| 29/29 [00:17<00:00,  1.63it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.66it/s]

                   all        230       1440      0.957       0.97      0.984      0.626

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       5/32      7.85G      1.309     0.7009      1.229        250        640: 100%|██████████| 29/29 [00:17<00:00,  1.63it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.67it/s]

                   all        230       1440      0.966      0.981      0.986      0.645

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       6/32      7.89G       1.28     0.6398      1.225        251        640: 100%|██████████| 29/29 [00:17<00:00,  1.63it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.959      0.963      0.983      0.638

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       7/32      7.92G      1.262     0.6186      1.213        257        640: 100%|██████████| 29/29 [00:17<00:00,  1.63it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.66it/s]

                   all        230       1440      0.977      0.982      0.984      0.638

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       8/32      7.96G      1.266     0.6077      1.216        273        640: 100%|██████████| 29/29 [00:17<00:00,  1.63it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.60it/s]

                   all        230       1440      0.983      0.985      0.985      0.657

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       9/32      5.79G      1.257     0.5789      1.218        265        640: 100%|██████████| 29/29 [00:17<00:00,  1.63it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.65it/s]

                   all        230       1440       0.98      0.975      0.983      0.658

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      10/32      5.79G      1.237     0.5721      1.199        233        640: 100%|██████████| 29/29 [00:17<00:00,  1.62it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.63it/s]

                   all        230       1440      0.986      0.984      0.988      0.653

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      11/32      5.79G      1.226     0.5601      1.205        282        640: 100%|██████████| 29/29 [00:17<00:00,  1.63it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.57it/s]

                   all        230       1440      0.981      0.985      0.987      0.657

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      12/32      5.81G      1.228     0.5538      1.213        205        640: 100%|██████████| 29/29 [00:17<00:00,  1.63it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.986      0.985      0.988      0.663

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      13/32      5.85G      1.202      0.543      1.189        219        640: 100%|██████████| 29/29 [00:17<00:00,  1.63it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.65it/s]

                   all        230       1440      0.984      0.986      0.986      0.668

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      14/32      5.88G      1.208     0.5409       1.19        239        640: 100%|██████████| 29/29 [00:17<00:00,  1.63it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.65it/s]

                   all        230       1440      0.985      0.984      0.987      0.665

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      15/32      5.92G      1.206     0.5234      1.185        254        640: 100%|██████████| 29/29 [00:17<00:00,  1.63it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.988      0.989      0.986      0.654

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      16/32      5.96G      1.183     0.5192       1.19        231        640: 100%|██████████| 29/29 [00:17<00:00,  1.63it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.66it/s]

                   all        230       1440      0.985      0.987      0.987      0.673

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      17/32      5.99G       1.18     0.5088      1.181        275        640: 100%|██████████| 29/29 [00:17<00:00,  1.63it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.65it/s]

                   all        230       1440      0.986      0.985      0.988       0.67

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      18/32      6.03G      1.169     0.4927      1.179        261        640: 100%|██████████| 29/29 [00:17<00:00,  1.63it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.983      0.985      0.986      0.678

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      19/32      6.06G      1.173     0.5041      1.187        187        640: 100%|██████████| 29/29 [00:17<00:00,  1.63it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.66it/s]

                   all        230       1440      0.989      0.987      0.988      0.671

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      20/32       6.1G      1.153     0.4894      1.161        223        640: 100%|██████████| 29/29 [00:17<00:00,  1.63it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.985      0.985      0.987       0.67

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      21/32      6.13G      1.136     0.4837      1.154        232        640: 100%|██████████| 29/29 [00:17<00:00,  1.63it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.66it/s]

                   all        230       1440      0.987      0.989      0.987       0.68

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      22/32      6.17G      1.131     0.4794       1.15        242        640: 100%|██████████| 29/29 [00:17<00:00,  1.63it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.985      0.989      0.987      0.677

Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      23/32       6.2G      1.118     0.4305      1.215        147        640: 100%|██████████| 29/29 [00:18<00:00,  1.53it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.66it/s]

                   all        230       1440      0.989      0.988      0.986       0.67

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      24/32      6.23G      1.104     0.4193      1.208        127        640: 100%|██████████| 29/29 [00:17<00:00,  1.64it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440      0.989      0.987      0.987      0.677

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      25/32      6.27G      1.099     0.4147      1.206        121        640: 100%|██████████| 29/29 [00:17<00:00,  1.64it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440      0.988       0.99      0.988      0.677

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      26/32       6.3G       1.08     0.4072      1.192        141        640: 100%|██████████| 29/29 [00:17<00:00,  1.64it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.67it/s]

                   all        230       1440      0.987      0.989      0.987      0.686

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      27/32      6.34G      1.078     0.4027      1.194        138        640: 100%|██████████| 29/29 [00:17<00:00,  1.64it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.66it/s]

                   all        230       1440      0.988      0.989      0.987      0.689

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      28/32      6.38G      1.068     0.3988      1.188        136        640: 100%|██████████| 29/29 [00:17<00:00,  1.64it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440       0.99       0.99      0.989      0.687

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      29/32      6.41G      1.057     0.3925      1.192        145        640: 100%|██████████| 29/29 [00:17<00:00,  1.64it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.65it/s]

                   all        230       1440      0.989      0.989      0.987      0.687

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      30/32      6.45G      1.047     0.3883      1.174        140        640: 100%|██████████| 29/29 [00:17<00:00,  1.64it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.65it/s]

                   all        230       1440      0.989       0.99      0.989      0.687

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      31/32      6.48G      1.035     0.3769       1.18        124        640: 100%|██████████| 29/29 [00:17<00:00,  1.64it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.64it/s]

                   all        230       1440      0.989      0.989      0.988      0.686

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      32/32      6.52G      1.029     0.3744      1.166        142        640: 100%|██████████| 29/29 [00:17<00:00,  1.64it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.61it/s]

                   all        230       1440      0.989      0.988      0.989      0.688

32 epochs completed in 0.185 hours.
Optimizer stripped from runs/detect/train15/weights/last.pt, 52.0MB
Optimizer stripped from runs/detect/train15/weights/best.pt, 52.0MB

Validating runs/detect/train15/weights/best.pt...
Ultralytics 8.3.185 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
Model summary (fused): 92 layers, 25,843,234 parameters, 0 gradients, 78.7 GFLOPs

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:03<00:00,  1.02it/s]
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        230       1440      0.988       0.99      0.987      0.689
     DC Voltage Source        103        144      0.984      0.979      0.982      0.765
              Resistor        183        605      0.984      0.992      0.986       0.65
        Current Source        113        150      0.987      0.997      0.986      0.733
              Inductor        117        177      0.987      0.989      0.992      0.652
             Capacitor        115        184      0.994      0.989      0.987      0.621
     AC Voltage Source         65        180      0.994      0.991       0.99      0.714
Speed: 0.1ms preprocess, 8.2ms inference, 0.0ms loss, 1.8ms postprocess per image
Results saved to runs/detect/train15

🚀 Case 8: Freeze Layers | Experiment 3: freeze=15
Ultralytics 8.3.185 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-component-data/YOLO_component-dataset/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=15, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8m.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train16, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/train16, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.001, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=6

                   from  n    params  module                                       arguments
  0                  -1  1      1392  ultralytics.nn.modules.conv.Conv             [3, 48, 3, 2]
  1                  -1  1     41664  ultralytics.nn.modules.conv.Conv             [48, 96, 3, 2]
  2                  -1  2    111360  ultralytics.nn.modules.block.C2f             [96, 96, 2, True]
  3                  -1  1    166272  ultralytics.nn.modules.conv.Conv             [96, 192, 3, 2]
  4                  -1  4    813312  ultralytics.nn.modules.block.C2f             [192, 192, 4, True]
  5                  -1  1    664320  ultralytics.nn.modules.conv.Conv             [192, 384, 3, 2]
  6                  -1  4   3248640  ultralytics.nn.modules.block.C2f             [384, 384, 4, True]
  7                  -1  1   1991808  ultralytics.nn.modules.conv.Conv             [384, 576, 3, 2]
  8                  -1  2   3985920  ultralytics.nn.modules.block.C2f             [576, 576, 2, True]
  9                  -1  1    831168  ultralytics.nn.modules.block.SPPF            [576, 576, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  2   1993728  ultralytics.nn.modules.block.C2f             [960, 384, 2]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  2    517632  ultralytics.nn.modules.block.C2f             [576, 192, 2]
 16                  -1  1    332160  ultralytics.nn.modules.conv.Conv             [192, 192, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  2   1846272  ultralytics.nn.modules.block.C2f             [576, 384, 2]
 19                  -1  1   1327872  ultralytics.nn.modules.conv.Conv             [384, 384, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  2   4207104  ultralytics.nn.modules.block.C2f             [960, 576, 2]
 22        [15, 18, 21]  1   3779170  ultralytics.nn.modules.head.Detect           [6, [192, 384, 576]]
Model summary: 169 layers, 25,859,794 parameters, 25,859,778 gradients, 79.1 GFLOPs

Transferred 469/475 items from pretrained weights
Freezing layer 'model.0.conv.weight'
Freezing layer 'model.0.bn.weight'
Freezing layer 'model.0.bn.bias'
Freezing layer 'model.1.conv.weight'
Freezing layer 'model.1.bn.weight'
Freezing layer 'model.1.bn.bias'
Freezing layer 'model.2.cv1.conv.weight'
Freezing layer 'model.2.cv1.bn.weight'
Freezing layer 'model.2.cv1.bn.bias'
Freezing layer 'model.2.cv2.conv.weight'
Freezing layer 'model.2.cv2.bn.weight'
Freezing layer 'model.2.cv2.bn.bias'
Freezing layer 'model.2.m.0.cv1.conv.weight'
Freezing layer 'model.2.m.0.cv1.bn.weight'
Freezing layer 'model.2.m.0.cv1.bn.bias'
Freezing layer 'model.2.m.0.cv2.conv.weight'
Freezing layer 'model.2.m.0.cv2.bn.weight'
Freezing layer 'model.2.m.0.cv2.bn.bias'
Freezing layer 'model.2.m.1.cv1.conv.weight'
Freezing layer 'model.2.m.1.cv1.bn.weight'
Freezing layer 'model.2.m.1.cv1.bn.bias'
Freezing layer 'model.2.m.1.cv2.conv.weight'
Freezing layer 'model.2.m.1.cv2.bn.weight'
Freezing layer 'model.2.m.1.cv2.bn.bias'
Freezing layer 'model.3.conv.weight'
Freezing layer 'model.3.bn.weight'
Freezing layer 'model.3.bn.bias'
Freezing layer 'model.4.cv1.conv.weight'
Freezing layer 'model.4.cv1.bn.weight'
Freezing layer 'model.4.cv1.bn.bias'
Freezing layer 'model.4.cv2.conv.weight'
Freezing layer 'model.4.cv2.bn.weight'
Freezing layer 'model.4.cv2.bn.bias'
Freezing layer 'model.4.m.0.cv1.conv.weight'
Freezing layer 'model.4.m.0.cv1.bn.weight'
Freezing layer 'model.4.m.0.cv1.bn.bias'
Freezing layer 'model.4.m.0.cv2.conv.weight'
Freezing layer 'model.4.m.0.cv2.bn.weight'
Freezing layer 'model.4.m.0.cv2.bn.bias'
Freezing layer 'model.4.m.1.cv1.conv.weight'
Freezing layer 'model.4.m.1.cv1.bn.weight'
Freezing layer 'model.4.m.1.cv1.bn.bias'
Freezing layer 'model.4.m.1.cv2.conv.weight'
Freezing layer 'model.4.m.1.cv2.bn.weight'
Freezing layer 'model.4.m.1.cv2.bn.bias'
Freezing layer 'model.4.m.2.cv1.conv.weight'
Freezing layer 'model.4.m.2.cv1.bn.weight'
Freezing layer 'model.4.m.2.cv1.bn.bias'
Freezing layer 'model.4.m.2.cv2.conv.weight'
Freezing layer 'model.4.m.2.cv2.bn.weight'
Freezing layer 'model.4.m.2.cv2.bn.bias'
Freezing layer 'model.4.m.3.cv1.conv.weight'
Freezing layer 'model.4.m.3.cv1.bn.weight'
Freezing layer 'model.4.m.3.cv1.bn.bias'
Freezing layer 'model.4.m.3.cv2.conv.weight'
Freezing layer 'model.4.m.3.cv2.bn.weight'
Freezing layer 'model.4.m.3.cv2.bn.bias'
Freezing layer 'model.5.conv.weight'
Freezing layer 'model.5.bn.weight'
Freezing layer 'model.5.bn.bias'
Freezing layer 'model.6.cv1.conv.weight'
Freezing layer 'model.6.cv1.bn.weight'
Freezing layer 'model.6.cv1.bn.bias'
Freezing layer 'model.6.cv2.conv.weight'
Freezing layer 'model.6.cv2.bn.weight'
Freezing layer 'model.6.cv2.bn.bias'
Freezing layer 'model.6.m.0.cv1.conv.weight'
Freezing layer 'model.6.m.0.cv1.bn.weight'
Freezing layer 'model.6.m.0.cv1.bn.bias'
Freezing layer 'model.6.m.0.cv2.conv.weight'
Freezing layer 'model.6.m.0.cv2.bn.weight'
Freezing layer 'model.6.m.0.cv2.bn.bias'
Freezing layer 'model.6.m.1.cv1.conv.weight'
Freezing layer 'model.6.m.1.cv1.bn.weight'
Freezing layer 'model.6.m.1.cv1.bn.bias'
Freezing layer 'model.6.m.1.cv2.conv.weight'
Freezing layer 'model.6.m.1.cv2.bn.weight'
Freezing layer 'model.6.m.1.cv2.bn.bias'
Freezing layer 'model.6.m.2.cv1.conv.weight'
Freezing layer 'model.6.m.2.cv1.bn.weight'
Freezing layer 'model.6.m.2.cv1.bn.bias'
Freezing layer 'model.6.m.2.cv2.conv.weight'
Freezing layer 'model.6.m.2.cv2.bn.weight'
Freezing layer 'model.6.m.2.cv2.bn.bias'
Freezing layer 'model.6.m.3.cv1.conv.weight'
Freezing layer 'model.6.m.3.cv1.bn.weight'
Freezing layer 'model.6.m.3.cv1.bn.bias'
Freezing layer 'model.6.m.3.cv2.conv.weight'
Freezing layer 'model.6.m.3.cv2.bn.weight'
Freezing layer 'model.6.m.3.cv2.bn.bias'
Freezing layer 'model.7.conv.weight'
Freezing layer 'model.7.bn.weight'
Freezing layer 'model.7.bn.bias'
Freezing layer 'model.8.cv1.conv.weight'
Freezing layer 'model.8.cv1.bn.weight'
Freezing layer 'model.8.cv1.bn.bias'
Freezing layer 'model.8.cv2.conv.weight'
Freezing layer 'model.8.cv2.bn.weight'
Freezing layer 'model.8.cv2.bn.bias'
Freezing layer 'model.8.m.0.cv1.conv.weight'
Freezing layer 'model.8.m.0.cv1.bn.weight'
Freezing layer 'model.8.m.0.cv1.bn.bias'
Freezing layer 'model.8.m.0.cv2.conv.weight'
Freezing layer 'model.8.m.0.cv2.bn.weight'
Freezing layer 'model.8.m.0.cv2.bn.bias'
Freezing layer 'model.8.m.1.cv1.conv.weight'
Freezing layer 'model.8.m.1.cv1.bn.weight'
Freezing layer 'model.8.m.1.cv1.bn.bias'
Freezing layer 'model.8.m.1.cv2.conv.weight'
Freezing layer 'model.8.m.1.cv2.bn.weight'
Freezing layer 'model.8.m.1.cv2.bn.bias'
Freezing layer 'model.9.cv1.conv.weight'
Freezing layer 'model.9.cv1.bn.weight'
Freezing layer 'model.9.cv1.bn.bias'
Freezing layer 'model.9.cv2.conv.weight'
Freezing layer 'model.9.cv2.bn.weight'
Freezing layer 'model.9.cv2.bn.bias'
Freezing layer 'model.12.cv1.conv.weight'
Freezing layer 'model.12.cv1.bn.weight'
Freezing layer 'model.12.cv1.bn.bias'
Freezing layer 'model.12.cv2.conv.weight'
Freezing layer 'model.12.cv2.bn.weight'
Freezing layer 'model.12.cv2.bn.bias'
Freezing layer 'model.12.m.0.cv1.conv.weight'
Freezing layer 'model.12.m.0.cv1.bn.weight'
Freezing layer 'model.12.m.0.cv1.bn.bias'
Freezing layer 'model.12.m.0.cv2.conv.weight'
Freezing layer 'model.12.m.0.cv2.bn.weight'
Freezing layer 'model.12.m.0.cv2.bn.bias'
Freezing layer 'model.12.m.1.cv1.conv.weight'
Freezing layer 'model.12.m.1.cv1.bn.weight'
Freezing layer 'model.12.m.1.cv1.bn.bias'
Freezing layer 'model.12.m.1.cv2.conv.weight'
Freezing layer 'model.12.m.1.cv2.bn.weight'
Freezing layer 'model.12.m.1.cv2.bn.bias'
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 53.6±41.3 MB/s, size: 51.9 KB)

train: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/train/labels... 919 images, 0 backgrounds, 0 corrupt: 100%|██████████| 919/919 [00:01<00:00, 545.10it/s]

WARNING ⚠️ train: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 21.6±13.1 MB/s, size: 35.4 KB)

val: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels... 230 images, 0 backgrounds, 0 corrupt: 100%|██████████| 230/230 [00:00<00:00, 299.42it/s]

WARNING ⚠️ val: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/val is not writeable, cache not saved.

Plotting labels to runs/detect/train16/labels.jpg...
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 77 weight(decay=0.0), 84 weight(decay=0.001), 83 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs/detect/train16
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       1/32      5.94G      2.494      3.165      2.117        249        640: 100%|██████████| 29/29 [00:17<00:00,  1.71it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.43it/s]

                   all        230       1440      0.617      0.827      0.756      0.435

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       2/32      7.68G       1.38      1.158       1.25        222        640: 100%|██████████| 29/29 [00:16<00:00,  1.74it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.61it/s]

                   all        230       1440      0.801      0.882      0.949      0.606

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       3/32      7.68G      1.359      1.005       1.22        203        640: 100%|██████████| 29/29 [00:16<00:00,  1.76it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.62it/s]

                   all        230       1440      0.939       0.96      0.978       0.63

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       4/32      7.68G      1.351     0.8901        1.2        241        640:  69%|██████▉   | 20/29 [00:11<00:05,  1.75it/s]

In [4]:
# Case 8: Freeze Layers
run_ablation("Case 8: Freeze Layers", "freeze", [15, 22])

🚀 Case 8: Freeze Layers | Experiment 1: freeze=15

Downloading https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov8m.pt to 'yolov8m.pt': 100%|██████████| 49.7M/49.7M [00:00<00:00, 115MB/s]

Ultralytics 8.3.185 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-component-data/YOLO_component-dataset/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=15, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8m.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/train, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.001, workers=8, workspace=None

Downloading https://ultralytics.com/assets/Arial.ttf to '/root/.config/Ultralytics/Arial.ttf': 100%|██████████| 755k/755k [00:00<00:00, 20.5MB/s]

Overriding model.yaml nc=80 with nc=6

                   from  n    params  module                                       arguments
  0                  -1  1      1392  ultralytics.nn.modules.conv.Conv             [3, 48, 3, 2]
  1                  -1  1     41664  ultralytics.nn.modules.conv.Conv             [48, 96, 3, 2]
  2                  -1  2    111360  ultralytics.nn.modules.block.C2f             [96, 96, 2, True]
  3                  -1  1    166272  ultralytics.nn.modules.conv.Conv             [96, 192, 3, 2]
  4                  -1  4    813312  ultralytics.nn.modules.block.C2f             [192, 192, 4, True]
  5                  -1  1    664320  ultralytics.nn.modules.conv.Conv             [192, 384, 3, 2]
  6                  -1  4   3248640  ultralytics.nn.modules.block.C2f             [384, 384, 4, True]
  7                  -1  1   1991808  ultralytics.nn.modules.conv.Conv             [384, 576, 3, 2]
  8                  -1  2   3985920  ultralytics.nn.modules.block.C2f             [576, 576, 2, True]
  9                  -1  1    831168  ultralytics.nn.modules.block.SPPF            [576, 576, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  2   1993728  ultralytics.nn.modules.block.C2f             [960, 384, 2]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  2    517632  ultralytics.nn.modules.block.C2f             [576, 192, 2]
 16                  -1  1    332160  ultralytics.nn.modules.conv.Conv             [192, 192, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  2   1846272  ultralytics.nn.modules.block.C2f             [576, 384, 2]
 19                  -1  1   1327872  ultralytics.nn.modules.conv.Conv             [384, 384, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  2   4207104  ultralytics.nn.modules.block.C2f             [960, 576, 2]
 22        [15, 18, 21]  1   3779170  ultralytics.nn.modules.head.Detect           [6, [192, 384, 576]]
Model summary: 169 layers, 25,859,794 parameters, 25,859,778 gradients, 79.1 GFLOPs

Transferred 469/475 items from pretrained weights
Freezing layer 'model.0.conv.weight'
Freezing layer 'model.0.bn.weight'
Freezing layer 'model.0.bn.bias'
Freezing layer 'model.1.conv.weight'
Freezing layer 'model.1.bn.weight'
Freezing layer 'model.1.bn.bias'
Freezing layer 'model.2.cv1.conv.weight'
Freezing layer 'model.2.cv1.bn.weight'
Freezing layer 'model.2.cv1.bn.bias'
Freezing layer 'model.2.cv2.conv.weight'
Freezing layer 'model.2.cv2.bn.weight'
Freezing layer 'model.2.cv2.bn.bias'
Freezing layer 'model.2.m.0.cv1.conv.weight'
Freezing layer 'model.2.m.0.cv1.bn.weight'
Freezing layer 'model.2.m.0.cv1.bn.bias'
Freezing layer 'model.2.m.0.cv2.conv.weight'
Freezing layer 'model.2.m.0.cv2.bn.weight'
Freezing layer 'model.2.m.0.cv2.bn.bias'
Freezing layer 'model.2.m.1.cv1.conv.weight'
Freezing layer 'model.2.m.1.cv1.bn.weight'
Freezing layer 'model.2.m.1.cv1.bn.bias'
Freezing layer 'model.2.m.1.cv2.conv.weight'
Freezing layer 'model.2.m.1.cv2.bn.weight'
Freezing layer 'model.2.m.1.cv2.bn.bias'
Freezing layer 'model.3.conv.weight'
Freezing layer 'model.3.bn.weight'
Freezing layer 'model.3.bn.bias'
Freezing layer 'model.4.cv1.conv.weight'
Freezing layer 'model.4.cv1.bn.weight'
Freezing layer 'model.4.cv1.bn.bias'
Freezing layer 'model.4.cv2.conv.weight'
Freezing layer 'model.4.cv2.bn.weight'
Freezing layer 'model.4.cv2.bn.bias'
Freezing layer 'model.4.m.0.cv1.conv.weight'
Freezing layer 'model.4.m.0.cv1.bn.weight'
Freezing layer 'model.4.m.0.cv1.bn.bias'
Freezing layer 'model.4.m.0.cv2.conv.weight'
Freezing layer 'model.4.m.0.cv2.bn.weight'
Freezing layer 'model.4.m.0.cv2.bn.bias'
Freezing layer 'model.4.m.1.cv1.conv.weight'
Freezing layer 'model.4.m.1.cv1.bn.weight'
Freezing layer 'model.4.m.1.cv1.bn.bias'
Freezing layer 'model.4.m.1.cv2.conv.weight'
Freezing layer 'model.4.m.1.cv2.bn.weight'
Freezing layer 'model.4.m.1.cv2.bn.bias'
Freezing layer 'model.4.m.2.cv1.conv.weight'
Freezing layer 'model.4.m.2.cv1.bn.weight'
Freezing layer 'model.4.m.2.cv1.bn.bias'
Freezing layer 'model.4.m.2.cv2.conv.weight'
Freezing layer 'model.4.m.2.cv2.bn.weight'
Freezing layer 'model.4.m.2.cv2.bn.bias'
Freezing layer 'model.4.m.3.cv1.conv.weight'
Freezing layer 'model.4.m.3.cv1.bn.weight'
Freezing layer 'model.4.m.3.cv1.bn.bias'
Freezing layer 'model.4.m.3.cv2.conv.weight'
Freezing layer 'model.4.m.3.cv2.bn.weight'
Freezing layer 'model.4.m.3.cv2.bn.bias'
Freezing layer 'model.5.conv.weight'
Freezing layer 'model.5.bn.weight'
Freezing layer 'model.5.bn.bias'
Freezing layer 'model.6.cv1.conv.weight'
Freezing layer 'model.6.cv1.bn.weight'
Freezing layer 'model.6.cv1.bn.bias'
Freezing layer 'model.6.cv2.conv.weight'
Freezing layer 'model.6.cv2.bn.weight'
Freezing layer 'model.6.cv2.bn.bias'
Freezing layer 'model.6.m.0.cv1.conv.weight'
Freezing layer 'model.6.m.0.cv1.bn.weight'
Freezing layer 'model.6.m.0.cv1.bn.bias'
Freezing layer 'model.6.m.0.cv2.conv.weight'
Freezing layer 'model.6.m.0.cv2.bn.weight'
Freezing layer 'model.6.m.0.cv2.bn.bias'
Freezing layer 'model.6.m.1.cv1.conv.weight'
Freezing layer 'model.6.m.1.cv1.bn.weight'
Freezing layer 'model.6.m.1.cv1.bn.bias'
Freezing layer 'model.6.m.1.cv2.conv.weight'
Freezing layer 'model.6.m.1.cv2.bn.weight'
Freezing layer 'model.6.m.1.cv2.bn.bias'
Freezing layer 'model.6.m.2.cv1.conv.weight'
Freezing layer 'model.6.m.2.cv1.bn.weight'
Freezing layer 'model.6.m.2.cv1.bn.bias'
Freezing layer 'model.6.m.2.cv2.conv.weight'
Freezing layer 'model.6.m.2.cv2.bn.weight'
Freezing layer 'model.6.m.2.cv2.bn.bias'
Freezing layer 'model.6.m.3.cv1.conv.weight'
Freezing layer 'model.6.m.3.cv1.bn.weight'
Freezing layer 'model.6.m.3.cv1.bn.bias'
Freezing layer 'model.6.m.3.cv2.conv.weight'
Freezing layer 'model.6.m.3.cv2.bn.weight'
Freezing layer 'model.6.m.3.cv2.bn.bias'
Freezing layer 'model.7.conv.weight'
Freezing layer 'model.7.bn.weight'
Freezing layer 'model.7.bn.bias'
Freezing layer 'model.8.cv1.conv.weight'
Freezing layer 'model.8.cv1.bn.weight'
Freezing layer 'model.8.cv1.bn.bias'
Freezing layer 'model.8.cv2.conv.weight'
Freezing layer 'model.8.cv2.bn.weight'
Freezing layer 'model.8.cv2.bn.bias'
Freezing layer 'model.8.m.0.cv1.conv.weight'
Freezing layer 'model.8.m.0.cv1.bn.weight'
Freezing layer 'model.8.m.0.cv1.bn.bias'
Freezing layer 'model.8.m.0.cv2.conv.weight'
Freezing layer 'model.8.m.0.cv2.bn.weight'
Freezing layer 'model.8.m.0.cv2.bn.bias'
Freezing layer 'model.8.m.1.cv1.conv.weight'
Freezing layer 'model.8.m.1.cv1.bn.weight'
Freezing layer 'model.8.m.1.cv1.bn.bias'
Freezing layer 'model.8.m.1.cv2.conv.weight'
Freezing layer 'model.8.m.1.cv2.bn.weight'
Freezing layer 'model.8.m.1.cv2.bn.bias'
Freezing layer 'model.9.cv1.conv.weight'
Freezing layer 'model.9.cv1.bn.weight'
Freezing layer 'model.9.cv1.bn.bias'
Freezing layer 'model.9.cv2.conv.weight'
Freezing layer 'model.9.cv2.bn.weight'
Freezing layer 'model.9.cv2.bn.bias'
Freezing layer 'model.12.cv1.conv.weight'
Freezing layer 'model.12.cv1.bn.weight'
Freezing layer 'model.12.cv1.bn.bias'
Freezing layer 'model.12.cv2.conv.weight'
Freezing layer 'model.12.cv2.bn.weight'
Freezing layer 'model.12.cv2.bn.bias'
Freezing layer 'model.12.m.0.cv1.conv.weight'
Freezing layer 'model.12.m.0.cv1.bn.weight'
Freezing layer 'model.12.m.0.cv1.bn.bias'
Freezing layer 'model.12.m.0.cv2.conv.weight'
Freezing layer 'model.12.m.0.cv2.bn.weight'
Freezing layer 'model.12.m.0.cv2.bn.bias'
Freezing layer 'model.12.m.1.cv1.conv.weight'
Freezing layer 'model.12.m.1.cv1.bn.weight'
Freezing layer 'model.12.m.1.cv1.bn.bias'
Freezing layer 'model.12.m.1.cv2.conv.weight'
Freezing layer 'model.12.m.1.cv2.bn.weight'
Freezing layer 'model.12.m.1.cv2.bn.bias'
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...

Downloading https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11n.pt to 'yolo11n.pt': 100%|██████████| 5.35M/5.35M [00:00<00:00, 78.0MB/s]

AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 7.1±6.2 MB/s, size: 51.9 KB)

train: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/train/labels... 919 images, 0 backgrounds, 0 corrupt: 100%|██████████| 919/919 [00:06<00:00, 147.82it/s]

WARNING ⚠️ train: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 4.2±1.5 MB/s, size: 35.4 KB)

val: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels... 230 images, 0 backgrounds, 0 corrupt: 100%|██████████| 230/230 [00:01<00:00, 125.14it/s]

WARNING ⚠️ val: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/val is not writeable, cache not saved.

Plotting labels to runs/detect/train/labels.jpg...
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 77 weight(decay=0.0), 84 weight(decay=0.001), 83 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs/detect/train
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       1/32      5.13G      2.494      3.165      2.117        249        640: 100%|██████████| 29/29 [00:17<00:00,  1.63it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:03<00:00,  1.06it/s]

                   all        230       1440      0.617      0.827      0.756      0.435

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       2/32      6.91G       1.38      1.158       1.25        222        640: 100%|██████████| 29/29 [00:16<00:00,  1.72it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.54it/s]

                   all        230       1440      0.801      0.882      0.949      0.606

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       3/32      6.94G      1.359      1.005       1.22        203        640: 100%|██████████| 29/29 [00:16<00:00,  1.74it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.55it/s]

                   all        230       1440      0.939       0.96      0.978       0.63

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       4/32      6.97G      1.335     0.8835      1.193        242        640: 100%|██████████| 29/29 [00:16<00:00,  1.74it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.56it/s]

                   all        230       1440       0.94      0.955       0.98      0.632

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       5/32         7G      1.324     0.7578      1.195        250        640: 100%|██████████| 29/29 [00:16<00:00,  1.75it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.56it/s]

                   all        230       1440      0.974      0.975      0.983      0.635

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       6/32      7.03G      1.299     0.6933      1.186        251        640: 100%|██████████| 29/29 [00:16<00:00,  1.74it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.55it/s]

                   all        230       1440      0.966      0.981      0.984      0.634

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       7/32      7.06G      1.274     0.6563      1.181        257        640: 100%|██████████| 29/29 [00:16<00:00,  1.74it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.55it/s]

                   all        230       1440      0.979      0.981      0.984      0.634

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       8/32       7.1G      1.285     0.6303      1.191        273        640: 100%|██████████| 29/29 [00:16<00:00,  1.74it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.57it/s]

                   all        230       1440      0.985      0.985      0.985      0.649

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       9/32      7.13G      1.268     0.6151      1.177        265        640: 100%|██████████| 29/29 [00:16<00:00,  1.74it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.56it/s]

                   all        230       1440       0.98      0.982      0.985       0.65

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      10/32      7.16G       1.26     0.6055      1.165        233        640: 100%|██████████| 29/29 [00:16<00:00,  1.74it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.55it/s]

                   all        230       1440      0.981      0.986      0.987      0.651

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      11/32      7.19G      1.252     0.5859      1.176        282        640: 100%|██████████| 29/29 [00:16<00:00,  1.74it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.54it/s]

                   all        230       1440      0.983      0.985      0.984      0.654

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      12/32      7.22G      1.244     0.5838      1.178        205        640: 100%|██████████| 29/29 [00:16<00:00,  1.74it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.56it/s]

                   all        230       1440      0.981      0.986      0.984      0.659

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      13/32      7.25G      1.226     0.5722      1.158        219        640: 100%|██████████| 29/29 [00:16<00:00,  1.75it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.56it/s]

                   all        230       1440       0.98      0.986      0.988      0.664

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      14/32      7.29G      1.233     0.5736       1.16        239        640: 100%|██████████| 29/29 [00:16<00:00,  1.74it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.56it/s]

                   all        230       1440      0.987      0.986      0.987      0.657

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      15/32      7.32G      1.226     0.5556       1.15        254        640: 100%|██████████| 29/29 [00:16<00:00,  1.74it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.56it/s]

                   all        230       1440      0.982      0.986      0.985      0.656

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      16/32      7.35G      1.213     0.5534      1.155        231        640: 100%|██████████| 29/29 [00:16<00:00,  1.74it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.56it/s]

                   all        230       1440      0.986      0.985      0.987      0.668

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      17/32      7.38G      1.214     0.5473      1.153        275        640: 100%|██████████| 29/29 [00:16<00:00,  1.75it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.54it/s]

                   all        230       1440      0.984      0.986      0.986      0.663

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      18/32      7.41G      1.205     0.5354      1.148        261        640: 100%|██████████| 29/29 [00:16<00:00,  1.75it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.59it/s]

                   all        230       1440      0.983      0.988      0.986      0.669

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      19/32      7.44G      1.204     0.5396      1.149        187        640: 100%|██████████| 29/29 [00:16<00:00,  1.75it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.57it/s]

                   all        230       1440      0.986      0.988      0.987      0.658

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      20/32      7.47G      1.188     0.5232      1.139        223        640: 100%|██████████| 29/29 [00:16<00:00,  1.74it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.57it/s]

                   all        230       1440      0.988      0.987      0.989      0.683

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      21/32      7.51G      1.178     0.5244      1.135        232        640: 100%|██████████| 29/29 [00:16<00:00,  1.75it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.56it/s]

                   all        230       1440      0.987      0.986      0.986      0.679

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      22/32      7.54G       1.18     0.5174      1.142        242        640: 100%|██████████| 29/29 [00:16<00:00,  1.75it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.58it/s]

                   all        230       1440      0.986      0.985      0.986      0.671

Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      23/32      7.57G      1.164     0.4726      1.179        147        640: 100%|██████████| 29/29 [00:18<00:00,  1.59it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.56it/s]

                   all        230       1440      0.986      0.987      0.988      0.674

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      24/32       7.6G      1.153     0.4586      1.162        127        640: 100%|██████████| 29/29 [00:16<00:00,  1.76it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.54it/s]

                   all        230       1440      0.987      0.986      0.987      0.677

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      25/32      7.63G      1.148     0.4551      1.162        121        640: 100%|██████████| 29/29 [00:16<00:00,  1.76it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.58it/s]

                   all        230       1440      0.988      0.987      0.987      0.683

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      26/32      7.66G      1.138     0.4455      1.152        141        640: 100%|██████████| 29/29 [00:16<00:00,  1.76it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.57it/s]

                   all        230       1440      0.988      0.984      0.987      0.686

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      27/32      7.69G      1.134     0.4409      1.154        138        640: 100%|██████████| 29/29 [00:16<00:00,  1.76it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.55it/s]

                   all        230       1440      0.988      0.986      0.987      0.685

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      28/32      7.72G      1.135     0.4436      1.154        136        640: 100%|██████████| 29/29 [00:16<00:00,  1.75it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.56it/s]

                   all        230       1440      0.987      0.986      0.986      0.682

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      29/32      7.76G      1.127     0.4331      1.154        145        640: 100%|██████████| 29/29 [00:16<00:00,  1.76it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.57it/s]

                   all        230       1440      0.989      0.986      0.987      0.687

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      30/32      7.79G      1.118     0.4308      1.142        140        640: 100%|██████████| 29/29 [00:16<00:00,  1.76it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.57it/s]

                   all        230       1440      0.988      0.986      0.987      0.689

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      31/32      7.82G      1.114     0.4211      1.151        124        640: 100%|██████████| 29/29 [00:16<00:00,  1.76it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.58it/s]

                   all        230       1440      0.989      0.988      0.987      0.689

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      32/32      7.85G      1.106     0.4186      1.144        142        640: 100%|██████████| 29/29 [00:16<00:00,  1.76it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.56it/s]

                   all        230       1440       0.99      0.988      0.987      0.688

32 epochs completed in 0.177 hours.
Optimizer stripped from runs/detect/train/weights/last.pt, 52.0MB
Optimizer stripped from runs/detect/train/weights/best.pt, 52.0MB

Validating runs/detect/train/weights/best.pt...
Ultralytics 8.3.185 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
Model summary (fused): 92 layers, 25,843,234 parameters, 0 gradients, 78.7 GFLOPs

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:04<00:00,  1.09s/it]
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        230       1440      0.988      0.986      0.987       0.69
     DC Voltage Source        103        144      0.993      0.972       0.98      0.758
              Resistor        183        605      0.986      0.992      0.987      0.651
        Current Source        113        150      0.985      0.993      0.989       0.75
              Inductor        117        177      0.988      0.983      0.986      0.636
             Capacitor        115        184      0.993      0.989      0.989       0.62
     AC Voltage Source         65        180      0.984      0.989      0.991      0.724
Speed: 0.1ms preprocess, 8.1ms inference, 0.0ms loss, 2.3ms postprocess per image
Results saved to runs/detect/train

🚀 Case 8: Freeze Layers | Experiment 2: freeze=22
Ultralytics 8.3.185 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-component-data/YOLO_component-dataset/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=22, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8m.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train2, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/train2, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.001, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=6

                   from  n    params  module                                       arguments
  0                  -1  1      1392  ultralytics.nn.modules.conv.Conv             [3, 48, 3, 2]
  1                  -1  1     41664  ultralytics.nn.modules.conv.Conv             [48, 96, 3, 2]
  2                  -1  2    111360  ultralytics.nn.modules.block.C2f             [96, 96, 2, True]
  3                  -1  1    166272  ultralytics.nn.modules.conv.Conv             [96, 192, 3, 2]
  4                  -1  4    813312  ultralytics.nn.modules.block.C2f             [192, 192, 4, True]
  5                  -1  1    664320  ultralytics.nn.modules.conv.Conv             [192, 384, 3, 2]
  6                  -1  4   3248640  ultralytics.nn.modules.block.C2f             [384, 384, 4, True]
  7                  -1  1   1991808  ultralytics.nn.modules.conv.Conv             [384, 576, 3, 2]
  8                  -1  2   3985920  ultralytics.nn.modules.block.C2f             [576, 576, 2, True]
  9                  -1  1    831168  ultralytics.nn.modules.block.SPPF            [576, 576, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  2   1993728  ultralytics.nn.modules.block.C2f             [960, 384, 2]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  2    517632  ultralytics.nn.modules.block.C2f             [576, 192, 2]
 16                  -1  1    332160  ultralytics.nn.modules.conv.Conv             [192, 192, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  2   1846272  ultralytics.nn.modules.block.C2f             [576, 384, 2]
 19                  -1  1   1327872  ultralytics.nn.modules.conv.Conv             [384, 384, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  2   4207104  ultralytics.nn.modules.block.C2f             [960, 576, 2]
 22        [15, 18, 21]  1   3779170  ultralytics.nn.modules.head.Detect           [6, [192, 384, 576]]
Model summary: 169 layers, 25,859,794 parameters, 25,859,778 gradients, 79.1 GFLOPs

Transferred 469/475 items from pretrained weights
Freezing layer 'model.0.conv.weight'
Freezing layer 'model.0.bn.weight'
Freezing layer 'model.0.bn.bias'
Freezing layer 'model.1.conv.weight'
Freezing layer 'model.1.bn.weight'
Freezing layer 'model.1.bn.bias'
Freezing layer 'model.2.cv1.conv.weight'
Freezing layer 'model.2.cv1.bn.weight'
Freezing layer 'model.2.cv1.bn.bias'
Freezing layer 'model.2.cv2.conv.weight'
Freezing layer 'model.2.cv2.bn.weight'
Freezing layer 'model.2.cv2.bn.bias'
Freezing layer 'model.2.m.0.cv1.conv.weight'
Freezing layer 'model.2.m.0.cv1.bn.weight'
Freezing layer 'model.2.m.0.cv1.bn.bias'
Freezing layer 'model.2.m.0.cv2.conv.weight'
Freezing layer 'model.2.m.0.cv2.bn.weight'
Freezing layer 'model.2.m.0.cv2.bn.bias'
Freezing layer 'model.2.m.1.cv1.conv.weight'
Freezing layer 'model.2.m.1.cv1.bn.weight'
Freezing layer 'model.2.m.1.cv1.bn.bias'
Freezing layer 'model.2.m.1.cv2.conv.weight'
Freezing layer 'model.2.m.1.cv2.bn.weight'
Freezing layer 'model.2.m.1.cv2.bn.bias'
Freezing layer 'model.3.conv.weight'
Freezing layer 'model.3.bn.weight'
Freezing layer 'model.3.bn.bias'
Freezing layer 'model.4.cv1.conv.weight'
Freezing layer 'model.4.cv1.bn.weight'
Freezing layer 'model.4.cv1.bn.bias'
Freezing layer 'model.4.cv2.conv.weight'
Freezing layer 'model.4.cv2.bn.weight'
Freezing layer 'model.4.cv2.bn.bias'
Freezing layer 'model.4.m.0.cv1.conv.weight'
Freezing layer 'model.4.m.0.cv1.bn.weight'
Freezing layer 'model.4.m.0.cv1.bn.bias'
Freezing layer 'model.4.m.0.cv2.conv.weight'
Freezing layer 'model.4.m.0.cv2.bn.weight'
Freezing layer 'model.4.m.0.cv2.bn.bias'
Freezing layer 'model.4.m.1.cv1.conv.weight'
Freezing layer 'model.4.m.1.cv1.bn.weight'
Freezing layer 'model.4.m.1.cv1.bn.bias'
Freezing layer 'model.4.m.1.cv2.conv.weight'
Freezing layer 'model.4.m.1.cv2.bn.weight'
Freezing layer 'model.4.m.1.cv2.bn.bias'
Freezing layer 'model.4.m.2.cv1.conv.weight'
Freezing layer 'model.4.m.2.cv1.bn.weight'
Freezing layer 'model.4.m.2.cv1.bn.bias'
Freezing layer 'model.4.m.2.cv2.conv.weight'
Freezing layer 'model.4.m.2.cv2.bn.weight'
Freezing layer 'model.4.m.2.cv2.bn.bias'
Freezing layer 'model.4.m.3.cv1.conv.weight'
Freezing layer 'model.4.m.3.cv1.bn.weight'
Freezing layer 'model.4.m.3.cv1.bn.bias'
Freezing layer 'model.4.m.3.cv2.conv.weight'
Freezing layer 'model.4.m.3.cv2.bn.weight'
Freezing layer 'model.4.m.3.cv2.bn.bias'
Freezing layer 'model.5.conv.weight'
Freezing layer 'model.5.bn.weight'
Freezing layer 'model.5.bn.bias'
Freezing layer 'model.6.cv1.conv.weight'
Freezing layer 'model.6.cv1.bn.weight'
Freezing layer 'model.6.cv1.bn.bias'
Freezing layer 'model.6.cv2.conv.weight'
Freezing layer 'model.6.cv2.bn.weight'
Freezing layer 'model.6.cv2.bn.bias'
Freezing layer 'model.6.m.0.cv1.conv.weight'
Freezing layer 'model.6.m.0.cv1.bn.weight'
Freezing layer 'model.6.m.0.cv1.bn.bias'
Freezing layer 'model.6.m.0.cv2.conv.weight'
Freezing layer 'model.6.m.0.cv2.bn.weight'
Freezing layer 'model.6.m.0.cv2.bn.bias'
Freezing layer 'model.6.m.1.cv1.conv.weight'
Freezing layer 'model.6.m.1.cv1.bn.weight'
Freezing layer 'model.6.m.1.cv1.bn.bias'
Freezing layer 'model.6.m.1.cv2.conv.weight'
Freezing layer 'model.6.m.1.cv2.bn.weight'
Freezing layer 'model.6.m.1.cv2.bn.bias'
Freezing layer 'model.6.m.2.cv1.conv.weight'
Freezing layer 'model.6.m.2.cv1.bn.weight'
Freezing layer 'model.6.m.2.cv1.bn.bias'
Freezing layer 'model.6.m.2.cv2.conv.weight'
Freezing layer 'model.6.m.2.cv2.bn.weight'
Freezing layer 'model.6.m.2.cv2.bn.bias'
Freezing layer 'model.6.m.3.cv1.conv.weight'
Freezing layer 'model.6.m.3.cv1.bn.weight'
Freezing layer 'model.6.m.3.cv1.bn.bias'
Freezing layer 'model.6.m.3.cv2.conv.weight'
Freezing layer 'model.6.m.3.cv2.bn.weight'
Freezing layer 'model.6.m.3.cv2.bn.bias'
Freezing layer 'model.7.conv.weight'
Freezing layer 'model.7.bn.weight'
Freezing layer 'model.7.bn.bias'
Freezing layer 'model.8.cv1.conv.weight'
Freezing layer 'model.8.cv1.bn.weight'
Freezing layer 'model.8.cv1.bn.bias'
Freezing layer 'model.8.cv2.conv.weight'
Freezing layer 'model.8.cv2.bn.weight'
Freezing layer 'model.8.cv2.bn.bias'
Freezing layer 'model.8.m.0.cv1.conv.weight'
Freezing layer 'model.8.m.0.cv1.bn.weight'
Freezing layer 'model.8.m.0.cv1.bn.bias'
Freezing layer 'model.8.m.0.cv2.conv.weight'
Freezing layer 'model.8.m.0.cv2.bn.weight'
Freezing layer 'model.8.m.0.cv2.bn.bias'
Freezing layer 'model.8.m.1.cv1.conv.weight'
Freezing layer 'model.8.m.1.cv1.bn.weight'
Freezing layer 'model.8.m.1.cv1.bn.bias'
Freezing layer 'model.8.m.1.cv2.conv.weight'
Freezing layer 'model.8.m.1.cv2.bn.weight'
Freezing layer 'model.8.m.1.cv2.bn.bias'
Freezing layer 'model.9.cv1.conv.weight'
Freezing layer 'model.9.cv1.bn.weight'
Freezing layer 'model.9.cv1.bn.bias'
Freezing layer 'model.9.cv2.conv.weight'
Freezing layer 'model.9.cv2.bn.weight'
Freezing layer 'model.9.cv2.bn.bias'
Freezing layer 'model.12.cv1.conv.weight'
Freezing layer 'model.12.cv1.bn.weight'
Freezing layer 'model.12.cv1.bn.bias'
Freezing layer 'model.12.cv2.conv.weight'
Freezing layer 'model.12.cv2.bn.weight'
Freezing layer 'model.12.cv2.bn.bias'
Freezing layer 'model.12.m.0.cv1.conv.weight'
Freezing layer 'model.12.m.0.cv1.bn.weight'
Freezing layer 'model.12.m.0.cv1.bn.bias'
Freezing layer 'model.12.m.0.cv2.conv.weight'
Freezing layer 'model.12.m.0.cv2.bn.weight'
Freezing layer 'model.12.m.0.cv2.bn.bias'
Freezing layer 'model.12.m.1.cv1.conv.weight'
Freezing layer 'model.12.m.1.cv1.bn.weight'
Freezing layer 'model.12.m.1.cv1.bn.bias'
Freezing layer 'model.12.m.1.cv2.conv.weight'
Freezing layer 'model.12.m.1.cv2.bn.weight'
Freezing layer 'model.12.m.1.cv2.bn.bias'
Freezing layer 'model.15.cv1.conv.weight'
Freezing layer 'model.15.cv1.bn.weight'
Freezing layer 'model.15.cv1.bn.bias'
Freezing layer 'model.15.cv2.conv.weight'
Freezing layer 'model.15.cv2.bn.weight'
Freezing layer 'model.15.cv2.bn.bias'
Freezing layer 'model.15.m.0.cv1.conv.weight'
Freezing layer 'model.15.m.0.cv1.bn.weight'
Freezing layer 'model.15.m.0.cv1.bn.bias'
Freezing layer 'model.15.m.0.cv2.conv.weight'
Freezing layer 'model.15.m.0.cv2.bn.weight'
Freezing layer 'model.15.m.0.cv2.bn.bias'
Freezing layer 'model.15.m.1.cv1.conv.weight'
Freezing layer 'model.15.m.1.cv1.bn.weight'
Freezing layer 'model.15.m.1.cv1.bn.bias'
Freezing layer 'model.15.m.1.cv2.conv.weight'
Freezing layer 'model.15.m.1.cv2.bn.weight'
Freezing layer 'model.15.m.1.cv2.bn.bias'
Freezing layer 'model.16.conv.weight'
Freezing layer 'model.16.bn.weight'
Freezing layer 'model.16.bn.bias'
Freezing layer 'model.18.cv1.conv.weight'
Freezing layer 'model.18.cv1.bn.weight'
Freezing layer 'model.18.cv1.bn.bias'
Freezing layer 'model.18.cv2.conv.weight'
Freezing layer 'model.18.cv2.bn.weight'
Freezing layer 'model.18.cv2.bn.bias'
Freezing layer 'model.18.m.0.cv1.conv.weight'
Freezing layer 'model.18.m.0.cv1.bn.weight'
Freezing layer 'model.18.m.0.cv1.bn.bias'
Freezing layer 'model.18.m.0.cv2.conv.weight'
Freezing layer 'model.18.m.0.cv2.bn.weight'
Freezing layer 'model.18.m.0.cv2.bn.bias'
Freezing layer 'model.18.m.1.cv1.conv.weight'
Freezing layer 'model.18.m.1.cv1.bn.weight'
Freezing layer 'model.18.m.1.cv1.bn.bias'
Freezing layer 'model.18.m.1.cv2.conv.weight'
Freezing layer 'model.18.m.1.cv2.bn.weight'
Freezing layer 'model.18.m.1.cv2.bn.bias'
Freezing layer 'model.19.conv.weight'
Freezing layer 'model.19.bn.weight'
Freezing layer 'model.19.bn.bias'
Freezing layer 'model.21.cv1.conv.weight'
Freezing layer 'model.21.cv1.bn.weight'
Freezing layer 'model.21.cv1.bn.bias'
Freezing layer 'model.21.cv2.conv.weight'
Freezing layer 'model.21.cv2.bn.weight'
Freezing layer 'model.21.cv2.bn.bias'
Freezing layer 'model.21.m.0.cv1.conv.weight'
Freezing layer 'model.21.m.0.cv1.bn.weight'
Freezing layer 'model.21.m.0.cv1.bn.bias'
Freezing layer 'model.21.m.0.cv2.conv.weight'
Freezing layer 'model.21.m.0.cv2.bn.weight'
Freezing layer 'model.21.m.0.cv2.bn.bias'
Freezing layer 'model.21.m.1.cv1.conv.weight'
Freezing layer 'model.21.m.1.cv1.bn.weight'
Freezing layer 'model.21.m.1.cv1.bn.bias'
Freezing layer 'model.21.m.1.cv2.conv.weight'
Freezing layer 'model.21.m.1.cv2.bn.weight'
Freezing layer 'model.21.m.1.cv2.bn.bias'
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 95.0±64.8 MB/s, size: 51.9 KB)

train: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/train/labels... 919 images, 0 backgrounds, 0 corrupt: 100%|██████████| 919/919 [00:01<00:00, 679.73it/s]

WARNING ⚠️ train: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 38.8±24.5 MB/s, size: 35.4 KB)

val: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels... 230 images, 0 backgrounds, 0 corrupt: 100%|██████████| 230/230 [00:00<00:00, 427.41it/s]

WARNING ⚠️ val: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/val is not writeable, cache not saved.

Plotting labels to runs/detect/train2/labels.jpg...
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 77 weight(decay=0.0), 84 weight(decay=0.001), 83 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs/detect/train2
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       1/32      4.79G       2.81      3.307       2.54        249        640: 100%|██████████| 29/29 [00:12<00:00,  2.28it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.43it/s]

                   all        230       1440      0.515      0.593      0.619      0.321

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       2/32      6.99G      1.629      1.555      1.539        222        640: 100%|██████████| 29/29 [00:12<00:00,  2.38it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.52it/s]

                   all        230       1440       0.65        0.8      0.805      0.448

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       3/32      6.99G      1.522      1.401      1.466        203        640: 100%|██████████| 29/29 [00:11<00:00,  2.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.56it/s]

                   all        230       1440      0.719       0.82      0.903      0.524

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       4/32      6.99G      1.464       1.29      1.421        242        640: 100%|██████████| 29/29 [00:11<00:00,  2.42it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.55it/s]

                   all        230       1440      0.765      0.821      0.929      0.557

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       5/32      6.99G      1.446      1.136      1.417        250        640: 100%|██████████| 29/29 [00:12<00:00,  2.41it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.56it/s]

                   all        230       1440      0.841      0.877      0.945      0.578

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       6/32      6.99G      1.436     0.9757       1.42        251        640: 100%|██████████| 29/29 [00:11<00:00,  2.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.56it/s]

                   all        230       1440      0.825      0.918      0.944      0.568

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       7/32      6.99G      1.404     0.9172       1.39        257        640: 100%|██████████| 29/29 [00:11<00:00,  2.42it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.56it/s]

                   all        230       1440      0.887      0.922      0.964      0.596

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       8/32      6.99G      1.389     0.8804       1.38        273        640: 100%|██████████| 29/29 [00:11<00:00,  2.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.54it/s]

                   all        230       1440       0.92       0.94      0.972      0.599

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

       9/32      7.01G      1.368     0.8494      1.371        265        640: 100%|██████████| 29/29 [00:11<00:00,  2.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.58it/s]

                   all        230       1440      0.942      0.955      0.973        0.6

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      10/32      7.04G      1.369     0.8139      1.353        233        640: 100%|██████████| 29/29 [00:11<00:00,  2.44it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.55it/s]

                   all        230       1440      0.948      0.948      0.972      0.605

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      11/32      7.07G      1.352     0.7894      1.364        282        640: 100%|██████████| 29/29 [00:11<00:00,  2.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.56it/s]

                   all        230       1440       0.94      0.959      0.976      0.607

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      12/32      7.09G      1.356     0.7863      1.365        205        640: 100%|██████████| 29/29 [00:11<00:00,  2.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.54it/s]

                   all        230       1440      0.929      0.958      0.977      0.618

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      13/32      7.12G      1.335     0.7672      1.346        219        640: 100%|██████████| 29/29 [00:11<00:00,  2.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.59it/s]

                   all        230       1440      0.946      0.968      0.976      0.608

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      14/32      7.15G      1.345      0.763      1.348        239        640: 100%|██████████| 29/29 [00:11<00:00,  2.42it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.55it/s]

                   all        230       1440      0.944      0.967      0.977      0.616

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      15/32      7.17G      1.332     0.7388      1.331        254        640: 100%|██████████| 29/29 [00:11<00:00,  2.42it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.58it/s]

                   all        230       1440      0.968      0.963      0.983      0.623

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      16/32       7.2G      1.332     0.7372      1.351        231        640: 100%|██████████| 29/29 [00:11<00:00,  2.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.59it/s]

                   all        230       1440      0.954      0.966      0.979      0.614

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      25/32      7.43G       1.27     0.6295      1.409        121        640: 100%|██████████| 29/29 [00:11<00:00,  2.46it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.57it/s]

                   all        230       1440      0.975      0.976      0.984      0.631

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      26/32      7.46G      1.255     0.6187      1.386        141        640: 100%|██████████| 29/29 [00:11<00:00,  2.45it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.58it/s]

                   all        230       1440       0.97      0.978      0.984      0.624

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      27/32      7.48G      1.255     0.6121      1.395        138        640: 100%|██████████| 29/29 [00:11<00:00,  2.47it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.56it/s]

                   all        230       1440      0.976      0.975      0.983      0.631

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      28/32      7.51G      1.265     0.6214        1.4        136        640: 100%|██████████| 29/29 [00:11<00:00,  2.44it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.58it/s]

                   all        230       1440      0.972      0.976      0.985      0.634

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      29/32      7.54G      1.248     0.6109      1.392        145        640: 100%|██████████| 29/29 [00:11<00:00,  2.43it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.59it/s]

                   all        230       1440      0.975      0.979      0.985      0.637

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      30/32      7.57G      1.243     0.6032       1.38        140        640: 100%|██████████| 29/29 [00:11<00:00,  2.44it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.55it/s]

                   all        230       1440      0.976      0.982      0.985      0.639

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      31/32      7.59G      1.245      0.602        1.4        124        640: 100%|██████████| 29/29 [00:11<00:00,  2.46it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.60it/s]

                   all        230       1440      0.978      0.977      0.984      0.645

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size

      32/32      7.62G      1.235     0.5962      1.383        142        640: 100%|██████████| 29/29 [00:11<00:00,  2.46it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.55it/s]

                   all        230       1440       0.98      0.978      0.985       0.64

32 epochs completed in 0.134 hours.
Optimizer stripped from runs/detect/train2/weights/last.pt, 52.0MB
Optimizer stripped from runs/detect/train2/weights/best.pt, 52.0MB

Validating runs/detect/train2/weights/best.pt...
Ultralytics 8.3.185 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
Model summary (fused): 92 layers, 25,843,234 parameters, 0 gradients, 78.7 GFLOPs

                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:04<00:00,  1.02s/it]
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        230       1440      0.978      0.977      0.984      0.645
     DC Voltage Source        103        144      0.994      0.972       0.98      0.715
              Resistor        183        605      0.983       0.98      0.987      0.623
        Current Source        113        150       0.96       0.98      0.984      0.691
              Inductor        117        177      0.978      0.983       0.98      0.577
             Capacitor        115        184      0.978      0.973      0.982      0.549
     AC Voltage Source         65        180      0.978      0.973      0.993      0.714
Speed: 0.1ms preprocess, 8.2ms inference, 0.0ms loss, 2.9ms postprocess per image
Results saved to runs/detect/train2

,Case,Experiment No,Experiment Name,Epochs,Batch,lr0,Weight Decay,Optimizer,Image Size,Dropout,Freeze Layers,Activation,Training Time (s),Precision,Recall,mAP@0.5,mAP@0.5:0.95
0,Case 8: Freeze Layers,1,freeze_15,32,32,0.01,0.001,SGD,640,0.0,15,SiLU,675.82,0.988366,0.986431,0.987107,0.689567
1,Case 8: Freeze Layers,2,freeze_22,32,32,0.01,0.001,SGD,640,0.0,22,SiLU,504.21,0.978447,0.976879,0.984360,0.644947

In [3]:
# Case 3: Varying Batch Size
# ===============================
run_ablation("Case 3: Batch Size", "batch", [16, 32, 64])

🚀 Case 3: Batch Size | Experiment 1: batch=16
Downloading https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov8m.pt to 'yolov8m.pt': 100% ━━━━━━━━━━━━ 49.7MB 318.0MB/s 0.2s0.1s<0.1s
Ultralytics 8.3.193 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-component-data/YOLO_component-dataset/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8m.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=/kaggle/working/runs/detect/train, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.001, workers=8, workspace=None
Downloading https://ultralytics.com/assets/Arial.ttf to '/root/.config/Ultralytics/Arial.ttf': 100% ━━━━━━━━━━━━ 755.1KB 22.4MB/s 0.0s
Overriding model.yaml nc=80 with nc=6

                   from  n    params  module                                       arguments
  0                  -1  1      1392  ultralytics.nn.modules.conv.Conv             [3, 48, 3, 2]
  1                  -1  1     41664  ultralytics.nn.modules.conv.Conv             [48, 96, 3, 2]
  2                  -1  2    111360  ultralytics.nn.modules.block.C2f             [96, 96, 2, True]
  3                  -1  1    166272  ultralytics.nn.modules.conv.Conv             [96, 192, 3, 2]
  4                  -1  4    813312  ultralytics.nn.modules.block.C2f             [192, 192, 4, True]
  5                  -1  1    664320  ultralytics.nn.modules.conv.Conv             [192, 384, 3, 2]
  6                  -1  4   3248640  ultralytics.nn.modules.block.C2f             [384, 384, 4, True]
  7                  -1  1   1991808  ultralytics.nn.modules.conv.Conv             [384, 576, 3, 2]
  8                  -1  2   3985920  ultralytics.nn.modules.block.C2f             [576, 576, 2, True]
  9                  -1  1    831168  ultralytics.nn.modules.block.SPPF            [576, 576, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  2   1993728  ultralytics.nn.modules.block.C2f             [960, 384, 2]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  2    517632  ultralytics.nn.modules.block.C2f             [576, 192, 2]
 16                  -1  1    332160  ultralytics.nn.modules.conv.Conv             [192, 192, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  2   1846272  ultralytics.nn.modules.block.C2f             [576, 384, 2]
 19                  -1  1   1327872  ultralytics.nn.modules.conv.Conv             [384, 384, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  2   4207104  ultralytics.nn.modules.block.C2f             [960, 576, 2]
 22        [15, 18, 21]  1   3779170  ultralytics.nn.modules.head.Detect           [6, [192, 384, 576]]
Model summary: 169 layers, 25,859,794 parameters, 25,859,778 gradients, 79.1 GFLOPs

Transferred 469/475 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
Downloading https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11n.pt to 'yolo11n.pt': 100% ━━━━━━━━━━━━ 5.4MB 103.7MB/s 0.1s
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 10.1±1.1 MB/s, size: 51.9 KB)
train: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/train/labels... 919 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 919/919 350.6it/s 2.6s0.1s
WARNING ⚠️ train: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 9.9±4.5 MB/s, size: 35.4 KB)
val: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels... 230 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 230/230 291.7it/s 0.8s0.1s
WARNING ⚠️ val: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/val is not writeable, cache not saved.
Plotting labels to /kaggle/working/runs/detect/train/labels.jpg...
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 77 weight(decay=0.0), 84 weight(decay=0.001), 83 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to /kaggle/working/runs/detect/train
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/32      7.77G      2.122       2.75      1.773         85        640: 100% ━━━━━━━━━━━━ 58/58 1.6it/s 36.8s0.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 2.4it/s 3.4s0.4ss
                   all        230       1440      0.717      0.881      0.906      0.558

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/32      7.81G       1.38     0.9795      1.273         92        640: 100% ━━━━━━━━━━━━ 58/58 1.6it/s 35.8s0.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 3.3it/s 2.4s0.4s
                   all        230       1440      0.944       0.95       0.98      0.605

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/32      7.86G      1.379     0.8193      1.279         51        640: 100% ━━━━━━━━━━━━ 58/58 1.6it/s 35.6s0.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 3.3it/s 2.4s0.4s
                   all        230       1440      0.954      0.981      0.984      0.609

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/32       7.9G      1.319     0.7223      1.241         72        640: 100% ━━━━━━━━━━━━ 58/58 1.6it/s 35.6s0.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 3.4it/s 2.4s0.4s
                   all        230       1440      0.979      0.984      0.986      0.598

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/32      7.95G      1.321     0.6473      1.241         77        640: 100% ━━━━━━━━━━━━ 58/58 1.6it/s 35.5s0.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 3.3it/s 2.4s0.4s
                   all        230       1440      0.981      0.983      0.985      0.623

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/32      8.06G      1.311     0.6099      1.238         50        640: 100% ━━━━━━━━━━━━ 58/58 1.6it/s 35.5s0.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 3.3it/s 2.4s0.4s
                   all        230       1440      0.969      0.956      0.982       0.65

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/32      7.93G      1.252     0.5998       1.21         78        640: 100% ━━━━━━━━━━━━ 58/58 1.6it/s 35.5s0.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 3.4it/s 2.4s0.4s
                   all        230       1440      0.982      0.981      0.987      0.652

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/32      7.95G      1.263     0.5603       1.22         86        640: 100% ━━━━━━━━━━━━ 58/58 1.6it/s 35.5s0.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 3.3it/s 2.4s0.4s
                   all        230       1440       0.98      0.985      0.984      0.656

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/32      7.94G       1.23     0.5602      1.199         68        640: 100% ━━━━━━━━━━━━ 58/58 1.6it/s 35.5s0.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 3.4it/s 2.4s0.4s
                   all        230       1440      0.982      0.989      0.986      0.655

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/32      8.14G      1.232      0.552      1.186         80        640: 100% ━━━━━━━━━━━━ 58/58 1.6it/s 35.5s0.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 3.3it/s 2.4s0.4s
                   all        230       1440      0.985      0.988      0.986      0.658

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/32      7.93G      1.217     0.5408      1.209         86        640: 100% ━━━━━━━━━━━━ 58/58 1.6it/s 35.5s0.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 3.4it/s 2.4s0.4s
                   all        230       1440      0.985      0.985      0.986      0.666

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/32      7.96G       1.21      0.529        1.2         81        640: 100% ━━━━━━━━━━━━ 58/58 1.6it/s 35.6s0.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 3.4it/s 2.4s0.4s
                   all        230       1440      0.973       0.98      0.983      0.651

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/32      7.94G      1.181     0.5092      1.188         55        640: 100% ━━━━━━━━━━━━ 58/58 1.6it/s 35.5s0.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 3.4it/s 2.4s0.4s
                   all        230       1440      0.986      0.987      0.987      0.676

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/32      8.15G      1.176     0.5176      1.178         80        640: 100% ━━━━━━━━━━━━ 58/58 1.6it/s 35.5s0.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 3.3it/s 2.4s0.4s
                   all        230       1440      0.988      0.987      0.989      0.669

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/32      7.91G      1.182     0.5081      1.172         90        640: 100% ━━━━━━━━━━━━ 58/58 1.6it/s 35.5s0.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 3.4it/s 2.4s0.4s
                   all        230       1440      0.985      0.987      0.988      0.667

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/32      7.96G       1.16      0.494       1.18         77        640: 100% ━━━━━━━━━━━━ 58/58 1.6it/s 35.5s0.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 3.4it/s 2.4s0.4s
                   all        230       1440      0.987      0.987      0.987      0.669

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/32      7.93G      1.161     0.4895      1.182         99        640: 100% ━━━━━━━━━━━━ 58/58 1.6it/s 35.5s0.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 3.4it/s 2.4s0.4s
                   all        230       1440      0.988      0.987      0.987      0.684

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/32      7.98G      1.137     0.4844      1.167         74        640: 100% ━━━━━━━━━━━━ 58/58 1.6it/s 35.6s0.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 3.4it/s 2.4s0.4s
                   all        230       1440      0.985      0.985      0.986      0.671

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/32      7.94G      1.134     0.4814      1.167         57        640: 100% ━━━━━━━━━━━━ 58/58 1.6it/s 35.5s0.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 3.4it/s 2.4s0.4s
                   all        230       1440      0.988      0.986      0.986      0.658

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/32      7.94G      1.129     0.4705      1.159         73        640: 100% ━━━━━━━━━━━━ 58/58 1.6it/s 35.5s0.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 3.4it/s 2.4s0.4s
                   all        230       1440      0.987      0.988      0.988      0.674

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/32      7.96G      1.113     0.4562       1.16         87        640: 100% ━━━━━━━━━━━━ 58/58 1.6it/s 35.5s0.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 3.4it/s 2.4s0.4s
                   all        230       1440       0.99      0.989      0.988      0.682

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/32      7.98G      1.109      0.449      1.145         98        640: 100% ━━━━━━━━━━━━ 58/58 1.6it/s 35.5s0.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 3.3it/s 2.4s0.4s
                   all        230       1440      0.989      0.988      0.989      0.682
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/32      7.93G       1.09     0.4062      1.209         38        640: 100% ━━━━━━━━━━━━ 58/58 1.6it/s 36.0s0.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 3.4it/s 2.4s0.4s
                   all        230       1440      0.989      0.988      0.988      0.676

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/32      7.94G      1.084     0.4004      1.198         40        640: 100% ━━━━━━━━━━━━ 58/58 1.6it/s 35.5s0.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 3.3it/s 2.4s0.4s
                   all        230       1440       0.99      0.989      0.988      0.678

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/32      7.97G      1.061     0.3978      1.192         31        640: 100% ━━━━━━━━━━━━ 58/58 1.6it/s 35.5s0.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 3.4it/s 2.4s0.4s
                   all        230       1440       0.99      0.989      0.987      0.676

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/32         8G      1.042     0.3893      1.172         43        640: 100% ━━━━━━━━━━━━ 58/58 1.6it/s 35.5s0.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 3.4it/s 2.4s0.4s
                   all        230       1440       0.99       0.99      0.987      0.683

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/32      7.91G      1.021     0.3808      1.175         44        640: 100% ━━━━━━━━━━━━ 58/58 1.6it/s 35.4s0.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 3.4it/s 2.4s0.4s
                   all        230       1440      0.988      0.987      0.987      0.683

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/32      7.95G       1.01     0.3748      1.169         37        640: 100% ━━━━━━━━━━━━ 58/58 1.6it/s 35.5s0.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 3.4it/s 2.4s0.4s
                   all        230       1440      0.989      0.989      0.987      0.685

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/32      7.94G     0.9958     0.3692      1.156         55        640: 100% ━━━━━━━━━━━━ 58/58 1.6it/s 35.4s0.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 3.4it/s 2.4s0.4s
                   all        230       1440       0.99       0.99      0.989      0.683

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/32      7.91G     0.9766     0.3599      1.144         38        640: 100% ━━━━━━━━━━━━ 58/58 1.6it/s 35.5s0.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 3.4it/s 2.4s0.4s
                   all        230       1440       0.99       0.99      0.988      0.683

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/32      7.94G     0.9545     0.3527       1.14         35        640: 100% ━━━━━━━━━━━━ 58/58 1.6it/s 35.4s0.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 3.3it/s 2.4s0.4s
                   all        230       1440       0.99      0.989      0.987      0.687

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/32       7.9G     0.9554     0.3496      1.137         42        640: 100% ━━━━━━━━━━━━ 58/58 1.6it/s 35.5s0.5ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 3.4it/s 2.4s0.4s
                   all        230       1440      0.989       0.99      0.988      0.687

32 epochs completed in 0.345 hours.
Optimizer stripped from /kaggle/working/runs/detect/train/weights/last.pt, 52.0MB
Optimizer stripped from /kaggle/working/runs/detect/train/weights/best.pt, 52.0MB


/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        230       1440       0.99      0.989      0.987      0.687
     DC Voltage Source        103        144      0.992      0.979      0.984      0.759
              Resistor        183        605      0.985      0.994      0.986      0.649
        Current Source        113        150      0.985          1      0.988      0.738
              Inductor        117        177      0.989      0.989      0.986      0.642
             Capacitor        115        184      0.993      0.989      0.986      0.611
     AC Voltage Source         65        180      0.994      0.986      0.993      0.721
Speed: 0.1ms preprocess, 9.0ms inference, 0.0ms loss, 1.4ms postprocess per image
Results saved to /kaggle/working/runs/detect/train

🚀 Case 3: Batch Size | Experiment 2: batch=32
Ultralytics 8.3.193 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-component-data/YOLO_component-dataset/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8m.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train2, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=/kaggle/working/runs/detect/train2, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.001, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=6

                   from  n    params  module                                       arguments
  0                  -1  1      1392  ultralytics.nn.modules.conv.Conv             [3, 48, 3, 2]
  1                  -1  1     41664  ultralytics.nn.modules.conv.Conv             [48, 96, 3, 2]
  2                  -1  2    111360  ultralytics.nn.modules.block.C2f             [96, 96, 2, True]
  3                  -1  1    166272  ultralytics.nn.modules.conv.Conv             [96, 192, 3, 2]
  4                  -1  4    813312  ultralytics.nn.modules.block.C2f             [192, 192, 4, True]
  5                  -1  1    664320  ultralytics.nn.modules.conv.Conv             [192, 384, 3, 2]
  6                  -1  4   3248640  ultralytics.nn.modules.block.C2f             [384, 384, 4, True]
  7                  -1  1   1991808  ultralytics.nn.modules.conv.Conv             [384, 576, 3, 2]
  8                  -1  2   3985920  ultralytics.nn.modules.block.C2f             [576, 576, 2, True]
  9                  -1  1    831168  ultralytics.nn.modules.block.SPPF            [576, 576, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  2   1993728  ultralytics.nn.modules.block.C2f             [960, 384, 2]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  2    517632  ultralytics.nn.modules.block.C2f             [576, 192, 2]
 16                  -1  1    332160  ultralytics.nn.modules.conv.Conv             [192, 192, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  2   1846272  ultralytics.nn.modules.block.C2f             [576, 384, 2]
 19                  -1  1   1327872  ultralytics.nn.modules.conv.Conv             [384, 384, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  2   4207104  ultralytics.nn.modules.block.C2f             [960, 576, 2]
 22        [15, 18, 21]  1   3779170  ultralytics.nn.modules.head.Detect           [6, [192, 384, 576]]
Model summary: 169 layers, 25,859,794 parameters, 25,859,778 gradients, 79.1 GFLOPs

Transferred 469/475 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 97.6±76.4 MB/s, size: 51.9 KB)
train: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/train/labels... 919 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 919/919 868.0it/s 1.1s0.0s
WARNING ⚠️ train: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 47.1±25.1 MB/s, size: 35.4 KB)
val: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels... 230 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 230/230 495.7it/s 0.5s0.1s
WARNING ⚠️ val: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/val is not writeable, cache not saved.
Plotting labels to /kaggle/working/runs/detect/train2/labels.jpg...
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 77 weight(decay=0.0), 84 weight(decay=0.001), 83 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to /kaggle/working/runs/detect/train2
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/32      14.1G      2.554      3.684       2.06        249        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.8s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.3it/s 3.0s1.2s
                   all        230       1440       0.67      0.688      0.714      0.407

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/32      13.9G      1.388      1.031      1.284        222        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.2s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.5s1.0s
                   all        230       1440       0.91      0.943      0.972      0.576

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/32      13.9G      1.354     0.8712      1.258        203        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.9s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.957      0.975      0.979      0.623

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/32      13.9G      1.343     0.7808      1.244        242        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440       0.98       0.98      0.988      0.651

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/32      13.9G        1.3     0.6796      1.231        250        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.9s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.974      0.964      0.982      0.648

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/32        14G      1.286     0.6039      1.235        251        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.9s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.984      0.983      0.986      0.627

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/32      13.9G      1.259     0.5836      1.216        257        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.9s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440       0.98      0.982      0.982       0.64

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/32      13.9G      1.262     0.5733      1.217        273        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.9s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.976       0.98      0.982      0.605

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/32      13.9G      1.258     0.5537      1.221        265        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.969      0.978      0.984      0.655

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/32      13.9G      1.232     0.5539      1.202        233        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.988      0.982      0.987      0.633

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/32      13.3G      1.223     0.5346      1.214        282        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.9s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.989      0.984      0.988      0.655

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/32      13.9G      1.217     0.5251      1.219        205        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.9s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.987      0.986      0.988      0.662

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/32      13.9G      1.186     0.5148      1.194        219        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.9s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440       0.99      0.986      0.989      0.652

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/32      13.9G      1.191     0.5082      1.204        239        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.985      0.985      0.986       0.66

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/32      13.9G      1.197     0.4964      1.214        254        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.9s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.982      0.983      0.987      0.672

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/32        14G      1.158     0.4899      1.211        231        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.985      0.989      0.987      0.676

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/32      13.9G       1.16     0.4824      1.211        275        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.9s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.981       0.98      0.986      0.671

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/32      13.9G       1.15     0.4686      1.222        261        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.9s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.987      0.983      0.985      0.678

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/32      13.9G      1.145     0.4676      1.219        187        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.9s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.987      0.984      0.987      0.669

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/32      13.9G      1.118     0.4547       1.18        223        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.9s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.989      0.983      0.988      0.677

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/32      13.9G      1.107     0.4494      1.184        232        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.9s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.989      0.989      0.987      0.686

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/32      13.9G      1.095     0.4451      1.168        242        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.9s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.988      0.986      0.988      0.684
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/32      13.9G      1.089     0.4029      1.238        147        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 33.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440       0.99      0.989      0.988       0.68

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/32      13.9G      1.068     0.3902       1.23        127        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.8s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.989      0.986      0.987      0.678

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/32      13.9G      1.051     0.3857      1.227        121        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.8s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.987      0.987      0.988       0.67

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/32      13.9G      1.031      0.373      1.204        141        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.8s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.987      0.989      0.987      0.685

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/32      13.9G      1.016      0.371      1.199        138        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.8s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440       0.99      0.989      0.986      0.687

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/32      13.9G      1.004     0.3684      1.199        136        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.8s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440       0.99      0.989      0.988      0.689

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/32      13.9G     0.9873     0.3578      1.192        145        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.8s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.992      0.989      0.988       0.69

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/32      13.9G     0.9779     0.3549      1.177        140        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.8s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.991       0.99      0.987      0.685

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/32      13.9G     0.9527     0.3435      1.178        124        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.8s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.991       0.99      0.987      0.691

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/32      13.9G     0.9411      0.342      1.159        142        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.8s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s

/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        230       1440      0.991      0.991      0.987      0.692
     DC Voltage Source        103        144          1      0.979      0.984       0.76
              Resistor        183        605      0.985      0.992      0.987       0.65
        Current Source        113        150      0.982          1      0.984       0.74
              Inductor        117        177      0.994      0.988       0.99      0.646
             Capacitor        115        184      0.993      0.989      0.985      0.638
     AC Voltage Source         65        180      0.993      0.994      0.995      0.717
Speed: 0.1ms preprocess, 8.1ms inference, 0.0ms loss, 1.7ms postprocess per image
Results saved to /kaggle/working/runs/detect/train2

🚀 Case 3: Batch Size | Experiment 3: batch=64
Ultralytics 8.3.193 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=64, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-component-data/YOLO_component-dataset/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8m.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train3, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=/kaggle/working/runs/detect/train3, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.001, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=6

                   from  n    params  module                                       arguments
  0                  -1  1      1392  ultralytics.nn.modules.conv.Conv             [3, 48, 3, 2]
  1                  -1  1     41664  ultralytics.nn.modules.conv.Conv             [48, 96, 3, 2]
  2                  -1  2    111360  ultralytics.nn.modules.block.C2f             [96, 96, 2, True]
  3                  -1  1    166272  ultralytics.nn.modules.conv.Conv             [96, 192, 3, 2]
  4                  -1  4    813312  ultralytics.nn.modules.block.C2f             [192, 192, 4, True]
  5                  -1  1    664320  ultralytics.nn.modules.conv.Conv             [192, 384, 3, 2]
  6                  -1  4   3248640  ultralytics.nn.modules.block.C2f             [384, 384, 4, True]
  7                  -1  1   1991808  ultralytics.nn.modules.conv.Conv             [384, 576, 3, 2]
  8                  -1  2   3985920  ultralytics.nn.modules.block.C2f             [576, 576, 2, True]
  9                  -1  1    831168  ultralytics.nn.modules.block.SPPF            [576, 576, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  2   1993728  ultralytics.nn.modules.block.C2f             [960, 384, 2]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  2    517632  ultralytics.nn.modules.block.C2f             [576, 192, 2]
 16                  -1  1    332160  ultralytics.nn.modules.conv.Conv             [192, 192, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  2   1846272  ultralytics.nn.modules.block.C2f             [576, 384, 2]
 19                  -1  1   1327872  ultralytics.nn.modules.conv.Conv             [384, 384, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  2   4207104  ultralytics.nn.modules.block.C2f             [960, 576, 2]
 22        [15, 18, 21]  1   3779170  ultralytics.nn.modules.head.Detect           [6, [192, 384, 576]]
Model summary: 169 layers, 25,859,794 parameters, 25,859,778 gradients, 79.1 GFLOPs

Transferred 469/475 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 102.7±77.4 MB/s, size: 51.9 KB)
train: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/train/labels... 919 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 919/919 895.1it/s 1.0s0.0s
WARNING ⚠️ train: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.3±0.7 ms, read: 46.2±25.6 MB/s, size: 35.4 KB)
val: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels... 230 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 230/230 493.4it/s 0.5s0.1s
WARNING ⚠️ val: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/val is not writeable, cache not saved.
Plotting labels to /kaggle/working/runs/detect/train3/labels.jpg...
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 77 weight(decay=0.0), 84 weight(decay=0.001), 83 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to /kaggle/working/runs/detect/train3
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
: 0% ──────────── 0/15  3.9s
❌ Error in batch=64: CUDA out of memory. Tried to allocate 600.00 MiB. GPU 0 has a total capacity of 15.89 GiB of which 251.12 MiB is free. Process 3754 has 15.64 GiB memory in use. Of the allocated memory 14.91 GiB is allocated by PyTorch, and 419.93 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

,Case,Experiment No,Experiment Name,Epochs,Batch,lr0,Weight Decay,Optimizer,Image Size,Dropout,Freeze Layers,Activation,Training Time (s),Precision,Recall,mAP@0.5,mAP@0.5:0.95
0,Case 3: Batch Size,1,batch_16,32,16,0.01,0.001,SGD,640,0.0,0,SiLU,1267.75,0.9898094080557646,0.9894705611842188,0.9873951921114864,0.6866352229419413
1,Case 3: Batch Size,2,batch_32,32,32,0.01,0.001,SGD,640,0.0,0,SiLU,1153.51,0.991306588627882,0.990504688006188,0.9873156486165096,0.6919208489023024
2,Case 3: Batch Size,3,batch_64,32,64,0.01,0.001,SGD,640,0.0,0,SiLU,Error,Error,Error,Error,Error

In [4]:
run_ablation("Case 7: Learning Rate", "lr0", [0.001, 0.005, 0.01, 0.05, 0.1])

🚀 Case 7: Learning Rate | Experiment 1: lr0=0.001
Ultralytics 8.3.193 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-component-data/YOLO_component-dataset/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.001, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8m.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train4, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=/kaggle/working/runs/detect/train4, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.001, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=6

                   from  n    params  module                                       arguments
  0                  -1  1      1392  ultralytics.nn.modules.conv.Conv             [3, 48, 3, 2]
  1                  -1  1     41664  ultralytics.nn.modules.conv.Conv             [48, 96, 3, 2]
  2                  -1  2    111360  ultralytics.nn.modules.block.C2f             [96, 96, 2, True]
  3                  -1  1    166272  ultralytics.nn.modules.conv.Conv             [96, 192, 3, 2]
  4                  -1  4    813312  ultralytics.nn.modules.block.C2f             [192, 192, 4, True]
  5                  -1  1    664320  ultralytics.nn.modules.conv.Conv             [192, 384, 3, 2]
  6                  -1  4   3248640  ultralytics.nn.modules.block.C2f             [384, 384, 4, True]
  7                  -1  1   1991808  ultralytics.nn.modules.conv.Conv             [384, 576, 3, 2]
  8                  -1  2   3985920  ultralytics.nn.modules.block.C2f             [576, 576, 2, True]
  9                  -1  1    831168  ultralytics.nn.modules.block.SPPF            [576, 576, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  2   1993728  ultralytics.nn.modules.block.C2f             [960, 384, 2]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  2    517632  ultralytics.nn.modules.block.C2f             [576, 192, 2]
 16                  -1  1    332160  ultralytics.nn.modules.conv.Conv             [192, 192, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  2   1846272  ultralytics.nn.modules.block.C2f             [576, 384, 2]
 19                  -1  1   1327872  ultralytics.nn.modules.conv.Conv             [384, 384, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  2   4207104  ultralytics.nn.modules.block.C2f             [960, 576, 2]
 22        [15, 18, 21]  1   3779170  ultralytics.nn.modules.head.Detect           [6, [192, 384, 576]]
Model summary: 169 layers, 25,859,794 parameters, 25,859,778 gradients, 79.1 GFLOPs

Transferred 469/475 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 91.4±59.8 MB/s, size: 51.9 KB)
train: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/train/labels... 919 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 919/919 920.9it/s 1.0s0.1s
WARNING ⚠️ train: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 50.2±26.5 MB/s, size: 35.4 KB)
val: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels... 230 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 230/230 497.4it/s 0.5s0.1s
WARNING ⚠️ val: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/val is not writeable, cache not saved.
Plotting labels to /kaggle/working/runs/detect/train4/labels.jpg...
optimizer: SGD(lr=0.001, momentum=0.937) with parameter groups 77 weight(decay=0.0), 84 weight(decay=0.001), 83 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to /kaggle/working/runs/detect/train4
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/32      13.7G      3.067      4.606      2.402        249        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.5s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.3it/s 3.0s1.2s
                   all        230       1440      0.272      0.208      0.114     0.0385

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/32      13.9G      1.889      2.422      1.629        222        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.2s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.4it/s 2.9s1.2s
                   all        230       1440      0.658      0.605      0.527      0.299

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/32      13.9G      1.466      1.345      1.331        203        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.4it/s 2.8s1.1s
                   all        230       1440      0.852      0.813      0.892      0.544

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/32      13.9G      1.335      0.894      1.238        242        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.5s1.0s
                   all        230       1440       0.94      0.937       0.97        0.6

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/32      13.9G      1.284     0.7307      1.213        250        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.9s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.5s1.0s
                   all        230       1440      0.941      0.965      0.979      0.633

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/32      13.9G      1.254      0.645      1.206        251        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.5s1.0s
                   all        230       1440      0.976      0.978      0.985       0.64

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/32      13.9G       1.24     0.6001      1.196        257        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.9s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.982      0.984      0.985      0.652

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/32        14G      1.232     0.5786      1.192        273        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.982       0.98      0.987      0.653

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/32      13.9G      1.217     0.5594       1.19        265        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.981      0.985      0.988      0.667

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/32      13.9G      1.209      0.541      1.173        233        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.985      0.987      0.986      0.669

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/32      13.9G      1.194     0.5252      1.176        282        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.979      0.978      0.988      0.641

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/32        14G       1.19     0.5225      1.176        205        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.988      0.983      0.987       0.67

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/32      13.9G      1.169     0.5109      1.155        219        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.9s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.983      0.985      0.988      0.673

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/32      13.9G      1.176      0.509      1.166        239        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.983      0.987      0.988      0.674

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/32      13.9G      1.173     0.4954      1.165        254        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.987      0.983      0.989      0.672

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/32      13.9G      1.146      0.492      1.166        231        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.989      0.987      0.988      0.675

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/32      13.9G      1.147     0.4837      1.162        275        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.988      0.988      0.989      0.672

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/32      13.9G      1.143     0.4728      1.163        261        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.987      0.989      0.989      0.676

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/32      13.9G       1.14     0.4755      1.166        187        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.989      0.987      0.988       0.68

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/32        14G      1.122      0.464      1.144        223        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.988      0.987      0.989      0.685

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/32      13.9G      1.117      0.461      1.143        232        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.987       0.99      0.988      0.689

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/32      13.9G      1.114     0.4599      1.136        242        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.988      0.988      0.989      0.687
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/32      13.9G      1.115     0.4275      1.195        147        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 33.1s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.986      0.986      0.987      0.682

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/32      13.9G      1.097     0.4086      1.186        127        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.9s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.984      0.986      0.988      0.683

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/32      13.9G      1.092     0.4073      1.189        121        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.8s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.987      0.986      0.988      0.685

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/32        14G       1.08      0.399      1.175        141        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.9s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.989      0.986      0.988      0.681

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/32      13.9G      1.072     0.3967      1.171        138        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.8s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.989      0.985      0.988      0.683

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/32      13.9G      1.073     0.3995      1.171        136        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.9s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.986      0.988      0.989      0.681

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/32      13.9G      1.059     0.3906      1.169        145        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.8s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.988      0.989      0.989      0.685

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/32      13.9G      1.065     0.3951      1.162        140        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.9s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.989      0.987      0.988      0.682

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/32      13.9G      1.056     0.3884      1.174        124        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.8s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440       0.99      0.987      0.989      0.685

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/32      13.9G      1.052     0.3878      1.162        142        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.9s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.991      0.988      0.989      0.685

32 epochs completed in 0.317 hours.
Optimizer stripped from /kaggle/working/runs/detect/train4/weights/last.pt, 52.0MB
Optimizer stripped from /kaggle/working/runs/detect/train4/weights/best.pt, 52.0MB

Validating /kaggle/working/runs/detect/train4/weights/best.pt...
Ultralytics 8.3.193 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
Model summary (fused): 92 layers, 25,843,234 parameters, 0 gradients, 78.7 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.0it/s 4.0s1.7s

/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        230       1440      0.987       0.99      0.988      0.689
     DC Voltage Source        103        144      0.986      0.979      0.981      0.757
              Resistor        183        605      0.985      0.989      0.987      0.649
        Current Source        113        150      0.979          1      0.986      0.744
              Inductor        117        177      0.985      0.989      0.992      0.644
             Capacitor        115        184      0.989      0.989       0.99      0.626
     AC Voltage Source         65        180      0.994      0.992      0.994      0.713
Speed: 0.1ms preprocess, 8.1ms inference, 0.0ms loss, 1.8ms postprocess per image
Results saved to /kaggle/working/runs/detect/train4

🚀 Case 7: Learning Rate | Experiment 2: lr0=0.005
Ultralytics 8.3.193 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-component-data/YOLO_component-dataset/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.005, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8m.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train5, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=/kaggle/working/runs/detect/train5, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.001, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=6

                   from  n    params  module                                       arguments
  0                  -1  1      1392  ultralytics.nn.modules.conv.Conv             [3, 48, 3, 2]
  1                  -1  1     41664  ultralytics.nn.modules.conv.Conv             [48, 96, 3, 2]
  2                  -1  2    111360  ultralytics.nn.modules.block.C2f             [96, 96, 2, True]
  3                  -1  1    166272  ultralytics.nn.modules.conv.Conv             [96, 192, 3, 2]
  4                  -1  4    813312  ultralytics.nn.modules.block.C2f             [192, 192, 4, True]
  5                  -1  1    664320  ultralytics.nn.modules.conv.Conv             [192, 384, 3, 2]
  6                  -1  4   3248640  ultralytics.nn.modules.block.C2f             [384, 384, 4, True]
  7                  -1  1   1991808  ultralytics.nn.modules.conv.Conv             [384, 576, 3, 2]
  8                  -1  2   3985920  ultralytics.nn.modules.block.C2f             [576, 576, 2, True]
  9                  -1  1    831168  ultralytics.nn.modules.block.SPPF            [576, 576, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  2   1993728  ultralytics.nn.modules.block.C2f             [960, 384, 2]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  2    517632  ultralytics.nn.modules.block.C2f             [576, 192, 2]
 16                  -1  1    332160  ultralytics.nn.modules.conv.Conv             [192, 192, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  2   1846272  ultralytics.nn.modules.block.C2f             [576, 384, 2]
 19                  -1  1   1327872  ultralytics.nn.modules.conv.Conv             [384, 384, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  2   4207104  ultralytics.nn.modules.block.C2f             [960, 576, 2]
 22        [15, 18, 21]  1   3779170  ultralytics.nn.modules.head.Detect           [6, [192, 384, 576]]
Model summary: 169 layers, 25,859,794 parameters, 25,859,778 gradients, 79.1 GFLOPs

Transferred 469/475 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 90.4±73.1 MB/s, size: 51.9 KB)
train: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/train/labels... 919 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 919/919 951.0it/s 1.0s0.1s
WARNING ⚠️ train: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 44.5±26.1 MB/s, size: 35.4 KB)
val: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels... 230 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 230/230 528.7it/s 0.4s0.0s
WARNING ⚠️ val: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/val is not writeable, cache not saved.
Plotting labels to /kaggle/working/runs/detect/train5/labels.jpg...
optimizer: SGD(lr=0.005, momentum=0.937) with parameter groups 77 weight(decay=0.0), 84 weight(decay=0.001), 83 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to /kaggle/working/runs/detect/train5
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/32        14G      2.666      3.913      2.125        249        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.7s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.3it/s 3.0s1.2s
                   all        230       1440      0.619      0.518      0.445       0.23

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/32      13.9G      1.415      1.201      1.297        222        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.2s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.5s1.0s
                   all        230       1440      0.909      0.912      0.956      0.606

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/32      13.9G      1.339     0.8187      1.246        203        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.9s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.5s1.0s
                   all        230       1440      0.913       0.93      0.958      0.609

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/32      13.9G      1.301     0.6943      1.219        242        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.948      0.957      0.975      0.636

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/32      13.9G      1.272     0.6168      1.205        250        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.9s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440       0.94      0.942      0.979      0.643

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/32      13.9G      1.248     0.5736      1.197        251        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440       0.98      0.972      0.984      0.651

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/32      13.9G      1.227      0.553      1.186        257        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.975      0.981      0.983      0.652

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/32      13.9G      1.218     0.5417      1.186        273        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.981      0.985      0.985      0.647

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/32      13.9G       1.22     0.5307      1.195        265        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.9s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.978      0.987      0.985      0.663

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/32      13.9G        1.2     0.5163      1.174        233        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.987      0.986       0.99      0.668

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/32      13.9G      1.186     0.4966      1.177        282        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.989      0.987      0.989      0.661

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/32      13.9G      1.179     0.4995      1.173        205        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.982      0.988      0.987      0.664

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/32      13.9G      1.158     0.4925      1.154        219        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.986      0.983      0.986      0.651

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/32      13.9G      1.163     0.4926      1.158        239        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.988      0.984      0.988      0.678

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/32      13.9G      1.161     0.4804      1.152        254        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.988      0.985      0.987      0.672

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/32      13.9G      1.133     0.4737       1.15        231        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.985      0.983      0.985      0.681

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/32      13.9G      1.127     0.4655      1.147        275        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.9s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.976      0.988      0.984       0.67

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/32      13.9G      1.117     0.4528      1.151        261        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.988      0.987      0.988      0.684

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/32      13.9G      1.115     0.4586      1.151        187        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.9s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.988      0.987      0.987      0.689

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/32      13.9G      1.091     0.4455      1.126        223        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.5s1.0s
                   all        230       1440       0.99      0.986      0.988      0.684

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/32      13.9G      1.078     0.4434       1.13        232        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.989      0.987      0.988      0.685

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/32      13.9G      1.064     0.4382      1.117        242        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.1s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.985      0.986      0.987      0.683
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/32      13.9G      1.064      0.394      1.173        147        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 33.2s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.987      0.989      0.987      0.676

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/32        14G      1.034     0.3792      1.155        127        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.9s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.987      0.987      0.986      0.677

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/32      13.9G      1.027     0.3736       1.15        121        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.8s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.984      0.985      0.986      0.681

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/32      13.9G      1.004     0.3657      1.133        141        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.9s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.989      0.985      0.986      0.691

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/32      13.9G     0.9869     0.3623      1.126        138        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.8s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440       0.99      0.986      0.988      0.692

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/32        14G     0.9767     0.3575       1.12        136        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.9s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.5s1.0s
                   all        230       1440       0.99      0.988      0.989      0.691

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/32      13.9G     0.9645     0.3482      1.118        145        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.8s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.991      0.985      0.988      0.692

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/32      13.9G     0.9572     0.3491      1.107        140        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.9s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.989      0.989      0.987      0.688

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/32      13.9G     0.9326     0.3372      1.114        124        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.8s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.5s1.0s
                   all        230       1440      0.991      0.989      0.987      0.692

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/32      13.9G     0.9333     0.3351      1.104        142        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.9s1.0ss

/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        230       1440       0.99       0.99      0.988      0.697
     DC Voltage Source        103        144          1      0.979      0.986      0.777
              Resistor        183        605      0.985      0.993       0.99      0.652
        Current Source        113        150       0.98      0.998      0.982      0.733
              Inductor        117        177      0.991      0.989      0.987      0.641
             Capacitor        115        184      0.992      0.989      0.986      0.651
     AC Voltage Source         65        180      0.992      0.994      0.994      0.725
Speed: 0.1ms preprocess, 8.2ms inference, 0.0ms loss, 2.7ms postprocess per image
Results saved to /kaggle/working/runs/detect/train5

🚀 Case 7: Learning Rate | Experiment 3: lr0=0.01
Ultralytics 8.3.193 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-component-data/YOLO_component-dataset/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8m.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train6, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=/kaggle/working/runs/detect/train6, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.001, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=6

                   from  n    params  module                                       arguments
  0                  -1  1      1392  ultralytics.nn.modules.conv.Conv             [3, 48, 3, 2]
  1                  -1  1     41664  ultralytics.nn.modules.conv.Conv             [48, 96, 3, 2]
  2                  -1  2    111360  ultralytics.nn.modules.block.C2f             [96, 96, 2, True]
  3                  -1  1    166272  ultralytics.nn.modules.conv.Conv             [96, 192, 3, 2]
  4                  -1  4    813312  ultralytics.nn.modules.block.C2f             [192, 192, 4, True]
  5                  -1  1    664320  ultralytics.nn.modules.conv.Conv             [192, 384, 3, 2]
  6                  -1  4   3248640  ultralytics.nn.modules.block.C2f             [384, 384, 4, True]
  7                  -1  1   1991808  ultralytics.nn.modules.conv.Conv             [384, 576, 3, 2]
  8                  -1  2   3985920  ultralytics.nn.modules.block.C2f             [576, 576, 2, True]
  9                  -1  1    831168  ultralytics.nn.modules.block.SPPF            [576, 576, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  2   1993728  ultralytics.nn.modules.block.C2f             [960, 384, 2]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  2    517632  ultralytics.nn.modules.block.C2f             [576, 192, 2]
 16                  -1  1    332160  ultralytics.nn.modules.conv.Conv             [192, 192, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  2   1846272  ultralytics.nn.modules.block.C2f             [576, 384, 2]
 19                  -1  1   1327872  ultralytics.nn.modules.conv.Conv             [384, 384, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  2   4207104  ultralytics.nn.modules.block.C2f             [960, 576, 2]
 22        [15, 18, 21]  1   3779170  ultralytics.nn.modules.head.Detect           [6, [192, 384, 576]]
Model summary: 169 layers, 25,859,794 parameters, 25,859,778 gradients, 79.1 GFLOPs

Transferred 469/475 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 99.5±75.9 MB/s, size: 51.9 KB)
train: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/train/labels... 919 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 919/919 922.2it/s 1.0s0.1s
WARNING ⚠️ train: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 33.6±23.3 MB/s, size: 35.4 KB)
val: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels... 230 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 230/230 522.2it/s 0.4s0.0s
WARNING ⚠️ val: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/val is not writeable, cache not saved.
Plotting labels to /kaggle/working/runs/detect/train6/labels.jpg...
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 77 weight(decay=0.0), 84 weight(decay=0.001), 83 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to /kaggle/working/runs/detect/train6
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/32      14.1G      2.554      3.684       2.06        249        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.5s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.3it/s 3.0s1.2s
                   all        230       1440       0.67      0.688      0.714      0.407

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/32      13.9G      1.388      1.031      1.284        222        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.2s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.5s1.0s
                   all        230       1440       0.91      0.943      0.972      0.576

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/32      13.9G      1.354     0.8712      1.258        203        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.957      0.975      0.979      0.623

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/32      13.9G      1.343     0.7808      1.244        242        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440       0.98       0.98      0.988      0.651

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/32      13.9G        1.3     0.6796      1.231        250        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.974      0.964      0.982      0.648

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/32      13.9G      1.286     0.6039      1.235        251        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.984      0.983      0.986      0.627

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/32      13.9G      1.259     0.5836      1.216        257        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.5s1.0s
                   all        230       1440       0.98      0.982      0.982       0.64

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/32      13.9G      1.262     0.5733      1.217        273        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.976       0.98      0.982      0.605

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/32      13.9G      1.258     0.5537      1.221        265        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.5s1.0s
                   all        230       1440      0.969      0.978      0.984      0.655

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/32      13.9G      1.232     0.5539      1.202        233        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.988      0.982      0.987      0.633

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/32      13.4G      1.223     0.5346      1.214        282        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.989      0.984      0.988      0.655

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/32      13.9G      1.217     0.5251      1.219        205        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.987      0.986      0.988      0.662

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/32      13.9G      1.186     0.5148      1.194        219        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440       0.99      0.986      0.989      0.652

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/32      13.9G      1.191     0.5082      1.204        239        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.985      0.985      0.986       0.66

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/32      13.9G      1.197     0.4964      1.214        254        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.982      0.983      0.987      0.672

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/32      13.9G      1.158     0.4899      1.211        231        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.985      0.989      0.987      0.676

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/32      13.9G       1.16     0.4824      1.211        275        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.981       0.98      0.986      0.671

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/32      13.9G       1.15     0.4686      1.222        261        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.987      0.983      0.985      0.678

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/32      13.9G      1.145     0.4676      1.219        187        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.9s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.987      0.984      0.987      0.669

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/32      13.9G      1.118     0.4547       1.18        223        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.989      0.983      0.988      0.677

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/32      13.9G      1.107     0.4494      1.184        232        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.989      0.989      0.987      0.686

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/32      13.9G      1.095     0.4451      1.168        242        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.988      0.986      0.988      0.684
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/32      13.9G      1.089     0.4029      1.238        147        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 33.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440       0.99      0.989      0.988       0.68

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/32      13.9G      1.068     0.3902       1.23        127        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.9s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.989      0.986      0.987      0.678

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/32      13.9G      1.051     0.3857      1.227        121        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.8s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.987      0.987      0.988       0.67

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/32      13.9G      1.031      0.373      1.204        141        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.8s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.987      0.989      0.987      0.685

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/32      13.9G      1.016      0.371      1.199        138        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.9s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.5s1.0s
                   all        230       1440       0.99      0.989      0.986      0.687

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/32      13.9G      1.004     0.3684      1.199        136        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.9s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440       0.99      0.989      0.988      0.689

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/32      13.9G     0.9873     0.3578      1.192        145        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.8s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.992      0.989      0.988       0.69

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/32      13.9G     0.9779     0.3549      1.177        140        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.9s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.991       0.99      0.987      0.685

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/32      13.9G     0.9527     0.3435      1.178        124        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.8s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.991       0.99      0.987      0.691

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/32      13.9G     0.9411      0.342      1.159        142        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.9s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s

/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        230       1440      0.991      0.991      0.987      0.692
     DC Voltage Source        103        144          1      0.979      0.984       0.76
              Resistor        183        605      0.985      0.992      0.987       0.65
        Current Source        113        150      0.982          1      0.984       0.74
              Inductor        117        177      0.994      0.988       0.99      0.646
             Capacitor        115        184      0.993      0.989      0.985      0.638
     AC Voltage Source         65        180      0.993      0.994      0.995      0.717
Speed: 0.1ms preprocess, 8.3ms inference, 0.0ms loss, 2.1ms postprocess per image
Results saved to /kaggle/working/runs/detect/train6

🚀 Case 7: Learning Rate | Experiment 4: lr0=0.05
Ultralytics 8.3.193 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-component-data/YOLO_component-dataset/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.05, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8m.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train7, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=/kaggle/working/runs/detect/train7, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.001, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=6

                   from  n    params  module                                       arguments
  0                  -1  1      1392  ultralytics.nn.modules.conv.Conv             [3, 48, 3, 2]
  1                  -1  1     41664  ultralytics.nn.modules.conv.Conv             [48, 96, 3, 2]
  2                  -1  2    111360  ultralytics.nn.modules.block.C2f             [96, 96, 2, True]
  3                  -1  1    166272  ultralytics.nn.modules.conv.Conv             [96, 192, 3, 2]
  4                  -1  4    813312  ultralytics.nn.modules.block.C2f             [192, 192, 4, True]
  5                  -1  1    664320  ultralytics.nn.modules.conv.Conv             [192, 384, 3, 2]
  6                  -1  4   3248640  ultralytics.nn.modules.block.C2f             [384, 384, 4, True]
  7                  -1  1   1991808  ultralytics.nn.modules.conv.Conv             [384, 576, 3, 2]
  8                  -1  2   3985920  ultralytics.nn.modules.block.C2f             [576, 576, 2, True]
  9                  -1  1    831168  ultralytics.nn.modules.block.SPPF            [576, 576, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  2   1993728  ultralytics.nn.modules.block.C2f             [960, 384, 2]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  2    517632  ultralytics.nn.modules.block.C2f             [576, 192, 2]
 16                  -1  1    332160  ultralytics.nn.modules.conv.Conv             [192, 192, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  2   1846272  ultralytics.nn.modules.block.C2f             [576, 384, 2]
 19                  -1  1   1327872  ultralytics.nn.modules.conv.Conv             [384, 384, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  2   4207104  ultralytics.nn.modules.block.C2f             [960, 576, 2]
 22        [15, 18, 21]  1   3779170  ultralytics.nn.modules.head.Detect           [6, [192, 384, 576]]
Model summary: 169 layers, 25,859,794 parameters, 25,859,778 gradients, 79.1 GFLOPs

Transferred 469/475 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 88.5±58.2 MB/s, size: 51.9 KB)
train: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/train/labels... 919 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 919/919 816.4it/s 1.1s0.0s
WARNING ⚠️ train: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 39.2±30.4 MB/s, size: 35.4 KB)
val: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels... 230 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 230/230 484.5it/s 0.5s0.1s
WARNING ⚠️ val: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/val is not writeable, cache not saved.
Plotting labels to /kaggle/working/runs/detect/train7/labels.jpg...
optimizer: SGD(lr=0.05, momentum=0.937) with parameter groups 77 weight(decay=0.0), 84 weight(decay=0.001), 83 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to /kaggle/working/runs/detect/train7
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/32      13.5G      2.302      3.394      1.836        249        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.5s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.5it/s 2.6s1.1s
                   all        230       1440       0.53      0.485      0.467      0.252

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/32      13.9G      1.556      1.876      1.272        222        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.2s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.5s1.0s
                   all        230       1440      0.399      0.859      0.493      0.184

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/32      13.9G       1.73      2.091      1.411        203        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.5it/s 2.6s1.1s
                   all        230       1440      0.207      0.508       0.25      0.128

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/32      13.9G      1.771      2.336      1.471        242        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.4it/s 2.9s1.2s
                   all        230       1440      0.106      0.256     0.0975      0.034

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/32      13.9G      1.695      1.618      1.465        250        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.6s1.0s
                   all        230       1440       0.16      0.199      0.158      0.067

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/32      13.9G       1.52      1.083      1.332        251        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.0it/s 3.9s1.5ss
                   all        230       1440      0.746     0.0613     0.0557     0.0236

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/32      13.9G      1.471     0.8517      1.284        257        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.5s1.0s
                   all        230       1440      0.674      0.711      0.724      0.395

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/32      13.9G      1.414     0.7656      1.255        273        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.586      0.651      0.682      0.303

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/32      13.9G      1.368     0.7152      1.245        265        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.9s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.943      0.963      0.967       0.57

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/32      13.9G      1.339     0.6631      1.216        233        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.955      0.967      0.977      0.623

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/32      13.9G       1.32       0.63       1.22        282        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.974      0.976      0.981      0.609

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/32      13.9G      1.317     0.6193       1.22        205        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.944      0.941      0.965      0.634

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/32      13.9G      1.277     0.6088      1.191        219        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.9s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.983      0.981      0.984      0.629

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/32      13.9G      1.276     0.6057      1.192        239        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.981      0.979      0.985      0.628

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/32      13.9G      1.278     0.5911      1.184        254        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.9s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.5s1.0s
                   all        230       1440      0.969      0.972      0.979      0.614

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/32      13.9G      1.253     0.5913      1.187        231        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.978      0.987      0.981      0.652

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/32      13.9G      1.249      0.584      1.181        275        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.972      0.965       0.98      0.631

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/32      13.9G       1.23      0.551      1.181        261        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.975      0.979      0.982      0.646

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/32      13.9G      1.236     0.5508      1.182        187        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.9s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.981      0.984      0.983      0.656

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/32      13.9G      1.211     0.5422      1.162        223        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.985      0.985      0.986      0.671

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/32      13.9G      1.194     0.5302      1.157        232        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.975      0.984      0.984      0.668

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/32      13.9G        1.2     0.5286      1.157        242        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.981      0.985      0.985       0.66
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/32      13.9G      1.181     0.4727      1.219        147        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 33.1s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.5s1.0s
                   all        230       1440      0.983      0.985      0.987      0.668

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/32      13.9G      1.177     0.4695      1.219        127        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.9s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.982      0.988      0.989      0.667

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/32      13.9G      1.171     0.4694      1.215        121        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.8s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440       0.98      0.985      0.986      0.646

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/32      13.9G      1.145     0.4529      1.193        141        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.8s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.984      0.987      0.987      0.669

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/32      13.9G      1.134     0.4393      1.191        138        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.8s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.986      0.985      0.988      0.686

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/32      13.9G      1.139     0.4414      1.196        136        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.9s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.987      0.987      0.989      0.683

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/32      13.9G      1.117     0.4286      1.192        145        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.8s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.988      0.987      0.989      0.683

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/32      13.9G      1.115     0.4286      1.178        140        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.9s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.5s1.0s
                   all        230       1440      0.988      0.988      0.989       0.69

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/32      13.9G      1.096     0.4132      1.183        124        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.9s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.987      0.987      0.989      0.695

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/32      13.9G      1.086     0.4085      1.171        142        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.8s1.0ss

/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        230       1440      0.987      0.987      0.989      0.695
     DC Voltage Source        103        144      0.993      0.969      0.984      0.761
              Resistor        183        605      0.982       0.99      0.986      0.654
        Current Source        113        150      0.979          1      0.989      0.741
              Inductor        117        177      0.992      0.989      0.994      0.659
             Capacitor        115        184      0.983      0.989      0.991      0.628
     AC Voltage Source         65        180      0.994      0.985      0.989      0.725
Speed: 0.1ms preprocess, 8.2ms inference, 0.0ms loss, 1.9ms postprocess per image
Results saved to /kaggle/working/runs/detect/train7

🚀 Case 7: Learning Rate | Experiment 5: lr0=0.1
Ultralytics 8.3.193 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-component-data/YOLO_component-dataset/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.1, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8m.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train8, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=/kaggle/working/runs/detect/train8, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.001, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=6

                   from  n    params  module                                       arguments
  0                  -1  1      1392  ultralytics.nn.modules.conv.Conv             [3, 48, 3, 2]
  1                  -1  1     41664  ultralytics.nn.modules.conv.Conv             [48, 96, 3, 2]
  2                  -1  2    111360  ultralytics.nn.modules.block.C2f             [96, 96, 2, True]
  3                  -1  1    166272  ultralytics.nn.modules.conv.Conv             [96, 192, 3, 2]
  4                  -1  4    813312  ultralytics.nn.modules.block.C2f             [192, 192, 4, True]
  5                  -1  1    664320  ultralytics.nn.modules.conv.Conv             [192, 384, 3, 2]
  6                  -1  4   3248640  ultralytics.nn.modules.block.C2f             [384, 384, 4, True]
  7                  -1  1   1991808  ultralytics.nn.modules.conv.Conv             [384, 576, 3, 2]
  8                  -1  2   3985920  ultralytics.nn.modules.block.C2f             [576, 576, 2, True]
  9                  -1  1    831168  ultralytics.nn.modules.block.SPPF            [576, 576, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  2   1993728  ultralytics.nn.modules.block.C2f             [960, 384, 2]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  2    517632  ultralytics.nn.modules.block.C2f             [576, 192, 2]
 16                  -1  1    332160  ultralytics.nn.modules.conv.Conv             [192, 192, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  2   1846272  ultralytics.nn.modules.block.C2f             [576, 384, 2]
 19                  -1  1   1327872  ultralytics.nn.modules.conv.Conv             [384, 384, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  2   4207104  ultralytics.nn.modules.block.C2f             [960, 576, 2]
 22        [15, 18, 21]  1   3779170  ultralytics.nn.modules.head.Detect           [6, [192, 384, 576]]
Model summary: 169 layers, 25,859,794 parameters, 25,859,778 gradients, 79.1 GFLOPs

Transferred 469/475 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 92.6±69.1 MB/s, size: 51.9 KB)
train: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/train/labels... 919 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 919/919 810.0it/s 1.1s0.3s
WARNING ⚠️ train: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 41.4±25.9 MB/s, size: 35.4 KB)
val: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels... 230 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 230/230 491.2it/s 0.5s0.1s
WARNING ⚠️ val: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/val is not writeable, cache not saved.
Plotting labels to /kaggle/working/runs/detect/train8/labels.jpg...
optimizer: SGD(lr=0.1, momentum=0.937) with parameter groups 77 weight(decay=0.0), 84 weight(decay=0.001), 83 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to /kaggle/working/runs/detect/train8
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/32        14G      2.345      4.019      1.836        249        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.5s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.4it/s 2.9s1.2s
                   all        230       1440      0.452      0.448      0.297       0.17

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/32      13.9G      1.823      3.201      1.523        222        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.2s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.3it/s 3.1s1.2s
                   all        230       1440     0.0164      0.121    0.00949    0.00305

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/32      13.9G      2.051      2.668      1.707        203        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 0.9it/s 4.4s1.8ss
                   all        230       1440      0.167     0.0353   0.000501   0.000125

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/32      13.9G      2.003       2.26      1.658        242        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 0.4it/s 10.7s.1ss
                   all        230       1440          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/32      13.9G      1.762       1.75      1.509        250        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440   2.42e-06   0.000942   1.29e-06   2.58e-07

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/32      13.9G      1.578      1.277      1.379        251        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.5s1.0s
                   all        230       1440     0.0633      0.531     0.0501     0.0246

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/32      13.9G      1.464      1.075      1.292        257        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.5s1.0s
                   all        230       1440      0.198      0.618      0.256      0.131

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/32      13.9G      1.452      1.001      1.281        273        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.5s1.0s
                   all        230       1440      0.353      0.819      0.464      0.254

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/32      13.9G      1.402     0.9123      1.281        265        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.554      0.724      0.639      0.331

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/32        14G       1.35     0.8408       1.24        233        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.5s1.0s
                   all        230       1440      0.754       0.84      0.857      0.511

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/32        14G      1.344     0.7562      1.249        282        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.755      0.871      0.878      0.523

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/32      13.9G      1.345     0.7014      1.249        205        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.935      0.963      0.976      0.635

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/32      13.9G      1.303     0.6657      1.215        219        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440       0.97       0.98      0.985      0.605

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/32      13.9G      1.294     0.6573      1.216        239        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.967       0.97      0.981      0.617

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/32      13.9G      1.301     0.6452      1.212        254        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.982      0.976      0.981      0.639

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/32      13.9G      1.276     0.6216      1.219        231        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.5s1.0s
                   all        230       1440      0.978      0.981      0.984      0.655

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/32      13.9G      1.277     0.6112      1.215        275        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.979      0.979      0.985      0.653

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/32      13.9G      1.256     0.5797      1.215        261        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.981      0.984      0.981       0.66

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/32      13.9G      1.253     0.5808      1.211        187        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440       0.92      0.928      0.969      0.573

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/32      13.9G      1.232     0.5656      1.191        223        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.982      0.978      0.987      0.673

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/32      13.9G      1.217     0.5573      1.187        232        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.978      0.979      0.987      0.664

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/32      13.9G      1.223     0.5484      1.188        242        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.0s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.982      0.978      0.986       0.65
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/32      13.9G      1.202     0.5018      1.254        147        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 33.2s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.985      0.978      0.986      0.671

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/32      13.9G      1.202     0.4981      1.256        127        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.9s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.971      0.964      0.983      0.663

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/32      13.9G       1.19     0.4894      1.255        121        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.8s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.5s1.0s
                   all        230       1440      0.983      0.983      0.983      0.659

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/32      13.9G      1.174     0.4806      1.234        141        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.9s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.986      0.986      0.985      0.653

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/32      13.9G      1.155     0.4681      1.232        138        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.8s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.985      0.981      0.988      0.679

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/32      13.9G      1.167     0.4681      1.238        136        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.9s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.979       0.98      0.985      0.679

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/32      13.9G      1.148     0.4536      1.231        145        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.8s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.983      0.987      0.986      0.689

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/32      13.9G      1.138      0.449      1.217        140        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.9s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.985      0.982      0.988      0.692

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/32      13.9G      1.125     0.4318      1.223        124        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.8s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.985      0.983      0.985      0.689

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/32      13.9G      1.113     0.4289       1.21        142        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.8s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s

/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        230       1440      0.984      0.981      0.989      0.693
     DC Voltage Source        103        144          1      0.952      0.985      0.758
              Resistor        183        605      0.983      0.988      0.989      0.656
        Current Source        113        150      0.946      0.993      0.985      0.734
              Inductor        117        177      0.993      0.989      0.993      0.653
             Capacitor        115        184      0.995      0.987       0.99       0.64
     AC Voltage Source         65        180      0.989      0.978      0.991      0.719
Speed: 0.1ms preprocess, 8.1ms inference, 0.0ms loss, 1.8ms postprocess per image
Results saved to /kaggle/working/runs/detect/train8

,Case,Experiment No,Experiment Name,Epochs,Batch,lr0,Weight Decay,Optimizer,Image Size,Dropout,Freeze Layers,Activation,Training Time (s),Precision,Recall,mAP@0.5,mAP@0.5:0.95
0,Case 3: Batch Size,1,batch_16,32,16,0.010,0.001,SGD,640,0.0,0,SiLU,1267.75,0.9898094080557646,0.9894705611842188,0.9873951921114864,0.6866352229419413
1,Case 3: Batch Size,2,batch_32,32,32,0.010,0.001,SGD,640,0.0,0,SiLU,1153.51,0.991306588627882,0.990504688006188,0.9873156486165096,0.6919208489023024
2,Case 3: Batch Size,3,batch_64,32,64,0.010,0.001,SGD,640,0.0,0,SiLU,Error,Error,Error,Error,Error
3,Case 7: Learning Rate,1,lr0_0.001,32,32,0.001,0.001,SGD,640,0.0,0,SiLU,1157.25,0.9865793731082227,0.9895758357409906,0.9881686723190005,0.6887520150251867
4,Case 7: Learning Rate,2,lr0_0.005,32,32,0.005,0.001,SGD,640,0.0,0,SiLU,1157.34,0.9901062556882234,0.9903801637215488,0.9875037459218959,0.696559365054343
5,Case 7: Learning Rate,3,lr0_0.01,32,32,0.010,0.001,SGD,640,0.0,0,SiLU,1157.42,0.9913065886278819,0.990504688006188,0.9873156486165097,0.6919208489023024
6,Case 7: Learning Rate,4,lr0_0.05,32,32,0.050,0.001,SGD,640,0.0,0,SiLU,1158.61,0.9871818691472248,0.9870353716572411,0.9888865121722459,0.6946677077190417
7,Case 7: Learning Rate,5,lr0_0.1,32,32,0.100,0.001,SGD,640,0.0,0,SiLU,1168.65,0.9843538302233757,0.98129790914341,0.9889075867339837,0.6934032622745152

In [6]:
import yaml
import shutil

def create_model_yaml(base_yaml, new_yaml, activation):
    """
    Create a new model YAML file with a custom activation function.
    """
    with open(base_yaml, "r") as f:
        cfg = yaml.safe_load(f)

    # Replace activation everywhere it appears
    if "backbone" in cfg:
        for layer in cfg["backbone"]:
            if isinstance(layer, list) and len(layer) > 0 and isinstance(layer[-1], dict):
                if "activation" in layer[-1]:
                    layer[-1]["activation"] = activation
    if "head" in cfg:
        for layer in cfg["head"]:
            if isinstance(layer, list) and len(layer) > 0 and isinstance(layer[-1], dict):
                if "activation" in layer[-1]:
                    layer[-1]["activation"] = activation

    # Save new yaml
    with open(new_yaml, "w") as f:
        yaml.safe_dump(cfg, f)

In [7]:
# ===============================
# Case 8: Activation Functions
# ===============================
activations = ["ReLU", "Mish", "LeakyReLU", "SiLU"]

for i, act in enumerate(activations, start=1):
    model_yaml = f"yolov8m_{act}.yaml"
    create_model_yaml("/kaggle/working/yolov8m.yaml", model_yaml, act)

    print(f"\n🚀 Case 8 | Experiment {i}: Activation={act}")
    gc.collect(); torch.cuda.empty_cache()
    model = YOLO(model_yaml)  # use custom YAML with new activation

    start_time = time.time()
    try:
        results = model.train(
            data=data_yaml,
            epochs=base_params["epochs"],
            batch=base_params["batch"],
            lr0=base_params["lr0"],
            optimizer=base_params["optimizer"],
            imgsz=base_params["imgsz"],
            weight_decay=base_params["weight_decay"],
            dropout=base_params["dropout"],
            freeze=base_params["freeze"]
        )
        end_time = time.time()
        log_result("Case 8: Activation", i, f"activation_{act}", 
                   {**base_params, "activation": act}, results, end_time - start_time)

    except Exception as e:
        print(f"❌ Error in Activation={act}: {e}")
        log_result("Case 8: Activation", i, f"activation_{act}", 
                   {**base_params, "activation": act}, None, 0, error=True)

# show results
df = pd.read_csv(results_file)
display(df)

FileNotFoundError: [Errno 2] No such file or directory: '/kaggle/working/yolov8m.yaml'

In [10]:
# ===============================
# Case 9: Activation Functions
# ===============================

import yaml, copy, os, time, gc
import pandas as pd
from ultralytics import YOLO
from ultralytics.nn.tasks import yaml_model_load
from tabulate import tabulate

# -------------------------------
# Results file
# -------------------------------
results_file = "case9_results.csv"
if not os.path.exists(results_file):
    pd.DataFrame(columns=[
        "Experiment", "Epochs", "Batch Size", "Optimizer", "Image Size", "Learning Rate",
        "Activation", "Freeze Layers", "Training Time (s)",
        "Precision", "Recall", "mAP@0.5", "mAP@0.5:0.95"
    ]).to_csv(results_file, index=False)

# -------------------------------
# Dataset
# -------------------------------
data_yaml = "/kaggle/input/yolo-component-data/YOLO_component-dataset/data.yaml"

# -------------------------------
# Baseline Params
# -------------------------------
base_params = {
    "epochs": 32,
    "batch": 32,
    "optimizer": "AdamW",      # best from earlier cases
    "lr0": 0.001,              # best from Case 7
    "weight_decay": 0.001,     # best from Case 2
    "dropout": 0.0,
    "imgsz": 640,
    "freeze": 0
}

# -------------------------------
# Load Base Config
# -------------------------------
cfg = yaml_model_load("yolov8m.yaml")  # you can switch to yolov8n.yaml or yolov8m.yaml

def create_yaml_with_activation(cfg, act_expr, base_name="yolov8s"):
    """
    Create a new YAML file with the given activation function.
    """
    cfg_mod = copy.deepcopy(cfg)
    cfg_mod['activation'] = act_expr

    safe_name = act_expr.replace("nn.","").replace("(","_").replace(")","").replace(".","")
    out_path = f"/kaggle/working/{base_name}_{safe_name.lower()}.yaml"

    with open(out_path, "w") as f:
        yaml.dump(cfg_mod, f)

    print(f"✅ Created {out_path}")
    return out_path

# -------------------------------
# Define Activations
# -------------------------------
activations = {
    "ReLU": create_yaml_with_activation(cfg, "nn.ReLU()"),
    "LeakyReLU": create_yaml_with_activation(cfg, "nn.LeakyReLU(0.1)"),
    "Mish": create_yaml_with_activation(cfg, "nn.Mish()"),
    "SiLU": create_yaml_with_activation(cfg, "nn.SiLU()")  # baseline
}

# -------------------------------
# Run Case 9
# -------------------------------
all_results = []

for act, yaml_path in activations.items():
    print(f"\n🚀 Training with {act} activation...")
    gc.collect(); 
    try:
        model = YOLO(yaml_path)

        start = time.time()
        results = model.train(
            data=data_yaml,
            epochs=base_params["epochs"],
            batch=base_params["batch"],
            lr0=base_params["lr0"],
            optimizer=base_params["optimizer"],
            imgsz=base_params["imgsz"],
            weight_decay=base_params["weight_decay"],
            dropout=base_params["dropout"],
            freeze=base_params["freeze"]
        )
        end = time.time()

        # Validate model after training
        val = model.val()
        metrics = val.results_dict

        result = {
            "Experiment": f"case9_act_{act}",
            "Epochs": base_params["epochs"],
            "Batch Size": base_params["batch"],
            "Optimizer": base_params["optimizer"],
            "Image Size": base_params["imgsz"],
            "Learning Rate": base_params["lr0"],
            "Activation": act,
            "Freeze Layers": base_params["freeze"],
            "Training Time (s)": round(end - start, 2),
            "Precision": metrics.get("metrics/precision(B)", metrics.get("metrics/precision", "N/A")),
            "Recall": metrics.get("metrics/recall(B)", metrics.get("metrics/recall", "N/A")),
            "mAP@0.5": metrics.get("metrics/mAP50(B)", metrics.get("metrics/mAP_0.5", "N/A")),
            "mAP@0.5:0.95": metrics.get("metrics/mAP50-95(B)", metrics.get("metrics/mAP_0.5:0.95", "N/A"))
        }

    except Exception as e:
        print(f"❌ Error training with {act}: {e}")
        result = {
            "Experiment": f"case9_act_{act}",
            "Epochs": base_params["epochs"],
            "Batch Size": base_params["batch"],
            "Optimizer": base_params["optimizer"],
            "Image Size": base_params["imgsz"],
            "Learning Rate": base_params["lr0"],
            "Activation": act,
            "Freeze Layers": base_params["freeze"],
            "Training Time (s)": "Error",
            "Precision": "Error",
            "Recall": "Error",
            "mAP@0.5": "Error",
            "mAP@0.5:0.95": "Error"
        }

    # Append to CSV
    df = pd.read_csv(results_file)
    df = pd.concat([df, pd.DataFrame([result])], ignore_index=True)
    df.to_csv(results_file, index=False)

    all_results.append(result)

# -------------------------------
# Show Final Results
# -------------------------------
print("\n📊 Case 9 Results Table:\n")
print(tabulate(pd.DataFrame(all_results), headers="keys", tablefmt="grid"))

✅ Created /kaggle/working/yolov8s_relu_.yaml
✅ Created /kaggle/working/yolov8s_leakyrelu_01.yaml
✅ Created /kaggle/working/yolov8s_mish_.yaml
✅ Created /kaggle/working/yolov8s_silu_.yaml

🚀 Training with ReLU activation...
Ultralytics 8.3.193 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-component-data/YOLO_component-dataset/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.001, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=/kaggle/working/yolov8s_relu_.yaml, momentum=0.937, mosaic=1.0, multi_scale=False, name=train11, nbs=64, nms=False, opset=None, optimize=False, optimizer=AdamW, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=/kaggle/working/runs/detect/train11, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.001, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=6
activation: nn.ReLU()

                   from  n    params  module                                       arguments
  0                  -1  1       928  ultralytics.nn.modules.conv.Conv             [3, 32, 3, 2]
  1                  -1  1     18560  ultralytics.nn.modules.conv.Conv             [32, 64, 3, 2]
  2                  -1  1     29056  ultralytics.nn.modules.block.C2f             [64, 64, 1, True]
  3                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  4                  -1  2    197632  ultralytics.nn.modules.block.C2f             [128, 128, 2, True]
  5                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  6                  -1  2    788480  ultralytics.nn.modules.block.C2f             [256, 256, 2, True]
  7                  -1  1   1180672  ultralytics.nn.modules.conv.Conv             [256, 512, 3, 2]
  8                  -1  1   1838080  ultralytics.nn.modules.block.C2f             [512, 512, 1, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  1    591360  ultralytics.nn.modules.block.C2f             [768, 256, 1]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  1    148224  ultralytics.nn.modules.block.C2f             [384, 128, 1]
 16                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  1    493056  ultralytics.nn.modules.block.C2f             [384, 256, 1]
 19                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  1   1969152  ultralytics.nn.modules.block.C2f             [768, 512, 1]
 22        [15, 18, 21]  1   2118370  ultralytics.nn.modules.head.Detect           [6, [128, 256, 512]]
YOLOv8s_relu_ summary: 129 layers, 11,137,922 parameters, 11,137,906 gradients, 28.7 GFLOPs

Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 63.8±51.2 MB/s, size: 51.9 KB)
train: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/train/labels... 919 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 919/919 1.1Kit/s 0.9s0.1ss
WARNING ⚠️ train: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 39.0±27.7 MB/s, size: 35.4 KB)
val: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels... 230 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 230/230 533.2it/s 0.4s0.0s
WARNING ⚠️ val: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/val is not writeable, cache not saved.
Plotting labels to /kaggle/working/runs/detect/train11/labels.jpg...
optimizer: AdamW(lr=0.001, momentum=0.937) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.001), 63 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to /kaggle/working/runs/detect/train11
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/32      6.52G      3.926      3.653      3.571        249        640: 100% ━━━━━━━━━━━━ 29/29 1.8it/s 15.8s0.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 3.6it/s 1.1s0.4s
                   all        230       1440          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/32      6.55G       2.42      2.098      2.298        222        640: 100% ━━━━━━━━━━━━ 29/29 1.9it/s 15.5s0.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 3.7it/s 1.1s0.4s
                   all        230       1440          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/32      6.59G      1.985      1.682      1.909        203        640: 100% ━━━━━━━━━━━━ 29/29 1.9it/s 15.2s0.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 3.6it/s 1.1s0.4s
                   all        230       1440          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/32      6.63G      1.709      1.389      1.657        242        640: 100% ━━━━━━━━━━━━ 29/29 1.9it/s 15.2s0.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 2.9it/s 1.4s0.6s
                   all        230       1440      0.304      0.242      0.225      0.107

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/32      6.66G      1.587      1.219      1.543        250        640: 100% ━━━━━━━━━━━━ 29/29 1.9it/s 15.1s0.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 2.8it/s 1.5s0.6s
                   all        230       1440      0.412      0.632      0.491      0.243

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/32       6.7G      1.514      1.151      1.461        251        640: 100% ━━━━━━━━━━━━ 29/29 1.9it/s 15.2s0.5s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 2.8it/s 1.4s0.6s
                   all        230       1440      0.655      0.775      0.812      0.482

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/32      6.74G      1.504      1.073      1.441        287        640: 72% ━━━━━━━━╸─── 21/29 12.8it/s 11.1s<0.6s

KeyboardInterrupt:

In [11]:
# ===============================
# Case 9: Activation Functions (YOLOv8m)
# ===============================

import yaml, copy, os, time, gc
import pandas as pd
from ultralytics import YOLO
from ultralytics.nn.tasks import yaml_model_load
from tabulate import tabulate

# -------------------------------
# Results file
# -------------------------------
results_file = "case9_results.csv"
if not os.path.exists(results_file):
    pd.DataFrame(columns=[
        "Experiment", "Epochs", "Batch Size", "Optimizer", "Image Size", "Learning Rate",
        "Activation", "Freeze Layers", "Training Time (s)",
        "Precision", "Recall", "mAP@0.5", "mAP@0.5:0.95"
    ]).to_csv(results_file, index=False)

# -------------------------------
# Dataset
# -------------------------------
data_yaml = "/kaggle/input/yolo-component-data/YOLO_component-dataset/data.yaml"

# -------------------------------
# Baseline Params
# -------------------------------
base_params = {
    "epochs": 32,
    "batch": 32,               # smaller batch to avoid OOM on YOLOv8m
    "optimizer": "SGD",
    "lr0": 0.005,
    "weight_decay": 0.001,
    "dropout": 0.0,
    "imgsz": 640,
    "freeze": 0
}

# -------------------------------
# Load Base Config for YOLOv8m
# -------------------------------
cfg = yaml_model_load("yolov8m.yaml")

def create_yaml_with_activation(cfg, act_expr, base_name="yolov8m"):
    """
    Create a new YAML file with the given activation function.
    """
    cfg_mod = copy.deepcopy(cfg)
    cfg_mod['activation'] = act_expr

    safe_name = act_expr.replace("nn.","").replace("(","_").replace(")","").replace(".","")
    out_path = f"/kaggle/working/{base_name}_{safe_name.lower()}.yaml"

    with open(out_path, "w") as f:
        yaml.dump(cfg_mod, f)

    print(f"✅ Created {out_path}")
    return out_path

# -------------------------------
# Define Activations
# -------------------------------
activations = {
    "ReLU": create_yaml_with_activation(cfg, "nn.ReLU()", base_name="yolov8m"),
    "LeakyReLU": create_yaml_with_activation(cfg, "nn.LeakyReLU(0.1)", base_name="yolov8m"),
    "Mish": create_yaml_with_activation(cfg, "nn.Mish()", base_name="yolov8m"),
    "SiLU": create_yaml_with_activation(cfg, "nn.SiLU()", base_name="yolov8m")  # baseline
}

# -------------------------------
# Run Case 9
# -------------------------------
all_results = []

for act, yaml_path in activations.items():
    print(f"\n🚀 Training with {act} activation...")
    gc.collect()
    try:
        model = YOLO(yaml_path)

        start = time.time()
        results = model.train(
            data=data_yaml,
            epochs=base_params["epochs"],
            batch=base_params["batch"],
            lr0=base_params["lr0"],
            optimizer=base_params["optimizer"],
            imgsz=base_params["imgsz"],
            weight_decay=base_params["weight_decay"],
            dropout=base_params["dropout"],
            freeze=base_params["freeze"]
        )
        end = time.time()

        # Validate model after training
        val = model.val()
        metrics = val.results_dict

        result = {
            "Experiment": f"case9_act_{act}",
            "Epochs": base_params["epochs"],
            "Batch Size": base_params["batch"],
            "Optimizer": base_params["optimizer"],
            "Image Size": base_params["imgsz"],
            "Learning Rate": base_params["lr0"],
            "Activation": act,
            "Freeze Layers": base_params["freeze"],
            "Training Time (s)": round(end - start, 2),
            "Precision": metrics.get("metrics/precision(B)", metrics.get("metrics/precision", "N/A")),
            "Recall": metrics.get("metrics/recall(B)", metrics.get("metrics/recall", "N/A")),
            "mAP@0.5": metrics.get("metrics/mAP50(B)", metrics.get("metrics/mAP_0.5", "N/A")),
            "mAP@0.5:0.95": metrics.get("metrics/mAP50-95(B)", metrics.get("metrics/mAP_0.5:0.95", "N/A"))
        }

    except Exception as e:
        print(f"❌ Error training with {act}: {e}")
        result = {
            "Experiment": f"case9_act_{act}",
            "Epochs": base_params["epochs"],
            "Batch Size": base_params["batch"],
            "Optimizer": base_params["optimizer"],
            "Image Size": base_params["imgsz"],
            "Learning Rate": base_params["lr0"],
            "Activation": act,
            "Freeze Layers": base_params["freeze"],
            "Training Time (s)": "Error",
            "Precision": "Error",
            "Recall": "Error",
            "mAP@0.5": "Error",
            "mAP@0.5:0.95": "Error"
        }

    # Append to CSV
    df = pd.read_csv(results_file)
    df = pd.concat([df, pd.DataFrame([result])], ignore_index=True)
    df.to_csv(results_file, index=False)

    all_results.append(result)

# -------------------------------
# Show Final Results
# -------------------------------
print("\n📊 Case 9 Results Table:\n")
print(tabulate(pd.DataFrame(all_results), headers="keys", tablefmt="grid"))

✅ Created /kaggle/working/yolov8m_relu_.yaml
✅ Created /kaggle/working/yolov8m_leakyrelu_01.yaml
✅ Created /kaggle/working/yolov8m_mish_.yaml
✅ Created /kaggle/working/yolov8m_silu_.yaml

🚀 Training with ReLU activation...
Ultralytics 8.3.193 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-component-data/YOLO_component-dataset/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.005, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=/kaggle/working/yolov8m_relu_.yaml, momentum=0.937, mosaic=1.0, multi_scale=False, name=train12, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=/kaggle/working/runs/detect/train12, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.001, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=6
activation: nn.ReLU()

                   from  n    params  module                                       arguments
  0                  -1  1      1392  ultralytics.nn.modules.conv.Conv             [3, 48, 3, 2]
  1                  -1  1     41664  ultralytics.nn.modules.conv.Conv             [48, 96, 3, 2]
  2                  -1  2    111360  ultralytics.nn.modules.block.C2f             [96, 96, 2, True]
  3                  -1  1    166272  ultralytics.nn.modules.conv.Conv             [96, 192, 3, 2]
  4                  -1  4    813312  ultralytics.nn.modules.block.C2f             [192, 192, 4, True]
  5                  -1  1    664320  ultralytics.nn.modules.conv.Conv             [192, 384, 3, 2]
  6                  -1  4   3248640  ultralytics.nn.modules.block.C2f             [384, 384, 4, True]
  7                  -1  1   1991808  ultralytics.nn.modules.conv.Conv             [384, 576, 3, 2]
  8                  -1  2   3985920  ultralytics.nn.modules.block.C2f             [576, 576, 2, True]
  9                  -1  1    831168  ultralytics.nn.modules.block.SPPF            [576, 576, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  2   1993728  ultralytics.nn.modules.block.C2f             [960, 384, 2]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  2    517632  ultralytics.nn.modules.block.C2f             [576, 192, 2]
 16                  -1  1    332160  ultralytics.nn.modules.conv.Conv             [192, 192, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  2   1846272  ultralytics.nn.modules.block.C2f             [576, 384, 2]
 19                  -1  1   1327872  ultralytics.nn.modules.conv.Conv             [384, 384, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  2   4207104  ultralytics.nn.modules.block.C2f             [960, 576, 2]
 22        [15, 18, 21]  1   3779170  ultralytics.nn.modules.head.Detect           [6, [192, 384, 576]]
YOLOv8m_relu_ summary: 169 layers, 25,859,794 parameters, 25,859,778 gradients, 79.1 GFLOPs

Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 89.7±59.7 MB/s, size: 51.9 KB)
train: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/train/labels... 919 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 919/919 947.4it/s 1.0s0.0s
WARNING ⚠️ train: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 57.5±15.7 MB/s, size: 35.4 KB)
val: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels... 230 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 230/230 568.4it/s 0.4s0.2s
WARNING ⚠️ val: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/val is not writeable, cache not saved.
Plotting labels to /kaggle/working/runs/detect/train12/labels.jpg...
optimizer: SGD(lr=0.005, momentum=0.937) with parameter groups 77 weight(decay=0.0), 84 weight(decay=0.001), 83 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to /kaggle/working/runs/detect/train12
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/32      14.9G      5.104      4.963       4.29        249        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.1s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.5s1.0s
                   all        230       1440          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/32      14.9G      3.988      4.002      3.749        222        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.8s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/32        15G      3.028      3.017      3.106        203        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.5s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/32      13.8G      2.329      2.444      2.497        242        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.7s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.5s1.0s
                   all        230       1440    0.00733      0.201     0.0865     0.0255

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/32        15G      1.991      1.933      2.084        250        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.6s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.5s1.0s
                   all        230       1440     0.0185      0.926      0.367      0.135

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/32      14.2G      1.724      1.612      1.809        251        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.7s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.5s1.0s
                   all        230       1440      0.952      0.136      0.587      0.299

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/32        15G      1.611      1.335       1.66        257        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.5s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.5s1.0s
                   all        230       1440      0.828      0.731      0.873      0.506

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/32      14.2G      1.522       1.21      1.567        273        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.6s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.5s1.0s
                   all        230       1440      0.816      0.799      0.893      0.472

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/32      14.6G      1.478      1.131      1.525        265        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.6s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.5s1.0s
                   all        230       1440      0.844      0.835      0.892      0.463

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/32      15.3G      1.435      1.045      1.456        233        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.7s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440       0.78      0.802      0.927      0.505

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/32      14.9G      1.403     0.9681       1.44        282        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.6s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.903      0.919      0.967      0.586

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/32      14.2G      1.393     0.9303      1.432        205        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.7s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.933       0.92      0.966      0.589

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/32        15G      1.359     0.8889      1.393        219        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.6s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.954      0.957      0.977      0.618

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/32      14.8G      1.353     0.8617      1.382        239        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.7s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.1it/s 3.7s1.5s
                   all        230       1440      0.537      0.532      0.511      0.173

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/32        15G      1.341     0.8229      1.359        254        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.5s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.6s1.0s
                   all        230       1440      0.933      0.172      0.413       0.17

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/32      13.7G      1.329      0.808      1.372        231        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.7s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.5it/s 2.7s1.1s
                   all        230       1440      0.722       0.36      0.478      0.151

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/32        15G      1.317     0.7786      1.358        275        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.6s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.932      0.942      0.975      0.627

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/32      14.3G      1.302     0.7607      1.352        261        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.7s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.957      0.965      0.978       0.61

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/32        15G      1.305     0.7504      1.354        187        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.6s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.5it/s 2.6s1.0s
                   all        230       1440      0.912      0.872      0.939      0.562

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/32      14.3G      1.284     0.7281      1.322        223        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.7s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.967      0.961      0.983      0.649

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/32      14.9G       1.27     0.7169      1.323        232        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.6s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.5s1.0s
                   all        230       1440       0.87      0.912       0.95      0.565

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/32      14.9G      1.268     0.7087       1.31        242        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.6s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.954      0.973      0.975      0.601
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/32        15G      1.256        0.7      1.413        147        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.6s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440     0.0575      0.144     0.0426    0.00828

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/32      14.7G      1.239     0.6771      1.404        127        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.6s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.949      0.966      0.983      0.644

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/32      14.9G      1.233     0.6577      1.398        121        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.4s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.5s1.0s
                   all        230       1440        0.9      0.877      0.941      0.489

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/32      14.9G      1.218     0.6335      1.376        141        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.4s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.961      0.975      0.983      0.639

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/32        15G      1.199     0.6237      1.374        138        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.5s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440       0.94      0.968      0.978      0.629

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/32      15.3G      1.212     0.6326      1.384        136        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.6s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.976      0.978      0.984      0.654

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/32        15G      1.188     0.6109      1.375        145        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.4s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.977      0.977      0.983      0.658

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/32      13.8G      1.193      0.612      1.368        140        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.5s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.971      0.981      0.985      0.663

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/32      14.9G      1.186     0.6011      1.382        124        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.4s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.5s1.0s
                   all        230       1440      0.974      0.982      0.985      0.659

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/32      15.3G      1.185     0.6008      1.368        142        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.6s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.5s1.0s
                   all        230       1440      0.982      0.979      0.986      0.662

32 epochs completed in 0.315 hours.
Optimizer stripped from /kaggle/working/runs/detect/train12/weights/last.pt, 52.0MB
Optimizer stripped from /kaggle/working/runs/detect/train12/weights/best.pt, 52.0MB

Validating /kaggle/working/runs/detect/train12/weights/best.pt...
Ultralytics 8.3.193 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
YOLOv8m_relu_ summary (fused): 92 layers, 25,843,234 parameters, 0 gradients, 78.7 GFLOPs

/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        230       1440      0.971       0.98      0.985      0.663
     DC Voltage Source        103        144      0.942      0.972      0.978      0.741
              Resistor        183        605      0.979      0.985      0.988      0.617
        Current Source        113        150      0.949      0.984       0.98      0.724
              Inductor        117        177      0.977      0.974      0.989      0.617
             Capacitor        115        184      0.993      0.984      0.983       0.57
     AC Voltage Source         65        180      0.989      0.983      0.991      0.705
Speed: 0.1ms preprocess, 8.2ms inference, 0.0ms loss, 2.2ms postprocess per image
Results saved to /kaggle/working/runs/detect/train12
Ultralytics 8.3.193 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
YOLOv8m_relu_ summary (fused): 92 layers, 25,843,234 parameters, 0 gradients, 78.7 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 76.1±51.6 MB/s, size: 58.5 KB)
val: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels... 230 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 230/230 628.2it/s 0.4s0.1s
WARNING ⚠️ val: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/val is not writeable, cache not saved.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 1.9it/s 4.3s0.4ss

/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        230       1440      0.971      0.981      0.985      0.663
     DC Voltage Source        103        144       0.94      0.972      0.978      0.741
              Resistor        183        605      0.979      0.987      0.988      0.618
        Current Source        113        150      0.949      0.986       0.98      0.726
              Inductor        117        177      0.977      0.974      0.989      0.618
             Capacitor        115        184      0.992      0.984      0.983       0.57
     AC Voltage Source         65        180      0.989      0.983      0.991      0.703
Speed: 2.0ms preprocess, 8.1ms inference, 0.0ms loss, 2.5ms postprocess per image
Results saved to /kaggle/working/runs/detect/train122

🚀 Training with LeakyReLU activation...
Ultralytics 8.3.193 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-component-data/YOLO_component-dataset/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.005, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=/kaggle/working/yolov8m_leakyrelu_01.yaml, momentum=0.937, mosaic=1.0, multi_scale=False, name=train13, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=/kaggle/working/runs/detect/train13, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.001, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=6
activation: nn.LeakyReLU(0.1)

                   from  n    params  module                                       arguments
  0                  -1  1      1392  ultralytics.nn.modules.conv.Conv             [3, 48, 3, 2]
  1                  -1  1     41664  ultralytics.nn.modules.conv.Conv             [48, 96, 3, 2]
  2                  -1  2    111360  ultralytics.nn.modules.block.C2f             [96, 96, 2, True]
  3                  -1  1    166272  ultralytics.nn.modules.conv.Conv             [96, 192, 3, 2]
  4                  -1  4    813312  ultralytics.nn.modules.block.C2f             [192, 192, 4, True]
  5                  -1  1    664320  ultralytics.nn.modules.conv.Conv             [192, 384, 3, 2]
  6                  -1  4   3248640  ultralytics.nn.modules.block.C2f             [384, 384, 4, True]
  7                  -1  1   1991808  ultralytics.nn.modules.conv.Conv             [384, 576, 3, 2]
  8                  -1  2   3985920  ultralytics.nn.modules.block.C2f             [576, 576, 2, True]
  9                  -1  1    831168  ultralytics.nn.modules.block.SPPF            [576, 576, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  2   1993728  ultralytics.nn.modules.block.C2f             [960, 384, 2]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  2    517632  ultralytics.nn.modules.block.C2f             [576, 192, 2]
 16                  -1  1    332160  ultralytics.nn.modules.conv.Conv             [192, 192, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  2   1846272  ultralytics.nn.modules.block.C2f             [576, 384, 2]
 19                  -1  1   1327872  ultralytics.nn.modules.conv.Conv             [384, 384, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  2   4207104  ultralytics.nn.modules.block.C2f             [960, 576, 2]
 22        [15, 18, 21]  1   3779170  ultralytics.nn.modules.head.Detect           [6, [192, 384, 576]]
YOLOv8m_leakyrelu_01 summary: 169 layers, 25,859,794 parameters, 25,859,778 gradients, 79.1 GFLOPs

Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.1±0.2 ms, read: 78.4±44.0 MB/s, size: 51.9 KB)
train: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/train/labels... 919 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 919/919 630.1it/s 1.5s0.0s
WARNING ⚠️ train: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 35.9±29.2 MB/s, size: 35.4 KB)
val: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels... 230 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 230/230 572.4it/s 0.4s0.1s
WARNING ⚠️ val: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/val is not writeable, cache not saved.
Plotting labels to /kaggle/working/runs/detect/train13/labels.jpg...
optimizer: SGD(lr=0.005, momentum=0.937) with parameter groups 77 weight(decay=0.0), 84 weight(decay=0.001), 83 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to /kaggle/working/runs/detect/train13
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/32      14.5G      4.864      4.788       4.16        249        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.6s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.5s1.0s
                   all        230       1440          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/32      14.9G      3.184      3.223      3.241        222        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.8s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.5s1.0s
                   all        230       1440          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/32        15G       2.43      2.505      2.618        203        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.6s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.5s1.0s
                   all        230       1440          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/32        15G      2.027      1.928      2.125        242        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.6s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440   6.16e-05     0.0011   3.11e-05   8.56e-06

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/32        15G      1.773      1.588      1.847        250        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.6s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.5s1.0s
                   all        230       1440      0.675      0.128      0.464      0.194

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/32      14.7G      1.601      1.402      1.679        251        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.7s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.5s1.0s
                   all        230       1440      0.649      0.509      0.641      0.335

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/32        15G      1.525       1.23      1.571        257        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.5s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.5s1.0s
                   all        230       1440       0.83      0.862      0.906      0.535

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/32      14.9G      1.467      1.133      1.507        273        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.6s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.5s1.0s
                   all        230       1440      0.855      0.815       0.92      0.442

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/32        15G      1.452      1.064      1.485        265        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.6s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.5s1.0s
                   all        230       1440       0.87      0.759       0.87       0.44

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/32      14.9G      1.406     0.9928      1.424        233        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.6s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.6s1.0s
                   all        230       1440      0.841      0.793      0.939      0.585

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/32        15G      1.378     0.9271      1.411        282        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.6s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.5it/s 2.6s1.1s
                   all        230       1440      0.774      0.745      0.841      0.476

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/32      14.9G       1.36      0.905      1.402        205        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.6s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.5s1.0s
                   all        230       1440      0.904      0.937      0.965      0.624

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/32        15G      1.335     0.8646      1.371        219        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.6s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.5s1.0s
                   all        230       1440      0.843      0.872      0.933      0.455

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/32        15G      1.337     0.8468      1.364        239        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.6s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.5it/s 2.7s1.1s
                   all        230       1440      0.847       0.88      0.926      0.422

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/32        15G      1.331     0.8066      1.343        254        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.6s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.2it/s 3.3s1.4s
                   all        230       1440      0.884      0.853       0.92      0.458

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/32        14G      1.313      0.793      1.354        231        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.7s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.968       0.97      0.985      0.611

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/32        15G      1.301     0.7753      1.342        275        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.6s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.959      0.944      0.981      0.625

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/32      13.7G      1.286     0.7569      1.337        261        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.7s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.922      0.943      0.967      0.575

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/32        15G      1.295     0.7451      1.343        187        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.6s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.962      0.969      0.983       0.64

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/32        15G      1.273      0.728      1.312        223        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.6s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440       0.97      0.972      0.985      0.655

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/32        15G      1.257     0.7176      1.313        232        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.6s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.2it/s 3.4s1.4ss
                   all        230       1440      0.923      0.821      0.969      0.606

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/32      14.9G      1.259     0.7041      1.302        242        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.6s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.939       0.94      0.965      0.584
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/32        15G      1.244     0.6996        1.4        147        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 32.8s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.966      0.964      0.975      0.584

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/32      14.9G      1.224     0.6704      1.387        127        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.5s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.2it/s 3.2s1.3s
                   all        230       1440      0.531      0.619      0.618      0.205

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/32        15G      1.213     0.6542      1.381        121        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.5s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.5s1.0s
                   all        230       1440      0.951      0.962      0.982      0.651

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/32        15G      1.199     0.6275      1.362        141        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.5s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.981      0.978      0.985      0.658

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/32        15G      1.186     0.6283      1.362        138        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.4s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440       0.97       0.98      0.983      0.654

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/32      14.9G      1.199     0.6308      1.371        136        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.5s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.7it/s 2.4s1.0s
                   all        230       1440      0.978      0.974      0.983       0.64

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/32        15G      1.182     0.6122      1.367        145        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.4s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.956      0.966      0.983      0.661

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/32      14.9G      1.178     0.6136      1.355        140        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.5s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.962      0.971      0.982      0.649

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/32        15G      1.177     0.6033      1.372        124        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.4s1.0ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 4/4 1.6it/s 2.4s1.0s
                   all        230       1440      0.974      0.971      0.982      0.657

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/32      14.9G      1.173     0.6017      1.357        142        640: 100% ━━━━━━━━━━━━ 29/29 0.9it/s 31.5s1.0ss

/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        230       1440       0.98      0.976      0.985      0.666
     DC Voltage Source        103        144          1       0.96      0.978      0.753
              Resistor        183        605      0.982      0.975      0.986      0.629
        Current Source        113        150       0.93      0.993      0.978      0.711
              Inductor        117        177      0.977       0.98      0.992      0.607
             Capacitor        115        184      0.994      0.989      0.985      0.591
     AC Voltage Source         65        180      0.994       0.96       0.99      0.708
Speed: 0.1ms preprocess, 8.2ms inference, 0.0ms loss, 2.7ms postprocess per image
Results saved to /kaggle/working/runs/detect/train13
Ultralytics 8.3.193 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
YOLOv8m_leakyrelu_01 summary (fused): 92 layers, 25,843,234 parameters, 0 gradients, 78.7 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 64.5±42.6 MB/s, size: 58.5 KB)
val: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels... 230 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 230/230 690.1it/s 0.3s0.0s
WARNING ⚠️ val: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/val is not writeable, cache not saved.
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 8/8 1.8it/s 4.5s0.4ss

/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        230       1440      0.979      0.976      0.985      0.666
     DC Voltage Source        103        144      0.998      0.958      0.978       0.75
              Resistor        183        605      0.982      0.975      0.986      0.631
        Current Source        113        150       0.93      0.993      0.978       0.71
              Inductor        117        177      0.977       0.98      0.992      0.609
             Capacitor        115        184      0.994      0.989      0.985      0.591
     AC Voltage Source         65        180      0.994      0.959       0.99      0.707
Speed: 1.7ms preprocess, 7.9ms inference, 0.0ms loss, 3.3ms postprocess per image
Results saved to /kaggle/working/runs/detect/train132

🚀 Training with Mish activation...
Ultralytics 8.3.193 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-component-data/YOLO_component-dataset/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.005, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=/kaggle/working/yolov8m_mish_.yaml, momentum=0.937, mosaic=1.0, multi_scale=False, name=train14, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=/kaggle/working/runs/detect/train14, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.001, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=6
activation: nn.Mish()

                   from  n    params  module                                       arguments
  0                  -1  1      1392  ultralytics.nn.modules.conv.Conv             [3, 48, 3, 2]
  1                  -1  1     41664  ultralytics.nn.modules.conv.Conv             [48, 96, 3, 2]
  2                  -1  2    111360  ultralytics.nn.modules.block.C2f             [96, 96, 2, True]
  3                  -1  1    166272  ultralytics.nn.modules.conv.Conv             [96, 192, 3, 2]
  4                  -1  4    813312  ultralytics.nn.modules.block.C2f             [192, 192, 4, True]
  5                  -1  1    664320  ultralytics.nn.modules.conv.Conv             [192, 384, 3, 2]
  6                  -1  4   3248640  ultralytics.nn.modules.block.C2f             [384, 384, 4, True]
  7                  -1  1   1991808  ultralytics.nn.modules.conv.Conv             [384, 576, 3, 2]
  8                  -1  2   3985920  ultralytics.nn.modules.block.C2f             [576, 576, 2, True]
  9                  -1  1    831168  ultralytics.nn.modules.block.SPPF            [576, 576, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  2   1993728  ultralytics.nn.modules.block.C2f             [960, 384, 2]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  2    517632  ultralytics.nn.modules.block.C2f             [576, 192, 2]
 16                  -1  1    332160  ultralytics.nn.modules.conv.Conv             [192, 192, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  2   1846272  ultralytics.nn.modules.block.C2f             [576, 384, 2]
 19                  -1  1   1327872  ultralytics.nn.modules.conv.Conv             [384, 384, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  2   4207104  ultralytics.nn.modules.block.C2f             [960, 576, 2]
 22        [15, 18, 21]  1   3779170  ultralytics.nn.modules.head.Detect           [6, [192, 384, 576]]
YOLOv8m_mish_ summary: 169 layers, 25,859,794 parameters, 25,859,778 gradients, 79.1 GFLOPs

Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 86.7±64.1 MB/s, size: 51.9 KB)
train: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/train/labels... 919 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 919/919 722.9it/s 1.3s0.0s
WARNING ⚠️ train: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 40.1±28.4 MB/s, size: 35.4 KB)
val: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels... 230 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 230/230 582.2it/s 0.4s0.2s
WARNING ⚠️ val: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/val is not writeable, cache not saved.
Plotting labels to /kaggle/working/runs/detect/train14/labels.jpg...
optimizer: SGD(lr=0.005, momentum=0.937) with parameter groups 77 weight(decay=0.0), 84 weight(decay=0.001), 83 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to /kaggle/working/runs/detect/train14
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
WARNING ⚠️ CUDA OutOfMemoryError in TaskAlignedAssigner, using CPU
: 0% ──────────── 0/29  1.6s
❌ Error training with Mish: CUDA out of memory. Tried to allocate 66.00 MiB. GPU 0 has a total capacity of 15.89 GiB of which 63.12 MiB is free. Process 3754 has 15.81 GiB memory in use. Of the allocated memory 15.38 GiB is allocated by PyTorch, and 114.54 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

🚀 Training with SiLU activation...
Ultralytics 8.3.193 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-component-data/YOLO_component-dataset/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.005, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=/kaggle/working/yolov8m_silu_.yaml, momentum=0.937, mosaic=1.0, multi_scale=False, name=train15, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=/kaggle/working/runs/detect/train15, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.001, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=6
activation: nn.SiLU()

                   from  n    params  module                                       arguments
  0                  -1  1      1392  ultralytics.nn.modules.conv.Conv             [3, 48, 3, 2]
  1                  -1  1     41664  ultralytics.nn.modules.conv.Conv             [48, 96, 3, 2]
  2                  -1  2    111360  ultralytics.nn.modules.block.C2f             [96, 96, 2, True]
  3                  -1  1    166272  ultralytics.nn.modules.conv.Conv             [96, 192, 3, 2]
  4                  -1  4    813312  ultralytics.nn.modules.block.C2f             [192, 192, 4, True]
  5                  -1  1    664320  ultralytics.nn.modules.conv.Conv             [192, 384, 3, 2]
  6                  -1  4   3248640  ultralytics.nn.modules.block.C2f             [384, 384, 4, True]
  7                  -1  1   1991808  ultralytics.nn.modules.conv.Conv             [384, 576, 3, 2]
  8                  -1  2   3985920  ultralytics.nn.modules.block.C2f             [576, 576, 2, True]
  9                  -1  1    831168  ultralytics.nn.modules.block.SPPF            [576, 576, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  2   1993728  ultralytics.nn.modules.block.C2f             [960, 384, 2]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  2    517632  ultralytics.nn.modules.block.C2f             [576, 192, 2]
 16                  -1  1    332160  ultralytics.nn.modules.conv.Conv             [192, 192, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  2   1846272  ultralytics.nn.modules.block.C2f             [576, 384, 2]
 19                  -1  1   1327872  ultralytics.nn.modules.conv.Conv             [384, 384, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  2   4207104  ultralytics.nn.modules.block.C2f             [960, 576, 2]
 22        [15, 18, 21]  1   3779170  ultralytics.nn.modules.head.Detect           [6, [192, 384, 576]]
YOLOv8m_silu_ summary: 169 layers, 25,859,794 parameters, 25,859,778 gradients, 79.1 GFLOPs

Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 87.1±76.9 MB/s, size: 51.9 KB)
train: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/train/labels... 919 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 919/919 1.2Kit/s 0.8s0.1ss
WARNING ⚠️ train: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 41.3±29.7 MB/s, size: 35.4 KB)
val: Scanning /kaggle/input/yolo-component-data/YOLO_component-dataset/val/labels... 230 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 230/230 609.9it/s 0.4s0.1s
WARNING ⚠️ val: Cache directory /kaggle/input/yolo-component-data/YOLO_component-dataset/val is not writeable, cache not saved.
Plotting labels to /kaggle/working/runs/detect/train15/labels.jpg...
optimizer: SGD(lr=0.005, momentum=0.937) with parameter groups 77 weight(decay=0.0), 84 weight(decay=0.001), 83 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to /kaggle/working/runs/detect/train15
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
: 0% ──────────── 0/29  0.0s
❌ Error training with SiLU: CUDA out of memory. Tried to allocate 300.00 MiB. GPU 0 has a total capacity of 15.89 GiB of which 43.12 MiB is free. Process 3754 has 15.83 GiB memory in use. Of the allocated memory 15.13 GiB is allocated by PyTorch, and 389.92 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

📊 Case 9 Results Table:

+----+---------------------+----------+--------------+-------------+--------------+-----------------+--------------+-----------------+---------------------+--------------------+--------------------+--------------------+--------------------+
|    | Experiment          |   Epochs |   Batch Size | Optimizer   |   Image Size |   Learning Rate | Activation   |   Freeze Layers | Training Time (s)   | Precision          | Recall             | mAP@0.5            | mAP@0.5:0.95       |
+====+=====================+==========+==============+=============+==============+=================+==============+=================+=====================+====================+====================+====================+====================+
|  0 | case9_act_ReLU      |       32 |           32 | SGD         |          640 |           0.005 | ReLU         |               0 | 1149.27             | 0.9708771198486144 | 0.981019021537795  | 0.9849200531357066 | 0.6625945498084829 |
+----+---------------------+----------+--------------+-------------+--------------+-----------------+--------------+-----------------+---------------------+--------------------+--------------------+--------------------+--------------------+
|  1 | case9_act_LeakyReLU |       32 |           32 | SGD         |          640 |           0.005 | LeakyReLU    |               0 | 1151.51             | 0.979393710406494  | 0.9759015881123579 | 0.9848490168677745 | 0.6662685020253438 |
+----+---------------------+----------+--------------+-------------+--------------+-----------------+--------------+-----------------+---------------------+--------------------+--------------------+--------------------+--------------------+
|  2 | case9_act_Mish      |       32 |           32 | SGD         |          640 |           0.005 | Mish         |               0 | Error               | Error              | Error              | Error              | Error              |
+----+---------------------+----------+--------------+-------------+--------------+-----------------+--------------+-----------------+---------------------+--------------------+--------------------+--------------------+--------------------+
|  3 | case9_act_SiLU      |       32 |           32 | SGD         |          640 |           0.005 | SiLU         |               0 | Error               | Error              | Error              | Error              | Error              |
+----+---------------------+----------+--------------+-------------+--------------+-----------------+--------------+-----------------+---------------------+--------------------+--------------------+--------------------+--------------------+