In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/data.yaml
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit193_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit488_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit224_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit396_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit492_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit293_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit344_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit2_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit180_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit388_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit181_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit472_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit165_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit29_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit35_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit272_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit217_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit356_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit399_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit174_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit276_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit361_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit236_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit67_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit475_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit301_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit301_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit241_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit98_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit207_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit159_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit479_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit460_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit181_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit458_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit456_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit423_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit358_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit4_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit133_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit381_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit39_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit354_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit96_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit201_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit379_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit146_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit76_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit3_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit77_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit436_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit94_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit198_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit449_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit357_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit60_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit210_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit405_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit212_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit258_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit286_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit302_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit217_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit203_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit499_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit325_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit82_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit41_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit298_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit497_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit295_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit16_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit379_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit213_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit133_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit344_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit495_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit209_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit257_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit32_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit388_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit438_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit369_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit473_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit467_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit293_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit104_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit461_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit404_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit264_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit398_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit258_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit345_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit436_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit145_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit195_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit481_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit218_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit118_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit223_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit451_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit264_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit487_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit488_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit431_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit50_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit459_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit146_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit102_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit187_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit71_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit406_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit113_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit213_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit143_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit499_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit412_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit138_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit399_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit33_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit430_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit121_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit309_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit91_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit228_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit101_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit233_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit176_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit300_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit235_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit455_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit384_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit134_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit315_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit321_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit188_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit298_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit70_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit147_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit25_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit482_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit81_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit113_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit425_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit177_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit89_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit41_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit83_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit323_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit389_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit434_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit92_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit101_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit235_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit375_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit112_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit42_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit290_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit104_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit400_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit34_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit106_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit322_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit495_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit421_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit278_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit378_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit394_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit292_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit108_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit281_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit446_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit31_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit63_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit232_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit39_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit481_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit276_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit496_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit182_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit85_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit102_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit377_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit204_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit376_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit466_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit368_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit262_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit212_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit136_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit448_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit99_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit48_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit8_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit413_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit303_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit442_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit314_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit319_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit449_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit184_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit271_aug_0.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit80_aug_1.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit494_aug_2.txt
/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels/circuit12_aug_2.txt

In [1]:
pip install ultralytics

Collecting ultralytics
  Downloading ultralytics-8.3.191-py3-none-any.whl.metadata (37 kB)
Requirement already satisfied: numpy>=1.23.0 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (1.26.4)
Requirement already satisfied: matplotlib>=3.3.0 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (3.7.2)
Requirement already satisfied: opencv-python>=4.6.0 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (4.11.0.86)
Requirement already satisfied: pillow>=7.1.2 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (11.2.1)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (6.0.2)
Requirement already satisfied: requests>=2.23.0 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (2.32.4)
Requirement already satisfied: scipy>=1.4.1 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (1.15.3)
Requirement already satisfied: torch>=1.8.0 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (2.6.0+cu124)
Requirement already satisfied: torchvision>=0.9.0 in /usr/local/lib/python3.11/dist-packages (from ultralytics) (0.21.0+cu124)
Requirement already satisfied: psutil in /usr/local/lib/python3.11/dist-packages (from ultralytics) (7.0.0)
Requirement already satisfied: py-cpuinfo in /usr/local/lib/python3.11/dist-packages (from ultralytics) (9.0.0)
Requirement already satisfied: polars in /usr/local/lib/python3.11/dist-packages (from ultralytics) (1.21.0)
Collecting ultralytics-thop>=2.0.0 (from ultralytics)
  Downloading ultralytics_thop-2.0.16-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.3.0->ultralytics) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.3.0->ultralytics) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.3.0->ultralytics) (4.58.4)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.3.0->ultralytics) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.3.0->ultralytics) (25.0)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.3.0->ultralytics) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.3.0->ultralytics) (2.9.0.post0)
Requirement already satisfied: mkl_fft in /usr/local/lib/python3.11/dist-packages (from numpy>=1.23.0->ultralytics) (1.3.8)
Requirement already satisfied: mkl_random in /usr/local/lib/python3.11/dist-packages (from numpy>=1.23.0->ultralytics) (1.2.4)
Requirement already satisfied: mkl_umath in /usr/local/lib/python3.11/dist-packages (from numpy>=1.23.0->ultralytics) (0.1.1)
Requirement already satisfied: mkl in /usr/local/lib/python3.11/dist-packages (from numpy>=1.23.0->ultralytics) (2025.2.0)
Requirement already satisfied: tbb4py in /usr/local/lib/python3.11/dist-packages (from numpy>=1.23.0->ultralytics) (2022.2.0)
Requirement already satisfied: mkl-service in /usr/local/lib/python3.11/dist-packages (from numpy>=1.23.0->ultralytics) (2.4.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.23.0->ultralytics) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.23.0->ultralytics) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.23.0->ultralytics) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.23.0->ultralytics) (2025.6.15)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (3.18.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (4.14.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (2025.5.1)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (12.4.127)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch>=1.8.0->ultralytics)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch>=1.8.0->ultralytics) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=1.8.0->ultralytics) (1.3.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib>=3.3.0->ultralytics) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch>=1.8.0->ultralytics) (3.0.2)
Requirement already satisfied: intel-openmp<2026,>=2024 in /usr/local/lib/python3.11/dist-packages (from mkl->numpy>=1.23.0->ultralytics) (2024.2.0)
Requirement already satisfied: tbb==2022.* in /usr/local/lib/python3.11/dist-packages (from mkl->numpy>=1.23.0->ultralytics) (2022.2.0)
Requirement already satisfied: tcmlib==1.* in /usr/local/lib/python3.11/dist-packages (from tbb==2022.*->mkl->numpy>=1.23.0->ultralytics) (1.4.0)
Requirement already satisfied: intel-cmplr-lib-rt in /usr/local/lib/python3.11/dist-packages (from mkl_umath->numpy>=1.23.0->ultralytics) (2024.2.0)
Requirement already satisfied: intel-cmplr-lib-ur==2024.2.0 in /usr/local/lib/python3.11/dist-packages (from intel-openmp<2026,>=2024->mkl->numpy>=1.23.0->ultralytics) (2024.2.0)
Downloading ultralytics-8.3.191-py3-none-any.whl (1.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 27.6 MB/s eta 0:00:0000:01
Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 4.7 MB/s eta 0:00:00:00:0100:01
Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 87.3 MB/s eta 0:00:00:00:0100:01
Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 75.4 MB/s eta 0:00:00:00:0100:01
Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 43.2 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.2 MB/s eta 0:00:00:00:0100:01
Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 2.9 MB/s eta 0:00:00:00:0100:01
Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 5.2 MB/s eta 0:00:000:00:0100:01
Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 13.4 MB/s eta 0:00:0000:0100:01
Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 8.3 MB/s eta 0:00:00:00:0100:01
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 82.3 MB/s eta 0:00:00:00:0100:01
Downloading ultralytics_thop-2.0.16-py3-none-any.whl (28 kB)
Installing collected packages: nvidia-nvjitlink-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12, ultralytics-thop, ultralytics
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.5.82
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.6.82
    Uninstalling nvidia-curand-cu12-10.3.6.82:
      Successfully uninstalled nvidia-curand-cu12-10.3.6.82
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.2.3.61
    Uninstalling nvidia-cufft-cu12-11.2.3.61:
      Successfully uninstalled nvidia-cufft-cu12-11.2.3.61
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.5.82
    Uninstalling nvidia-cuda-runtime-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.5.82
    Uninstalling nvidia-cuda-nvrtc-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.5.82
    Uninstalling nvidia-cuda-cupti-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.5.82
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.5.3.2
    Uninstalling nvidia-cublas-cu12-12.5.3.2:
      Successfully uninstalled nvidia-cublas-cu12-12.5.3.2
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.1.3
    Uninstalling nvidia-cusparse-cu12-12.5.1.3:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.1.3
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.3.0.75
    Uninstalling nvidia-cudnn-cu12-9.3.0.75:
      Successfully uninstalled nvidia-cudnn-cu12-9.3.0.75
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.6.3.83
    Uninstalling nvidia-cusolver-cu12-11.6.3.83:
      Successfully uninstalled nvidia-cusolver-cu12-11.6.3.83
Successfully installed nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-nvjitlink-cu12-12.4.127 ultralytics-8.3.191 ultralytics-thop-2.0.16
Note: you may need to restart the kernel to use updated packages.

In [2]:
import time
import json
import pandas as pd
from ultralytics import YOLO
from pathlib import Path

# =============================
# CONFIG
# =============================
DATA_PATH = "/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/data.yaml"
RESULTS_CSV = "yolov8s_ablation_results.csv"

# Global Best Parameters (update as you go)
BEST_PARAMS = {
    "epochs": 32,          # default, update after finding best
    "batch": 32,
    "lr0": 0.01,
    "weight_decay": 0.0005,
    "optimizer": "SGD",
    "img_size": 640,
    "dropout": 0.0,
    "freeze": 0,
    "activation": "SiLU"
}

# Initialize results DataFrame
if Path(RESULTS_CSV).exists():
    results_df = pd.read_csv(RESULTS_CSV)
else:
    results_df = pd.DataFrame(columns=[
        "Case", "Exp No", "Experiment Name", "Epochs", "Batch", "lr0", "Weight Decay",
        "Optimizer", "Image Size", "Dropout", "Freeze Layers", "Activation",
        "Training Time (s)", "Precision", "Recall", "mAP@0.5", "mAP@0.5:0.95"
    ])

Creating new Ultralytics Settings v0.0.6 file ✅
View Ultralytics Settings with 'yolo settings' or at '/root/.config/Ultralytics/settings.json'
Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/quickstart/#ultralytics-settings.

In [3]:
def run_experiment(case, exp_no, exp_name, epochs=32, batch=32, lr0=0.01,
                   weight_decay=0.0005, optimizer="SGD", img_size=640,
                   dropout=0.0, freeze=0, activation="SiLU"):
    global results_df

    model = YOLO("yolov8m.pt")  # Using YOLOv8 samll

    # Track training time
    start_time = time.time()
    model.train(
        data=DATA_PATH,
        epochs=epochs,
        batch=batch,
        lr0=lr0,
        optimizer=optimizer,
        imgsz=img_size,
        dropout=dropout,
        freeze=freeze,
        verbose=False
    )
    train_time = time.time() - start_time

    # ✅ FIX: Load YOLO metrics from results.csv
    results_file = Path(model.trainer.save_dir) / "results.csv"
    results_df_yolo = pd.read_csv(results_file)
    last_row = results_df_yolo.iloc[-1]

    precision = last_row["metrics/precision(B)"]
    recall = last_row["metrics/recall(B)"]
    map50 = last_row["metrics/mAP50(B)"]
    map5095 = last_row["metrics/mAP50-95(B)"]

    new_row = {
        "Case": case,
        "Exp No": exp_no,
        "Experiment Name": exp_name,
        "Epochs": epochs,
        "Batch": batch,
        "lr0": lr0,
        "Weight Decay": weight_decay,
        "Optimizer": optimizer,
        "Image Size": img_size,
        "Dropout": dropout,
        "Freeze Layers": freeze,
        "Activation": activation,
        "Training Time (s)": round(train_time, 2),
        "Precision": precision,
        "Recall": recall,
        "mAP@0.5": map50,
        "mAP@0.5:0.95": map5095,
    }
    results_df = pd.concat([results_df, pd.DataFrame([new_row])], ignore_index=True)

    results_df.to_csv(RESULTS_CSV, index=False)
    display(results_df.tail(10))
# =============================
# Wrapper to use BEST_PARAMS
# =============================
def run_with_best(case, exp_no, exp_name, **kwargs):
    params = BEST_PARAMS.copy()
    params.update(kwargs)
    run_experiment(case, exp_no, exp_name, **params)

In [5]:
# Case 1: Epoch Variation
def case1_epoch_variation():
    run_with_best("Case 1: Epoch Variation", 1, "epochs_16", epochs=16)
    run_with_best("Case 1: Epoch Variation", 2, "epochs_32", epochs=32)
    run_with_best("Case 1: Epoch Variation", 3, "epochs_64", epochs=64)

# Case 2: Weight Decay
def case2_weight_decay():
    run_with_best("Case 2: Weight Decay", 1, "wd_0", weight_decay=0)
    run_with_best("Case 2: Weight Decay", 2, "wd_0.0001", weight_decay=0.0001)
    run_with_best("Case 2: Weight Decay", 3, "wd_0.0005", weight_decay=0.0005)
    run_with_best("Case 2: Weight Decay", 4, "wd_0.001", weight_decay=0.001)
    run_with_best("Case 2: Weight Decay", 5, "wd_0.005", weight_decay=0.005)

# Case 3: Batch Size
def case3_batch_size():
    run_with_best("Case 3: Batch Size", 1, "batch_16", batch=16)
    run_with_best("Case 3: Batch Size", 2, "batch_32", batch=32)
    run_with_best("Case 3: Batch Size", 3, "batch_64", batch=64)  # may OOM

# Case 4: Dropout
def case4_dropout():
    for i, d in enumerate([0, 0.1, 0.2, 0.3, 0.5], start=1):
        run_with_best("Case 4: Dropout", i, f"dropout_{d}", dropout=d)

# Case 6: Optimizer
def case6_optimizer():
    opts = ["SGD", "Adam", "AdamW", "RMSProp", "Adamax"]
    for i, opt in enumerate(opts, start=1):
        run_with_best("Case 6: Optimizer", i, f"optimizer_{opt}", optimizer=opt)
# Case 7: Learning Rate
def case7_learning_rate():
    for i, lr in enumerate([0.001, 0.005, 0.01, 0.05], start=1):
        run_with_best("Case 7: Learning Rate", i, f"lr_{lr}", lr0=lr)

# Case 8: Freeze Layers
def case8_freeze_layers():
    for i, freeze in enumerate([0, 10, 15, 22], start=1):
        run_with_best("Case 8: Freeze Layers", i, f"freeze_{freeze}", freeze=freeze)
# Case 10: Image Size
def case10_image_size():
    sizes = [320, 512, 640]
    for i, sz in enumerate(sizes, start=1):
        run_with_best("Case 10: Image Size", i, f"imgsz_{sz}", img_size=sz)

In [5]:
case1_epoch_variation()

Downloading https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov8m.pt to 'yolov8m.pt': 100% ━━━━━━━━━━━━ 49.7/49.7MB 120.5MB/s 0.4s0.0s
Ultralytics 8.3.191 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=16, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8m.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/train, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Downloading https://ultralytics.com/assets/Arial.ttf to '/root/.config/Ultralytics/Arial.ttf': 100% ━━━━━━━━━━━━ 755.1/755.1KB 34.2MB/s 0.0s
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1      1392  ultralytics.nn.modules.conv.Conv             [3, 48, 3, 2]
  1                  -1  1     41664  ultralytics.nn.modules.conv.Conv             [48, 96, 3, 2]
  2                  -1  2    111360  ultralytics.nn.modules.block.C2f             [96, 96, 2, True]
  3                  -1  1    166272  ultralytics.nn.modules.conv.Conv             [96, 192, 3, 2]
  4                  -1  4    813312  ultralytics.nn.modules.block.C2f             [192, 192, 4, True]
  5                  -1  1    664320  ultralytics.nn.modules.conv.Conv             [192, 384, 3, 2]
  6                  -1  4   3248640  ultralytics.nn.modules.block.C2f             [384, 384, 4, True]
  7                  -1  1   1991808  ultralytics.nn.modules.conv.Conv             [384, 576, 3, 2]
  8                  -1  2   3985920  ultralytics.nn.modules.block.C2f             [576, 576, 2, True]
  9                  -1  1    831168  ultralytics.nn.modules.block.SPPF            [576, 576, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  2   1993728  ultralytics.nn.modules.block.C2f             [960, 384, 2]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  2    517632  ultralytics.nn.modules.block.C2f             [576, 192, 2]
 16                  -1  1    332160  ultralytics.nn.modules.conv.Conv             [192, 192, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  2   1846272  ultralytics.nn.modules.block.C2f             [576, 384, 2]
 19                  -1  1   1327872  ultralytics.nn.modules.conv.Conv             [384, 384, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  2   4207104  ultralytics.nn.modules.block.C2f             [960, 576, 2]
 22        [15, 18, 21]  1   3776275  ultralytics.nn.modules.head.Detect           [1, [192, 384, 576]]
Model summary: 169 layers, 25,856,899 parameters, 25,856,883 gradients, 79.1 GFLOPs

Transferred 469/475 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
Downloading https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11n.pt to 'yolo11n.pt': 100% ━━━━━━━━━━━━ 5.4/5.4MB 159.4MB/s 0.0s
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 9.4±2.7 MB/s, size: 52.0 KB)
train: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train/labels... 1200 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1200/1200 179.4it/s 6.7s0.1s
WARNING ⚠️ train: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 6.7±3.2 MB/s, size: 61.5 KB)
val: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels... 300 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 300/300 156.9it/s 1.9s0.1s
WARNING ⚠️ val: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val is not writeable, cache not saved.
Plotting labels to runs/detect/train/labels.jpg...
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 77 weight(decay=0.0), 84 weight(decay=0.0005), 83 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs/detect/train
Starting training for 16 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/16      13.7G      2.233      2.202      1.647        145        640: 100% ━━━━━━━━━━━━ 38/38 0.89it/s 42.8s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.3it/s 3.8s0.9sss
                   all        300       1798      0.976      0.969      0.983      0.581

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/16      13.9G      1.326     0.7107      1.125        166        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.6s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.993      0.989      0.995       0.62

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/16        14G      1.321     0.5955      1.139        166        640: 100% ━━━━━━━━━━━━ 38/38 0.92it/s 41.5s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.989      0.985      0.989      0.616

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/16        14G       1.27     0.5873      1.123        136        640: 100% ━━━━━━━━━━━━ 38/38 0.92it/s 41.5s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.985      0.968       0.99      0.558

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/16        14G      1.263     0.5211      1.145        165        640: 100% ━━━━━━━━━━━━ 38/38 0.92it/s 41.5s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.989      0.987      0.993      0.637

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/16        14G       1.22     0.5001      1.129        171        640: 100% ━━━━━━━━━━━━ 38/38 0.92it/s 41.5s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.984      0.983      0.991      0.511
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/16        14G      1.162     0.4559      1.118         96        640: 100% ━━━━━━━━━━━━ 38/38 0.89it/s 42.5s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.985      0.983      0.993       0.67

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/16        14G      1.174     0.4549      1.107         85        640: 100% ━━━━━━━━━━━━ 38/38 0.92it/s 41.3s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.985      0.983       0.99      0.639

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/16        14G      1.153     0.4351      1.103         98        640: 100% ━━━━━━━━━━━━ 38/38 0.92it/s 41.3s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798       0.99      0.955      0.973      0.644

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/16        14G      1.125     0.4275      1.095         94        640: 100% ━━━━━━━━━━━━ 38/38 0.92it/s 41.3s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.995      0.987      0.994      0.687

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/16      13.9G       1.11      0.421      1.092         84        640: 100% ━━━━━━━━━━━━ 38/38 0.92it/s 41.3s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.995      0.993      0.994      0.712

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/16        14G       1.08     0.3988      1.087        102        640: 100% ━━━━━━━━━━━━ 38/38 0.92it/s 41.3s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.997      0.995      0.994       0.72

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/16        14G      1.049     0.3846      1.076         93        640: 100% ━━━━━━━━━━━━ 38/38 0.92it/s 41.3s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.995      0.996      0.994      0.709

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/16        14G      1.034     0.3736      1.063         99        640: 100% ━━━━━━━━━━━━ 38/38 0.92it/s 41.3s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.993      0.996      0.995      0.735

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/16        14G      1.006     0.3607      1.038         97        640: 100% ━━━━━━━━━━━━ 38/38 0.92it/s 41.3s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.994      0.997      0.994       0.73

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/16        14G     0.9954     0.3508      1.044         89        640: 100% ━━━━━━━━━━━━ 38/38 0.92it/s 41.3s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.997      0.994      0.994      0.741

16 epochs completed in 0.203 hours.
Optimizer stripped from runs/detect/train/weights/last.pt, 52.0MB
Optimizer stripped from runs/detect/train/weights/best.pt, 52.0MB

Validating runs/detect/train/weights/best.pt...
Ultralytics 8.3.191 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
Model summary (fused): 92 layers, 25,840,339 parameters, 0 gradients, 78.7 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.1it/s 4.4s<1.3s

/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        300       1798      0.997      0.994      0.994      0.741
Speed: 0.1ms preprocess, 7.4ms inference, 0.0ms loss, 1.5ms postprocess per image
Results saved to runs/detect/train

,Case,Exp No,Experiment Name,Epochs,Batch,lr0,Weight Decay,Optimizer,Image Size,Dropout,Freeze Layers,Activation,Training Time (s),Precision,Recall,mAP@0.5,mAP@0.5:0.95
0,Case 1: Epoch Variation,1,epochs_16,16,32,0.01,0.0005,SGD,640,0.0,0,SiLU,763.86,0.99663,0.99388,0.99412,0.74142

Ultralytics 8.3.191 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8m.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train2, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/train2, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1      1392  ultralytics.nn.modules.conv.Conv             [3, 48, 3, 2]
  1                  -1  1     41664  ultralytics.nn.modules.conv.Conv             [48, 96, 3, 2]
  2                  -1  2    111360  ultralytics.nn.modules.block.C2f             [96, 96, 2, True]
  3                  -1  1    166272  ultralytics.nn.modules.conv.Conv             [96, 192, 3, 2]
  4                  -1  4    813312  ultralytics.nn.modules.block.C2f             [192, 192, 4, True]
  5                  -1  1    664320  ultralytics.nn.modules.conv.Conv             [192, 384, 3, 2]
  6                  -1  4   3248640  ultralytics.nn.modules.block.C2f             [384, 384, 4, True]
  7                  -1  1   1991808  ultralytics.nn.modules.conv.Conv             [384, 576, 3, 2]
  8                  -1  2   3985920  ultralytics.nn.modules.block.C2f             [576, 576, 2, True]
  9                  -1  1    831168  ultralytics.nn.modules.block.SPPF            [576, 576, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  2   1993728  ultralytics.nn.modules.block.C2f             [960, 384, 2]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  2    517632  ultralytics.nn.modules.block.C2f             [576, 192, 2]
 16                  -1  1    332160  ultralytics.nn.modules.conv.Conv             [192, 192, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  2   1846272  ultralytics.nn.modules.block.C2f             [576, 384, 2]
 19                  -1  1   1327872  ultralytics.nn.modules.conv.Conv             [384, 384, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  2   4207104  ultralytics.nn.modules.block.C2f             [960, 576, 2]
 22        [15, 18, 21]  1   3776275  ultralytics.nn.modules.head.Detect           [1, [192, 384, 576]]
Model summary: 169 layers, 25,856,899 parameters, 25,856,883 gradients, 79.1 GFLOPs

Transferred 469/475 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 71.6±26.3 MB/s, size: 52.0 KB)
train: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train/labels... 1200 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1200/1200 825.2it/s 1.5s0.0s
WARNING ⚠️ train: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 93.5±46.0 MB/s, size: 61.5 KB)
val: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels... 300 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 300/300 508.1it/s 0.6s0.1s
WARNING ⚠️ val: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val is not writeable, cache not saved.
Plotting labels to runs/detect/train2/labels.jpg...
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 77 weight(decay=0.0), 84 weight(decay=0.0005), 83 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs/detect/train2
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/32      14.1G      2.233      2.202      1.647        145        640: 100% ━━━━━━━━━━━━ 38/38 0.90it/s 42.2s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.6it/s 3.1s0.9ss
                   all        300       1798      0.976      0.969      0.983      0.581

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/32      13.9G      1.341     0.7044      1.144        166        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.7s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798       0.99      0.989      0.992      0.642

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/32        14G      1.324     0.6317      1.145        166        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.6s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.979      0.972      0.988      0.563

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/32        14G      1.271     0.6135      1.133        136        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.5s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798       0.99      0.982      0.993        0.6

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/32        14G      1.282     0.5407      1.139        165        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.6s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.981       0.97      0.991      0.589

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/32        14G      1.232      0.534      1.129        171        640: 100% ━━━━━━━━━━━━ 38/38 0.92it/s 41.5s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.991      0.988      0.994      0.642

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/32        14G      1.206     0.4966      1.119        167        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.5s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.994      0.991      0.994      0.645

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/32        14G      1.198     0.4973       1.12        141        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.5s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798       0.99      0.991      0.994      0.661

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/32        14G      1.189     0.4836      1.131        129        640: 100% ━━━━━━━━━━━━ 38/38 0.92it/s 41.5s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.989      0.982      0.992      0.617

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/32        14G      1.169     0.4752      1.121        153        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.5s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.987      0.981      0.992      0.668

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/32        14G      1.152      0.462      1.108        192        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.5s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.992      0.989      0.994      0.685

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/32        14G      1.124     0.4544      1.097        186        640: 100% ━━━━━━━━━━━━ 38/38 0.92it/s 41.5s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.994      0.996      0.994      0.655

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/32        14G      1.126     0.4457      1.102        168        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.5s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.992      0.996      0.993      0.702

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/32        14G      1.106     0.4364      1.101        169        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.6s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.996      0.993      0.994      0.697

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/32        14G      1.103     0.4386      1.115        156        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.5s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.994      0.994      0.993      0.707

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/32        14G      1.095     0.4334      1.108        176        640: 100% ━━━━━━━━━━━━ 38/38 0.92it/s 41.5s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.997      0.996      0.994      0.685

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/32        14G      1.072     0.4163      1.077        188        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.6s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.993      0.995      0.994      0.723

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/32        14G      1.056     0.4101      1.075        169        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.6s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.995      0.997      0.994      0.716

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/32        14G      1.043     0.4022      1.068        155        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.6s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.6it/s 3.0s0.8ss
                   all        300       1798      0.994      0.997      0.994      0.723

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/32        14G       1.03     0.3971      1.069        180        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.6s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.996      0.996      0.994      0.727

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/32        14G      1.013     0.3897      1.069        174        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.6s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.996      0.997      0.995      0.722

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/32        14G          1     0.3859      1.055        149        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.6s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.997      0.996      0.995       0.74
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/32        14G     0.9801     0.3513      1.065         96        640: 100% ━━━━━━━━━━━━ 38/38 0.89it/s 42.6s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.996      0.997      0.995      0.741

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/32        14G     0.9723     0.3529      1.064        100        640: 100% ━━━━━━━━━━━━ 38/38 0.92it/s 41.4s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.996      0.998      0.995       0.74

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/32        14G      0.949     0.3435      1.043         99        640: 100% ━━━━━━━━━━━━ 38/38 0.92it/s 41.4s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.996      0.997      0.995      0.741

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/32        14G     0.9285     0.3338      1.016        100        640: 100% ━━━━━━━━━━━━ 38/38 0.92it/s 41.4s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.995      0.997      0.995       0.75

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/32        14G     0.9113     0.3258       1.02         82        640: 100% ━━━━━━━━━━━━ 38/38 0.92it/s 41.4s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.997      0.998      0.995      0.745

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/32        14G     0.9058     0.3226      1.025         92        640: 100% ━━━━━━━━━━━━ 38/38 0.92it/s 41.4s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.997      0.998      0.995      0.755

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/32        14G     0.8889     0.3165      1.016         96        640: 100% ━━━━━━━━━━━━ 38/38 0.92it/s 41.3s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.996      0.998      0.994      0.752

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/32        14G     0.8784     0.3104      1.012         89        640: 100% ━━━━━━━━━━━━ 38/38 0.92it/s 41.4s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.997      0.996      0.994      0.758

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/32        14G     0.8538     0.3033     0.9996         93        640: 100% ━━━━━━━━━━━━ 38/38 0.92it/s 41.4s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.998      0.997      0.995      0.759

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/32        14G     0.8484      0.298     0.9968         99        640: 100% ━━━━━━━━━━━━ 38/38 0.92it/s 41.4s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.996      0.998      0.995      0.765

32 epochs completed in 0.406 hours.
Optimizer stripped from runs/detect/train2/weights/last.pt, 52.0MB
Optimizer stripped from runs/detect/train2/weights/best.pt, 52.0MB

Validating runs/detect/train2/weights/best.pt...
Ultralytics 8.3.191 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
Model summary (fused): 92 layers, 25,840,339 parameters, 0 gradients, 78.7 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.2it/s 4.3s<1.1s

/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        300       1798      0.996      0.998      0.995      0.764
Speed: 0.1ms preprocess, 7.6ms inference, 0.0ms loss, 1.4ms postprocess per image
Results saved to runs/detect/train2

,Case,Exp No,Experiment Name,Epochs,Batch,lr0,Weight Decay,Optimizer,Image Size,Dropout,Freeze Layers,Activation,Training Time (s),Precision,Recall,mAP@0.5,mAP@0.5:0.95
0,Case 1: Epoch Variation,1,epochs_16,16,32,0.01,0.0005,SGD,640,0.0,0,SiLU,763.86,0.99663,0.99388,0.99412,0.74142
1,Case 1: Epoch Variation,2,epochs_32,32,32,0.01,0.0005,SGD,640,0.0,0,SiLU,1474.82,0.99606,0.99778,0.99467,0.76455

Ultralytics 8.3.191 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=64, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8m.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train3, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/train3, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1      1392  ultralytics.nn.modules.conv.Conv             [3, 48, 3, 2]
  1                  -1  1     41664  ultralytics.nn.modules.conv.Conv             [48, 96, 3, 2]
  2                  -1  2    111360  ultralytics.nn.modules.block.C2f             [96, 96, 2, True]
  3                  -1  1    166272  ultralytics.nn.modules.conv.Conv             [96, 192, 3, 2]
  4                  -1  4    813312  ultralytics.nn.modules.block.C2f             [192, 192, 4, True]
  5                  -1  1    664320  ultralytics.nn.modules.conv.Conv             [192, 384, 3, 2]
  6                  -1  4   3248640  ultralytics.nn.modules.block.C2f             [384, 384, 4, True]
  7                  -1  1   1991808  ultralytics.nn.modules.conv.Conv             [384, 576, 3, 2]
  8                  -1  2   3985920  ultralytics.nn.modules.block.C2f             [576, 576, 2, True]
  9                  -1  1    831168  ultralytics.nn.modules.block.SPPF            [576, 576, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  2   1993728  ultralytics.nn.modules.block.C2f             [960, 384, 2]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  2    517632  ultralytics.nn.modules.block.C2f             [576, 192, 2]
 16                  -1  1    332160  ultralytics.nn.modules.conv.Conv             [192, 192, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  2   1846272  ultralytics.nn.modules.block.C2f             [576, 384, 2]
 19                  -1  1   1327872  ultralytics.nn.modules.conv.Conv             [384, 384, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  2   4207104  ultralytics.nn.modules.block.C2f             [960, 576, 2]
 22        [15, 18, 21]  1   3776275  ultralytics.nn.modules.head.Detect           [1, [192, 384, 576]]
Model summary: 169 layers, 25,856,899 parameters, 25,856,883 gradients, 79.1 GFLOPs

Transferred 469/475 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 110.4±25.5 MB/s, size: 52.0 KB)
train: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train/labels... 1200 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1200/1200 759.7it/s 1.6s0.1s
WARNING ⚠️ train: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 82.6±45.3 MB/s, size: 61.5 KB)
val: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels... 300 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 300/300 461.6it/s 0.6s0.0s
WARNING ⚠️ val: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val is not writeable, cache not saved.
Plotting labels to runs/detect/train3/labels.jpg...
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 77 weight(decay=0.0), 84 weight(decay=0.0005), 83 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs/detect/train3
Starting training for 64 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/64      14.1G      2.233      2.202      1.647        145        640: 100% ━━━━━━━━━━━━ 38/38 0.90it/s 42.1s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.6it/s 3.1s0.9ss
                   all        300       1798      0.976      0.969      0.983      0.581

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/64      13.9G      1.342     0.7059      1.141        166        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.7s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.989      0.985      0.993      0.626

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/64        14G      1.333     0.6203      1.142        166        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.5s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.988      0.988      0.992      0.623

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/64        14G      1.304     0.6434      1.142        136        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.5s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.984      0.979      0.992      0.643

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/64        14G      1.285     0.5629      1.143        165        640: 100% ━━━━━━━━━━━━ 38/38 0.92it/s 41.5s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.6it/s 3.0s0.8ss
                   all        300       1798       0.98      0.971      0.991      0.631

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/64        14G      1.253     0.5415      1.157        171        640: 100% ━━━━━━━━━━━━ 38/38 0.92it/s 41.5s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.979      0.967      0.988      0.638

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/64        14G      1.221     0.5214      1.138        167        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.6s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.6it/s 3.0s0.8ss
                   all        300       1798      0.981      0.971      0.989      0.536

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/64        14G      1.221     0.5099      1.127        141        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.5s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.969      0.897      0.959      0.577

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/64        14G      1.216     0.5065      1.145        129        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.5s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.992      0.991      0.993      0.642

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/64        14G      1.201     0.4899      1.133        153        640: 100% ━━━━━━━━━━━━ 38/38 0.92it/s 41.5s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.993      0.994      0.994      0.666

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/64        14G      1.182     0.4781      1.141        192        640: 100% ━━━━━━━━━━━━ 38/38 0.92it/s 41.5s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798       0.99      0.993      0.993      0.666

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/64      13.9G      1.144     0.4769      1.116        186        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.5s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.996      0.993      0.994      0.684

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/64        14G      1.154     0.4637      1.131        168        640: 100% ━━━━━━━━━━━━ 38/38 0.92it/s 41.5s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.993      0.983      0.993      0.695

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/64        14G      1.136     0.4595      1.124        169        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.5s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.981      0.964      0.989       0.67

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/64        14G      1.133     0.4564      1.121        156        640: 100% ━━━━━━━━━━━━ 38/38 0.92it/s 41.5s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.993      0.992      0.993      0.665

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/64        14G      1.131     0.4484      1.125        176        640: 100% ━━━━━━━━━━━━ 38/38 0.92it/s 41.5s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.994      0.994      0.994      0.657

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/64        14G      1.108     0.4395      1.099        188        640: 100% ━━━━━━━━━━━━ 38/38 0.92it/s 41.5s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.993      0.993      0.995      0.688

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/64        14G      1.106      0.434      1.091        169        640: 100% ━━━━━━━━━━━━ 38/38 0.92it/s 41.5s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.984      0.972      0.993      0.668

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/64        14G      1.095     0.4275      1.095        155        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.6s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.995      0.997      0.994      0.704

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/64        14G       1.08      0.423      1.095        180        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.5s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.993      0.993      0.994      0.714

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/64        14G      1.062       0.42       1.09        174        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.6s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.996      0.993      0.995      0.705

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/64        14G      1.054     0.4182      1.078        149        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.5s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.995      0.995      0.995      0.709

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/64        14G       1.07     0.4203      1.091        148        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.5s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.996      0.992      0.994       0.72

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/64        14G      1.058     0.4128      1.066        143        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.6s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.996      0.992      0.994      0.717

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/64      13.9G      1.046     0.4102      1.077        165        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.6s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.993      0.994      0.994      0.722

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/64        14G       1.04     0.4075       1.06        141        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.5s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.995      0.994      0.994       0.73

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/64        14G      1.016     0.3986      1.057        165        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.6s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.996      0.994      0.994      0.711

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/64        14G      1.024     0.3992      1.063        161        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.5s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.997      0.997      0.995      0.704

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/64        14G     0.9991     0.3872      1.067        184        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.6s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.994      0.995      0.994       0.73

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/64        14G      1.002     0.3886      1.063        151        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.6s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.993      0.996      0.994      0.739

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/64        14G     0.9928     0.3849      1.049        131        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.6s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.997      0.994      0.994      0.739

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/64        14G     0.9861     0.3827      1.055        146        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.6s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.997      0.995      0.994      0.737

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      33/64        14G     0.9801     0.3813       1.05        166        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.6s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.997      0.995      0.995       0.74

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      34/64        14G     0.9656     0.3711      1.051        201        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.6s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.996      0.997      0.994      0.744


/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        300       1798      0.997      0.996      0.995      0.791
Speed: 0.1ms preprocess, 7.6ms inference, 0.0ms loss, 1.5ms postprocess per image
Results saved to runs/detect/train3

,Case,Exp No,Experiment Name,Epochs,Batch,lr0,Weight Decay,Optimizer,Image Size,Dropout,Freeze Layers,Activation,Training Time (s),Precision,Recall,mAP@0.5,mAP@0.5:0.95
0,Case 1: Epoch Variation,1,epochs_16,16,32,0.01,0.0005,SGD,640,0.0,0,SiLU,763.86,0.99663,0.99388,0.99412,0.74142
1,Case 1: Epoch Variation,2,epochs_32,32,32,0.01,0.0005,SGD,640,0.0,0,SiLU,1474.82,0.99606,0.99778,0.99467,0.76455
2,Case 1: Epoch Variation,3,epochs_64,64,32,0.01,0.0005,SGD,640,0.0,0,SiLU,2931.67,0.99653,0.99555,0.99452,0.79041

In [6]:
case3_batch_size()

Downloading https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov8m.pt to 'yolov8m.pt': 100% ━━━━━━━━━━━━ 49.7/49.7MB 296.2MB/s 0.2s0.1s
Ultralytics 8.3.191 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8m.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/train, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Downloading https://ultralytics.com/assets/Arial.ttf to '/root/.config/Ultralytics/Arial.ttf': 100% ━━━━━━━━━━━━ 755.1/755.1KB 28.8MB/s 0.0s
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1      1392  ultralytics.nn.modules.conv.Conv             [3, 48, 3, 2]
  1                  -1  1     41664  ultralytics.nn.modules.conv.Conv             [48, 96, 3, 2]
  2                  -1  2    111360  ultralytics.nn.modules.block.C2f             [96, 96, 2, True]
  3                  -1  1    166272  ultralytics.nn.modules.conv.Conv             [96, 192, 3, 2]
  4                  -1  4    813312  ultralytics.nn.modules.block.C2f             [192, 192, 4, True]
  5                  -1  1    664320  ultralytics.nn.modules.conv.Conv             [192, 384, 3, 2]
  6                  -1  4   3248640  ultralytics.nn.modules.block.C2f             [384, 384, 4, True]
  7                  -1  1   1991808  ultralytics.nn.modules.conv.Conv             [384, 576, 3, 2]
  8                  -1  2   3985920  ultralytics.nn.modules.block.C2f             [576, 576, 2, True]
  9                  -1  1    831168  ultralytics.nn.modules.block.SPPF            [576, 576, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  2   1993728  ultralytics.nn.modules.block.C2f             [960, 384, 2]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  2    517632  ultralytics.nn.modules.block.C2f             [576, 192, 2]
 16                  -1  1    332160  ultralytics.nn.modules.conv.Conv             [192, 192, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  2   1846272  ultralytics.nn.modules.block.C2f             [576, 384, 2]
 19                  -1  1   1327872  ultralytics.nn.modules.conv.Conv             [384, 384, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  2   4207104  ultralytics.nn.modules.block.C2f             [960, 576, 2]
 22        [15, 18, 21]  1   3776275  ultralytics.nn.modules.head.Detect           [1, [192, 384, 576]]
Model summary: 169 layers, 25,856,899 parameters, 25,856,883 gradients, 79.1 GFLOPs

Transferred 469/475 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
Downloading https://github.com/ultralytics/assets/releases/download/v8.3.0/yolo11n.pt to 'yolo11n.pt': 100% ━━━━━━━━━━━━ 5.4/5.4MB 103.0MB/s 0.1s
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.1±0.3 ms, read: 6.8±3.6 MB/s, size: 52.0 KB)
train: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train/labels... 1200 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1200/1200 169.5it/s 7.1s0.1s
WARNING ⚠️ train: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 10.1±2.5 MB/s, size: 61.5 KB)
val: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels... 300 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 300/300 178.7it/s 1.7s0.1s
WARNING ⚠️ val: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val is not writeable, cache not saved.
Plotting labels to runs/detect/train/labels.jpg...
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 77 weight(decay=0.0), 84 weight(decay=0.0005), 83 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs/detect/train
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/32      7.77G      1.928      1.684      1.477        142        640: 100% ━━━━━━━━━━━━ 75/75 1.6it/s 47.6s0.6ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 2.6it/s 3.9s.3s4s
                   all        300       1798      0.988      0.974      0.992      0.617

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/32      7.81G      1.334     0.6459      1.133        164        640: 100% ━━━━━━━━━━━━ 75/75 1.6it/s 46.5s0.6ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.3it/s 3.1s.3s0s
                   all        300       1798      0.986      0.984      0.991      0.587

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/32      7.86G      1.314     0.6648      1.134        201        640: 100% ━━━━━━━━━━━━ 75/75 1.6it/s 46.3s0.6ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.3it/s 3.1s.3s0s
                   all        300       1798       0.99      0.992      0.994      0.642

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/32       7.9G      1.311     0.5815      1.137        190        640: 100% ━━━━━━━━━━━━ 75/75 1.6it/s 46.2s0.6ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.3it/s 3.1s.3s0s
                   all        300       1798      0.992      0.986      0.993      0.652

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.3it/s 3.1s.3s
                   all        300       1798      0.994      0.994      0.994      0.686

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/32      7.97G      1.206     0.5044      1.107        198        640: 100% ━━━━━━━━━━━━ 75/75 1.6it/s 46.2s0.6ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.2it/s 3.1s.3s6s
                   all        300       1798      0.985      0.891      0.949      0.608

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/32      7.81G      1.185     0.4917      1.106        162        640: 100% ━━━━━━━━━━━━ 75/75 1.6it/s 46.2s0.6ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.3it/s 3.0s.3ss
                   all        300       1798      0.975      0.951      0.983      0.638

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/32      7.86G      1.171     0.4871      1.108        122        640: 100% ━━━━━━━━━━━━ 75/75 1.6it/s 46.2s0.6ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.3it/s 3.1s.3ss
                   all        300       1798      0.996      0.995      0.994      0.683

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/32       7.9G      1.153     0.4728      1.094        148        640: 100% ━━━━━━━━━━━━ 75/75 1.6it/s 46.3s0.6ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.3it/s 3.1s.3s0s
                   all        300       1798      0.994      0.996      0.994      0.674

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/32      7.95G      1.136     0.4661      1.105        156        640: 100% ━━━━━━━━━━━━ 75/75 1.6it/s 46.2s0.6ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.3it/s 3.1s.3s0s
                   all        300       1798      0.994      0.994      0.993      0.681

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/32      7.83G      1.125     0.4507      1.091        149        640: 100% ━━━━━━━━━━━━ 75/75 1.6it/s 46.2s0.6ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.3it/s 3.0s.3ss
                   all        300       1798      0.995      0.992      0.994      0.701

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/32      7.84G      1.118     0.4424      1.113        180        640: 100% ━━━━━━━━━━━━ 75/75 1.6it/s 46.2s0.6ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.3it/s 3.1s.3s0s
                   all        300       1798      0.998      0.995      0.995      0.713

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/32      7.88G      1.107     0.4427       1.09        139        640: 100% ━━━━━━━━━━━━ 75/75 1.6it/s 46.2s0.6ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.3it/s 3.0s.3ss
                   all        300       1798      0.996      0.995      0.994      0.708

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/32      7.93G      1.102     0.4328      1.082        178        640: 100% ━━━━━━━━━━━━ 75/75 1.6it/s 46.2s0.6ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.3it/s 3.0s.3ss
                   all        300       1798      0.994      0.995      0.993      0.682

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/32      7.97G      1.079     0.4219      1.078        189        640: 100% ━━━━━━━━━━━━ 75/75 1.6it/s 46.2s0.6ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.3it/s 3.1s.3ss
                   all        300       1798      0.996      0.994      0.995       0.71

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/32      7.97G      1.075     0.4173      1.091        124        640: 100% ━━━━━━━━━━━━ 75/75 1.6it/s 46.2s0.6ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.2it/s 3.1s.3s0s
                   all        300       1798      0.996      0.995      0.995      0.718

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/32         8G      1.053     0.4118      1.072        195        640: 100% ━━━━━━━━━━━━ 75/75 1.6it/s 46.2s0.6ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.3it/s 3.1s.3s0s
                   all        300       1798      0.996      0.996      0.995      0.724

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/32      7.98G      1.046     0.4058      1.057        174        640: 100% ━━━━━━━━━━━━ 75/75 1.6it/s 46.2s0.6ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.3it/s 3.1s.3s0s
                   all        300       1798      0.996      0.996      0.995      0.731

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/32      8.04G      1.034      0.407      1.046        174        640: 100% ━━━━━━━━━━━━ 75/75 1.6it/s 46.2s0.6ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.3it/s 3.1s.3s3s
                   all        300       1798      0.998      0.996      0.994      0.714

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/32      7.94G      1.023     0.3966      1.048        192        640: 100% ━━━━━━━━━━━━ 75/75 1.6it/s 46.2s0.6ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.2it/s 3.1s.3s0s
                   all        300       1798      0.996      0.997      0.995      0.727
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/32      7.96G     0.9993     0.3606      1.057         95        640: 100% ━━━━━━━━━━━━ 75/75 1.6it/s 46.6s0.6ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.3it/s 3.1s.3s2s
                   all        300       1798      0.997      0.997      0.995      0.739

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/32         8G     0.9796     0.3531      1.037         96        640: 100% ━━━━━━━━━━━━ 75/75 1.6it/s 46.1s0.6ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.3it/s 3.1s.3ss
                   all        300       1798      0.996      0.998      0.995      0.742

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/32      7.97G     0.9601     0.3455      1.037        100        640: 100% ━━━━━━━━━━━━ 75/75 1.6it/s 46.1s0.6ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.3it/s 3.1s.3ss
                   all        300       1798      0.997      0.997      0.995      0.735

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/32      7.96G     0.9444     0.3437      1.041        100        640: 100% ━━━━━━━━━━━━ 75/75 1.6it/s 46.1s0.6ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.3it/s 3.1s.3s1s
                   all        300       1798      0.997      0.997      0.994      0.745

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/32         8G     0.9313     0.3332      1.031         84        640: 100% ━━━━━━━━━━━━ 75/75 1.6it/s 46.1s0.6ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.3it/s 3.1s.3s0s
                   all        300       1798      0.997      0.996      0.995      0.745

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/32      7.98G     0.9153     0.3266      1.009         93        640: 100% ━━━━━━━━━━━━ 75/75 1.6it/s 46.1s0.6ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.3it/s 3.0s.3ss
                   all        300       1798      0.997      0.997      0.995      0.756

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/32      7.79G     0.8988     0.3203      1.012         97        640: 100% ━━━━━━━━━━━━ 75/75 1.6it/s 46.1s0.6ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.3it/s 3.0s.3ss
                   all        300       1798      0.997      0.997      0.995      0.749

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/32      7.84G     0.8879     0.3143      1.003         91        640: 100% ━━━━━━━━━━━━ 75/75 1.6it/s 46.0s0.6ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.3it/s 3.0s.3ss
                   all        300       1798      0.998      0.996      0.995      0.761

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/32      7.88G     0.8707     0.3084     0.9888         93        640: 100% ━━━━━━━━━━━━ 75/75 1.6it/s 46.1s0.6ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.3it/s 3.1s.3s0s
                   all        300       1798      0.997      0.997      0.995      0.761

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/32      7.93G      0.856     0.3016     0.9817        100        640: 100% ━━━━━━━━━━━━ 75/75 1.6it/s 46.1s0.6ss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 3.3it/s 3.1s.3ss
                   all        300       1798      0.996      0.997      0.995      0.764

32 epochs completed in 0.446 hours.
Optimizer stripped from runs/detect/train/weights/last.pt, 52.0MB
Optimizer stripped from runs/detect/train/weights/best.pt, 52.0MB

Validating runs/detect/train/weights/best.pt...
Ultralytics 8.3.191 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
Model summary (fused): 92 layers, 25,840,339 parameters, 0 gradients, 78.7 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 2.7it/s 3.8s.4s8s

/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        300       1798      0.996      0.997      0.995      0.764
Speed: 0.1ms preprocess, 7.6ms inference, 0.0ms loss, 1.4ms postprocess per image
Results saved to runs/detect/train

,Case,Exp No,Experiment Name,Epochs,Batch,lr0,Weight Decay,Optimizer,Image Size,Dropout,Freeze Layers,Activation,Training Time (s),Precision,Recall,mAP@0.5,mAP@0.5:0.95
0,Case 3: Batch Size,1,batch_16,32,16,0.01,0.0005,SGD,640,0.0,0,SiLU,1637.85,0.99598,0.99666,0.9948,0.7645

Ultralytics 8.3.191 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=32, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8m.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train2, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/train2, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1      1392  ultralytics.nn.modules.conv.Conv             [3, 48, 3, 2]
  1                  -1  1     41664  ultralytics.nn.modules.conv.Conv             [48, 96, 3, 2]
  2                  -1  2    111360  ultralytics.nn.modules.block.C2f             [96, 96, 2, True]
  3                  -1  1    166272  ultralytics.nn.modules.conv.Conv             [96, 192, 3, 2]
  4                  -1  4    813312  ultralytics.nn.modules.block.C2f             [192, 192, 4, True]
  5                  -1  1    664320  ultralytics.nn.modules.conv.Conv             [192, 384, 3, 2]
  6                  -1  4   3248640  ultralytics.nn.modules.block.C2f             [384, 384, 4, True]
  7                  -1  1   1991808  ultralytics.nn.modules.conv.Conv             [384, 576, 3, 2]
  8                  -1  2   3985920  ultralytics.nn.modules.block.C2f             [576, 576, 2, True]
  9                  -1  1    831168  ultralytics.nn.modules.block.SPPF            [576, 576, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  2   1993728  ultralytics.nn.modules.block.C2f             [960, 384, 2]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  2    517632  ultralytics.nn.modules.block.C2f             [576, 192, 2]
 16                  -1  1    332160  ultralytics.nn.modules.conv.Conv             [192, 192, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  2   1846272  ultralytics.nn.modules.block.C2f             [576, 384, 2]
 19                  -1  1   1327872  ultralytics.nn.modules.conv.Conv             [384, 384, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  2   4207104  ultralytics.nn.modules.block.C2f             [960, 576, 2]
 22        [15, 18, 21]  1   3776275  ultralytics.nn.modules.head.Detect           [1, [192, 384, 576]]
Model summary: 169 layers, 25,856,899 parameters, 25,856,883 gradients, 79.1 GFLOPs

Transferred 469/475 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 76.4±20.1 MB/s, size: 52.0 KB)
train: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train/labels... 1200 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1200/1200 770.6it/s 1.6s0.0s
WARNING ⚠️ train: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 84.7±45.5 MB/s, size: 61.5 KB)
val: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels... 300 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 300/300 466.8it/s 0.6s0.0s
WARNING ⚠️ val: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val is not writeable, cache not saved.
Plotting labels to runs/detect/train2/labels.jpg...
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 77 weight(decay=0.0), 84 weight(decay=0.0005), 83 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs/detect/train2
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/32      14.1G      2.233      2.202      1.647        145        640: 100% ━━━━━━━━━━━━ 38/38 0.88it/s 43.0s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.6it/s 3.1s0.8ss
                   all        300       1798      0.976      0.969      0.983      0.581

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/32      13.9G      1.341     0.7044      1.144        166        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.7s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798       0.99      0.989      0.992      0.642

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/32        14G      1.324     0.6317      1.145        166        640: 100% ━━━━━━━━━━━━ 38/38 0.92it/s 41.5s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.979      0.972      0.988      0.563

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       4/32        14G      1.271     0.6135      1.133        136        640: 100% ━━━━━━━━━━━━ 38/38 0.92it/s 41.5s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798       0.99      0.982      0.993        0.6

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       5/32        14G      1.282     0.5407      1.139        165        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.6s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.981       0.97      0.991      0.589

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       6/32        14G      1.232      0.534      1.129        171        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.5s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.991      0.988      0.994      0.642

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       7/32        14G      1.206     0.4966      1.119        167        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.6s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.994      0.991      0.994      0.645

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       8/32        14G      1.198     0.4973       1.12        141        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.6s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798       0.99      0.991      0.994      0.661

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       9/32        14G      1.189     0.4836      1.131        129        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.6s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.6it/s 3.0s0.9ss
                   all        300       1798      0.989      0.982      0.992      0.617

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      10/32        14G      1.169     0.4752      1.121        153        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.6s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.987      0.981      0.992      0.668

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      11/32        14G      1.152      0.462      1.108        192        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.6s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.992      0.989      0.994      0.685

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      12/32        14G      1.124     0.4544      1.097        186        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.6s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.994      0.996      0.994      0.655

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      13/32        14G      1.126     0.4457      1.102        168        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.6s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.992      0.996      0.993      0.702

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      14/32        14G      1.106     0.4364      1.101        169        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.6s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.996      0.993      0.994      0.697

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      15/32        14G      1.103     0.4386      1.115        156        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.6s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.994      0.994      0.993      0.707

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      16/32        14G      1.095     0.4334      1.108        176        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.6s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.997      0.996      0.994      0.685

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      17/32        14G      1.072     0.4163      1.077        188        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.6s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.993      0.995      0.994      0.723

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      18/32        14G      1.056     0.4101      1.075        169        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.6s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.995      0.997      0.994      0.716

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      19/32        14G      1.043     0.4022      1.068        155        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.6s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.994      0.997      0.994      0.723

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      20/32        14G       1.03     0.3971      1.069        180        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.6s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.6it/s 3.1s0.8ss
                   all        300       1798      0.996      0.996      0.994      0.727

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      21/32        14G      1.013     0.3897      1.069        174        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.6s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.996      0.997      0.995      0.722

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      22/32        14G          1     0.3859      1.055        149        640: 100% ━━━━━━━━━━━━ 38/38 0.91it/s 41.6s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.997      0.996      0.995       0.74
Closing dataloader mosaic
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      23/32        14G     0.9801     0.3513      1.065         96        640: 100% ━━━━━━━━━━━━ 38/38 0.89it/s 42.7s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.996      0.997      0.995      0.741

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      24/32        14G     0.9723     0.3529      1.064        100        640: 100% ━━━━━━━━━━━━ 38/38 0.92it/s 41.4s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.996      0.998      0.995       0.74

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      25/32        14G      0.949     0.3435      1.043         99        640: 100% ━━━━━━━━━━━━ 38/38 0.92it/s 41.4s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.996      0.997      0.995      0.741

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      26/32        14G     0.9285     0.3338      1.016        100        640: 100% ━━━━━━━━━━━━ 38/38 0.92it/s 41.4s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.995      0.997      0.995       0.75

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      27/32        14G     0.9113     0.3258       1.02         82        640: 100% ━━━━━━━━━━━━ 38/38 0.92it/s 41.4s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.997      0.998      0.995      0.745

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      28/32        14G     0.9058     0.3226      1.025         92        640: 100% ━━━━━━━━━━━━ 38/38 0.92it/s 41.4s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.997      0.998      0.995      0.755

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      29/32        14G     0.8889     0.3165      1.016         96        640: 100% ━━━━━━━━━━━━ 38/38 0.92it/s 41.4s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.996      0.998      0.994      0.752

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      30/32        14G     0.8784     0.3104      1.012         89        640: 100% ━━━━━━━━━━━━ 38/38 0.92it/s 41.4s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.997      0.996      0.994      0.758

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      31/32        14G     0.8538     0.3033     0.9996         93        640: 100% ━━━━━━━━━━━━ 38/38 0.92it/s 41.4s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.998      0.997      0.995      0.759

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      32/32        14G     0.8484      0.298     0.9968         99        640: 100% ━━━━━━━━━━━━ 38/38 0.92it/s 41.4s.9sss
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.7it/s 3.0s0.8ss
                   all        300       1798      0.996      0.998      0.995      0.765

32 epochs completed in 0.406 hours.
Optimizer stripped from runs/detect/train2/weights/last.pt, 52.0MB
Optimizer stripped from runs/detect/train2/weights/best.pt, 52.0MB

Validating runs/detect/train2/weights/best.pt...
Ultralytics 8.3.191 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
Model summary (fused): 92 layers, 25,840,339 parameters, 0 gradients, 78.7 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 5/5 1.2it/s 4.2s<1.1s

/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1
/usr/local/lib/python3.11/dist-packages/matplotlib/colors.py:721: RuntimeWarning: invalid value encountered in less
  xa[xa < 0] = -1

                   all        300       1798      0.996      0.998      0.995      0.764
Speed: 0.1ms preprocess, 7.4ms inference, 0.0ms loss, 2.2ms postprocess per image
Results saved to runs/detect/train2

,Case,Exp No,Experiment Name,Epochs,Batch,lr0,Weight Decay,Optimizer,Image Size,Dropout,Freeze Layers,Activation,Training Time (s),Precision,Recall,mAP@0.5,mAP@0.5:0.95
0,Case 3: Batch Size,1,batch_16,32,16,0.01,0.0005,SGD,640,0.0,0,SiLU,1637.85,0.99598,0.99666,0.99480,0.76450
1,Case 3: Batch Size,2,batch_32,32,32,0.01,0.0005,SGD,640,0.0,0,SiLU,1477.32,0.99606,0.99778,0.99467,0.76455

Ultralytics 8.3.191 🚀 Python-3.11.13 torch-2.6.0+cu124 CUDA:0 (Tesla P100-PCIE-16GB, 16269MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=64, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/data.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, epochs=32, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=0, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolov8m.pt, momentum=0.937, mosaic=1.0, multi_scale=False, name=train3, nbs=64, nms=False, opset=None, optimize=False, optimizer=SGD, overlap_mask=True, patience=100, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, save=True, save_conf=False, save_crop=False, save_dir=runs/detect/train3, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=False, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None
Overriding model.yaml nc=80 with nc=1

                   from  n    params  module                                       arguments
  0                  -1  1      1392  ultralytics.nn.modules.conv.Conv             [3, 48, 3, 2]
  1                  -1  1     41664  ultralytics.nn.modules.conv.Conv             [48, 96, 3, 2]
  2                  -1  2    111360  ultralytics.nn.modules.block.C2f             [96, 96, 2, True]
  3                  -1  1    166272  ultralytics.nn.modules.conv.Conv             [96, 192, 3, 2]
  4                  -1  4    813312  ultralytics.nn.modules.block.C2f             [192, 192, 4, True]
  5                  -1  1    664320  ultralytics.nn.modules.conv.Conv             [192, 384, 3, 2]
  6                  -1  4   3248640  ultralytics.nn.modules.block.C2f             [384, 384, 4, True]
  7                  -1  1   1991808  ultralytics.nn.modules.conv.Conv             [384, 576, 3, 2]
  8                  -1  2   3985920  ultralytics.nn.modules.block.C2f             [576, 576, 2, True]
  9                  -1  1    831168  ultralytics.nn.modules.block.SPPF            [576, 576, 5]
 10                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 11             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 12                  -1  2   1993728  ultralytics.nn.modules.block.C2f             [960, 384, 2]
 13                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 14             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 15                  -1  2    517632  ultralytics.nn.modules.block.C2f             [576, 192, 2]
 16                  -1  1    332160  ultralytics.nn.modules.conv.Conv             [192, 192, 3, 2]
 17            [-1, 12]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 18                  -1  2   1846272  ultralytics.nn.modules.block.C2f             [576, 384, 2]
 19                  -1  1   1327872  ultralytics.nn.modules.conv.Conv             [384, 384, 3, 2]
 20             [-1, 9]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 21                  -1  2   4207104  ultralytics.nn.modules.block.C2f             [960, 576, 2]
 22        [15, 18, 21]  1   3776275  ultralytics.nn.modules.head.Detect           [1, [192, 384, 576]]
Model summary: 169 layers, 25,856,899 parameters, 25,856,883 gradients, 79.1 GFLOPs

Transferred 469/475 items from pretrained weights
Freezing layer 'model.22.dfl.conv.weight'
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 78.8±36.8 MB/s, size: 52.0 KB)
train: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train/labels... 1200 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1200/1200 771.6it/s 1.6s0.0s
WARNING ⚠️ train: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/train is not writeable, cache not saved.
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 89.1±43.6 MB/s, size: 61.5 KB)
val: Scanning /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val/labels... 300 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 300/300 454.9it/s 0.7s0.0s
WARNING ⚠️ val: Cache directory /kaggle/input/yolo-text-detection-data2/YOLO_text_detection_data/val is not writeable, cache not saved.
Plotting labels to runs/detect/train3/labels.jpg...
optimizer: SGD(lr=0.01, momentum=0.937) with parameter groups 77 weight(decay=0.0), 84 weight(decay=0.0005), 83 bias(decay=0.0)
Image sizes 640 train, 640 val
Using 4 dataloader workers
Logging results to runs/detect/train3
Starting training for 32 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
: 0% ──────────── 0/19  3.4s<

OutOfMemoryError: CUDA out of memory. Tried to allocate 600.00 MiB. GPU 0 has a total capacity of 15.89 GiB of which 67.12 MiB is free. Process 3978 has 15.82 GiB memory in use. Of the allocated memory 15.02 GiB is allocated by PyTorch, and 484.71 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)